### ISSUE TITLE
unable to run Steam on F25 ("missing 32-bit libraries: libc.so.6")

### ISSUE THREAD

**Issue by FelixSchwarz** [flathub/com.valvesoftware.Steam#1]
I installed steam flatpak from flathub (via GNOME software) but it does not work after installing.
- `flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
- run gnome software and install the "steam" item from flathub, click "run"
- agree to the steam eula
- then I see a message box telling me: "You are missing the following 32-bit libraries, and Steam may not run: libc.so.6"

components:
- gnome-software-3.22.7-1.fc25.x86_64
- flatpak-0.9.5-1.fc25.x86_64

Probably I'm missing something here...

**Comment by FelixSchwarz** [comment]
Ah, I just noticed that `flatpak --user update` got me to a working state. So probably just one of the current shortcomings of flatpak/infrastracture (when compared to rpm/dnf).

**Comment by fastrizwaan** [comment]
for me **`flatpak update`** worked instead on fedora 25 workstation.

**Comment by alexlarsson** [comment]
I think the problem here is that the CLI auto-installs/updates the dependencies, but gnome-software doesn't yet.
@hughsie.

**Comment by hughsie** [comment]
What should I be calling to install deps? Could this be a flag to `flatpak_installation_install`?

**Comment by Vaesper** [comment]
This issue still exists.

**Comment by sirredbeard** [comment]
This issue still occurs when installing the Steam flatpak on CentOS 7.5.

The workaround mentioned above is still to run:

`$ flatpak --user update`

The required 32-bit libraries will be downloaded and installed.

Soon the Steam client will be switching to 64-bit anyways so this issue going forward will be moot.

**Comment by nanonyme** [comment]
Are you installing through command line or Gnome Software? CentOS will most likely have too old flatpak and Gnome Software for this to work out of the box currently. You might be able to get command line to work as expected by not using distro package but installing a newer build

**Comment by Newbytee** [comment]
I still experience this, and the update workaround did not help. Updating did not install the required 32-bit libraries. However, this only happens if I install the version of Steam from flathub-beta. flathub is fine.

**Comment by nanonyme** [comment]
Yes, that is expected. Dependency resolution works as expected only with main ostree repo.
