### ISSUE TITLE
Font issue if liberation-fonts not installed on system

### ISSUE THREAD

**Issue by k4ffee** [flathub/com.valvesoftware.Steam#1000]
Hi there, 
i am not sure if this belongs here. My assumption is, that the needed fonts should be shipped with the flatpak app. Sorry if this is false one. 

If the liberation-fonts are not installed on the system, steam looks like described here: https://github.com/ValveSoftware/steam-for-linux/issues/2763

Installing the suggest package helped me.

Thank you!

**Comment by nanonyme** [comment]
No, flatpak is supposed to be able to use fonts from host.

**Comment by k4ffee** [comment]
Thank you for clarification

**Comment by 22p** [comment]
run  `ln -srv ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/tenfoot/resource/fonts ~/.var/app/com.valvesoftware.Steam/.fonts`

**Comment by nanonyme** [comment]
That should not be necessary
