### ISSUE TITLE
Non-community  builds of Proton do not work with mesa-git

### ISSUE THREAD

**Issue by MayeulC** [flathub/com.valvesoftware.Steam#1006]
**Game information**
I only tested these three, which were installed:
- [Shattered Horizon](https://store.steampowered.com/app/18110/Shattered_Horizon/) (note that this one requires `protontricks 18110 d3dx10`).
- [Halo MCC](https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/)
- [Halo Infinite](https://store.steampowered.com/app/1240440/Halo_Infinite/)

**Distribution name and version where applicable**
Arch

**Flatpak info**

```
% flatpak --version
Flatpak 1.15.0
% flatpak --gl-drivers
default
host
% FLATPAK_GL_DRIVERS=mesa-git flatpak --gl-drivers
mesa-git
```

**Problem description**
Running steam with `FLATPAK_GL_DRIVERS=mesa-git flatpak run com.valvesoftware.Steam` seems to prevent "vanilla" (steam-provided) proton from starting up. Community builds provided through flathub work fine.

When starting steam without mesa-git, both steam-provided proton and community builds work.

Example with Halo: MCC (prefix deleted every time):
1. default mesa, community build of Proton Experimental: WORKS [steam-976730-def-community-works.log](https://github.com/flathub/com.valvesoftware.Steam/files/9996215/steam-976730-def-community-works.log)
2. default mesa, Steam-provided Proton Experimental: WORKS [steam-976730-def-steam-works.log](https://github.com/flathub/com.valvesoftware.Steam/files/9996214/steam-976730-def-steam-works.log)
3. Mesa-git, community build of Proton Experimental: WORKS [steam-976730-git-community-works.log](https://github.com/flathub/com.valvesoftware.Steam/files/9996217/steam-976730-git-community-works.log)
4. Mesa-git: Steam-provided Proton Experimental: issue (same issue if mesa is not installed): [steam-976730-git-steam-fail.log](https://github.com/flathub/com.valvesoftware.Steam/files/9996211/steam-976730-git-steam-fail.log)

![image](https://user-images.githubusercontent.com/3952726/201498785-4f38985b-092d-407b-b5da-9a7e6cd67293.png)

This issue is a bit annoying as there's currently a free trinket in Halo Infinite, that has stopped working with community builds of Proton (needs the Hotfix branch on Steam, or the bleeding-edge experimental branch).

**Does this issue reproduce with native Steam**
Not really relevant

**Comment by nanonyme** [comment]
Yes, this is known. You can follow up on https://gitlab.com/freedesktop-sdk/mesa-git-extension/-/issues/4

**Comment by rjawiygvozd** [comment]
for people running steam in flatpak
i've learned that using mesa-git, as in
`FLATPAK_GL_DRIVERS=mesa-git flatpak run com.valvesoftware.Steam`
actually only works with proton builds that are installed as literal flatpaks, such as com.valvesoftware.Steam.CompatibilityTool.Proton
builds installed via protonup-gui flatpak don't work
