### ISSUE TITLE
Steam SEGFAULT on exit in libgobject-2.0.so

### ISSUE THREAD

**Issue by HBRJZ** [flathub/com.valvesoftware.Steam#1011]
**Distribution name and version where applicable**

- Operating System: Fedora Linux 37
- KDE Plasma Version: 5.26.3
- KDE Frameworks Version: 5.100.0
- Qt Version: 5.15.7
- Kernel Version: 6.0.9-300.fc37.x86_64 (64-bit)
- Graphics Platform: Wayland
- Processors: 20 × 12th Gen Intel® Core™ i7-12700K
- Memory: 31,1 GiB of RAM
- Graphics Processor: AMD Radeon RX 6800 XT

**Flatpak info**

- flatpak --version: Flatpak 1.14.0
- flatpak --gl-drivers: default host

**Problem description**
Every time I exit the Steam Flatpak a SEGFAULT happens, example:

```
steam[10755]: segfault at aaaaaaaa ip 00000000f0bcf0a1 sp 00000000ffa99770 error 4 in libgobject-2.0.so.0.7200.4[f0ba4000+35000]

Code: 5b 5e 5f c3 8d 74 26 00 90 f3 0f 1e fb 53 e8 b6 83 fd ff 81 c3 2e fc 02 00 83 ec 08 8b 44 24 10 85 c0 74 75 8b 00 85 c0 74 7f <8b> 10 81 fa fc 03 00 00 77 45 89 d0 c1 e8 02 8b 8c 83 28 04 00 00
```

This isn't exactly a new thing to happen and has happend occasionally for months on different distributions (e.g. also on EndeavourOS). But since I switched to Fedora it seems to happen every time now when I exit Steam.

**Does this issue reproduce with native Steam**
It does, see issue https://github.com/ValveSoftware/steam-for-linux/issues/8922

The difference is the frequency (it happens less for me on native Steam) and where the SEGAULT happens.

On the Steam Flatpak it always seems to be in **libgobject-2.0.so** while on native Steam it happens in a bunch of different libraries, mostly **libc.so** tho.

**Comment by damajor** [comment]
Happens also on Fedora 36 using Steam Flatpak.
Each time it is closed it segfaults.
