### ISSUE TITLE
Question-This version uses SDL of my system or an embedded version?

### ISSUE THREAD

**Issue by moacirrf** [flathub/com.valvesoftware.Steam#1012]
Hi, first all, awesome work i appreciate your job

I would like to upgrade my SDL version to test if it fix this issue:
[https://github.com/ValveSoftware/Proton/issues/6323](https://github.com/ValveSoftware/Proton/issues/6323)

This flatpack version uses SDL of my system or an embedded version?

I don't know if i can just upgrade my system's SDL.

Thank you

**Comment by berarma** [comment]
Why not simply install the Steam client beta as suggested?

**Comment by moacirrf** [comment]
> Why not simply install the Steam client beta as suggested?

I will try that 
thanks
