### ISSUE TITLE
Blank login screen

### ISSUE THREAD

**Issue by KirmesBude** [flathub/com.valvesoftware.Steam#1022]
**Distribution name and version where applicable**
Operating System: Fedora Linux 35
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.18.6-100.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 15,5 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

**Flatpak info**
Flatpak 1.12.7
default
host
client glx vendor string: Mesa Project and SGI
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.3.9
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.3.9
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.3.9

**Problem description**
Login screen is blank.
![image](https://user-images.githubusercontent.com/8339817/207900562-b05bfec0-f42f-47c5-9837-b83e82229f04.png)

**Does this issue reproduce with native Steam**
Have not tested

**Additional Information**
Steam was working fine yesterday. Only occured today, but I can not recall updating flatpak steam/runtime.
Command line output:
flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /var/home/bude/.var/app/com.valvesoftware.Steam
DEBUG:root:Checking input devices permissions
INFO:root:Overriding TZ to Europe/Berlin
steam.sh[2]: Running Steam on org.freedesktop.platform 22.08 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
setup.sh[77]: Steam runtime environment up-to-date!
steam.sh[2]: Steam client's requirements are satisfied
[2022-12-15 16:26:32] Startup - updater built Dec 15 2022 02:01:56
[2022-12-15 16:26:32] Startup - Steam Client launched with: '/var/home/bude/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
[2022-12-15 16:26:32] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1671079580)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2022-12-15 16:26:32] Loading cached metrics from disk (/var/home/bude/.var/app/com.valvesoftware.Steam/.local/share/Steam/package/steam_client_metrics.bin)
[2022-12-15 16:26:32] Using the following download hosts for Public, Realm steamglobal
[2022-12-15 16:26:32] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2022-12-15 16:26:32] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2022-12-15 16:26:32] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1671079580)
[2022-12-15 16:26:32] Checking for update on startup
[2022-12-15 16:26:32] Checking for available updates...
[2022-12-15 16:26:32] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_publicbeta_ubuntu12
[2022-12-15 16:26:32] Manifest download: send request
Installing breakpad exception handler for appid(steam)/version(1671079580)
[2022-12-15 16:26:32] Manifest download: waiting for download to finish
[2022-12-15 16:26:33] Manifest download: finished
[2022-12-15 16:26:33] Download skipped: /steam_client_publicbeta_ubuntu12 version 1671079580, installed version 1671079580, existing pending version 0
[2022-12-15 16:26:33] Nothing to do
[2022-12-15 16:26:33] Verifying installation...
[2022-12-15 16:26:33] Performing checksum verification of executable files
[2022-12-15 16:26:33] Verification complete
Loaded SDL version 2.27.0-p7718664
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xee51b8f0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xee51a1c0
ComputeStartupMode: found registry default startup mode: 0Installing breakpad exception handler for appid(steam)/version(1671079580)
steamwebhelper.sh[173]: Runtime for steamwebhelper: defaulting to /var/home/bude/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[173]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[173]: CEF sandbox already disabled
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
CAppInfoCacheReadFromDiskThread took 48 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
src/clientdll/user.cpp (8118) : Calling GetUserConfigFolder before we know our SteamID
src/clientdll/user.cpp (8118) : Calling GetUserConfigFolder before we know our SteamID
Installing breakpad exception handler for appid(steam)/version(1671079580)
assert_20221215162633_24.dmp[311]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221215162633_24.dmp
Installing breakpad exception handler for appid(steam)/version(1671079580)
assert_20221215162633_24.dmp[311]: Finished uploading minidump (out-of-process): success = yes
assert_20221215162633_24.dmp[311]: response: CrashID=bp-90b28c26-7aa9-4b31-9ef9-281bf2221215
assert_20221215162633_24.dmp[311]: file ''/tmp/dumps/assert_20221215162633_24.dmp'', upload yes: ''CrashID=bp-90b28c26-7aa9-4b31-9ef9-281bf2221215''
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)
Installing breakpad exception handler for appid(steam)/version(1671079580)

**Comment by KirmesBude** [comment]
It seems to be an issue with the latest beta release of steam. (I did not even realize I was still on the beta branch).
Revert back to stable by deleting ~/.var/app/com.valvesoftware.Steam/.steam/root/package/beta 

I will leave this up for a few days in case it persists to be an issue on beta.

**Comment by CyborgDragonFire** [comment]
I've just run into this issue, on a new clean fresh installation of Manjaro.
I'm NOT using the steam beta client, this is a first time launch on a new clean distro install.

This issue is now in stable.
