### ISSUE TITLE
Wrapper broken for steamcmd?

### ISSUE THREAD

**Issue by joshqou** [flathub/com.valvesoftware.Steam#1028]
The `steamcmd` command doesn't seem to work. Version 1.0.0.75, Flatpak 1.14.1, Fedora 37

```sh
$ flatpak run --command=steamcmd com.valvesoftware.Steam
Traceback (most recent call last):
  File "/app/bin/steamcmd", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.10/site-packages/steamcmd_wrapper.py", line 18, in main
    steam_wrapper.copytree(
AttributeError: module 'steam_wrapper' has no attribute 'copytree'
```

**Comment by SantiagoPaak** [comment]
Having the same problem. Trying to reach the source of the problem, it appears that "copytree" is marked as private in steam_wrapper but steamcmd_wrapper tries to use it.

**Comment by doraskayo** [comment]
@gasinvein, @nanonyme, I think this PR broke it: https://github.com/flathub/com.valvesoftware.Steam/pull/992
