### ISSUE TITLE
Civilization VI blue glitches after last update.

### ISSUE THREAD

**Issue by nintyfan** [flathub/com.valvesoftware.Steam#103]
I updated framework and com.valvesoftware.Steam lately and Civilization VI starts displaying blue glitches.

I have this error on normal Steam installation, but this bug was fixed in Mesa and (on normal Steam installation - OpenSuSE Tumbleweed rpms) everything works perfectly, After installed flatpaked Steam everything works, but after this update blue glitches appear again.

**Comment by nanonyme** [comment]
Happen to know which Mesa release should have the fix?

**Comment by nintyfan** [comment]
https://www.reddit.com/r/civ/comments/76zmcg/civ_vi_linux_blue_glitch_fixed/

It looks like mesa-17.4 , I don't know, which version introduced fix, but the game works before last Steam/Runtime update.

**Comment by TingPing** [comment]
It has Mesa 18.0.4 currently.

**Comment by nintyfan** [comment]
So maybe it is regression. I will fill a bug report to the Mesa devs.

**Comment by nintyfan** [comment]
Is there a way to use system Mesa in freedesktop runtime (flatpak)? Some bind of files? I tried to copy files, but it complains about some private symbol in libc.

**Comment by nanonyme** [comment]
Afaik not really. You can't normally expect internals of a Flatpak to be ABI-compatible with host system

**Comment by nintyfan** [comment]
Problem solved. I do:
flatpak --user uninstall org.freedesktop.Platform.GL.default

Probably org.freedesktop.Platform.GL.default was installed automatically, so somebody must do something to solve this problem, but that's rather problem of freedesktop runtime authors.

Thanks for help.

**Comment by nanonyme** [comment]
That sounds like a fairly bad workaround. Maybe it's worth it to keep this one open for now since Summer time seems silent with regards to devs being present

**Comment by nanonyme** [comment]
Can you still get this to reproduce with the new runtime?

**Comment by nintyfan** [comment]
Meanwhile, I must remove Steam from my system. I installed it today, but it doesn't requires GL_defaults extension to freedesktop platform.
I change computer, so maybe that's the reason this extension isn't installed?

**Comment by nanonyme** [comment]
Runtime was recently update from 1.6 to 18.08, behaviour may have changed with that

**Comment by nanonyme** [comment]
If you can't repro anymore, closing as fixed. Please re-open if you notice this again

**Comment by nintyfan** [comment]
Can I test it on old computer? I think Steam allows to keep the same game on many computers, but you can get logged only from one machine at the same time.

**Comment by nanonyme** [comment]
Sure, re-open if this still happens on the old one.
