### ISSUE TITLE
Project R (Planescape Tourment Enchancement Edition) won't run

### ISSUE THREAD

**Issue by nintyfan** [flathub/com.valvesoftware.Steam#104]
As in topic.
Wine old version obtained form GOG works, but I decided to play in native port with new features.

It shows, there's missing symbol in libssl and libcurl

**Comment by nanonyme** [comment]
Sounds like a probable game bug

**Comment by nintyfan** [comment]
Maybe.
Game works on some systems, but on some others not.

PS:
Here somebody wrote, that patch for OpenSSL exist - https://steamcommunity.com/app/466300/discussions/0/1698300679775014859/

**Comment by nanonyme** [comment]
Meh. That's essentially about forking OpenSSL to start bringing back symbols they intentionally removed

**Comment by nintyfan** [comment]
So there's only two options:
1. Planescape Tourment vendors would fix thier game.
2. Valve release Steam for flatpak, so Steam guys can deliver patched version of OpenSSL

3. I will compile patched version of OpenSSL, put into game directory and set LD_LIBRARY_PATH to game directory

**Comment by nanonyme** [comment]
That's three options. Has anyone reported this to game maker/Valve

**Comment by nintyfan** [comment]
The last option was not a real option - it is only fix for me.

**Comment by nintyfan** [comment]
Ok. I have compiled to OpenSSL by myself and game ran, but that's no solution for normal users :-( . Maybe wrote flatpak-builder .json manifest to build this library and script to install it into Steam?

**Comment by nanonyme** [comment]
OpenSSL is one of the last possible things you might want to manually maintain. It's a source of constant security vulnerabilities. Shipping it in Steam doesn't really sound like a maintainable solution to me (this saying as someone who has been maintaining products that shipped their own OpenSSL build)

**Comment by nanonyme** [comment]
And those aren't really the real alternatives. Fix should be
1) In game
2) In Steam runtime
Steam runtime is shared between non-Flatpak and Flatpak Steam and maintained by Valve. There's a separate Github project for Steam runtime

**Comment by valentindavid** [comment]
Seems distributions have patched in some way.

Debian: https://sources.debian.org/patches/openssl1.0/1.0.2o-1/version-script.patch/
Fedora: https://src.fedoraproject.org/rpms/compat-openssl10/blob/master/f/openssl-1.0.2a-version.patch

I am fine with applying it. I think Fedora's patch does not require much maintenance.

**Comment by nanonyme** [comment]
@valentindavid sounds fine although I would really like some audit trail about this having communicated with upstream and them having acked this approach as reasonably secure

**Comment by nanonyme** [comment]
The Fedora patch does look quite simple

**Comment by valentindavid** [comment]
Upstream:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/329
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/468

**Comment by nanonyme** [comment]
This should now work as the change is integrated into runtime

**Comment by nanonyme** [comment]
Tested, closing as fixed
