### ISSUE TITLE
Cannot install Microsoft Visual C++ Runtime error

### ISSUE THREAD

**Issue by sith-on-mars** [flathub/com.valvesoftware.Steam#1074]
**Game information**

I can't launch [Ready or Not](https://www.protondb.com/app/1144200) and [Ground Branch](https://www.protondb.com/app/16900). Both are UE4 games.

**Distribution name and version where applicable**

OpenSUSE MicroOS

**Flatpak info**

flatpak --version: Flatpak 1.14.4
flatpak --gl-drivers:
nvidia-525-116-03
default
host

**Problem description**

I couldn't launch both games. Steam gave me the error like this `The following components are required to run this program: Microsoft Visual C++ Runtime. Would you like to install them now?`

![image](https://user-images.githubusercontent.com/37974764/235404980-dd51afb7-4eff-4b6e-b252-69803e0cb394.png)

I have tested both games on Proton 7, 8, and experimental and none of them worked. It seems for some reasons Proton wasn't able to install Microsoft Visual C++ Runtime. Strangely enough, I was able to run Ready or Not on Proton 6, but when I switched back to Proton 7, 8, or experimental, it still gave me the aforementioned error.

**Does this issue reproduce with native Steam**

Have not tested. However I believe the native Steam shouldn't have any problem as many people on ProtonDB reported that they're able to run the games on Proton 7 or 7 GE.

**Comment by groutc** [comment]
I am also running MicroOS (Aeon now) and I had issues with proton 7 and 8. I resolved it by following these instructions on the Aeon Troubleshooting guide: [https://en.opensuse.org/Portal:Aeon#Steam_Proton,_Bottles,_WINE,_Lutris,_Android_Studio_emulator_not_working_from_flatpaks](https://en.opensuse.org/Portal:Aeon#Steam_Proton,_Bottles,_WINE,_Lutris,_Android_Studio_emulator_not_working_from_flatpaks)

It appears to be a bug that won't be fixed: [https://bugzilla.opensuse.org/show_bug.cgi?id=1206292](https://bugzilla.opensuse.org/show_bug.cgi?id=1206292)
