### ISSUE TITLE
Steam forgets drives on boot

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [flathub/com.valvesoftware.Steam#1075]
**Game information**
not about a game

**Distribution name and version where applicable**
Fedora 38

**Flatpak info**
Version: Flatpak 1.15.4
gl-drivers: default
host

**Problem description**
I have two other drives I have added to the steam flatpak other than the library folder in the flatpak installation itself. Whenever I boot my pc it sometimes forgets both of those drives or sometimes one of them and I have to manually re add. Sometimes it remembers them, it seems to be pretty random.

**Does this issue reproduce with native Steam**
no

**Comment by lsdamota** [comment]
Experiencing the same issue with Steam Flatpak and Fedora WS 38.

Upon system boot, Steam will forget one drive out of two and requires to be re-added. The flatpak does remember drive permission, so re-adding is quick.

**Comment by Vovkiv** [comment]
Same for Fedora 38 Silverblue

**Comment by Wa-ffle** [comment]
same for me, im pretty new in Linux so i can't say you what distribution is but i installed the last one from steampowered.com

**Comment by Aman9das** [comment]
If you quit steam before rebooting it doesn't happen

**Comment by TheAnnoyingFruit** [comment]
This seems to of stopped happening

**Comment by Aman9das** [comment]
Fix is to select the steamlibrary folder rather than the root of the drive
