### ISSUE TITLE
Please consider making --command=steam go via the wrapper

### ISSUE THREAD

**Issue by smcv** [flathub/com.valvesoftware.Steam#1078]
At the moment `/app/bin/steam` is Valve's `bin_steam.sh` (which users should never run directly in this Flatpak app), and `/app/bin/steam-wrapper` is the correct entry point for users (which does some necessary setup and then execs `/app/bin/steam`).

With https://github.com/flatpak/flatpak/pull/5404 and https://github.com/flatpak/flatpak/issues/5395 in mind, it might be better to have `/app/bin/steam` be the wrapper, and make it exec Valve's script as `/app/lib/steam/bin_steam.sh` (or via a symlink `/app/lib/steam/steam` after prepending `/app/lib/steam` to the `PATH`, if having it available in the `PATH` as `steam` is desirable).

That would make it less likely that users will get broken behaviour by running it with `--command=steam`. If https://github.com/flatpak/flatpak/pull/5404 gets merged, it would also allow the `steam` executable to be exported as a more explicit entry point `/var/lib/flatpak/com.valvesoftware.Steam+steam` alongside `/var/lib/flatpak/com.valvesoftware.Steam+steamcmd`.

`/app/bin/steamcmd` is already a symlink to `steamcmd-wrapper`, ensuring that `--command=steamcmd` goes via the wrapper as expected, instead of running Valve's code directly.

**Comment by nanonyme** [comment]
@smcv this sounds fine, I actually considered it years back but wasn't sure if it was considered supported approach from Steam side.

**Comment by nanonyme** [comment]
This is now changed in beta.
