### ISSUE TITLE
Steam overlay input issues

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [flathub/com.valvesoftware.Steam#1079]
**Game information**
Not a game

**Distribution name and version where applicable**
Distro: Fedora 38 
Steam:Apr 28
1682708537

**Flatpak info**
Version: Flatpak 1.15.4
gl-drivers: default
host

**Problem description**

When I open the steam overlay in many games and I try to type a message to my friend I have to press each character on the keyboard twice for it to be registered.
**Does this issue reproduce with native Steam**

Yes

**Comment by nomadfh** [comment]
I also have this issue and have always had this issue.
