### ISSUE TITLE
[bug] Ps3 controller doesn't work

### ISSUE THREAD

**Issue by user5145** [flathub/com.valvesoftware.Steam#108]
Ps3 controller doesn't work. I don't have any idea why. Controller works normally on html5gamepad.com within firefox. I configured it according to this guide https://wiki.archlinux.org/index.php/Gamepad#Connecting_via_Bluetooth 
It was tested with both usb and bluetooth.
Flatpak version is 0.99.3.
Steam was installed by gnome-software and followed by sudo flatpak update command.

**Comment by TingPing** [comment]
It works fine here you just need to have the controller connected before launching Steam.

**Comment by user5145** [comment]
It was it. :) Now, I'm able to connect it using usb and this connection works everywhere.
By third party controller handling did you mean "generic gamepad configuration support"?

Unfortunately, bluetooth is buggy. It seems that steam is able to detect (via bluetooth) my ps3 controller and it's listed in settings (Steam -> settings -> controller -> general steam controller) and controller works using big picture mode, but it doesn't work in games :(
I tested it with different configurations everything gives the same effect. I used different general steam controller option's check boxes, x11, wayland, nvidia, nouveau, desktop, laptop, lightdm, gdm, gnome 3.28, terraria, n++).

**Comment by TingPing** [comment]
>  By third party controller handling did you mean "generic gamepad configuration support"?

Yea, at least I had problems with that.

**Comment by user5145** [comment]
Ok. I don't know what to think about it. Now even terraria works for me and my controller is detected as a generic one (sometimes it's not detected at all, but input works), but previously is was recognized as a ps3 controller. 

It's for sure not a flatpak issue, but steam so i will close it.
Yet one question have you checked ps4 controller checkbox?

**Comment by TingPing** [comment]
>  Yet one question have you checked ps4 controller checkbox?

No I don't think that applies to ps3 controllers at all.
