### ISSUE TITLE
Can't launch Steam anymore, can't update it through Discover

### ISSUE THREAD

**Issue by Maxtimot** [flathub/com.valvesoftware.Steam#1109]
I got a recent nvidia driver update, but since then there's a bunch of requested updates I can't apply, including Steam, it returns the following error message instead (my config is set in French):
```
Aborted due to failure (While pulling runtime/org.freedesktop.Platform.GL.nvidia-535-54-03/x86_64/1.4 from remote flathub: Writing content object: Entrée nécessitant plus de données)
```
The other requested updates that shows this same message are from Freedesktop, Gnome, and KDE.

When I try to launch Steam, it either gets stuck at the "logging user info" loading screen, or it starts only to immediately close the window. In this case the app seems to be still running in the background but I can't get it to show anything.
Running it through Konsole does not show any specific error message.

I run using Fedora Kinoite 38, more details under the cut:
<details><summary>System details</summary>
<p>

 OS: Fedora 
 Kernel: x86_64 Linux 6.3.8-200.fc38.x86_64
 Uptime: 13m
 Packages: 1713
 Shell: bash 5.2.15
 Resolution: 3286x1080
 DE: KDE 5.107.0 / Plasma 5.27.5
 WM: KWin
 GTK Theme:  [GTK2/3]
 Icon Theme: breeze-dark
 Disk: 900G / 5,5T (17%)
 CPU: Intel Core i5-3450 @ 4x 3.1GHz [40.0°C]
 GPU: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
 RAM: 4208MiB / 15924MiB

</p>
</details>

**Comment by srsam89** [comment]
This fun was caused by an ostree update that slipped out, breaking installations from flatpaks. 

https://github.com/ostreedev/ostree/issues/2900

**Comment by Maxtimot** [comment]
> 

Okay so through this thread I've seen they were working on a fix three days ago, I went outside my house during that time. Today I booted up my computer, updated via OSTree and now I'm able to update my apps via Discover. So this has been officially fixed.
