### ISSUE TITLE
Do not use discrete gpu by default

### ISSUE THREAD

**Issue by kaanyalova** [flathub/com.valvesoftware.Steam#1110]
Revert #559

Steam always launches using the discrete GPU, which may not always be desired especially on laptops, users can launch using discrete GPU by right clicking and selecting an option (at least on Gnome) or by setting it using launch options for games.

**Comment by serhii-nakon** [comment]
Looks like I can not run Steam due this... I can run only from terminal using iGPU. If i trying to run Steam using discrete graphics by setting DRI_PRIME=1 or just from clicking UI icon I have infinite loop of Steam restarts.

**Comment by kaanyalova** [comment]
> Looks like I can not run Steam due this... I can run only from terminal using iGPU. If i trying to run Steam using discrete graphics by setting DRI_PRIME=1 or just from clicking UI icon I have infinite loop of Steam restarts.

I had the exact same issue. You can manually edit the .desktop file on `~/.var/lib/flatpak/exports/share/applications/com.valvesoftware.Steam.desktop` as a workaround.

**Comment by jntesteves** [comment]
Merged in #1086
