### ISSUE TITLE
CS:GO Failed to reach any official servers

### ISSUE THREAD

**Issue by pschichtel** [flathub/com.valvesoftware.Steam#112]
Upstream issues:
- https://github.com/ValveSoftware/csgo-osx-linux/issues/1678 (CSGO)
- https://github.com/ValveSoftware/steam-for-linux/issues/5545 (Steam)

The upstream issues mention, that the issue is solved by the latest stable update and people confirmed it working after the update release. I have updated my steam in flatpak to the latest release, but the issue persists.

It still only works, as suggested in the issues, by supplying `--env=LC_ALL=C`.
Not sure if this is the right place to report this.

**Comment by pschichtel** [comment]
I'm aware of that and I did receive the update that is supposed to fix the problem (which it did for seemingly anyone else), but it didn't fix it for me. That is why I suspect the flatpak package to still cause this.

**Comment by nanonyme** [comment]
The curious bit is the problem was externally reported only with beta Steam, not proper Steam. You're running latter, right?

**Comment by pschichtel** [comment]
The issue has been introduced with the chat beta and has finally been fixed with the stable update. I've updated to the stable version, yes.

**Comment by pschichtel** [comment]
Given the workaround sets LC_ALL=C this seems to be a locale problem, so is it possible the flatpak container might be missing some locale information, isn't it?

**Comment by nanonyme** [comment]
Maybe although it sounds like the fix included changing some configuration file not to contain special characters. You could try running command locale both outside and inside Flatpak sandbox. You can get shell in latter through
flatpak run --command=bash com.valvesoftware.Steam

**Comment by pschichtel** [comment]
`locale` returns the same output on both sides, including `LC_ALL=` (no value set).
I'm thinking about just removing the steam flatpak and all the things it stored and installing it freshly. Maybe a config has been corrupted during the beta and not properly recovered on linux.

**Comment by nanonyme** [comment]
LC_ALL is "never" supposed to be set. It's a mass override. Normally LC_* values are handled individually.

**Comment by pschichtel** [comment]
Setting steam up freshly did not help, so it's not some messed up file from the beta.

**Comment by nanonyme** [comment]
In theory it's simple to add environment override into the app but LC_ALL=C is such a hammer solution that I don't like doing that without further information on what exactly causes this. It could very well have side-effects

**Comment by nanonyme** [comment]
Can you confirm through relevant logs and md5sums that this is actually same issue and doesn't just look the same?

**Comment by nanonyme** [comment]
I was discussing with upstream and LC_ALL=C should be a no-op assuming up-to-date Steam so something is off here. 
FWIW I'm just now updating also the bundled components through https://github.com/flathub/com.valvesoftware.Steam/pull/119 since noticed there had been a recent update. Not expecting it to change anything, your issues aren't even mentioned in changelogs

**Comment by nanonyme** [comment]
Did you by the way touch contents under .var/app when setting up Steam freshly?

**Comment by pschichtel** [comment]
> In theory it's simple to add environment override into the app but LC_ALL=C is such a hammer solution that I don't like doing that without further information on what exactly causes this. It could very well have side-effects

I completely agree.

> Can you confirm through relevant logs and md5sums that this is actually same issue and doesn't just look the same?

Which logs/files are you thinking of? I can not really guarantee it's the same issue, but the behavior is exactly the same and the same workaround works, so I'm pretty certain. I start CS:GO, try to search a competitive game and after a few moments I get a message telling me it cannot reach official servers. From the upstream reports this also happens for Dota in case you want to test anything.

> Not expecting it to change anything, your issues aren't even mentioned in changelogs

Yep, nothing changed with the new version.

> Did you by the way touch contents under .var/app when setting up Steam freshly?

I completely removed `.var/app/com.valvesoftware.Steam` after removing the flatpak first. I have all my games in external libraries, so all it takes is logging in and adding the libraries back in.

Btw I'm also not using any crazy locale on my system: `en_US.UTF-8`.

**Comment by nanonyme** [comment]
Well, the Valve dev said Steam now ignores locale for this purpose so there's something weird going on

**Comment by pschichtel** [comment]
I'm wondering if anyone else has the same issue with the flatpak or if the problem exists only on my system. Do you have CS:GO or Dota to test this as well?

**Comment by nanonyme** [comment]
Nope, I don't have either in my catalogue

**Comment by pschichtel** [comment]
I'll try to reproduce on a few other systems and get back to you. Dota would free AFAIK and I'd be open to sponsor a CS:GO key to get this fixed.

**Comment by nanonyme** [comment]
I can take a look at Dota later if it's free. What exact locale did you have again?

**Comment by pschichtel** [comment]
That would be great! I use locale `en_US.UTF-8`.

**Comment by nanonyme** [comment]
Could you please also attach output from help->about steam?

**Comment by pschichtel** [comment]
![image](https://user-images.githubusercontent.com/526104/43608001-4ca331ea-96a0-11e8-8140-74aefef4d718.png)
And Dota 2.

**Comment by nanonyme** [comment]
That is actually interesting. The version number is significantly higher than mine. I wonder if that's still a beta build since I've been repeatedly wiping my installation to test a cloud sync bug so I should have up to date Steam

**Comment by pschichtel** [comment]
![image](https://user-images.githubusercontent.com/526104/43611118-6be1dcc0-96a8-11e8-9502-6bc1796e4c0d.png)
Just checked, it's not^^

**Comment by pschichtel** [comment]
I have also checked with a mate, he has the same problem.

**Comment by nanonyme** [comment]
Also why I grew suspicious is your version is identical to #91 in logs

**Comment by pschichtel** [comment]
Do you mean my steam thinks its "out of beta" but it's really not? The automatic updates came up for me. I tested the early beta of the chat feature, then disabled the beta as I found out about this problem and then it recently updated normally on the stable channel and I received the new chat stuff together with this bug. So it updated from the "good" old stable version to the "broken" new version by itself.
Also an issue that may or may not be related to the flatpak: The steam client is not aware of the games I have, so the context menu of on friends does not show an option to launch their game even if I have it installed.

Haven't mentioned here so far: My host system is Archlinux with Flatpak 0.99.3

**Comment by nanonyme** [comment]
The problem is I haven't found a good source for the information of what is the up to date version in stable

**Comment by pschichtel** [comment]
I could try to install Steam directly on my system this evening to test if it's also happening there and I can also post a screenshot of the about screen then.
If Archlinux is not a reliable source, I'd guess SteamOS might be.

**Comment by pablodav** [comment]
Try with:

    flatpak run com.valvesoftware.Steam --reset

**Comment by pschichtel** [comment]
@pablodav should removing `.var/app/com.valvesoftware,Steam` have the same effect?

**Comment by pablodav** [comment]
I think it does something else, this option --reset is owned by steam and don't know exactly what it does but helps in many cases.

**Comment by pschichtel** [comment]
@pablodav tried it, but it didn't help. From what I've seen it removes the steam runtime and the user session, but e.g. steam library folders stay untouched. So it's a little less aggressive than deleting `.var/app/com.valvesoftware.Steam`.

**Comment by pschichtel** [comment]
To confirm my assumption: It does work normally when I install Steam normally (`pacman -S steam steam-native-runtime`).

![image](https://user-images.githubusercontent.com/526104/43658382-075d0b06-9759-11e8-9812-c5b07db2bacf.png)

Seems to be the same version.

**Comment by pschichtel** [comment]
Just tried Steam without the native runtime as well: it still works.

**Comment by pschichtel** [comment]
Still a problem with the latest flatpak build

**Comment by nanonyme** [comment]
Not surprised, recent app updates just added some helper binaries into the sandbox as workarounds for game issues

**Comment by nanonyme** [comment]
Note that because of #41 I suspect not everyone shares the connection issue with Dota 2

**Comment by nanonyme** [comment]
Freedesktop runtime was just updated, might be worth it to retest

**Comment by pschichtel** [comment]
With the new runtime it finally works.

**Comment by Amosar** [comment]
How can I update to the enw runtime? I have do ```flatpak update``` and I still have this issue.

**Comment by Amosar** [comment]
I have still matchmaking issue, and it work with the native version
Steam + CSGO logs: https://pastebin.com/1qg2QgXC
System info (from steam) : https://pastebin.com/si94C8cX
The runtime information: 
``com.valvesoftware.Steam/x86_64/stable                  flathub 0469d744f676  -               3,3 MB       system,current``
And the steam info:
![](http://imgur.com/iicew64l.png)

**Comment by nanonyme** [comment]
Can you please update and retry now?

**Comment by Amosar** [comment]
I still have this issue with the latest patch :'(
``com.valvesoftware.Steam/x86_64/stable                  flathub 4cc924a6a2d8  -               3,3 MB       system,current``

**Comment by nanonyme** [comment]
You're running steam wrong and bypassing steam-wrapper

**Comment by Amosar** [comment]
How do I need to run it?
I have tried with
``amosar@amosar-linux:~$ flatpak run --command=bash com.valvesoftware.Steam/x86_64/stable
bash-4.4$ steam``
and with 
``/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper --file-forwarding com.valvesoftware.Steam @@u %U @@``

**Comment by nanonyme** [comment]
flatpak run com.valvesoftware.Steam/x86_64/stable

**Comment by Amosar** [comment]
:/ I have tried with this command but it still doesn't work.
https://pastebin.com/XJVTjZLf

**Comment by nanonyme** [comment]
I can see from your latest log that the timezone quirk is being applied

**Comment by pschichtel** [comment]
yep, the issue is back.

**Comment by pschichtel** [comment]
Is there a good guide somewhere on how to use flatpak-bisect ? Or do you already know which verison introduced the problem?

**Comment by nanonyme** [comment]
No and given how intensive data relocations have been done recently, bisect would be hard.

**Comment by nanonyme** [comment]
Could you please test if setting LC_NUMERIC=C is enough to fix this issue?

**Comment by nanonyme** [comment]
This came up in possibly related issue. If it does, I might consider applying that as a workaround in general. That should be largely harmless if it fixes the issue, may just make numbers look a bit non-native to some users

**Comment by nanonyme** [comment]
Does this still reproduce?

**Comment by pschichtel** [comment]
Works now.

**Comment by andres-jurado** [comment]
(Also posted this in #1678 ValveSoftware/csgo-osx-linux)

I still have this issue on Linux. 

OS: Ubuntu 18.04.2 64-bit.
Hardware: Ryzen 7-1700, RX 580 (8GB), 32 GB DDR4 RAM
Using the default drivers in Ubuntu (AMDGPU-PRO)

Steam API: v018
Steam package versions: 1550534751
**NOT** running steam beta

running steam with flatpak: 

`flatpak run --env=LC_ALL=C com.valvesoftware.Steam`
`flatpak run --env=LC_NUMERIC=C com.valvesoftware.Steam`

The MD5 checksum of `libsteamnetworkingsockets.so` is `fc7417c468b9b816cc8a9ebbdde5eb2e`

I have tried solutions posted elsewhere such as going to CSGO properties > LOCAL FILES > Verify Integrity of Game Files. 1 file fails the test and is downloaded. This **doesn't** solve the issue. 

This problem occurs with any configuration of the firewall (UFW). Currently is set to deny in and allow out.

Another piece of information is that this occurs randomly (I had been able to play in multiplayer for the last few weeks and suddenly couldn't).

This problem persists even if I launch steam without launching any other application, and no application running in the background except those that run in a vanilla Ubuntu install. 

I **don't** have any skins installed, and this problem persists if I reinstall steam.

**Comment by nanonyme** [comment]
Could you post a first 20 or so lines of log when you start Steam?

**Comment by andres-jurado** [comment]
It seems that it's working today! (can't reproduce this issue. Yesterday February 27, 2019 it wasn't working as I described in my post). Anyway, here's the output:

`flatpak run --env=LC_NUMERIC=C com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Overriding TZ to America/New_York
Running Steam on org.freedesktop.platform 18.08 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
[2019-02-27 15:09:45] Startup - updater built Feb 18 2019 22:08:53
[2019-02-27 15:09:45] Verifying installation...
[2019-02-27 15:09:45] Verification complete
surface_linux.cpp (2096) : Assertion Failed: None of the authentication protocols specified are supported
surface_linux.cpp (2096) : Assertion Failed: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1550534751)
assert_20190227150946_5.dmp[217]: Uploading dump (out-of-process)
/tmp/dumps/assert_20190227150946_5.dmp
[0227/150946.424067:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: browser
[0227/150946.460751:WARNING:crash_reporting.cc(281)] Failed to set crash key: UserID with value: 0
[0227/150946.460812:WARNING:crash_reporting.cc(281)] Failed to set crash key: BuildID with value: 1550527787
[0227/150946.460818:WARNING:crash_reporting.cc(281)] Failed to set crash key: SteamUniverse with value: Public
[0227/150946.460823:WARNING:crash_reporting.cc(281)] Failed to set crash key: Vendor with value: Valve
[0227/150946.508649:ERROR:gpu_process_transport_factory.cc(1026)] Lost UI shared context.
assert_20190227150946_5.dmp[217]: Finished uploading minidump (out-of-process): success = yes
assert_20190227150946_5.dmp[217]: response: CrashID=bp-d2b2cbc0-f26e-474e-9dec-6d62d2190227
assert_20190227150946_5.dmp[217]: file ''/tmp/dumps/assert_20190227150946_5.dmp'', upload yes: ''CrashID=bp-d2b2cbc0-f26e-474e-9dec-6d62d2190227''
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
CApplicationManagerPopulateThread took 4 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
CAppInfoCacheReadFromDiskThread took 45 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
`
