### ISSUE TITLE
Steam often fails to start

### ISSUE THREAD

**Issue by SootDan** [flathub/com.valvesoftware.Steam#1121]
**Distribution Name**
Arch Linux

**Flatpak Info**
Flatpak 1.15.4

**Flatpak Drivers**
default
host

**Problem Description**
Basically, after I open Steam, it shows the 'Verifying Steam installation' screen for a fraction of a second then closes. If I click open Steam enough, eventually it will open Steam in its entirety but it is tiring to do so and feels random.

**Does this issue reproduce with native Steam?**
Yes.

**Comment by nanonyme** [comment]
If it happens with native Steam, please open issue to https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by SootDan** [comment]
Thanks, I have done so.

**Comment by Ridhubharan** [comment]
I have the same issue when i launch it from apps grid, it just shows verifying steam page and vanishes. However when I launch it from terminal, it works without any issue. Weird!

Any updates on it?

**Comment by SootDan** [comment]
@Ridhubharan For me, it was the fact that I had two desktop environments. I removed one desktop environment, and it worked perfectly from then on.
