### ISSUE TITLE
steam mouse interference

### ISSUE THREAD

**Issue by BETLOG** [flathub/com.valvesoftware.Steam#1122]
```
user@betlogbeast:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar
DISTRIB_DESCRIPTION="Ubuntu 23.04"
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
```

**Problem description**
Steam interferes with mouse movement for about a minute after starting steam, and also for several minutes during the time a new proton prefix is generated/pre-game DX etc is being installed.
[Moving the mouse continuously in a circle shows frequent disruption of mouse input.](https://odysee.com/@BETLOG:0/steamMouseIssue:a)

This interferes with selecting library/menu items and does not inspire confidence in the efficiency of the steam interface.
I'm not sure but I think maybe even clicks are dropped from time to time.

**Does this issue reproduce with native Steam**
If "native steam" means `sudo apt install steam`, then yes.

Mouse: Logitech G502 LOL Hero
Piper 0.7 installed
https://gist.github.com/BETLOG/742155a431ca94b23c899b198a45745d

**Comment by nanonyme** [comment]
If reproduces with Steam you install with apt, then I suggest also filing into https://github.com/ValveSoftware/steam-for-linux/issues so the problem is visible to Valve.

**Comment by BETLOG** [comment]
my bad... not sure why i didnt notice this was the flathub git
