### ISSUE TITLE
getting SSL error with the beta branch 

### ISSUE THREAD

**Issue by ahjolinna** [flathub/com.valvesoftware.Steam#1129]
**Distribution name and version where applicable**
```
Operating System: openSUSE MicroOS 20230727
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.6-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 46.8 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
```

**Flatpak info**

flatpak --version :
`Flatpak 1.15.4`
flatpak --gl-drivers : 
```
nvidia-535-86-05
default
host
```

**Problem description**
I have been using the beta (flatpak) branch and now the latest update two days ago apparently has broken web view, downloading and gaming ...everything else does work just fine...I cant just see the steam page now

![image](https://github.com/flathub/com.valvesoftware.Steam/assets/6993072/5e165e8e-1d0b-4a2e-8671-7c12228c0f40)

**Does this issue reproduce with native Steam**

when reverting back to the stable (flatpak) branch everything works fine

**Comment by nikzasel** [comment]
same situation

**Comment by ahjolinna** [comment]
@nanonyme it seems you did the changes any idea what the problem is and could you fix it ...kiitos

**Comment by nanonyme** [comment]
App beta branch is using upcoming runtime release 23.08 whereas stable uses 22.08. Potentially there is some issue with that.

**Comment by doraskayo** [comment]
This should solve the issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/14557

**Comment by doraskayo** [comment]
> This should solve the issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/14557

This was eventually solved with https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/14558

An updated release is expected in the next few days.

**Comment by nanonyme** [comment]
This is now expected to be fixed through updating runtime.

**Comment by ahjolinna** [comment]
retested it and was working now for me just fine, so I will close this issue

thanks / kiitos

**Comment by nanonyme** [comment]
Good to hear. Freedesktop-sdk 23.08 is soon going to be released after which both stable and beta branches of this runtime switch to it.
