### ISSUE TITLE
Cannot install org.freedesktop.Platform.GL.nvidia-390-48

### ISSUE THREAD

**Issue by kylemiller3** [flathub/com.valvesoftware.Steam#113]
If I download from ```http://download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48-no-compat32.run``` in my broswer I can get the file but ```http://http.download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48-no-compat32.run``` appears to be the wrong url.

```
Installing: org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4 from flathub
[#=                  ] Downloading: 355.4 kB/46.7 MB (5.7 kB/s)    
Warning: Failed to install org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4: While downloading http://http.download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48-no-compat32.run: Socket I/O timed out

```

**Comment by nanonyme** [comment]
This should be filed against the relevant Freedesktop runtime, not a problem in the application

**Comment by kylemiller3** [comment]
Thanks wasn't sure if the problem was here or there.

**Comment by nanonyme** [comment]
https://github.com/flathub/com.valvesoftware.Steam/blob/master/com.valvesoftware.Steam.json references resource by name, not by URL
