### ISSUE TITLE
Unable to run on blank davinci rocky 8 linux. with security level minimal frensh blabla

### ISSUE THREAD

**Issue by NicTanghe** [flathub/com.valvesoftware.Steam#1131]
hello when i try to run steam oin Rocky 8 i get the following error.

bash-4.4$ flatpak run com.valvesoftware.Steam
bwrap: Can't mkdir parents for /app/lib/debug/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256

**Comment by nanonyme** [comment]
@doraskayo I suppose this is relataed to the debug GL extension?

**Comment by doraskayo** [comment]
@NicTanghe, it sounds like you have the `org.freedesktop.Platform.GL32.Debug.default` extension installed but not the `org.freedesktop.Sdk.Compat.i386.Debug` extension. As far as I remember this cannot work.

**Comment by doraskayo** [comment]
Also `com.valvesoftware.Steam.Debug` must be installed if one wishes to use `org.freedesktop.Platform.GL32.Debug.default` or `org.freedesktop.Platform.Compat.i386.Debug`.

**Comment by NicTanghe** [comment]
i have no clue what the issue was, but I’ve since switched distros to have everything i need working
