### ISSUE TITLE
Unknown feature type bluetooth / valid types devel multiarch

### ISSUE THREAD

**Issue by aldevel** [flathub/com.valvesoftware.Steam#114]
It seems something feature was set incorrectly and steam won't start.
My Steam starts with this:
/usr/bin/flatpak run --branch=stable --arch=x86_64 --filesystem=/mnt --command=/app/bin/steam-wrapper --file-forwarding com.valvesoftware.Steam @@u %U @@

and I get this result lately:
error: Unknown feature type bluetooth, valid types are: devel, multiarch

It's Flatpak 0.10.2 on KDE neon 5.13.

**Comment by nanonyme** [comment]
Which version of Flatpak are you running with?

**Comment by nanonyme** [comment]
It's the USB enablement. Get your distro to update to latest 0.10.3 at minimum. 0.10.4 is latest bugfix release in that series

**Comment by aldevel** [comment]
I forgot to mention it works without this problem on my other pc with Flatpak 0.99.3 on the same KDE neon 5.13. How is it possible? This bug didn't existed in previous versions?

**Comment by nanonyme** [comment]
Hmm, was expected to be fine (if no-op) for semi-new versions and work for new ones. Sounds like the change may need revering. @TingPing anyclue?

**Comment by nanonyme** [comment]
https://github.com/flatpak/flatpak/commit/c8c0df3fba458844d99ddd773244467fa4a35408 ping @alexlarsson as well

**Comment by nanonyme** [comment]
https://github.com/flatpak/flatpak/commit/858534069e21a674c28921d68bc299194e21cd8c should be in 0.99.3 unless I'm totally wrong

**Comment by aldevel** [comment]
Yep, for now, downgrade was the solution as I suspected. KDE neon gives ""unstable"" packages now and then. ppa:alexlarsson/flatpak was implemented on my other pc and I get it to the one with this Steam issue and it works now.

**Comment by nanonyme** [comment]
I reverted the bluetooth PR since this is sounding too hairy to sort out here and now. We obviously do want bluetooth support

**Comment by nanonyme** [comment]
See https://github.com/flathub/com.valvesoftware.Steam/issues/89 for original issue

**Comment by nanonyme** [comment]
@aldevel do you mean downgrade of Steam app or Flatpak?

**Comment by nanonyme** [comment]
Ok. I'd say the course of action then is to reintroduce the change, add warnings and create a ticket against Ubuntu so they update their Flatpak to 0.10.4

**Comment by aldevel** [comment]
Hmmm, I removed the ppa above and reinstalled flatpak and it works now on both pc with KDE neon. It was something with my system specifically but I wasn't able to find out what was it. Anyway 0.10.2 works, sorry for the false alarm.

**Comment by nanonyme** [comment]
There's no good way to enable bluetooth by default for now. It has been disabled again for now, closing this
