### ISSUE TITLE
Steam crashes due to missing runtime

### ISSUE THREAD

**Issue by joserebelo** [flathub/com.valvesoftware.Steam#1145]
**Distribution name and version where applicable**

* Arch Linux
* KDE Plasma 5.27.7 on Wayland

**Flatpak info**

```
$ flatpak --version
Flatpak 1.15.4

$ flatpak --gl-drivers
nvidia-535-104-05
default
host
```

**Problem description**

1. Start from a clean install
2. `flatpak run com.valvesoftware.Steam`
3. Steam downloads the updates, and then crashes (flatpak run log: [flatpak-run.log](https://github.com/flathub/com.valvesoftware.Steam/files/12501783/flatpak-run.log))

Checking `~/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs/steamwebhelper.log`, it looks like the runtime is missing (or looking in the wrong directory?):

```
/home/jose/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: /home/jose/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/1/scripts/switch-runtime.sh: No such file or directory
```

Looking for the missing script:

```
$ find ~/.var/app/com.valvesoftware.Steam -name switch-runtime.sh
/home/jose/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime.old/scripts/switch-runtime.sh
/home/jose/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/scripts/switch-runtime.sh
```

Copying the runtime (probably a bad idea, but it works) to the expected directory:

```
mkdir -p ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/1
cp -d -r \
  ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/* \
  ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/1
```

Steam now starts.

- Saw #1141, but the symptoms and only logs were different.

**Does this issue reproduce with native Steam**

No

**Comment by nanonyme** [comment]
Sounds like disk corruption, potentially as a result of Steam self-update failure. There might be some repair you can trigger.

**Comment by joserebelo** [comment]
I am able to reproduce this 100% of the time against a clean install. If that's the case, would an issue make more sense in the ValveSoftware/steam-for-linux repository?

**Comment by nanonyme** [comment]
Does it also reproduce with beta branch of this app?

**Comment by joserebelo** [comment]
Yup, exact same error.

1. Window with "Updating steam runtime environment"
2. Steam "shows the "Updating Steam..." downloading the update
3. Window with "Unpacking Steam Runtime"
4. Window with "Reconfiguring  Steam Runtime"

Then it takes a couple of seconds without showing any UI, and crashes with the same error.

**Comment by nanonyme** [comment]
Yeah, it sounds like there's a crash setting up Steam runtime. Is there anything more obvious visible if you run Steam from command line?

**Comment by joserebelo** [comment]
The command line output of `flatpak run com.valvesoftware.Steam` is in the first post, I don't see anything obvious in the logs.-

**Comment by doraskayo** [comment]
As far as I know the entirety of the `Steam` directory under `.local/share` is managed by Steam itself. It downloads its own runtimes and unpacks them.

This sounds like a Steam issue that should be reported in https://github.com/ValveSoftware/steam-for-linux/issues.

**Comment by dnkmmr69420** [comment]
It is crashing after five minutes of playing a game for me too for the flatpak

**Comment by nanonyme** [comment]
Unless you have as well corrupted Steam directory, your issue is likely unrelated and should not be mangled with this one.

**Comment by dnkmmr69420** [comment]
my steam directory is not corrupted

**Comment by nanonyme** [comment]
Then your problem is unrelated. File a new issue.

**Comment by joserebelo** [comment]
Not sure when or how it got fixed, but I am not able to reproduce the issue anymore.
