### ISSUE TITLE
[UPGRADE] Info: (pinned) runtime com.valvesoftware.Steam.Utility.gamescope branch stable is end-of-life

### ISSUE THREAD

**Issue by cassiofb-dev** [flathub/com.valvesoftware.Steam#1147]
Hi, thanks for the flatpak package. I'm using it for quite some time now and every time I upgrade my flatpaks I got this message:

```txt
Info: (pinned) runtime com.valvesoftware.Steam.Utility.gamescope branch stable is end-of-life, with reason:
   The gamescope Flatpak has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope.
Info: applications using this extension:
   com.valvesoftware.Steam
```

**Comment by nanonyme** [comment]
The message says you have installed com.valvesoftware.Steam.Utility.gamescope and should uninstall it.

**Comment by cassiofb-dev** [comment]
> The message says you have installed com.valvesoftware.Steam.Utility.gamescope and should uninstall it.

@nanonyme but flatpak says its used by com.valvesoftware.Steam this same message appears when I try to uninstall.

**Comment by nanonyme** [comment]
Pinned means you installed it. If you fail to uninstall the app extension, file a bug in flatpak repo. This app does not install that extension.
