### ISSUE TITLE
Fossilize memory leak with latest runtime update

### ISSUE THREAD

**Issue by valeth** [flathub/com.valvesoftware.Steam#1156]
Steam's fossilize leaks memory with some games when updating to the latest stable branch using runtime 23.08.

I've noticed a severe leak with Deep Rock Galactic, where it filled up 32GB of available memory in seconds.
Other games like Warframe don't seem to have this problem, other than the compilation step taking a very long time.

After downgrading to Flatpak commit `227a5e654498b890a13fc6612fdc3b12a4ebd943f1e764972a5ff0e65882b9a4` which uses the previous runtime 22.08, the issue went away.

System:
CPU: AMD Ryzen 5 7600X
GPU: AMD RX 6950XT
MEM: 32GB DDR5 (+8GB of swap)
Base OS: Arch Linux
Flatpak Version: 1.15.4

**Comment by doogie544** [comment]
this is a known issue with mesa 23.1.6

https://github.com/ValveSoftware/Fossilize/issues/231
https://github.com/ValveSoftware/Proton/issues/284
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9717
https://github.com/ValveSoftware/Fossilize/issues/230

Flatpak need to add 23.1.7 as a fix or maybe temporarily the Steam flatpak can to be re-released to temporarily use mesa 23.1.5 until 23.1.7 is added to the available flatpak (non-beta) runtimes

**Comment by valeth** [comment]
@doogie544 
The version I rolled back to is using Mesa 23.1.6 and does not leak memory.

**Comment by valeth** [comment]
The runtime seems to now have updated their Mesa version to 23.1.7, and this seems to fix the issue.
