### ISSUE TITLE
Steam won't start

### ISSUE THREAD

**Issue by ritchierope** [flathub/com.valvesoftware.Steam#1159]
**Game information**
Not game-related

**Distribution name and version where applicable**
 Ubuntu 20.04.6 LTS x86_64

**Flatpak info**
Output of following commands:

flatpak --version
Flatpak 1.14.4

flatpak --gl-drivers
default
host

**Steam version:**
Steam 1.0.0.78

**Problem description**
Starting steam with flatpak run com.valvesoftware.Steam. Steam won't start, gives me the following error message:

bwrap: Can't mkdir parents for /app/lib/debug/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256

**Does this issue reproduce with native Steam**
Have not tested

**Comment by doraskayo** [comment]
Possibly a duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/1131

See this comment for potential solutions: https://github.com/flathub/com.valvesoftware.Steam/issues/1131#issuecomment-1676437111

**Comment by ritchierope** [comment]
I have tried the potential solutions, none of them worked, unfortunately. I have run flatpak update several times, everything is up-to-date.

From org.freedesktop.Platform.GL32.Debug.default the following versions are installed:

22.08
22.08-extra
23.08
23.08-extra

(I tried removing 22.08 to try, whether the two installed versions are causing the problem, but 22.08 is used by a bunch of other flatpak apps, so I did not remove it.)

I also installed org.freedesktop.Platform.Compat.i386.Debug, version 23.08, but it did not make any change, the error message remains the same.

**Comment by doraskayo** [comment]
It seems that either having `org.freedesktop.Platform.GL32.Debug.default` or `org.freedesktop.Platform.Compat.i386.Debug` installed results in the reported error.

The reason seems to be that `com.valvesoftware.Steam.Debug` doesn't get mounted when running `com.valvesoftware.Steam`.

**Comment by doraskayo** [comment]
@ritchierope, you must install `com.valvesoftware.Steam.Debug` if you want to use additional `.Debug` extensions, such as `org.freedesktop.Platform.GL32.Debug.default` and `org.freedesktop.Platform.Compat.i386.Debug`.

**Comment by ritchierope** [comment]
@doraskayo Thank you for the tip, it worked! I would like to add that I did not want to use any of these debug extensions, Steam wanted to use them and was fine without them for some time, then after an update it just did not start...

**Comment by ritchierope** [comment]
Fixed.
