### ISSUE TITLE
OBS Vulkan Capture and Mangohud stopped working

### ISSUE THREAD

**Issue by VortexAcherontic** [flathub/com.valvesoftware.Steam#1160]
**Distribution name and version where applicable**
NAME="openSUSE MicroOS"
VERSION="20230906"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20230906"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20230906"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo-MicroOS"

**Flatpak info**
Flatpak 1.14.4
flatpak --gl-drivers
nvidia-535-104-05
default
host

**Problem description**
I apologize if this might be the wrong issue tracker to start with this issue but since this only happens with flatpak Steam (others like flatpak Bottles do still work fine) I'll start here:

Mangohud and OBS Vulkan Capture stopped working.
Usually you install them via flatpak as well as Steam and then enable them using either MANGOHUD=1 or OBS_VKCAPTURE=1 in a game launch option or as an override to the flatpak env of a given app.
This no longer happens to works since a couple of days.
As there where changes to the runtime-version in the last couple of days to this flatpak too I feel confident this could be related.

If just using the environment variables I get no further output from Steam or mangoud but if I try to run an app using:
```mangohud %command%``` I get:
```com.valvesoftware.Steam.desktop[24462]: /bin/sh: line 1: mangohud: command not found```

Which made me think if the PATH is somehow missing stuff:
flatpak runtime of Steam seems to have this set by default:
```/home/vortexacherontic/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin:/home/vortexacherontic/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/vortexacherontic/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/usr/bin:/app/bin:/app/utils/bin:/usr/bin```

Which seems to be missing something as bottles has these added to it's PATH:
```PATH=/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/usr/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin/:/usr/lib/extensions/vulkan/gamescope/bin/```
Whereas ```/usr/lib/extensions/vulkan/MangoHud/bin/:/usr/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin/:/usr/lib/extensions/vulkan/gamescope/bin/``` seems to be missing.

But even after adding the PATH with what bottles uses I couldn't get MangoHud or OBS Vulkan Capture to work.
Both, MangoHud and OBS Vulkan Capture, function by utilizing Vulkan Layers if this info is of any use.

**Does this issue reproduce with native Steam**
No. With Native Steam MangoHud still works (Tested from within a distrobox container on a fresh Tumbleweed image)
I've chosen Tumbleweed because it's what openSUSE MicroOS (aka Aeon) is based off.
Which makes me suspect something is missing in the flatpak build as of lately.

**Additional attempts I made to solve the issue (with no success)**
- Resting the Steam configs by deleting / renaming ~/.var/app/com.valvesoftware.Steam
- Reverting any possible changes I've made using flatseal
- Removing / renaming the entire ~/.var/app directory in case something else was broken not related to Steam.

**Comment by fastoslinux** [comment]
Is OBSVKCapture 23.08 installed?
Mangohud has not been updated to 23.08 yet.

**Comment by VortexAcherontic** [comment]
> Is OBSVKCapture 23.08 installed? Mangohud has not been updated to 23.08 yet.

Uhm how do I go to verify this?
Using flatpak list I only get:
```OBS VkCapture Plugin com.obsproject.Studio.Plugin.OBSVkCapture 1.4.2 stable flathub user```
Looking at the yaml of VKCapture it reads runtime.version stable. How do I know what stable actually is?

Reading your question it is required of Steam, OBSVkCapture and MangoHud to run with the same runtime version?

**Comment by doraskayo** [comment]
@VortexAcherontic, this should suffice: 
```
flatpak install flathub org.freedesktop.Platform.VulkanLayer.OBSVkCapture//23.08 org.freedesktop.Platform.VulkanLayer.MangoHud//23.08
```

**Comment by VortexAcherontic** [comment]
> @VortexAcherontic, this should suffice:
> 
> ```
> flatpak install --user flathub org.freedesktop.Platform.VulkanLayer.OBSVkCapture//23.08 org.freedesktop.Platform.VulkanLayer.MangoHud//23.08
> ```

Many many thanks all. Yes that worked!

Sorry for this report, didn't that the runtime was important here 😄
