### ISSUE TITLE
Can't get steam-<appid>.log for Proton compatibility reports

### ISSUE THREAD

**Issue by sanecito** [flathub/com.valvesoftware.Steam#1167]
**Game information**
N/A

**Distribution name and version where applicable**
Fedora Linux 38.20230915.0 (Silverblue)

**Flatpak info**
Flatpak 1.15.4
Drivers:
default
host

**Problem description**
According to the [repository instructions where you file Proton compatibility reports](https://github.com/ValveSoftware/Proton/issues), the logs are to be found in: `$HOME/steam-$APPID.log`

However,  the Flatpak doesn't have $HOME permissions, and when you try to override with a tool like Flatseal so it has filesytem=home permissions, Steam refuses to launch:

```
flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
WARNING:root:Found filesystem "home" in static permissions
ERROR:root:Refusing to launch in order to prevent issues; if you've added an override with access to some of the filesystems above, please remove it and see https://github.com/flathub/com.valvesoftware.Steam/wiki#i-want-to-add-external-disk-for-steam-libraries
```

Thus, based on where Steam tries to write Proton logs when `PROTON_LOG=1 %command%` is set as a game launch parameter, and what the Flatpak allows, it's impossible to get Proton logs to file compatibility reports.

I've also used KDE's Dolphin to search using `.*<appid>.*` on the `/` directory, but get 0 results which confirms that Steam Flatpak doesn't write somewhere else like some Flatpak related directory.

The desired situation is one where anyone running Steam via Flatpak can get Proton logs from some location without having to tweak permissions.

**Does this issue reproduce with native Steam**
Have not tested

**Comment by Equivocal90** [comment]
These should be created in `~/.var/app/com.valvesoftware.Steam/` by default.
It is also working correctly for me.

**Comment by sanecito** [comment]
Thanks for the correction. Dolphin on a Silverblue (GNOME) system only shows org.kde.Dolphin in `~/.var/app/` which explains why it didn't return the .log's in the search results. I'm able to access the path with GNOME's Files however.
