### ISSUE TITLE
gamescope runtime is EOL

### ISSUE THREAD

**Issue by Roman19S** [flathub/com.valvesoftware.Steam#1177]
The com.valvesoftware.Steam.Utility.gamescope runtime is end of life, and has been so for a while now. It has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope

**Comment by nanonyme** [comment]
Yes, you should be uninstalling com.valvesoftware.Steam.Utility.gamescope. You have manually installed it earlier.
