### ISSUE TITLE
Steam GUI turns "crazy" when I exit of Big Picture to go back to windowed mode

### ISSUE THREAD

**Issue by cold-distance** [flathub/com.valvesoftware.Steam#1192]
Hi, I use Fedora 39 Silverblue with GNOME 45 and the Wayland session and I see that the GUI of Steam client turns crazy every time I exit of Big Picture to go to the windowed mode. The wasn't there in the previous version of the app. The buggy version is 1698777785.

This a video to demonstrate the bug (it seems too heavy for GitHub). https://drive.google.com/file/d/1BnP6xBVDFi66A16YCM5l2UqAPtQAY6u-/view?usp=sharing

**Comment by nanonyme** [comment]
I suggest looking for upstream issue at https://github.com/ValveSoftware/steam-for-linux/issues and filing if there's none. Does not sounds like an issue with the app but rather Steam  itself.

**Comment by SrivatsanSenthilkumar** [comment]
There is an issue upstream https://github.com/ValveSoftware/steam-for-linux/issues/10167
