### ISSUE TITLE
Steam/any game crashes on launch with __GLX_VENDOR_LIBRARY_NAME=nvidia

### ISSUE THREAD

**Issue by amsyarzero** [flathub/com.valvesoftware.Steam#1198]
Hello, I would like to report an issue.
## Issue description
Starting from **yesterday (26th Nov 2023)**, after an NVIDIA driver upgrade, Steam crashes every single time I try to launch it. The culprit apparently is the environment variable `__GLX_VENDOR_LIBRARY_NAME=nvidia`.
## System info
```OS: Arch Linux x86_64
Host: HP Pavilion Gaming Laptop 15-dk0xxx
Kernel: 6.6.2-arch1-1
Uptime: 5 hours, 2 mins
Packages: 650 (pacman), 50 (flatpak)
Shell: bash 5.2.21
Resolution: 1920x1080
WM: sway
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: alacritty
CPU: Intel i7-9750H (12) @ 4.500GHz
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
Memory: 2289MiB / 15836MiB
```
## NVIDIA driver version
545.29.06
## Logs
| File | Description |
| --- | --- |
| [installation_bootstrap_log.txt](https://github.com/flathub/com.valvesoftware.Steam/files/13467462/installation_bootstrap_log.txt) | the `bootstrap_log.txt` file generated after reinstalling Steam |
| [launch_bootstrap_log.txt](https://github.com/flathub/com.valvesoftware.Steam/files/13467463/launch_bootstrap_log.txt) | the `bootstrap_log.txt` generated every time I try to launch Steam |
| [flatpak_launch_log.txt](https://github.com/flathub/com.valvesoftware.Steam/files/13467461/flatpak_launch_log.txt) | the wall of text generated every time I run `flatpak run com.valvesoftware.Steam` |
## Modifications to Steam Flatpak
Through Flatseal, I added these variables to run Steam with NVIDIA:
1. `__NV_PRIME_RENDER_OFFLOAD=1`
2. `__GLX_VENDOR_LIBRARY_NAME=nvidia`
3. `__VK_LAYER_NV_optimus=NVIDIA_only`
When I removed them from Steam, I added it to a game I'm testing it with (The Binding of Isaac: Rebirth). Note that **this issue happens with other games too**.
## Workarounds tried
| Workaround | Result |
| --- | --- |
| Reinstalling Steam and rebooting | Steam/game crashes |
| Running Steam in Big Picture mode (`flatpak run com.valvesoftware.Steam -bigpicture`) as described in #1040 | Steam/game crashes |
| Running Steam with `-gamepadui` flag enabled as described in #102 | Steam/game crashes |
| Reinstalling the latest NVIDIA drivers | Steam/game crashes |
| Running Steam with `steam -vgui` parameter | Steam/game crashes |
| Changing `nvidia_drm.modeset=1` to `modeset=1` (thanks @Syntist ) | Steam/game crashes |
| Properly putting `modeset=1` and `fbdev=1` under `/etc/modprobe.d/nvidia.conf` | Steam/game crashes |
| Replacing NVIDIA with `nvidia-open` | Steam/game crashes |
| Removing the variables listed above through Flatseal/launch options | Steam/game can run with integrated graphics only |
| **Removing only `__GLX_VENDOR_LIBRARY_NAME=nvidia`**| Steam/game can run with integrated graphics only |

**Comment by amsyarzero** [comment]
The native package from Arch's `multilib` repository launches as intended. However, I'm still keeping this issue open as it seems to be a problem with the Flatpak version of Steam rather than Steam itself.

**Comment by Syntist** [comment]
@amsyarzero Any luck? I am facing the same issue, I t was working fine before, but now i can't run any game on steam, While Lutris works fine.

**Comment by amsyarzero** [comment]
> Any luck? I am facing the same issue, I t was working fine before, but now i can't run any game on steam, While Lutris works fine.
 
@Syntist Unfortunately, no. I'll try reinstalling the NVIDIA drivers first (along with the Flatpak NVIDIA installations). If that doesn't work, then I'll try reinstalling Arch next.

**Comment by Syntist** [comment]
@amsyarzero I got it fixed, you using Wayland?
You might have to update the nvidia_drm.modeset=1 to modeset=1, now it's working for me. I don't know a silent change by nvidia driver, 545 was causing the issue.
`To enable DRM ([Direct Rendering Manager](https://en.wikipedia.org/wiki/Direct_Rendering_Manager)) [kernel mode setting](https://wiki.archlinux.org/title/Kernel_mode_setting), set modeset=1 and fbdev=1 [kernel module parameters](https://wiki.archlinux.org/title/Kernel_module_parameter) for the nvidia_drm module. The latter is required to tell the nvidia driver to provide its own framebuffer device instead of relying on efifb or vesafb, which don't work under simpledrm. For nvidia driver version < 545, the nvidia_drm.modeset=1 option must be set through [kernel parameters](https://wiki.archlinux.org/title/Kernel_parameters), in order to disable simpledrm`

**Comment by amsyarzero** [comment]
@Syntist changing `nvidia_drm.modeset=1` to `modeset=1` doesn't work for me. Where did you change it? Mine is located in GRUB's config line.

**Comment by amsyarzero** [comment]
Update: I found a similar issue on [Reddit](https://www.reddit.com/r/archlinux/comments/17z7azk/nvidia_driver_works_but_badalloc_insufficient/). Apparently, it's due to upgrading to version 545, and the solution is to downgrade to 535. I'll update here if it works.

**Comment by Syntist** [comment]
Any update regarding this, I tried 535 and it was slow. 
Sometimes game run but that's only once in a while

**Comment by amsyarzero** [comment]
This issue should now be fixed with future versions, I hope.

Closing this issue.
