### ISSUE TITLE
Support for pure 64 Bit systems

### ISSUE THREAD

**Issue by ShalokShalom** [flathub/com.valvesoftware.Steam#12]
![screenshot_20170624_212149](https://user-images.githubusercontent.com/6344099/27511428-0dc36eaa-5924-11e7-852e-66647d1f47b3.png)

There is no 32 Bit lib installed here: https://github.com/flathub/com.valvesoftware.Steam/blob/master/com.valvesoftware.Steam.json#L24

Is it possible to include lib32 also? Maybe in another release or so?

**Comment by TingPing** [comment]
Yea its not really possible for us to build 32bit libs easily atm, certainly on the todo list though.

**Comment by TingPing** [comment]
The error you posted is #2 btw.

**Comment by nanonyme** [comment]
@ShalokShalom does this still repro for you with latest runtimes?

**Comment by ShalokShalom** [comment]
It is reported by community members that it works now, thanks a lot.
