### ISSUE TITLE
OneShot: version `GLIBC_PRIVATE' not found

### ISSUE THREAD

**Issue by nekoedges** [flathub/com.valvesoftware.Steam#1234]
**Game information**
Name: OneShot
AppID: 420530
Build ID: 10086695

**Distribution name and version where applicable**
```
~ > cat /etc/lsb-release                                    
DISTRIB_ID="EndeavourOS"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME="rolling"
~ > cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
~ > cat /etc/arch-release 
~ > 
```

**Flatpak info**
```
~ > flatpak --version                  
Flatpak 1.15.6
~ > flatpak --gl-drivers 
default
host
```

**Problem description**
I installed OneShot, after that I clicked play and game just was not starting. I started Steam from terminal and after clicking play it gave me this:
```
/bin/sh\0-c\0/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=420530 -- /home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/OneShot/steamshim'\0
chdir "/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/OneShot"
ERROR: ld.so: object '/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/OneShot/steamshim: /usr/lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /home/edges/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/OneShot/librt.so.1)
```
**Also on native Steam?**
Yes

**Comment by nekoedges** [comment]
[https://steamcommunity.com/app/420530/discussions/1/6957562508420052277/](This link) should help. I'll try tomorrow

**Comment by nekoedges** [comment]
It helped

**Comment by JamesTheAwesomeDude** [comment]
As painful as this bug is, yeah, the workaround was just to delete (or rename to \*.bak) any library you *already have*

For Flatpak users, this will look something like

```bash
flatpak run --command=python com.valvesoftware.Steam -c "import collections,pathlib,pprint,sys;collections.deque(map(lambda p: (pprint.pprint(f'Disabling {p.stem} (in {p.parent})'), p.rename(p.with_suffix(p.suffix + '.bak'))), filter(lambda p: '.bak' not in p.suffix and any(p.stem == p0.stem for p0 in pathlib.Path('/usr/lib/i386-linux-gnu').iterdir()), pathlib.Path(sys.argv[1]).iterdir())),0)" ~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/OneShot/
```

**Comment by JamesTheAwesomeDude** [comment]
All told, here's the list of libraries Oneshot shipped with which I had to disable; it was about a third of them, pretty random looking:

> `libcairo.so.2` `libsystemd.so.0` `libdatrie.so.1` `libdbus-1.so.3` `libdrm.so.2` `libXfixes.so.3` `libepoxy.so.0` `libexpat.so.1` `libffi.so.6` `libudev.so.1` `libFLAC.so.8` `libfribidi.so.0` `libgcc_s.so.1` `libgcrypt.so.20` `libgdk-3.so.0` `libgdk_pixbuf-2.0.so.0` `libgio-2.0.so.0` `libGLdispatch.so.0` `libglib-2.0.so.0` `libgmodule-2.0.so.0` `libgmp.so.10` `libgobject-2.0.so.0` `libgpg-error.so.0` `libgtk-3.so.0` `libharfbuzz.so.0` `libICE.so.6` `libicudata.so.64` `libicui18n.so.64` `libicuuc.so.64` `libjpeg.so.8` `liblz4.so.1` `liblzma.so.5` `libXext.so.6` `libEGL.so.1` `libogg.so.0` `libopenal.so.1` `libpangoft2-1.0.so.0` `libpcre2-16.so.0` `libpixman-1.so.0` `libzstd.so.1` `libcrypt.so.1` `libreadline.so.8` `libresolv.so.2` `librt.so.1` `libXrandr.so.2` `libSM.so.6` `libstdc++.so.6` `libxcb-icccm.so.4` `libtiff.so.5` `libthai.so.0` `libuuid.so.1` `libvorbisfile.so.3` `libX11-xcb.so.1` `libvorbis.so.0` `libwayland-egl.so.1` `libwebp.so.7` `libX11.so.6` `libXau.so.6` `libxcb-keysyms.so.1` `libxcb-render-util.so.0` `libxcb.so.1` `libxcb-sync.so.1` `libxcb-util.so.1` `libxcb-xfixes.so.0` `libxcb-xinerama.so.0` `libXrender.so.1` `libz.so.1` `libSDL2-2.0.so.0` `libGLX.so.0` `libSDL2_image-2.0.so.0` `libxcb-shm.so.0` `libXcursor.so.1` `libatk-bridge-2.0.so.0` `libblkid.so.1` `libpango-1.0.so.0` `libfreetype.so.6` `libgthread-2.0.so.0` `libncursesw.so.6` `libspeex.so.1` `libgraphite2.so.3` `libpangocairo-1.0.so.0` `libxcb-render.so.0` `libatspi.so.0` `libfontconfig.so.1` `libpng16.so.16` `libxcb-image.so.0` `libxcb-randr.so.0` `libxcb-xinput.so.0` `libXdmcp.so.6` `libXinerama.so.1` `libxkbcommon-x11.so.0` `libatk-1.0.so.0` `libXdamage.so.1` `libXi.so.6` `libxkbcommon.so.0` `libxcb-shape.so.0` `libmount.so.1` `libSDL2_ttf-2.0.so.0` `libwayland-client.so.0` `libXcomposite.so.1` `libcairo-gobject.so.2` `libwayland-cursor.so.0` `libxcb-xkb.so.1`

The ones Oneshot shipped with but I did NOT have to disable were as follows:

> `ld-linux-x86-64.so.2` `libboost_program_options.so.1.69.0` `libbz2.so.1.0` `libcrypto.so.1.1` `libdbus-glib-1.so.2` `libdouble-conversion.so.3` `libevdev.so.2` `libgdk-x11-2.0.so.0` `libgtk-x11-2.0.so.0` `libgudev-1.0.so.0` `libinput.so.10` `libKF5WindowSystem.so.5` `libmodplug.so.1` `libmtdev.so.1` `libpcre.so.1` `libphysfs.so.1` `libQt5Core.so.5` `libQt5DBus.so.5` `libQt5EglFSDeviceIntegration.so.5` `libQt5Gui.so.5` `libQt5Network.so.5` `libQt5Svg.so.5` `libQt5Widgets.so.5` `libQt5X11Extras.so.5` `libQt5XcbQpa.so.5` `libruby.so.2.6` `libSDL_sound-1.0.so.1` `libsigc-2.0.so.0` `libssl.so.1.1` `libsteam_api.so` `libts.so.0` `libwacom.so.2` `libxfconf-0.so.2`
>
> `binascii.cpython-37m-x86_64-linux-gnu.so` `grp.cpython-37m-x86_64-linux-gnu.so` `libpython3.7m.so.1.0` `math.cpython-37m-x86_64-linux-gnu.so` `pyexpat.cpython-37m-x86_64-linux-gnu.so` `readline.cpython-37m-x86_64-linux-gnu.so` `resource.cpython-37m-x86_64-linux-gnu.so` `select.cpython-37m-x86_64-linux-gnu.so` `termios.cpython-37m-x86_64-linux-gnu.so` `unicodedata.cpython-37m-x86_64-linux-gnu.so` `zlib.cpython-37m-x86_64-linux-gnu.so` `_bisect.cpython-37m-x86_64-linux-gnu.so` `_blake2.cpython-37m-x86_64-linux-gnu.so` `_bz2.cpython-37m-x86_64-linux-gnu.so` `_codecs_cn.cpython-37m-x86_64-linux-gnu.so` `_codecs_hk.cpython-37m-x86_64-linux-gnu.so` `_codecs_iso2022.cpython-37m-x86_64-linux-gnu.so` `_codecs_jp.cpython-37m-x86_64-linux-gnu.so` `_codecs_kr.cpython-37m-x86_64-linux-gnu.so` `_codecs_tw.cpython-37m-x86_64-linux-gnu.so` `_ctypes.cpython-37m-x86_64-linux-gnu.so` `_datetime.cpython-37m-x86_64-linux-gnu.so` `_hashlib.cpython-37m-x86_64-linux-gnu.so` `_heapq.cpython-37m-x86_64-linux-gnu.so` `_lzma.cpython-37m-x86_64-linux-gnu.so` `_md5.cpython-37m-x86_64-linux-gnu.so` `_multibytecodec.cpython-37m-x86_64-linux-gnu.so` `_opcode.cpython-37m-x86_64-linux-gnu.so` `_pickle.cpython-37m-x86_64-linux-gnu.so` `_posixsubprocess.cpython-37m-x86_64-linux-gnu.so` `_random.cpython-37m-x86_64-linux-gnu.so` `_sha1.cpython-37m-x86_64-linux-gnu.so` `_sha256.cpython-37m-x86_64-linux-gnu.so` `_sha3.cpython-37m-x86_64-linux-gnu.so` `_sha512.cpython-37m-x86_64-linux-gnu.so` `_socket.cpython-37m-x86_64-linux-gnu.so` `_ssl.cpython-37m-x86_64-linux-gnu.so` `_struct.cpython-37m-x86_64-linux-gnu.so`

**Comment by mrsalo** [comment]
Worked for me as well, thanks!
Here is a script for it:
```bash
for lib in libcairo.so.2 libsystemd.so.0 libdatrie.so.1 libdbus-1.so.3 libdrm.so.2 libXfixes.so.3 libepoxy.so.0 libexpat.so.1 libffi.so.6 libudev.so.1 libFLAC.so.8 libfribidi.so.0 libgcc_s.so.1 libgcrypt.so.20 libgdk-3.so.0 libgdk_pixbuf-2.0.so.0 libgio-2.0.so.0 libGLdispatch.so.0 libglib-2.0.so.0 libgmodule-2.0.so.0 libgmp.so.10 libgobject-2.0.so.0 libgpg-error.so.0 libgtk-3.so.0 libharfbuzz.so.0 libICE.so.6 libicudata.so.64 libicui18n.so.64 libicuuc.so.64 libjpeg.so.8 liblz4.so.1 liblzma.so.5 libXext.so.6 libEGL.so.1 libogg.so.0 libopenal.so.1 libpangoft2-1.0.so.0 libpcre2-16.so.0 libpixman-1.so.0 libzstd.so.1 libcrypt.so.1 libreadline.so.8 libresolv.so.2 librt.so.1 libXrandr.so.2 libSM.so.6 libstdc++.so.6 libxcb-icccm.so.4 libtiff.so.5 libthai.so.0 libuuid.so.1 libvorbisfile.so.3 libX11-xcb.so.1 libvorbis.so.0 libwayland-egl.so.1 libwebp.so.7 libX11.so.6 libXau.so.6 libxcb-keysyms.so.1 libxcb-render-util.so.0 libxcb.so.1 libxcb-sync.so.1 libxcb-util.so.1 libxcb-xfixes.so.0 libxcb-xinerama.so.0 libXrender.so.1 libz.so.1 libSDL2-2.0.so.0 libGLX.so.0 libSDL2_image-2.0.so.0 libxcb-shm.so.0 libXcursor.so.1 libatk-bridge-2.0.so.0 libblkid.so.1 libpango-1.0.so.0 libfreetype.so.6 libgthread-2.0.so.0 libncursesw.so.6 libspeex.so.1 libgraphite2.so.3 libpangocairo-1.0.so.0 libxcb-render.so.0 libatspi.so.0 libfontconfig.so.1 libpng16.so.16 libxcb-image.so.0 libxcb-randr.so.0 libxcb-xinput.so.0 libXdmcp.so.6 libXinerama.so.1 libxkbcommon-x11.so.0 libatk-1.0.so.0 libXdamage.so.1 libXi.so.6 libxkbcommon.so.0 libxcb-shape.so.0 libmount.so.1 libSDL2_ttf-2.0.so.0 libwayland-client.so.0 libXcomposite.so.1 libcairo-gobject.so.2 libwayland-cursor.so.0 libxcb-xkb.so.1; do
    mv "$lib" "$lib.bak"
done
```

**Comment by Marocsalinux** [comment]
Actually this way broke the part when you have to open an app and open the game at the same time so what I do was not touching the file
libicudata.so.64 libicuuc.so.64 libicui18n.so.64
And the game work properly and also that part

**Comment by katnova** [comment]
The game would not start until I un-'bak' `libFLAC.so.8` &  `libSDL2_ttf-2.0.so.0`.

**Comment by Marocsalinux** [comment]
> The game would not start until I un-'bak' `libFLAC.so.8` & `libSDL2_ttf-2.0.so.0`.

probably you have an old pc since the version of sdl2 that oneshot uses is way to outdated I think idk I'm not too smart with this things
