### ISSUE TITLE
Big Picture mode doesn't display the boot animation and menu options become invisible

### ISSUE THREAD

**Issue by CiscoDeTours** [flathub/com.valvesoftware.Steam#1263]
**INFO**
---

**- Steam Client**

Steam Beta Branch:  Stable Client
Steam Version:  1709168962
Steam Client Build Date:  Wed, Feb 28 8:39 PM UTC -08:00
Steam Web Build Date:  Mon, Feb 26 4:21 PM UTC -08:00
Steam API Version:  SteamClient021

**- System**

~~~
~$ neofetch
 
DEVICE 
•PC: OMEN by HP Laptop 16-c0xxx 
 
SOFTWARE 
•Distro: Debian GNU/Linux 12 (bookworm) 
•Desktop: GNOME 43.9 
•Kernel: 6.6.15-amd64 
•Packages: 2567 (dpkg), 62 (flatpak) 
•Shell: bash 5.2.15 
 
COMPONENTS 
•CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 4.680GHz 
•GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
•GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
•Memory: 3,63GiB / 14,98GiB (24%)
~~~

**- Flatpak**

~~~
~$ flatpak --version

1.14.4
~~~

~~~
~$ flatpak --gl-drivers

default
host
~~~

**QUESTIONNAIRE**
---

**1. What's your problem with Steam?**

https://github.com/flathub/com.valvesoftware.Steam/assets/67841579/88b2ac8c-dd47-4e51-a33b-be3f19e82bb7

**2. Does this issue reproduce with native Steam?**
No.

**Comment by b-wize** [comment]
Also running into this issue after the Feb stable update. No boot animation, and no menu options in BPM

**Comment by sniperking0619** [comment]
Can confirm, same issue here started happening recently, using  an RX 6600 and R5 3600 on latest Manjaro GNOME LTS distro and latest Steam Flatpak.

**Comment by RobotRoss** [comment]
Also happening here. Using RX6900XT and 5800X3D; Fedora 39 GNOME.

**Comment by CiscoDeTours** [comment]
@b-wize @sniperking0619 & @RobotRoss 

I replicated this report in [Valve's repo](https://github.com/ValveSoftware/steam-for-linux/issues/10568) which has already been tagged; generate your Steam logs using this command  if you can:

 ~~~
tar -zcvf ~/steam-logs.tar.gz ~/.var/app/com.valvesoftware.Steam/.steam/steam/logs
~~~

Then upload the compressed file located in your home folder while commenting about this strange issue that have AMD dGPUs in common.

**Comment by poisonsnak** [comment]
Same issue here 

```
Steam Client
Steam Beta Branch: Stable Client
Steam Version: 1709168962
Steam Client Build Date: Wed, Feb 28 6:39 PM UTC -08:00
Steam Web Build Date: Mon, Feb 26 2:21 PM UTC -08:00
Steam API Version: SteamClient021
```
```
System
SOFTWARE
Distro: Debian GNU/Linux 12 (bookworm)
Desktop: KDE Plasma 5.27.5
Kernel: 6.1.0-18-amd64 (6.1.76-1)
```
```
COMPONENTS
CPU: AMD Ryzen 7 5800X
GPU: AMD ATI Radeon RX 6900 XT
Memory: 18.86GB / 32GB
```
```
Flatpak
flatpak --version
1.14.4

flatpak --gl-drivers
default
host
```

Since it's only people with AMD graphics maybe it's because the version of Mesa is so much newer in flatpak (24.0.1 vs. 22.3.6 in Debian 12)

**Comment by bnpfeife** [comment]
What's interesting is that previewing the startup movie from the settings works. You can access the settings /customization menu via the internet connection icon.

The issuet seems to transcend distribution and specific graphics hardware. It persists on Debian Bookworm and ArchLinux -- and on Intel/AMD (both running Mesa).

**Comment by poisonsnak** [comment]
If it helps narrow down the issue, it started after some updates I installed on March 1st.

The Steam client updated from 1708985249 to 1709168962.

Flatpak had a lot of updates. `flatpak history` doesn't show what version I went from/to so this is the best I can do

```
Mar  1 19:50:51 pull           org.freedesktop.Platform.Compat.i386                23.08       system       flathub
Mar  1 19:50:52 deploy update  org.freedesktop.Platform.Compat.i386                23.08       system       flathub
Mar  1 19:50:55 pull           org.freedesktop.Platform.GL.default                 23.08       system       flathub
Mar  1 19:50:55 deploy update  org.freedesktop.Platform.GL.default                 23.08       system       flathub
Mar  1 19:50:56 pull           org.freedesktop.Platform.GL.default                 23.08-extra system       flathub
Mar  1 19:50:56 deploy update  org.freedesktop.Platform.GL.default                 23.08-extra system       flathub
Mar  1 19:50:59 pull           org.freedesktop.Platform.GL32.default               23.08       system       flathub
Mar  1 19:50:59 deploy update  org.freedesktop.Platform.GL32.default               23.08       system       flathub
Mar  1 19:51:01 pull           org.freedesktop.Platform.GL32.default               23.08-extra system       flathub
Mar  1 19:51:01 deploy update  org.freedesktop.Platform.GL32.default               23.08-extra system       flathub
Mar  1 19:51:01 pull           org.freedesktop.Platform.Locale                     23.08       system       flathub
Mar  1 19:51:01 deploy update  org.freedesktop.Platform.Locale                     23.08       system       flathub
Mar  1 19:51:01 pull           org.freedesktop.Platform.ffmpeg-full                23.08       system       flathub
Mar  1 19:51:01 deploy update  org.freedesktop.Platform.ffmpeg-full                23.08       system       flathub
Mar  1 19:51:01 pull           org.freedesktop.Platform.ffmpeg_full.i386           23.08       system       flathub
Mar  1 19:51:02 deploy update  org.freedesktop.Platform.ffmpeg_full.i386           23.08       system       flathub
Mar  1 19:51:05 pull           org.freedesktop.Platform                            23.08       system       flathub
Mar  1 19:51:05 deploy update  org.freedesktop.Platform                            23.08       system       flathub
Mar  1 19:51:05 pull           org.gnome.Platform.Locale                           45          system       flathub
Mar  1 19:51:05 deploy update  org.gnome.Platform.Locale                           45          system       flathub
Mar  1 19:51:06 pull           org.gnome.Platform                                  45          system       flathub
Mar  1 19:51:07 deploy update  org.gnome.Platform                                  45          system       flathub
```

**Comment by b-wize** [comment]
> @b-wize @sniperking0619 @RobotRoss & @poisonsnak
> 
> I replicated this report in [Valve's repo](https://github.com/ValveSoftware/steam-for-linux/issues/10568) which has already been tagged; generate your Steam logs using this command if you can:
> 
> ```
> tar -zcvf ~/steam-logs.tar.gz ~/.var/app/com.valvesoftware.Steam/.steam/steam/logs
> ```
> 
> Then upload the compressed file located in your home folder while commenting about this strange issue that have AMD dGPUs in common.

Finally got around to adding my logs here and in the valve repo you linked. Thanks for that.

**Comment by b-wize** [comment]
Switching to client beta seems to have BPM working properly again.

**Comment by garhow** [comment]
> Switching to client beta seems to have BPM working properly again.

Switching to client beta fixed the issue for me as well.

**Comment by poisonsnak** [comment]
Fixed on the beta for me too.

**Comment by cold-distance** [comment]
Hi, sorry to be late, but I was playing to Deus Ex: Revision with the mouse and keyboard so I didn't need the Big Picture mode.

Everything perfect here.

**Comment by CiscoDeTours** [comment]
Steam version 1721173382 solved this issue in the stable channel. To avoid a laggy boot and increase responsiveness while using the menus, hardware acceleration options must be enabled.
