### ISSUE TITLE
Name of Application Incorrect when installed

### ISSUE THREAD

**Issue by Sapein** [flathub/com.valvesoftware.Steam#1265]
Recently I noticed that, when installed, the name of the Flatpak for Steam is incorrect.

It should be "Steam", but it is instead "Valve Corporation", this is shown when doing `flatpak list` and `flatpak info com.valvesoftware.Steam`

This might be related to: https://github.com/flatpak/flatpak/issues/5700 

Example of Incorrect information with `flatpak info com.valvesoftware.Steam`
![image](https://github.com/flathub/com.valvesoftware.Steam/assets/5852983/2981cf7f-f24c-42cd-a8a7-3a1f2f8c329e)

**Comment by smcv** [comment]
This is just an instance of flatpak/flatpak#5700 (for which a fix is in progress), and there doesn't seem to be anything actionable that can be done from the app side. I think this should be closed as "not planned".

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/com.valvesoftware.Steam/issues/1265#issue-2165510673

@Sapein, this should be closed, per https://github.com/flathub/com.valvesoftware.Steam/issues/1265#issuecomment-1978536013.
