### ISSUE TITLE
Grand ages: Medieval won't start

### ISSUE THREAD

**Issue by nintyfan** [flathub/com.valvesoftware.Steam#128]
Linux distribution and version

OpenSuSE Tumbleweed.
Flatpak version

Flatpak 0.11.8.3
Description of the problem

Won't load without any error. It doesn't depend how I launch the game. When launching from Steam - no any important message, When run Steam with --command=/bin/bash, ran Steam-wrapper in background, move into directory with and start ./App file - same error here.
Steps to reproduce

As above.

**Comment by nanonyme** [comment]
What does "same error" mean?

**Comment by nanonyme** [comment]
Heard rumours this might require OpenGL compatibility context 4.4 so the new Mesa release might fix this. @valentindavid any plans on handling those?

**Comment by valentindavid** [comment]
Yes. We will try to update Mesa to 18.2. If it breaks ABI, we will provide GL extension.

**Comment by nanonyme** [comment]
Mesa 18.2.1 made this to start working for me. Please re-open if problem persists

**Comment by nintyfan** [comment]
I updated runtime to newest version, try to start with mesa override string (I used it before, when trying to start game) and game starts, but only black screen is displayed and no sound. After removing mesa override string, game won't start. I don't remember how looking this string.
I used technology similar to NVidia Prime (AMD + Intel graphics and read before Prime can causes problem in this game - not only on Linux). I will test the game in next week,

**Comment by nintyfan** [comment]
Ok. I set environment variables to:
MESA_GL_VERSION_OVERRIDE=4.1 MESA_GLSL_VERSION_OVERRIDE=410
Game starts, but there's graphics error (some objects not render), in menu for example . When game starts only UI was rendered - no terrain, town, etc.

**Comment by nanonyme** [comment]
Please try without any environment variables set. Sounds like the remaining issues are GPU-specific.

**Comment by nintyfan** [comment]
When running without any variable game exits (now window or only for few seconds displayed). When running with DRI_PRIME only white screen is displayed, but game loads (music is playing in menu).  In both cases no debug information displayed in terminal.

**Comment by nanonyme** [comment]
Hmm, what kind of a dual GPU setup are you running, btw?

**Comment by nintyfan** [comment]
[code]
/sbin/lspci -nn | grep -E 'VGA|Display'
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02)
01:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] [1002:6900] (rev 83)
[/code]
I think this information is sufficient.

**Comment by nanonyme** [comment]
What does glxinfo output in the host for both of these GPU's?

**Comment by nanonyme** [comment]
Okay, so

1. The Intel GPU isn't even capable of doing this high GL levels. PRIME is indeed mandatory
2. The second card should be capable of GL compat 4.5. It's not clear why it doesn't work, could be related to the prime setup
3. Maybe we should set prime by default for Steam? Needs discussion with driver upstream for whether it has side-effects

**Comment by nintyfan** [comment]
I have trouble also with Civilization VI. I don't even know when problem starts. Civilization VI is very slow in game and in option I cannot select default graphic card. Game complains about missing lspci. Maybe these problems are related?

**Comment by nanonyme** [comment]
Agh, I wonder if they hardcoded the path. We install lspci under /app
Can you see from logs where it's looking?

**Comment by nintyfan** [comment]
Ok. I saw the debug messages (terminal output) and there's no complain about missing lspci. This message was displayed earlier. But cannot select/show video cards in graphic configuration window.

**Comment by nintyfan** [comment]
I installed rpm version (OpenSUSE) of flatpak in parell. In this case I cannot ran Grand Ages: Medieval with or without DRI_PRIME=1 env. Also CivVI still doesn't allow me to select graphic adapter. Ok - it looks I can select, but game doesn't display ID of GPU.

**Comment by nintyfan** [comment]
Everything worked. I use some kernel switch, but have other troubles. On never kernel/Mesa I can remove these switches and Grand Ages: Medieval still worked.

**Comment by nanonyme** [comment]
We now ship lspci in runtime (not in app) in expected path. It might have fixed this. Closing
