### ISSUE TITLE
MangoHud and vkBasalt stopped working without apparent reason

### ISSUE THREAD

**Issue by minisori** [flathub/com.valvesoftware.Steam#1280]
**Game information**
Any game.

**Distribution name and version where applicable**
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Flatpak info**
```
Flatpak 1.14.4
default
host
```

**flatpak info com.valvesoftware.Steam**
```
Valve Corporation - Juega a los juegos populares y los últimos lanzamientos

          ID: com.valvesoftware.Steam
  Referencia: app/com.valvesoftware.Steam/x86_64/stable
Arquitectura: x86_64
        Rama: stable
     Versión: 1.0.0.79
    Licencia: LicenseRef-proprietary
      Origen: flathub
   Colección: org.flathub.Stable
 Instalación: system
   Instalada: 45,5 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 98f034b154eed70b957bedcba0a5ce3785e70999b4aef85e1f6dd66f2eb15ff7
       Padre: 31e5dfccc4e4b287b5c07776bfe9b9168805f45443710b90a27b81aa3ac2093b
      Asunto: Update hwdata (a380271d)
       Fecha: 2024-03-05 13:07:50 +0000
```
**flatpak info --show-permissions com.valvesoftware.Steam**
[permisions.txt](https://github.com/flathub/com.valvesoftware.Steam/files/14757928/permisions.txt)

**Problem description**
Since last night MangoHud and vkBasalt stopped working without apparent reason. Looks like the libraries are not being preloaded when the game is launched, no matter if the game is native or using proton.
I use MANGOHUD=1 as env variable and I also tried with `mangohud %command%`, the game launches but there is no MangoHud nor vkBasalt.

- This is the output of flatpak [steam-flatpak.log](https://github.com/flathub/com.valvesoftware.Steam/files/14757550/steam-flatpak.log)
- This is the output of darksouls3, (NOTE: is use a mod for ultrawirde): 
[steam-374320.log](https://github.com/flathub/com.valvesoftware.Steam/files/14757802/steam-374320.log)

**Does this issue reproduce with native Steam**
I don't have native steam due to old mesa libraries in debian.

**Comment by zastrixarundell** [comment]
+, doesn't work for Elder Scrolls Online and Doom Eternal (haven't tested other games)

**Comment by Mershl** [comment]
+ on Fedora Silverblue (Gnome) 39 and 40. it still works for GL games.

**Comment by toupeira** [comment]
Same on Debian sid, using:

- com.valvesoftware.Steam 1.0.0.79
- org.freedesktop.Platform.VulkanLayer.MangoHud 0.7.1
- flatpak 1.14.5-1+b3

MangoHud doesn't work for Vulkan games, but does work for OpenGL games with `mangohud --dlsym`.

**Comment by C0Nd3Mnd** [comment]
Can confirm, stopped working under Fedora 39 (KDE, Wayland), tested kernel 6.7.10 and 6.8.1. OpenGL games work.

**Comment by zastrixarundell** [comment]
Anybody tried with that native version? Is this only happening on the flatpak version?

**Comment by C0Nd3Mnd** [comment]
> Anybody tried with that native version? Is this only happening on the flatpak version?

It's working fine for me with the rpm package from rpmfusion-nonfree.

**Comment by dominikzogg** [comment]
Same issue here. I meant its cause i already updated to fedora 40 (still beta) but it seems not the case, reading this issue.

**Comment by Sporif** [comment]
It seems Vulkan extensions are not being exposed in the Steam Pressure-Vessel subcontainer.

Here is a temporary workaround for MangoHud 64-bit (can be extended to other layers):
```
flatpak run --command=/usr/bin/bash com.valvesoftware.Steam
cp /usr/lib/extensions/vulkan/share/vulkan/implicit_layer.d/MangoHud.x86_64.json ~/data/vulkan/implicit_layer.d/
cp /usr/lib/extensions/vulkan/MangoHud/lib/x86_64-linux-gnu/libMangoHud.so ~/data/vulkan/
sed -i "s#/usr/lib/extensions/vulkan/MangoHud/lib/x86_64-linux-gnu#$HOME/.var/app/com.valvesoftware.Steam/data/vulkan#" data/vulkan/implicit_layer.d/MangoHud.x86_64.json
```

**Comment by maboroshinokiseki** [comment]
For @Sporif 's workaround, some games work, but some don't, and I can't figure out why 😅

**Comment by jntesteves** [comment]
I've sent PR #1281 with a workaround for this issue. Should hopefully be on the next version.

I'd recommend against applying Sporif's workaround if you don't know what you're doing. You will have to remove those files later, or they will break your setup in a future update. You can set an environment variable to solve this issue much more easily, but most people should just way for an update.

**Comment by C0Nd3Mnd** [comment]
Can confirm this PR also works for me. You can simply set the value of `XDG_DATA_DIRS` to what's in the PR if you don't want to install a test build and/or wait for this to appear in a release.

**Comment by minisori** [comment]
I confirm MangoHud and vkBasalt work with the test build.

**Comment by JamesMcMahon** [comment]
> I've sent PR #1281 with a workaround for this issue. Should hopefully be on the next version.
> 
> I'd recommend against applying Sporif's workaround if you don't know what you're doing. You will have to remove those files later, or they will break your setup in a future update. You can set an environment variable to solve this issue much more easily, but most people should just wait for an update.

I am not sure that PR fixes 32 bit apps, or at least one of the games I have that I can confirm to be 32 bit doesn't get fixed by adding `:/usr/lib/pressure-vessel/overrides/share` to  `XDG_DATA_DIRS`.

Can anyone else confirm one way or another?

**Comment by maboroshinokiseki** [comment]
> > I've sent PR #1281 with a workaround for this issue. Should hopefully be on the next version.
> > I'd recommend against applying Sporif's workaround if you don't know what you're doing. You will have to remove those files later, or they will break your setup in a future update. You can set an environment variable to solve this issue much more easily, but most people should just wait for an update.
> 
> I am not sure that PR fixes 32 bit apps, or at least one of the games I have that I can confirm to be 32 bit doesn't get fixed by adding `:/usr/lib/pressure-vessel/overrides/share` to `XDG_DATA_DIRS`.
> 
> Can anyone else confirm one way or another? @maboroshinokiseki

I just tested 2 32 bit games, The Witcher 2 and Oblivion, and they are working correctly.

**Comment by C0Nd3Mnd** [comment]
@JamesMcMahon Is the game that's not working a Linux-native OpenGL game by any chance?

**Comment by JamesMcMahon** [comment]
> I just tested 2 32 bit games, The Witcher 2 and Oblivion, and they are working correctly.

Awesome! Chalk this up to a false alarm then.

> @JamesMcMahon Is the game that's not working a Linux-native OpenGL game by any chance?

Game in question is [Zortch](https://store.steampowered.com/app/2443360/Zortch/). It's not Linux native but it could be OpenGL, not sure how to confirm that.

**Comment by C0Nd3Mnd** [comment]
> Game in question is [Zortch](https://store.steampowered.com/app/2443360/Zortch/). It's not Linux native but it could be OpenGL, not sure how to confirm that.

That explains it then. MangoHud can tell you if a game uses OpenGL or Vulkan (or DXVK), but in order to run an OpenGL game with MangoHud you have to set launch options to `mangohud --dslym %command%` in Steam. I just checked out the demo of Zortch and can confirm it's running via OpenGL and MangoHud works when launched like I explained.
