### ISSUE TITLE
Big Picture is very broken in the Flatpak version

### ISSUE THREAD

**Issue by cold-distance** [flathub/com.valvesoftware.Steam#1291]
Hi, I have an issue with the Big Picture mode. Previously I had [this problem](https://github.com/flathub/com.valvesoftware.Steam/issues/1192), that was general, but now I have this one that is much worse than the previous.

The opening of the Big Picture doesn't work and the left menu is disappeared, so I have to navigate through it using memorization. The gamepad is many times showed out of the center of the screen when I boot a game, but in this video I couldn't reproduce that. https://drive.google.com/file/d/1W1Mfefz_fLhh-KM04ArBl_3ZgoN1_JdO/view?usp=sharing

The current version of Steam I use is **1709846872** and the Steam API is **SteamClient021**. My system is Fedora 39 Silverblue with GNOME 45.5 on the Wayland session and my hardware is basically a Intel Core i5-12600K CPU with a RX 7600 GPU.

I tried to start the Big Picture mode on a virtual machine with Ubuntu 22.04 LTS and it worked, but I had basically the same problems using Fedora Kinoite 40 on a virtual machine with Steam Flatpak.

**Comment by charlesritchea** [comment]
Really wish these busted flatpak/snap versions weren't featured so prominently in the equally busted app stores

**Comment by SrivatsanSenthilkumar** [comment]
This is already being tracked on issue #1263. Please close this and follow that. Multiple copies of the issue is not helpful for the maintainer. Cheers

**Comment by cold-distance** [comment]
This seems a duplicate issue. Closing.
