### ISSUE TITLE
Fedora - missing dpkg

### ISSUE THREAD

**Issue by xerus** [flathub/com.valvesoftware.Steam#13]
I was able to run Steam once, on the second try it asks for dpkg

$ flatpak run com.valvesoftware.Steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically

**Comment by TingPing** [comment]
That is fine, steam runs without `dpkg`.

**Comment by meoow** [comment]
I have encountered the exact problem. The first run is working, the second time it complained about no dpkg when starting.
My OS is update to date ArchLinux.

@TingPing Why do you say is fine?

**Comment by TingPing** [comment]
You may have a problem but the `dpkg` warning isn't relevant.

**Comment by xerus** [comment]
hi @meoow in my case steam process did not exit (it stayed running). I had to kill it "manually"
