### ISSUE TITLE
Keyboard Input lag

### ISSUE THREAD

**Issue by mcphee11** [flathub/com.valvesoftware.Steam#1317]
**Game information**
subnautica

**Distribution name and version where applicable**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Flatpak info**
isntalled from PopShop flatpack is not able to be ran in the cli

**Problem description**
The mouse responds totally fine but keyboard presses have huge lag and the longer you are holding a button eg "w" to go forward the longer it takes to stop going forward. This game is running with Proton Experemential as its not officially supported on Linux. I have tried bluetooth keyboards but the same issue happens. The Laptop im using is a System76 machine with PopOS 22.04 as above running so the harware is built for this OS. 

**Does this issue reproduce with native Steam**
YES same issue happened with the deb install from the steam website. Hence I thought id try the flatpack from teh popShop to install it.

**Comment by mcphee11** [comment]
So I appear to of found the problem, it seems that ibus was causing the issue. All I had to do is run "ibus exit" and now it runs fine... for others reference I'm using ibus version 1.5.26. I did also diable "Repeat Keys" in the GNOME settings but that did not seem to make a difference in my case. ibus was the answer, I hope this is able to help someone else with this issue.

**Comment by nikodunk** [comment]
Thank you very much @mcphee11  - this solved my issue too on Bluefin under Steam/Proton. `ibus exit` did the trick!
