### ISSUE TITLE
Vulkan apps does not works with org.freedesktop.Platform 18.08

### ISSUE THREAD

**Issue by Shished** [flathub/com.valvesoftware.Steam#132]
OS: openSUSE Tumbleweed
Flatpak: 0.11.8.3
DE: Gnome 3.28

Vulkan games such as The Talos Principle, Serious Sam Fusion, unity3d games with -force-vulkan parameter stopped to work after runtime update..
Here is output from The Talos Principle:

```
INF:  * Desktop settings...
INF:  Color depth: 32-bit
INF:  Desktop resolution: 1920 x 1080
WRN:  [Vulkan] No instance layers found - validation disabled!
ERR:  Cannot set requested display mode 1920x1080: GfxAPI error: 
ERR:  Vulkan error: No physical devices attached!
ERR:  
INF:  (display mode already stopped)
INF:  Trying fallback modes...
WRN:  [Vulkan] No instance layers found - validation disabled!
ERR:  Cannot set requested display mode 1920x1080: GfxAPI error: 
ERR:  Vulkan error: No physical devices attached!
ERR:  
INF:  (display mode already stopped)
WRN:  [Vulkan] No instance layers found - validation disabled!
ERR:  Cannot set requested display mode 1024x768: GfxAPI error: 
ERR:  Vulkan error: No physical devices attached!
ERR:  
INF:  (display mode already stopped)
WRN:  [Vulkan] No instance layers found - validation disabled!
ERR:  Cannot set requested display mode 0x0: GfxAPI error: 
ERR:  Vulkan error: No physical devices attached!
ERR:  
INF:  (display mode already stopped)
WRN:  [Vulkan] No instance layers found - validation disabled!
ERR:  Cannot set requested display mode 0x0: GfxAPI error: 
ERR:  Vulkan error: No physical devices attached!
ERR:  
INF:  (display mode already stopped)
FTL:  Fatal error: Cannot set display mode.
```

Cannot get any more info because vulkaninfo app is not available in flathub repo.

**Comment by nanonyme** [comment]
That hints towards a framework issue then

**Comment by valentindavid** [comment]
I will test tomorrow on the machine with Nvidia card.

**Comment by valentindavid** [comment]
Found the issue. Filed bug upstream. Will patch it in not long.

Follow upstream bug: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/315

**Comment by jjardon** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/315 fixed, import of the new version of the runtime being done here: https://flathub.org/builds/#/builders/7/builds/16

**Comment by nanonyme** [comment]
How long do those builds normally take?

**Comment by jjardon** [comment]
@nanonyme last import took ~9 hours: https://flathub.org/builds/#/builders/7/builds/15

**Comment by Shished** [comment]
Runtime was updated and now everything works.
The update is about 1 MiB in size.
