### ISSUE TITLE
Missing 32-bit libraries crash make steamui.so fail, crashing steam on startup

### ISSUE THREAD

**Issue by Raxelgrande** [flathub/com.valvesoftware.Steam#1329]
Running on Arch Linux 6.10.5-zen1-1-zen, Gnome 46.4 Wayland

**Flatpak info**
  Flatpak Version: 1.15.0 
  flatpak Gl Drivers: default, host

**Problem description**
When i go launch steam, i get the following error:
You are missing the following 32-bit libraries, and Steam might not run:
libgtk-x11-2.0.so.0 
libbz2.so.1.0

Logs: 
[Flatpak Steam Logs Raxelgrande 00.txt](https://github.com/user-attachments/files/16663211/Flatpak.Steam.Logs.Raxelgrande.00.txt)

**Does this issue reproduce with native Steam**
Have not tested.

**Comment by Raxelgrande** [comment]
I had some corrupted files, ignore this report, im sorry.

**Comment by cherrryb0mb** [comment]
what did you actually do to resolve this? I'm having the exact same issue and I've tried everything from reinstalling steam and compat libs all the way to a clean reinstall of flatpak itself

**Comment by acerspyro** [comment]
I just experienced this issue today, same symptoms, same error. I'm on GNOME OS.

**Comment by nanonyme** [comment]
Please open new case rather than commenting on closed ones.

**Comment by nanonyme** [comment]
For the record, reinstalling app will not help in case of corrupted Steam runtime, there is persistent data inside .var/app/com.valvesoftware.Steam in user home.
