### ISSUE TITLE
Flatpak Steam issue with Adobe Substance 10.1.0

### ISSUE THREAD

**Issue by SysAdminShed** [flathub/com.valvesoftware.Steam#1355]
**Game information**
Adobe Substance Painter 2024 (10.1.0)

**Distribution name and version where applicable**
AlmaLinux release 9.4 (Seafoam Ocelot)

**Flatpak info**
Flatpak 1.12.9
flatpak --gl-drivers :

nvidia-550-120
default
host

**Problem description**
Hello,

We’re missing libraries under the Steam flatpak and knocking at the Adobe door hasn’t led anywhere so far.

To be more precise we are having the following issue with the latest version of Adobe Substance 10.1.0 under Steam (Flatpak) on AlmaLinux 9 (Tried 8 also) :

app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Substance 3D Painter 2024/Adobe Substance 3D Painter: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory

I’ve already opened issue and commented multiple time on the Steam community of the software, no joy.

https://community.adobe.com/t5/substance-3d-painter-bugs/substance-3d-painter-2024-10-1-0-broken-for-linux-steam/idc-p/14924204#M1774

https://steamcommunity.com/app/2718190/eventcomments/6495968678940369926?snr=1_5_9_&ctp=2

Also opened a thread on Flathub : https://discourse.flathub.org/t/flatpak-steam-issue-with-adobe-substance-10-1-0/7902

**Does this issue reproduce with native Steam**
Yes

**Comment by Melhart2** [comment]
🙏

**Comment by devlinnm** [comment]
Bumping, also having this issue

**Comment by bbhtt** [comment]
Ask Adobe to bump their libtiff version. 23.08 or 24.08 runtime has libtiff.so.6

libtiff.so.5 is an older version and we cannot provide a compat package for every old library because Adobe can't update their dependencies.
