### ISSUE TITLE
No sound in rocket league

### ISSUE THREAD

**Issue by Tids** [flathub/com.valvesoftware.Steam#137]
I'm just testing the new flatpak, now that we have the new runtime ant it's great to see that I can run it now in 4K at almost constant 60FPS ... (while before 720P at >30FPS ...)

However, one thing thats broken is sound for me. Not in general, but in rocket league. All other games are with sound so far.

RL also shows up on pulseaudio, just without sound. Sadly I can't see any errors somewhere.

**Comment by Tids** [comment]
I'm not sure if thats a game bug. I have completely normal sound with the normal version of steam. Its only the flatpak that does this.

**Comment by Amosar** [comment]
I also have this issue, the log don't seem to give good information.
https://pastebin.com/e08esuvh
Or maybe this line ``shell-init: error retrieving current directory: getcwd: cannot access parent directories: Bad file descriptor``
And the game freeze when I try to leave it

**Comment by valentindavid** [comment]
Thanks for the report. I suspect it is because we have not compiled libSDL2 against libsamplerate. I will fix that in runtime.

**Comment by valentindavid** [comment]
Upstream issue and MR:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/327
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/449

**Comment by Amosar** [comment]
Issue fixed with the latest runtime
