### ISSUE TITLE
Serious Sam Fusion 2017 license check failure

### ISSUE THREAD

**Issue by sterdev** [flathub/com.valvesoftware.Steam#14]
When I press any key on the game's splash screen in order to get into the main menu, the game gives out this message:
![SSF2017 failure](https://user-images.githubusercontent.com/15799238/27658817-f8ad3b8e-5c59-11e7-882f-681e888b0041.png)
The in-game console prompts some SSL certificate error.
![image](https://user-images.githubusercontent.com/15799238/27659111-fc41782c-5c5a-11e7-8df4-026bd0205112.png)

The bug may also affect Croteam's other games, such as The Talos Principle and standalone Serious Sam 3.

**Comment by TingPing** [comment]
Some tls problem, `strace` output like mentioned here could be useful: https://github.com/flathub/com.valvesoftware.Steam/issues/5#issuecomment-309327727

**Comment by adityashah1212** [comment]
Nope,The Talos Principle seems to work fine.

**Comment by nanonyme** [comment]
I know it's a bit silly question at this point but does this still repro?

**Comment by tiulkin** [comment]
I have the same problem on macOS 10.13.6

**Comment by ernestask** [comment]
I installed it just now and was able to start a single player game just fine.
