### ISSUE TITLE
Steam won't start since attempting cloud cleanup, relocation fails

### ISSUE THREAD

**Issue by matthew-cline** [flathub/com.valvesoftware.Steam#141]
After updating the Steam flatpk and starting I got a popup asking if I wanted to cleanup my Steam cloud stuff, which I said yes to since I don't use Steam cloud.  After doing this Steam won't start.  The problem appears to be in the steam wrapper after trying to relocate a bunch of Steam files.  Here is the
[Flatpak/Steam output](https://github.com/flathub/com.valvesoftware.Steam/files/2300646/steam.log) of one failed attempt to start it.
.

**Comment by nanonyme** [comment]
Looks like that's some back up directory it was trying to relocate. I'll add that to blacklist right now

**Comment by nanonyme** [comment]
BAK clearly has a copy of your Steam directory left over because of some failures. Steam was not copied over on purpose since it's massive

**Comment by nanonyme** [comment]
Can you please update and start Steam again?

**Comment by matthew-cline** [comment]
> Looks like that's some back up directory it was trying to relocate. 

Oops, yes, you're right, I put it there myself a while ago.  I removed BAK and Steam started fine.

**Comment by nanonyme** [comment]
Oh, I assumed from what you said that Steam created it. I guess I should remove the workaround then

**Comment by JKoehler11** [comment]
I ran into this same problem as well. After the migration ran, I received this error in the output:

Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 11, in <module>
    load_entry_point('steam-wrapper==1.0.0', 'console_scripts', 'steam-wrapper')()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 167, in main
    timezone_workaround()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 30, in timezone_workaround
    if localtime == read_file(candidate):
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 22, in read_file
    with open(path, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: '/usr/share/zoneinfo/America/North_Dakota'
