### ISSUE TITLE
Weird Menu items in Bound by Flames

### ISSUE THREAD

**Issue by adityashah1212** [flathub/com.valvesoftware.Steam#15]
It seems that items in menu and button names are not strings but some variables/Macros in the code of Bound by Flames.

![screenshot from 2017-07-05 17-53-44](https://user-images.githubusercontent.com/25403870/27886695-34d4f86c-61ab-11e7-9c54-6acec8be931e.png)

**Comment by TingPing** [comment]
And the menu is correct if steam is ran on the host?

**Comment by adityashah1212** [comment]
Well I did play this game Fedora 25 a month ago and everything was fine (of course on host), so I think everything should be same on Fedora 26.

**Comment by TingPing** [comment]
Probably some path issue, would need to run it under `strace`.

**Comment by adityashah1212** [comment]
Here is the strace result. I think it isn't able to find fonts or somthing on those grounds
[steam_bound_by_flame_strace.txt](https://github.com/flathub/com.valvesoftware.Steam/files/1126274/steam_bound_by_flame_strace.txt)

**Comment by TingPing** [comment]
I think you need to do `strace -f` so it picks up the game, that is just steams output.

**Comment by adityashah1212** [comment]
Sorry about that,  but if I run `strace -f` steam crashes before showing the main window. Here's the strace.
[bound_by_flame_strace.txt](https://github.com/flathub/com.valvesoftware.Steam/files/1126328/bound_by_flame_strace.txt)

**Comment by nanonyme** [comment]
Does this still reproduce?

**Comment by FastOSlinux** [comment]
![Captura de tela de 2019-10-01 17-40-05](https://user-images.githubusercontent.com/17401812/65998859-917ffe80-e472-11e9-86fe-c4b6320c7168.png)
