### ISSUE TITLE
Distance, ps3 controller not detected

### ISSUE THREAD

**Issue by Amosar** [flathub/com.valvesoftware.Steam#153]
Hi,
I have tried distance but i'm not able to use my ps3 controller to play, the game don't detect it.
This is log how native steam and flatpak steam handle controller.
And btw the controller work with game that have official controller support.

steam native controller support : https://pastebin.com/jCxcVHzv
steam flatpak controller support : https://pastebin.com/CtHAqrar

**Comment by nanonyme** [comment]
Possibly related to #8

**Comment by Amosar** [comment]
Yes that seems to be the issue, I haven't see it sorry

**Comment by nanonyme** [comment]
Yeah, need proper entry of this into FAQ
