### ISSUE TITLE
steam-wrapper makes incorrect assumption that current working directory is always home

### ISSUE THREAD

**Issue by t0kieu** [flathub/com.valvesoftware.Steam#155]
Hi I have clean installation of steam via flatpak and I have problem with running steam
```
flatpak run com.valvesoftware.Steam
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 11, in <module>
    load_entry_point('steam-wrapper==1.0.0', 'console_scripts', 'steam-wrapper')()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 229, in main
    mesa_shader_workaround()
  File "/app/lib/python3.7/site-packages/steam_wrapper.py", line 49, in mesa_shader_workaround
    shutil.copy2(candidate, current)
  File "/usr/lib/python3.7/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/t0ki/.var/app/com.valvesoftware.Steam/.config/.flatpak-info'
```
It looks like some files are missing. Is packaged in flatpak image all ?

**Comment by valentindavid** [comment]
What version of flatpak are you using?

**Comment by t0kieu** [comment]
1.0.0

**Comment by valentindavid** [comment]
Thanks for reporting. I have created a PR that should fix it. Let's see what @nanonyme has to say about it.

As a work-around if you want to play some games while this is being fixed, run the following command once:

```
touch ~/.var/app/com.valvesoftware.Steam/config/.flatpak-info
```

**Comment by nanonyme** [comment]
flatpak run --command=bash com.valvesoftware.Steam
followed by
ls -la
and attach the output?

**Comment by t0kieu** [comment]
```flatpak run --command=bash com.valvesoftware.Steam
bash-4.4$ ls -la
total 28
drwxr-xr-x 8 t0ki t0ki 4096 Aug 22 21:03 .
drwxr-xr-x 3 t0ki t0ki   60 Aug 22 21:03 ..
drwxr-xr-x 2 t0ki t0ki 4096 Aug 22 21:03 .ld.so
drwxr-xr-x 3 t0ki t0ki 4096 Aug 22 21:03 .local
drwxr-xr-x 3 t0ki t0ki 4096 Aug 22 21:03 .var
drwxr-xr-x 4 t0ki t0ki 4096 Aug 22 21:03 cache
drwxr-xr-x 2 t0ki t0ki 4096 Aug 22 21:03 config
drwxr-xr-x 2 t0ki t0ki 4096 Aug 22 21:03 data
bash-4.4$ ls config/
bash-4.4$ 
```

**Comment by nanonyme** [comment]
It looks like symlinks were never created. How have you been starting Steam?

**Comment by nanonyme** [comment]
It looks as if the migration never took place on your machine, you're missing .config completely and cache, config and data aren't symlinks

**Comment by t0kieu** [comment]
From terminal by command `flatpak run com.valvesoftware.Steam`.

**Comment by valentindavid** [comment]
Did you press "no"?

**Comment by nanonyme** [comment]
It shouldn't even ask if .config does not exist

**Comment by t0kieu** [comment]
@valentindavid I don't understand you :). When exactly press "no"?

**Comment by nanonyme** [comment]
@t0kieu is this a fresh install of Steam Flatpak app?

**Comment by valentindavid** [comment]
Is that a fresh installation then?

@t0kieu Do not worry. If you do not understand, then you were not asked.

**Comment by t0kieu** [comment]
Yes, It was fresh installation.

**Comment by nanonyme** [comment]
Ok. I'll need to obtain Flatpak 1.0.0 and see if the contents still gets properly created during first-time install or if there's a regression

**Comment by valentindavid** [comment]
@nanonyme in  the else, we need to make an empty directory.

**Comment by valentindavid** [comment]
Yes. I can reproduce with an empty installation.

**Comment by nanonyme** [comment]
I don't understand because I just verified that it works fine with flatpak 0.99.3 when I wiped .var/app/com.valvesoftware.Steam

**Comment by valentindavid** [comment]
OK, so `os.makedirs` is required  before copying `.flatpak-info`. Because the directory does not exist yet. I have reproduced and tested.

**Comment by valentindavid** [comment]
Got locked out of logging in. So cannot push PR.

```
diff --git a/steam_wrapper/steam_wrapper.py b/steam_wrapper/steam_wrapper.py
index e3566fa..6b07ff5 100644
--- a/steam_wrapper/steam_wrapper.py
+++ b/steam_wrapper/steam_wrapper.py
@@ -46,6 +46,7 @@ def mesa_shader_workaround():
         flush_mesa_cache()
     elif read_flatpak_info(current) != read_flatpak_info(candidate):
         flush_mesa_cache()
+        os.makedirs(os.path.expandvars("$XDG_CONFIG_HOME"), exist_ok=True)
         shutil.copy2(candidate, current)
 
 def read_file(path):
```

**Comment by nanonyme** [comment]
@valentindavid that will just make things worse

**Comment by t0kieu** [comment]
If I correct remember that, symbolic link was created, but directory `.config` was missing.

**Comment by nanonyme** [comment]
The migration first relocates everything from config to .config, then makes config a symlink to .config. That doesn't sound like a plausible scenario

**Comment by nanonyme** [comment]
I've difficulty debugging because I don't have Flatpak 1.0.0

**Comment by valentindavid** [comment]
To reproduce the bug, you need to start in `/home`, `$HOME/.var` or `$HOME/.var/app`. And start fresh steam.

**Comment by nanonyme** [comment]
Excellent, that was never noticed in initial analysis of the Cloud Sync. That allows it to be reproduced with 0.99.3 too

**Comment by nanonyme** [comment]
https://flathub.org/builds/#/builders/2/builds/3771

**Comment by nanonyme** [comment]
Should now be available as an update

**Comment by t0kieu** [comment]
You are welcome

**Comment by jadbox** [comment]
I have the latest release, but reinstalling Steam gives me this error (top post), but 'touching' the config file only yields another error. https://github.com/flathub/com.valvesoftware.Steam/issues/222
