### ISSUE TITLE
Gnome running on Wayland-Intel session, but Games run on nVidia

### ISSUE THREAD

**Issue by adityashah1212** [flathub/com.valvesoftware.Steam#16]
Well I don't have issues with the fact that everything including steam itself is using Intel graphics, while session itself is on Wayland and the games themselves run on nVidia graphics. Its just that it is really confusing why this is happening on an optimus laptop. I am using Fedora 26 beta with nvidia proprietary drivers installed and logged in with Wayland session (currently only works with intel driver). The nvidia-modeset is disabled, also fedora uses libglvnd. Considering all these factors I am not certain why it uses nvidia graphics inside container.

**Comment by TingPing** [comment]
This might be an issue to bring up for https://github.com/flatpak/flatpak

**Comment by adityashah1212** [comment]
I see I'll raise a issue over there. Thanks

**Comment by nanonyme** [comment]
Looks like the created remote ticket is flatpak/flatpak#902

**Comment by nanonyme** [comment]
To be honest, it sounds sensible to me that Steam would use the weaker GPU for its own GUI and run games with the more powerful GPU

**Comment by nanonyme** [comment]
Does this work the same way in native Steam?

**Comment by nanonyme** [comment]
Closing as no response and this isn't really an issue in the first place
