### ISSUE TITLE
I cannot run Steam, something with "libglnx/glnx-shutil.c:147:mkdir_p_at_internal: assertion failed: (!did_recurse)"

### ISSUE THREAD

**Issue by Hund** [flathub/com.valvesoftware.Steam#161]
I just found this repo, so I'm going to copy-paste the content from my issue [here](https://github.com/flatpak/flatpak/issues/1998):

## Linux distribution and version
Gentoo Linux

## Flatpak version
Version 1.0.0, installed via this[[1]] overlay with `seccomp` as the only enabled USE-flag.

[1]: https://github.com/fosero/flatpak-overlay

## Description of the problem
I does not start, it only gives me this message:
```
flatpak:ERROR:libglnx/glnx-shutil.c:147:mkdir_p_at_internal: assertion failed: (!did_recurse)
zsh: abort      flatpak run com.valvesoftware.Steam
```
## Steps to reproduce
Run command `flatpak run com.valvesoftware.Steam`.

**Comment by Maldela** [comment]
Same problem here on Arch with flatpak version 1.0

**Comment by LeandroStanger** [comment]
What happens when you enter this command?
>flatpak run com.valvesoftware.Steam --debug

**Comment by Hund** [comment]
After [this](https://github.com/flatpak/flatpak/issues/1998#issuecomment-415383332) comment I checked the folder and found these two symlinks there:

```
cache -> .cache
config -> .config
```

They where both pointing to dead ends and after creating the folders it worked for me. :)

**Comment by nanonyme** [comment]
Okay, so I really need to know whether this is still happening with up to date version of the app with no pre-existing .var/app/com.valvesoftware.Steam

**Comment by Maldela** [comment]
Moving .var/app/com.valvesoftware.Steam and restarting Steam worked for me.

**Comment by nanonyme** [comment]
May potentially be related to #161

**Comment by nanonyme** [comment]
Was able to repro by
1) Start Steam in one terminal from fresh
2) Start Steam in second terminal without exiting the first one
If I exit the first Steam, both work fine again. @alexlarsson ?

**Comment by nanonyme** [comment]
This is actually fairly probable to happen since if you start Steam through GUI, it will remain in bonkers state as long as the GUI is running

**Comment by nanonyme** [comment]
The conclusion was incorrect. The thing is that normally executing Steam bootstrap puts contents into cache, hence the directory does eventually get created. Changed migration code somewhat, now it creates empty directories in target directory including target directory itself if needed. On the upside the algorithm is also safer than makedirs because it won't start directory creation from / but given target so it should break if the parent of target does not exist

**Comment by nanonyme** [comment]
Managed to reproduce the original problem by adding a long sleep before executing Steam. Now with changed algorithm this no longer causes error as described in this issue

**Comment by nanonyme** [comment]
https://flathub.org/builds/#/builders/2/builds/3809

**Comment by nanonyme** [comment]
Looks like there's a bit of a queue in the build system. The fix will roll out soon. You can flatpak info com.valvesoftware.Steam and check subject to see whether you have the correct build

**Comment by nanonyme** [comment]
https://flathub.org/builds/#/builders/2/builds/3811 stalled currently waiting for worker to publish into repo
