### ISSUE TITLE
Most Games Won't Start [Fedora 28]

### ISSUE THREAD

**Issue by koenigjaeger** [flathub/com.valvesoftware.Steam#163]
OS: Fedora 28 
CPU: AMD® Ryzen 5 1600 six-core processor × 12 
GPU: Radeon RX 580 Series (POLARIS10 / DRM 3.25.0 / 4.17.14-202.fc28.x86_64, LLVM 6.0.0)
Wayland Display Manager

A couple of weeks ago most/ if not all of my games won't start. Going to their install directory and running their executable works but the steam launcher fails to start them. Launching steam from the terminal gives the following output. (Game tested to give the following output was Stellaris)
[steam_error.txt](https://github.com/flathub/com.valvesoftware.Steam/files/2316570/steam_error.txt)

Edit:
Looks like the issue isn't with all games. Avorion works for example.

**Comment by nanonyme** [comment]
Freedesktop runtime was updated to new release since then so could be a regression

**Comment by nanonyme** [comment]
Looks like I have multiple Stellaris games so I can see if I have time to see if this reproduces for me too

**Comment by nanonyme** [comment]
You could try running steam-wrapper with strace - f

**Comment by EspadaV8** [comment]
I was going to post about this issue but I wasn't sure if it was because I switched to the Steam beta client and messed around with the new Proton stuff.

@nanonyme how would I go about running the steam-wrapper?

**Comment by koenigjaeger** [comment]
@nanonyme I ran `flatpak run com.valvesoftware.Steam strace -f` and got the following.
[steam_error_2.txt](https://github.com/flathub/com.valvesoftware.Steam/files/2318811/steam_error_2.txt)

Also I am using the Steam Beta Client as well, but I saw the same issue without the beta.

**Comment by nanonyme** [comment]
Hmm, there seems to be a crash in that output

**Comment by valentindavid** [comment]
If you have nvidia drivers, and you updated them. Please remember to run `flatpak update` so that flatpak drivers match the version.

**Comment by valentindavid** [comment]
I would try to clean up manually the shader cache. Maybe for some reason the wrapper did not detect an update.

**Comment by valentindavid** [comment]
```
rm -rf .var/app/com.valvesoftware.Steam/cache/mesa_shader_cache
rm -rf .var/app/com.valvesoftware.Steam/cache/radv_builtin_shaders
```

If it still does not work, please try running:

```
flatpak run --env=MESA_GLSL_CACHE_DISABLE=true com.valvesoftware.Steam
```

**Comment by valentindavid** [comment]
If anything works, please report to us.

**Comment by EspadaV8** [comment]
I have tried manually clearing the cache with

```
rm -r $HOME/.var/app/com.valvesoftware.Steam/cache/mesa_shader_cache
```

I'll try deleting the other folder too.

I'm running an AMD card and also have the issue so it might not be related to driver updates.

**Comment by nanonyme** [comment]
Are you running amd pro or the opensource solution on host side?

**Comment by valentindavid** [comment]
Also what is the version of your kernel?

**Comment by EspadaV8** [comment]
So, deleting the shader cache folder doesn't help, but running with `--env=MESA_GLSL_CACHE_DISABLE=true` works. Loading RimWorld, Factorio and Rocker League all worked as where before they would crash before showing even the loading screen.

Kernel: 4.17.17-200.fc28.x86_64

Although I have also tried 4.17.12 and a 4.18.3 kernel that's in testing and they all has the same issue

Graphics driver I'm pretty sure is the opensource one, glxinfo shows the following

```
espadav8@localhost:~
> glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.25.0 / 4.17.17-200.fc28.x86_64, LLVM 6.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by EspadaV8** [comment]
`lspci` also has this

```
0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev c7) (prog-if 00 [VGA controller])
        Subsystem: Micro-Star International Co., Ltd. [MSI] Radeon RX 480
        Flags: bus master, fast devsel, latency 0, IRQ 50
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        Memory at f0000000 (64-bit, prefetchable) [size=2M]
        I/O ports at d000 [size=256]
        Memory at fe900000 (32-bit, non-prefetchable) [size=256K]
        Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu
```

So yeah, it is using the in-kernel `amdgpu` driver

**Comment by nanonyme** [comment]
Note Flatpak works so that you get another set of userspace drivers which talk with your kernel drivers. Running glxinfo outside Flatpak container produces slightly misleading results. Good to hear your kernel  driver is most likely stock opensource one though

**Comment by valentindavid** [comment]
@EspadaV8 Yes, please see if same as #130. Maybe you can contribute to information on upstream bug to Mesa that was filed. Specially a stack trace of crash would be nice.

**Comment by nanonyme** [comment]
Merging this into the other issue until debugging proves otherwise
