### ISSUE TITLE
sh: lspci: command not found

### ISSUE THREAD

**Issue by Holzhaus** [flathub/com.valvesoftware.Steam#164]
When starting steam from the command line, you can see that steam tries to use `lspci`, but does not find it:

```
Overriding TZ to Europe/Berlin
PATH: /home/user/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Proton 3.7
Running Steam on org.freedesktop.platform 18.08 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
sh: lspci: command not found
Installing breakpad exception handler for appid(steam)/version(1535062307)
[...]
```

And later:
```
[...]
Failed to init SteamVR because it isn't installed
sh: lspci: command not found
ExecCommandLine: "'/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 17,66 seconds
Generating new string page texture 79: 1024x256, total string texture memory is 1,49 MB
[...]
```

I don't know if this has any implications though.

**Comment by nanonyme** [comment]
Bogus failure. We should probably suppress  it unless we can provide machine info from within the app

**Comment by nanonyme** [comment]
Looks like this is part of pciutils https://mirrors.edge.kernel.org/pub/software/utils/pciutils/ https://en.m.wikipedia.org/wiki/Lspci

**Comment by EspadaV8** [comment]
If this is something that's wanted I actually have a patch that adds `lspci` into the pak.

**Comment by EspadaV8** [comment]
Looks like 3.6.2 has been released since then too.

**Comment by nanonyme** [comment]
I suspect you want default buildsystem with cleanups rather than simple

**Comment by nanonyme** [comment]
If you're just starting with designing these things, are you familiar with http://docs.flatpak.org/en/latest/first-build.html? You can do a full local build, install and test

**Comment by nanonyme** [comment]
Pull request is fine

**Comment by EspadaV8** [comment]
Yeah, that's actually what I started with (in the docs). I did try to copy the `xrandr` layout but couldn't get it to work without doing `simple`

```
Building module lspci in /home/espadav8/Workspace/com.valvesoftware.Steam/.flatpak-builder/build/lspci-4
========================================================================
Error: module lspci: Can't find autogen, autogen.sh or bootstrap
```

I'll open the PR and move the discussion there
