### ISSUE TITLE
[Steam Proton] Spore cannot detect GPU model and driver version

### ISSUE THREAD

**Issue by Shished** [flathub/com.valvesoftware.Steam#166]
When Spore is launched in flatpak environment, it drops this error:

```
Sorry, your graphics card is below our min spec.
The game will not run.
Please see the README for details.
```
GPU and driver detection is described in the file Spore/Data/Config/ConfigManager.txt
https://gist.github.com/Shished/a1ac11554e82bf859785a89ea4995c4c

Terminal output:
```
ERROR: Could Not Get Primary Adapter Handle
ERROR: Could Not Get Primary Adapter Handle
```

Game fails to detect the GPU and driver version and assumes that GPU is below the min spec.

This game works perfectly when launched in normal native Steam installation.

**Comment by nanonyme** [comment]
Sorry but I don't see from attachment any hint where it's reading its info from

**Comment by Shished** [comment]
Gams obtains the info from elsewhere and scripts in this file matches this info with predefined constants and decides which settings to use.
It is possible to edit this file and bypass the checks which will allow the game to run.
The file itself is not a problem.

**Comment by nanonyme** [comment]
Yes, the issue is likely in that other place

**Comment by nanonyme** [comment]
We don't currently ship glxinfo or lspci which might affect this

**Comment by nanonyme** [comment]
I could probably take a look if when I have time since I have Spore in my catalogue. I recall it was very unstable on Windows too though

**Comment by Shished** [comment]
This is 10 yo DX9 game, it works out of the bot with non-flatpak native Steam, i'm playing it on GTX660 with 396.54 driver and have no problems with it.

**Comment by nanonyme** [comment]
I mean it crashed frequently on me on different Windows machines. Anyway, need info what it's trying to query

**Comment by nanonyme** [comment]
I would appreciate someone with Mesa try to repro and see if this happens there too

**Comment by nanonyme** [comment]
Also, does running flatpak update help any here?

**Comment by Shished** [comment]
Flatpak apps and runtime are updated but flatpak itself is still on 0.11.8.3.

**Comment by nanonyme** [comment]
With nVidia you should run flatpak update after every driver update to be sure you have compatible runtime extension

**Comment by Shished** [comment]
I know that. Steam will not work if runtime extension is not updated.

**Comment by nanonyme** [comment]
Was just checking since the error sounded like Wine was having issues accessing your display driver

**Comment by Shished** [comment]
Many other Proton games works without problems for me in flatpak runtime.

**Comment by LeandroStanger** [comment]
@Shished Upgrade flatpak to 1.0

**Comment by Shished** [comment]
After the latest com.valvesoftware.Steam update (commit id 068c639fb903) Spore started to work without any errors.
