### ISSUE TITLE
I can not change the Steam profile photo

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#169]
![captura de tela de 2018-08-24 20-02-04](https://user-images.githubusercontent.com/26097419/44611630-9f2b7500-a7d8-11e8-8b86-18075fa823c8.png)

**Comment by nanonyme** [comment]
I don't understand. Do you mean you cannot access your pictures?

**Comment by valentindavid** [comment]
If you want to give Steam access to some part of your disk, you need to override access. For example if you want to give access to pictures, please use this command:

```
flatpak override --filesystem=xdg-pictures com.valvesoftware.Steam
```

Please refer to `flatpak-override` man page.

**Comment by nanonyme** [comment]
We could probably add read-only access by default if this is about that. We already do for music

**Comment by LeandroStanger** [comment]
@nanonyme add read-only access

**Comment by nanonyme** [comment]
@LeandroStanger is this what this ticket is about?

**Comment by LeandroStanger** [comment]
Yes

**Comment by LeandroStanger** [comment]
@nanonyme Get so good access to video and document folder
have some [Steam Software](https://store.steampowered.com/software/) that precision

**Comment by jurf** [comment]
Hm, not exactly excited about Steam having access to my photos. Not a big issue, but not preferable either.

**Comment by nanonyme** [comment]
Should not be ransomware-level thing as it's read-only. I agree, I don't totally like either music or pictures but they both have valid use cases.

**Comment by jurf** [comment]
Gah, I wish it used portals. 😃 But it’s not so much of an issue with Steam, more with all the games.

**Comment by nanonyme** [comment]
Good point. Is it even theoretically possible here to use portals?

**Comment by nanonyme** [comment]
Right, which they probably will not do because they don't want a Flatpak dependency
