### ISSUE TITLE
steam "minimize to tray". A bad thing today? [Discussion]

### ISSUE THREAD

**Issue by Tids** [flathub/com.valvesoftware.Steam#170]
On Linux we have that "problem" of many desktops. Some of them without tray support at all. Like Ubuntus new Main desktop GNOME (but they shipp tray support for now, I think) But this keeps me thinking If we should set the option

`STEAM_FRAME_FORCE_CLOSE=${STEAM_FRAME_FORCE_CLOSE:-0}`
So steam will minimize on close, instead of minimize to tray on close. We already do this for a long time on Manjaros Steam client without users going crazy. So that's not a problem here.

What do you think?

**Comment by nanonyme** [comment]
I don't understand the explanation. There is no Tray on eg Gnome and I think it just exits as expected there

**Comment by Tids** [comment]
@nanonyme when you just press on ![grafik](https://user-images.githubusercontent.com/18744080/44618010-4c9c9800-a86e-11e8-8412-0a8b410b9374.png) the default behavior is to "minimize to tray" Steam wont exit.
look at here: https://streamable.com/u0edu

with 
`STEAM_FRAME_FORCE_CLOSE=${STEAM_FRAME_FORCE_CLOSE:-0}` set it would behave this way: 
https://streamable.com/glnsn

**Comment by nanonyme** [comment]
Iirc it does not behave like that in Gnome. Seems DE-dependent

**Comment by nanonyme** [comment]
Iirc currently the environment variable is just passed through so you could always set it for the distro

**Comment by Tids** [comment]
In the videos that's actually gnome. But it's the same on every desktop.
I also know that environment vars reaches the sandbox. It was just a talk about if it would be a good idea to set this by default, or ship some kind of script that's sets it depending on the desktop/wm?

**Comment by nanonyme** [comment]
That is most definitely not out of the box Gnome 3, it doesn't have that kind of a bar at all

**Comment by Tids** [comment]
It's dash to panel or something like that. It doesn't change anything in the behavior of steam. One tried it on xfce, kde and gnome. It's the same on all of them.

**Comment by nanonyme** [comment]
Looks like some Steam for Linux users are still expecting tray icon to work, see #4; also apparently a common usage pattern for eg Dota 2 is to minimize Steam and wait for a match, see #41

**Comment by Tids** [comment]
@nanonyme The tray icon will still work. In fact it wont change anything for the tray Icon itself, just where the steam client minimizes itself to.

For Dota2, It wont interact in any way with Dota or any other game. It is only for the Steam Client. You will still get Dota notifications on game start.

On current gnome, we don't have a tray anymore. So if steam is using "minimize to tray" wich is the default action on "[x]" (close). You are simply not able to un-minimize steam and needs to re-run it from the launcher. And thats the case for every WM/desktop without tray support. In general it's a bad Idea to minimize to tray.

We made the [change in january](https://github.com/manjaro/packages-community/commit/b3c418b5ab9d9dd4fc4c03a22cbae4977cec59f6), and almost [no response for this](https://forum.manjaro.org/search?q=steam%20after%3A2018-02-01).

**Comment by nanonyme** [comment]
I mean, with tray icon the x means "close window and leave tray icon open". Doesn't it actually exit entire Steam if you set that environment variable?

**Comment by Tids** [comment]
> Doesn't it actually exit entire Steam if you set that environment variable?

No. If the ENV is set, the close button will act like the minimize button.

>  I'm just not sure if you can reliably detect whether there is one

I also don't think that's possible. But it would be possible to blacklist some of them. 🤔

**Comment by nanonyme** [comment]
I guess you mean if it's not set. We are not setting it which is the default

**Comment by Tids** [comment]
@nanonyme No if it is NOT set, the close button does: "close to tray"
if it is set the close button does: "minimize window"
Default is: "close to tray"
^ wich is a bad thing for desktops/wm without tray support

**Comment by Shished** [comment]
I just tried to use Steam on Gnome 3.30 with no tray extensions.
When STEAM_FRAME_FORCE_CLOSE is set to 1, closing Steam window makes it disappear but it does not shuts down and can be opened from menu..
When STEAM_FRAME_FORCE_CLOSE is set to 0 (the default value), closing Steam window hides it from desktop but it stays opened in the overview menu all the time.
^ which is a bad thing for desktops/wm without taskbar support.

**Comment by nanonyme** [comment]
Ehh, are you sure the default is 0 and not 1? The change I just did sets it to 0 if not set

**Comment by Shished** [comment]
You should set it to 1.

**Comment by nanonyme** [comment]
I'm pretty sure 1 was the default if you saw behavioural change. The original request suggested using 0 instead which is what it is now. I'm getting the impression this is one of those things that should just be left as they are. I'm reverting the change and closing this

**Comment by Tids** [comment]
Right now its just like it should be
[x] will minimize it
[_] will minimize it
this was perfect.

The revert will bringt back
[x] to "tray" it, where it wont be seen if you dont have any tray.

**Comment by Tids** [comment]
@Shished in no case steam will shut down on pressing [x]. There is just value `0` where it will minimize the window, just like if you press the minimize button or the `1`value (wich is the same as unset), where the window will disappear and will only come back if you press on the tray icon or restart the app from a menü.
