### ISSUE TITLE
doing test with controller firmware upgrade

### ISSUE THREAD

**Issue by pablodav** [flathub/com.valvesoftware.Steam#177]
I have just done a test with steam controller (see #8 ) 

Test: update  bluetooth firmware on device

Expected result: update success

Got result: update error

Screenshots and logs attached
![captura de pantalla de 2018-08-25 19-46-51](https://user-images.githubusercontent.com/4460447/44623263-42938d00-a8a0-11e8-9854-6de33051740b.png)
![captura de pantalla de 2018-08-25 19-46-16](https://user-images.githubusercontent.com/4460447/44623264-432c2380-a8a0-11e8-98e0-52df7dcde3cc.png)

Probably some additional permission should be added, due to this line:

```
Unable to open local device: 0005:0012:02
```

**Comment by nanonyme** [comment]
I'm not sure I agree you should have permissions to update firmware by default. Fortunately udev rules are out of scope for application and we can only provide documentation

**Comment by LeandroStanger** [comment]
@nanonyme Could this break the Linux distribution?

**Comment by nanonyme** [comment]
Note, I don't know entirely why this doesn't work. I'm just questioning whether it's even a safe thing by default

**Comment by pablodav** [comment]
It worked on latests tests
