### ISSUE TITLE
Missing fonts in LIMBO and Civ5

### ISSUE THREAD

**Issue by cheese** [flathub/com.valvesoftware.Steam#179]
steam app at 9714f8195570
flatpak 1.0
Fedora 28 GNOME
Intel integrated graphic card

![screenshot from 2018-08-27 09-21-35](https://user-images.githubusercontent.com/303331/44636051-fbaab200-a9db-11e8-8444-3f902cd470c5.png)
![screenshot from 2018-08-27 09-24-17](https://user-images.githubusercontent.com/303331/44636052-fc434880-a9db-11e8-9d55-c667276de156.png)

**Comment by nanonyme** [comment]
Can you try to obtain strace output similar to https://github.com/flathub/com.valvesoftware.Steam/issues/5#issuecomment-309327727?

**Comment by nanonyme** [comment]
https://github.com/flathub/com.valvesoftware.Steam/issues/32 looks similar

**Comment by nanonyme** [comment]
The other issue was also with Intel/Mesa but disappeared by itself

**Comment by cheese** [comment]
Different parts of texts are missing randomly between running.

**Comment by cheese** [comment]
![screenshot from 2018-08-27 16-05-22](https://user-images.githubusercontent.com/303331/44648321-40057480-aa13-11e8-9026-5ad678fc21cf.png)

**Comment by nanonyme** [comment]
Pictures aren't going to solve this. Can you please try to obtain the strace output?

**Comment by cheese** [comment]
strace on which program?

**Comment by cheese** [comment]
Here first the main process of the game is straced. Start at game launching, stop at the missing text issue occur. 
[Civ5XP-strace.gz](https://github.com/flathub/com.valvesoftware.Steam/files/2323193/Civ5XP-strace.gz)

**Comment by cheese** [comment]
And the output of steam stdout/stderr 
[steam-output.gz](https://github.com/flathub/com.valvesoftware.Steam/files/2323205/steam-output.gz)

**Comment by nanonyme** [comment]
Can't see anything suspicious. What's your output when you run Steam through
flatpak run com.valvesoftware.Steam though?
Does flatpak run --env=MESA_GLSL_CACHE_DISABLE=true com.valvesoftware.Steam
make any difference?

**Comment by cheese** [comment]
Settng MESA_GLSL_CACHE_DISABLE=true seams not increase logging verboseness. Here the output of  `flatpak run --env=MESA_GLSL_CACHE_DISABLE=true com.valvesoftware.Steam` and launching Civ5. 
[steam_mesa_output.txt.gz](https://github.com/flathub/com.valvesoftware.Steam/files/2326159/steam_mesa_output.txt.gz)

**Comment by nanonyme** [comment]
It's not supposed to, that is just a test for whethet this was a shader cache bug

**Comment by nanonyme** [comment]
Looks like I get massive graphical corruption with Civ 5 myself with amdgpu (Ryzen 5 with Vega)

**Comment by nanonyme** [comment]
Limbo looks fine so not related, probably

**Comment by nanonyme** [comment]
@Pixelnarium looks like this again may be shipping binaries that conflict with runtime. Might be beneficial to get list of bundled libraries for both games in case we get the blacklist feature working

**Comment by Pixelnarium** [comment]
I don't have Limbo on Steam.
Can't try Civ V right now but the file list is:

```
~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Sid Meier's Civilization V $ ls
binkawin.asi                    libCvGameCoreDLL_Expansion2.so  libMilesX64.so       libtbb.so.2       mssmp3.asi
Civ5XP                          libCvGameCoreDLL.so             libopenal.so         libtier0_s.so     mssogg.asi
com.aspyr.civ5xp.version.json   libcxxrt.so                     libopenal.so.1       libuuid.so.1      msssrs.flt
libcrypto.so.1.0.0              libiconv.so                     libopenal.so.1.13.0  libuuid.so.1.3.0  mssvoice.asi
libc++.so                       libiconv.so.2                   libssl.so.1.0.0      libvstdlib_s.so   steamassets/
libc++.so.1                     libiconv.so.2.5.1               libsteam_api.so      mssdolby.flt      steamclient.so
libc++.so.1.0                   libMilesMidi.so                 libsteam.so          mssdsp.flt
libCvGameCoreDLL_Expansion1.so  libMiles.so                     libtbb.so            mssmixer.mix

```

**Comment by cheese** [comment]
Limbo comes only one executable and libsteam_api.so:

```
$ ldd /home/cheese/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Limbo/limbo
	linux-gate.so.1 (0xf7fa3000)
	libGL.so.1 => not found
	libSDL2-2.0.so.0 => not found
	libsteam_api.so => /home/cheese/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Limbo/libsteam_api.so (0xf7f5d000)
	libstdc++.so.6 => not found
	libm.so.6 => /lib/libm.so.6 (0xf7e5b000)
	libgcc_s.so.1 => not found
	libpthread.so.0 => /lib/libpthread.so.0 (0xf7e3c000)
	libc.so.6 => /lib/libc.so.6 (0xf7c99000)
	libdl.so.2 => /lib/libdl.so.2 (0xf7c94000)
	/lib/ld-linux.so.2 (0xf7fa5000)
	libstdc++.so.6 => not found
```

I can later get the runtime status

**Comment by Pixelnarium** [comment]
OK, I now tried Civ 5 on my flatpaked Steam on an Intel iGPU (Iris Pro 5200). I don't have this problem. Maybe a locale issue? It is running fine in german. All text is shown as far as I can see.

Sidenote that Civ 5 is a 32bit game. Also the output of ld

```
~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Sid Meier's Civilization V $ ldd Civ5XP 
        linux-gate.so.1 (0xf7efc000)
        libcrypto.so.1.0.0 => ./libcrypto.so.1.0.0 (0xf7d4c000)
        libMiles.so => ./libMiles.so (0xf7cc4000)
        libtbb.so.2 => ./libtbb.so.2 (0xf7c93000)
        libssl.so.1.0.0 => ./libssl.so.1.0.0 (0xf7c3d000)
        libX11.so.6 => /usr/lib32/libX11.so.6 (0xf7ab1000)
        libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xf7a90000)
        librt.so.1 => /usr/lib32/librt.so.1 (0xf7a85000)
        libc++.so.1 => ./libc++.so.1 (0xf79db000)
        libcxxrt.so => ./libcxxrt.so (0xf79bc000)
        libc.so.6 => /usr/lib32/libc.so.6 (0xf77df000)
        /lib/ld-linux.so.2 => /usr/lib/ld-linux.so.2 (0xf7efe000)
        libsteam_api.so => ./libsteam_api.so (0xf77cd000)
        libGL.so.1 => /usr/lib32/libGL.so.1 (0xf7769000)
        libopenal.so.1 => ./libopenal.so.1 (0xf771f000)
        libdl.so.2 => /usr/lib32/libdl.so.2 (0xf7719000)
        libm.so.6 => /usr/lib32/libm.so.6 (0xf764c000)
        libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf762f000)
        libuuid.so.1 => ./libuuid.so.1 (0xf7629000)
        libiconv.so.2 => ./libiconv.so.2 (0xf7545000)
        libz.so.1 => /usr/lib32/libz.so.1 (0xf752c000)
        libstdc++.so.6 => /usr/lib32/libstdc++.so.6 (0xf73a8000)
        libxcb.so.1 => /usr/lib32/libxcb.so.1 (0xf737c000)
        libGLX.so.0 => /usr/lib32/libGLX.so.0 (0xf7359000)
        libXext.so.6 => /usr/lib32/libXext.so.6 (0xf7344000)
        libGLdispatch.so.0 => /usr/lib32/libGLdispatch.so.0 (0xf72e2000)
        libXau.so.6 => /usr/lib32/libXau.so.6 (0xf72dd000)
        libXdmcp.so.6 => /usr/lib32/libXdmcp.so.6 (0xf72d6000)
```

**Comment by nanonyme** [comment]
Yeah, that Civ 5 thing is a known game issue, it's shipping libstdc++ and libcxxrt

**Comment by nanonyme** [comment]
Sounds like ABI changed though and they might have turned to non-issues

**Comment by Pixelnarium** [comment]
OK, not related and slightly Off-Topic [but I found out](https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Game_crashes_on_startup_with_an_error_in_libpulsecommon-12.0.so.22) why the game does not start on my non-flatpaked Steam install on the NVidia-PC. It is unclear if this is a bug inside the pulseaudio library in ArchLinux or a bug in libopenal from Civ 5. If this is a bug in pulseaudio it may happen in flatpak too at some point in the future.

Overall the port of this game is pretty poor. It just wrappes the DirectX9 version of the game to OpenGL and ignores the DX11 renderer altogether. I think it's better played inside WINE using DXVK but that just my opinion :D

**Comment by nanonyme** [comment]
I think you have a valid point there. It's quite possible Proton will as it matures probably be better than many bad ports. I will be watching with interest whether Valve will start having a blacklist for known broken ports same as there is now a whitelist for Proton

**Comment by nanonyme** [comment]
@Pixelnarium can you please try deleting libopenal.so.1 from your copy of the game and see if it helps?

**Comment by nanonyme** [comment]
@cheese did the new Freedesktop runtime change anythign for you for Limbo?

**Comment by cheese** [comment]
> @cheese did the new Freedesktop runtime change anythign for you for Limbo?

I tried to run LIMBO with steam 1c290595ee23 just now. The first run was missing text. The second run turned perfect.

**Comment by nanonyme** [comment]
It wasn't an update in Steam application but Freedesktop runtime that updated Mesa

**Comment by cheese** [comment]
org.freedesktop.Platform/x86_64/18.08 was updated from flathub at 2eddd51a6035

**Comment by nanonyme** [comment]
Can you still reproduce the Civ 5 issues? We don't currently have a mechanism to workaround but it's good to know for future

**Comment by cheese** [comment]
Still missing texture

**Comment by nanonyme** [comment]
@jjardon you have Intel GPU: Do you own Civ 5? Do you get these same font issues?

**Comment by nanonyme** [comment]
@Pixelnarium also to you: which GPU did you test with?

**Comment by nanonyme** [comment]
@jurf who reported the original problem also had Intel though according to testing the issue disappeared

**Comment by jurf** [comment]
Civ V and Limbo both work correctly on my machine. This is Sandy Bridge BTW.

**Comment by cheese** [comment]
My tested computers have i5-6500(Skylake-S) and m7-6Y75(Skylake-Y) respectively. The status is more serious on the i5-6500 machine, with more texture missing.

**Comment by cheese** [comment]
I got another machine with i5-3360M(Ivy Bridge) to test Civ5. The issue does not occur. So it seems a problem with only later Intel CPU models.

**Comment by nanonyme** [comment]
Any chance in testing with that specific hardware if this happens with native Steam? This is starting to sound like a driver issue for certain families of hardware in which case we need a ticket on Freedesktop bugzilla on Mesa

**Comment by jjardon** [comment]
@nanonyme sorry for the late replay; civ 5 works fine here. My GPU:
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Graphics 540 [8086:1926] (rev 0a) (prog-if 00 [VGA controller])
```

**Comment by nanonyme** [comment]
I don't understand Intel model versioning enough whether that disputes earlier theory or not

**Comment by nanonyme** [comment]
@cheese is there some OpenGL version for you on help->system information?

**Comment by nanonyme** [comment]
It might be a bit of hit or miss but once Mesa git extension is usable, might be worth trying

**Comment by cheese** [comment]
Here is the information of old Intel model that Civ5 works:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.10-300.fc29.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  12001000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
    Driver Version:  3.0 Mesa 18.2.1
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 11.02" x 6.69" (12.87" diag)
                                            28.0cm x 17.0cm (32.7cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: IDT 92HD81B1X5

Memory:
    RAM:  7840 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  16171 Mb
    Largest Free Hard Disk Block:  2091 Mb
    VR Headset: None detected

Recent Failure Reports:
```

I will get the information of broken one several days later.

**Comment by nanonyme** [comment]
Hm, the game declares it needs GL 3.3. If that's an actually working setup, this is still yet more confusing... Unless they use core contexts and Steam reports compat contexts

**Comment by Pixelnarium** [comment]
Sorry for the late reply, but I already told you my working GPU ;) Intel Iris Pro 5200. Haswell based. All sounds like a GPU / driver related issue in the Skylake variant.
And yes, deleting/overwriting the openal library helps if the game does not start. But my off-topic sidenote was for a non-flatpaked steam on ArchLinux. Just if Civ5 stopps working altogether in flatpak anytime in the future.

**Comment by nanonyme** [comment]
@valentindavid should we also block libopenal above?

**Comment by cheese** [comment]
I have not run these games for a long time. But recent runs do not reproduce this issue any more.
