### ISSUE TITLE
Use add-extensions instead of finish-args if possible 

### ISSUE THREAD

**Issue by gasinvein** [flathub/com.valvesoftware.Steam#183]
As flatpak-builder suppurts defining extensions in app manifest like so
```json
"add-extensions": {
    "org.freedesktop.Platform.Compat.i386": {
         "directory": "lib/i386-linux-gnu",
         "version": "18.08"
```
I'm curious, why extensions are defined as finish args?
https://github.com/flathub/com.valvesoftware.Steam/blob/46b1232029e334b08c97595ae8cad83f6c411e5c/com.valvesoftware.Steam.json#L25-L26

**Comment by nanonyme** [comment]
@TingPing

**Comment by gasinvein** [comment]
Just checked: replacing the `--extension=` finish-args with appropriate definitions in json, seems to produce exactly the same metadata for the app, up to lines order.

**Comment by nanonyme** [comment]
This was something specific to Flathub build system

**Comment by nanonyme** [comment]
Closing as CI limitation

**Comment by gasinvein** [comment]
Are you sure? [Some apps](https://github.com/flathub/org.gajim.Gajim/blob/3c36d3d8bfd4877bf57c51d73bd168bb0fc1e1d0/org.gajim.Gajim.json#L28-L35) actually define extensions in json.

**Comment by nanonyme** [comment]
Wasn't supported last Spring, may be worth revisiting

**Comment by nanonyme** [comment]
If this does work, we would definitely want to use it too

**Comment by gasinvein** [comment]
Yeah, it would be very good for clarity and readability.

**Comment by gasinvein** [comment]
I think is should be left as is, at least for historucal reasons - it was so initially in finish-args.
