### ISSUE TITLE
Remove access to org.gnome.SettingsDaemon

### ISSUE THREAD

**Issue by hadess** [flathub/com.valvesoftware.Steam#184]
The correct D-Bus name is `org.gnome.SettingsDaemon.MediaKeys`, and host implementations should be fixed instead of allowing access to a potentially dangerous daemon. See:
https://bugzilla.gnome.org/show_bug.cgi?id=781326#c8

**Comment by nanonyme** [comment]
Looks like we inherited the setting all the way from https://github.com/endlessm/steam-flatpak/commit/1865fc846918b2f00b272594bcd25c9eae9a300f

**Comment by nanonyme** [comment]
Can you elaborate what will break if setting is changed and host-side changes are missing?

**Comment by nanonyme** [comment]
Looks like the suggestion from upstream is not to change this for now to let distributions acommodate

**Comment by nanonyme** [comment]
Oh, oops, those comments were from last year....

**Comment by nanonyme** [comment]
@hadess can you try to find out some relnotes on which releases contain the fixes?

**Comment by nanonyme** [comment]
I don't even know why we need the Dbus access, it hasn't been documented in commit history

**Comment by nanonyme** [comment]
Yeah, let's fix this

**Comment by nanonyme** [comment]
bot, build

**Comment by hadess** [comment]
> @hadess can you try to find out some relnotes on which releases contain the fixes?

Could you please check first why you're poking a hole to `org.gnome.SettingsDaemon`? The only applications that should use this are music playback applications.

**Comment by hadess** [comment]
The fix is available for GNOME 3.22 (September 2016) and anything newer. It's trivial to apply to older versions of GNOME as well.

**Comment by nanonyme** [comment]
Steam is a music playback application

**Comment by nanonyme** [comment]
But I don't really know why exactly it was added, this is inherited code from beginning of time

**Comment by hadess** [comment]
> Steam is a music playback application

Huh, ok. I missed that: https://store.steampowered.com/news/14358/

**Comment by hadess** [comment]
> But I don't really know why exactly it was added, this is inherited code from beginning of time

If it can play back music, it's to allow being controlled by media-keys when running in the GNOME desktop.

**Comment by nanonyme** [comment]
Original documentation says this was its purpose

**Comment by nanonyme** [comment]
alexlarsson just copypasted this stuff. If it was being used for something else than mediakeys, that was never by intent

**Comment by nanonyme** [comment]
But yeah, will investigate further and document if I find more usages

**Comment by nanonyme** [comment]
As discussed in IRC, without #188 there's not much security improvement by this.

**Comment by hadess** [comment]
> As discussed in IRC, without #188 there's not much security improvement by this.

`org.gnome.SettingsDaemon` isn't on the system bus, but on the session bus.

**Comment by nanonyme** [comment]
So who currently owns org.gnome.SettingsDaemon?

**Comment by hadess** [comment]
> So who currently owns org.gnome.SettingsDaemon?

In recent (>= 3.22) versions, nothing.

**Comment by nanonyme** [comment]
Okay. So was your security perspective a concern that the app might get access to unintended service or that a malicious service could attack the app through Dbus?

**Comment by hadess** [comment]
> Okay. So was your security perspective a concern that the app might get access to unintended service or that a malicious service could attack the app through Dbus?

The former, mainly, though a malicious app running outside the sandbox could attack Steam specifically by owning the `org.gnome.SettingsDaemon` name. In any event, whether a security issue or not at this point in time, this doesn't do anything anymore, so should either be replaced by the name of the gnome-settings-daemon plugin it really wants to talk to (they're all namespaced since GNOME 3.24, March 2017), or removed.

**Comment by nanonyme** [comment]
To be fair, I'm not sure how much that kind of issues on session bus can be avoided. Different machines have different DE's and tooling running and as a result if we want to be compatible, we just have accept that the session bus names might get hijacked. Your entire sandbox home directory is anyway writable as your current user so filtering session bus isn't really very useful against host to guest attacks. Filtering does make sense for protecting services from the application though, hence why I asked whether the name had been re-used

**Comment by nanonyme** [comment]
I'm leaving this issue open as a reminder but nothing will most likely be done to this in near future. If you would like to document the situation on the sandbox hardening wiki page, that would be appreciated. I'll otherwise make a note of this there myself

**Comment by nanonyme** [comment]
I would to be honest say Gnome project would be best to blacklist that name for any future services and instead use org.gnome.SettingsDaemon2 if they need it as recognition of the mistake

**Comment by nanonyme** [comment]
FWIW I'm considering doing this at the same go as bumping minimum requirement to 1.0.0 once Debian 10 goes live.
