### ISSUE TITLE
Remove Python 2

### ISSUE THREAD

**Issue by nanonyme** [flathub/com.valvesoftware.Steam#194]
Proton no longer requires Python 2, starting countdown on its removal
Requires 3.7-4 to hit stable https://github.com/ValveSoftware/Proton/blob/proton_3.7/CHANGELOG.md

**Comment by da2x** [comment]
Issue #225 beg to differ. Where did you hear that Python 2.7 isn’t required anymore? It seems very much like it’s still required.

**Comment by nanonyme** [comment]
I put it back for now. Downsides: build speeds more than doubled and you get significantly larger diffs

**Comment by nanonyme** [comment]
Based on changelog it looks a lot like you should not use Proton with stable for now, there's crash fixes etc in beta

**Comment by LeandroStanger** [comment]
@nanonyme Already released the new version of Proton 3.7-6
