### ISSUE TITLE
CentOS 7 - Steam Error - glxChooseVisual - failed

### ISSUE THREAD

**Issue by skibur** [flathub/com.valvesoftware.Steam#203]
Everything was working fine until I updated com.valvesoftware.Steam. Please help.

`glXChooseVisual failed
 glXChooseVisual failedMain.cpp (326) : Assertion Failed: Fatal Error: glXChooseVisual failed
`

**Comment by nanonyme** [comment]
Which version of Flatpak are you using?

**Comment by nanonyme** [comment]
Also when exactly does this fail? Does is fail when running the application or when running a game? Which graphics card do you have and do you use open or closed drivers?

**Comment by nanonyme** [comment]
Also, which game is this about?

**Comment by nanonyme** [comment]
Also, what does flatpak --gl-drivers output?

**Comment by nanonyme** [comment]
I also think something may have broken with pre-0.9.99 compat hack with 18.08 migration. The fix I did to it may have been insufficient

**Comment by nanonyme** [comment]
Please update your Flatpak to 0.10.3 or newer

**Comment by brx75** [comment]
Flatpak > 0.8.8 does not seems to be avilable for CentOS 7 / RHEL 7 / OL 7.

**Comment by nanonyme** [comment]
It's most likely Freedesktop runtime 18.08 which resulted in the breakage. You were runnning in a legacy codepath that wasn't using normal Steam library loading logic and that apparently stopped working with the update. While I did find a possible fix to that, in the light of #212 it doesn't really sound to me like there's much hope for 0.8.x branch at this point. I've heard amigadave has a COPR repo available that might be interesting to you. As for trustability, Flathub itself is apparently using that COPR repo
