### ISSUE TITLE
Steam Controller undetected for Fight The Dragon

### ISSUE THREAD

**Issue by RX4NT9UP** [flathub/com.valvesoftware.Steam#207]
The game Fight the Dragon does not detect Steam Controllers when using the flatpak. Tested on Fedora 28 and openSUSE Tumbleweed. The SC udev rules were in place and I tried the overrides --device=all and --filesystem=host with no luck. On F28 using the steam rpm package the SC is detected in game. Thanks.

**Comment by nanonyme** [comment]
Did you take a look at https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#my-controller-isnt-recognized-at-all?

**Comment by RX4NT9UP** [comment]
Yes, the thing is the steam controller udev rules are set up on the host. I tried a couple variations, using input group, and set mode to 0666. The controller is recognized in other games (and in this one if using the fedora steam package). As far as I can tell it only seems to happen with this game using the steam flatpak. Not sure anything can be done but thought I'd record it. Thanks.

**Comment by nanonyme** [comment]
It is not possible to set up udev rules from a Flatpak application nor is there a compatibility guarantee with udev and its configurations

**Comment by nanonyme** [comment]
Note using filesystem=host isn't really recommended ever. Putting udev rules in place manually is the right option. They may need customizing for your distro
