### ISSUE TITLE
Persisting all of home

### ISSUE THREAD

**Issue by kujeger** [flathub/com.valvesoftware.Steam#21]
Instead of re-homing in the start wrapper, it's probably just as well to do "--persist=." to persist all of the sadbox's home.

**Comment by nanonyme** [comment]
Except now the content is logically scoped according to Flatpak conventions instead of random locations being written into and the results are easier to erase

**Comment by kujeger** [comment]
How so?
The recipe is currently persisting `.steam` and `.local`, creating `~/.var/app/com.valvesoftware.Steam/home/` as part of the wrapper, and then setting $HOME to that path.
Any random dirs created by a game (assuming they're using the $HOME env) would be placed at `~/.var/app/com.valvesoftware.Steam/home/<randomdir>`

by doing `--persist=.` you do not need to explicitly persist .var and .steam, and you can get rid of the wrapper that changes $HOME.
Random dirs created by the game would be placed in `~/.var/app/com.valvesoftware.Steam/<randomdir>`

it's still all under `~/.var/app/com.valvesoftware.Steam/` , so I don't see how it is any less following the Flatpak conventions.

(or are you mixing up persistent paths and shared paths?)

**Comment by nanonyme** [comment]
Ah, never mind. I've apparently been misunderstanding the wrapper thus far

**Comment by kujeger** [comment]
I created a pull request doing this: #22

**Comment by kujeger** [comment]
Implemented with merge of #22

**Comment by da2x** [comment]
This wasn’t the correct fix. Please see issue #60.
