### ISSUE TITLE
"/usr/bin/env: ‘python2.7’: No such file or directory" when launching a game using Steam Play (Proton)

### ISSUE THREAD

**Issue by m-khvoinitsky** [flathub/com.valvesoftware.Steam#216]
**Game information**
Any Steam Play (Proton) game

**Distribution name and version where applicable**
Archlinux

**Flatpak info**
Flatpak 1.0.1
```flatpak --gl-drivers
default
host
```

**Problem description**
Nothing happens when launching a game, error in console:
```
ExecuteSteamURL: "steam://rungameid/12110"
GameAction [AppID 12110, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
/usr/bin/env: ‘python2.7’: No such file or directory
/usr/bin/env: ‘python2.7’: No such file or directory
/usr/bin/env: ‘python2.7’: No such file or directory
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 12110
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 12110
Installing breakpad exception handler for appid(steam)/version(1535576546)
assert_20180909141653_29.dmp[247]: Uploading dump (out-of-process)
```

**Does this issue reproduce with native Steam**
Have not tested

**Comment by m-khvoinitsky** [comment]
Stable steam and stable (3.7-3) Proton. I've tried Proton 3.7-6 Beta and it indeed works.
Thank you.

**Comment by nanonyme** [comment]
It's good to know this is still broken with stable Proton though. Thanks

**Comment by nanonyme** [comment]
https://github.com/ValveSoftware/Proton/blob/proton_3.7/CHANGELOG.md actually looks like a sensible reference to follow
