### ISSUE TITLE
Proton games no longer work after GPU upgrade

### ISSUE THREAD

**Issue by Israphel** [flathub/com.valvesoftware.Steam#225]
**Game information**
Several games

**Distribution name and version where applicable**
KaOS

**Flatpak info**
flatpak --version
Flatpak 1.0.1

flatpak --gl-drivers
nvidia-396-54
default
host

**Problem description**
I was running games with Intel HD 2500 (with Mesa) and now I upgraded to an Nvidia 1050ti. I installed the latest drivers and I ran flatpak update, which downloaded more nvidia stuff.

Now native games run but proton games that are confirmed to work, just won't launch anymore. 

Full log when running Steam from the console: https://gist.github.com/Israphel/ed06e26f12481e7af8187a675a36d35b

**Does this issue reproduce with native Steam**
Have not tested

**Comment by da2x** [comment]
I believe the issue to be this line:

> /usr/bin/env: ‘python2.7’: No such file or directory

This is a regression from commit 5fa9718b9e39d22d68c515945bf1591f99b0eb8a via pull request #210 and issue #194.

**Comment by da2x** [comment]
You can open Steam Settings: Steam Play: Compatibility Tool, and change to the beta version of Proton instead of Stable. (I still say 5fa9718 should be reverted until this change moves from Proton beta to stable. Deprecating Py2.7 was way too premature.)

**Comment by nanonyme** [comment]
Well,  "way" is exaggerated. When stable gets the next build, it will work. I guess I'll revert anyhow

**Comment by Israphel** [comment]
Thanks for the info. So how do we revert?

**Comment by nanonyme** [comment]
flatpak update

**Comment by Israphel** [comment]
Everything works fine, thank you guys.
