### ISSUE TITLE
legacy version check broken with flatpak 0.11.8.3

### ISSUE THREAD

**Issue by moben** [flathub/com.valvesoftware.Steam#229]
the minimum flatpak version check introduced in https://github.com/flathub/com.valvesoftware.Steam/commit/55f7e814baffcf9c6f0a5f3c33fcc42b35c77730 breaks with e.g. flatpak 0.11.8.3 because `distutils.StrictVersion` only supports versions with 2 or 3 components. See [PEP-386](https://www.python.org/dev/peps/pep-0386/#distutils) for documentation and alternatives. I haven't looked into what the best one is (maybe `LooseVersion` instead or the `setuptools` implementation?) and this PEP is also superseded by [PEP-440](https://www.python.org/dev/peps/pep-0440/) which does not offer an API afaict from a quick glance

**Comment by nanonyme** [comment]
Argh. I wonder why @alexlarsson changed the versioning scheme. Oh, well

**Comment by nanonyme** [comment]
PEP's don't as such matter, we're not dealing with Python package versions here but Flatpak version. StrictVersion was way too strict though, apparently
