### ISSUE TITLE
Cities Skylines fails to start: failed to load driver: swrast

### ISSUE THREAD

**Issue by Qwertie-** [flathub/com.valvesoftware.Steam#233]
**Game information**
Cities Skylines

**Distribution name and version where applicable**
Fedora 28

**Flatpak info**
Flatpak 1.0.2
nvidia-396-45

**Problem description**
Game fails to load with the error 
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
Was working fine before installing nvidia proprietary drivers.

**Does this issue reproduce with native Steam**
Have not tested

**Comment by Qwertie-** [comment]
Ran `flatpak update` and it works again.

**Comment by nanonyme** [comment]
Can you please add comment about this in FAQ? I dont't think there's currently anything there
