### ISSUE TITLE
32-bit ICD files for Vulkan not installed, despite library being present

### ISSUE THREAD

**Issue by eternaleye** [flathub/com.valvesoftware.Steam#239]
In `/usr/share/vulkan/icd.d`, only these two files are present:
- `intel_icd.x86_64.json`
- `radeon_icd.x86_64.json`

These reference the 64-bit Vulkan drivers that live in `/usr/lib/x86_64-linux-gnu/` by their full paths.

However, the equivalent drivers are _also_ present for 32-bit in `/usr/lib/i386-linux-gnu/`, though there are no ICD files for them. As a result, any 32-bit application that uses Vulkan will encounter spurious failures.

I encountered this because Proton (for Steam Play) uses DXVK by default, and when launching a 32-bit Windows game that requires DX11, this will cause the game to fail to launch.

**Comment by nanonyme** [comment]
@valentindavid ping; any clue?

**Comment by nanonyme** [comment]
Tracking ticket in runtime https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/398

**Comment by nanonyme** [comment]
The change is integrated is going to be included in next import https://flathub.org/builds/#/builders/7

**Comment by nanonyme** [comment]
@eternaleye slight warning: the runtime has LLVM 6. Proton devs guide that LLVM 7 or newer is required to avoid GPU hangs with DX11 games. @valentindavid had some plans with regards a runtime extension to get Mesa Git + LLVM Git but that's work in progress thing

**Comment by nanonyme** [comment]
Looks like there was an import. Can you please re-test?

**Comment by eternaleye** [comment]
That fixed it!
