### ISSUE TITLE
Uninstall procedure for Steam flatpak not clear (not documented?)

### ISSUE THREAD

**Issue by heis2201** [flathub/com.valvesoftware.Steam#240]
Hi, 

I think it is not entirely clear how to properly remove the Steam client. 

```flatpak uninstall com.valvesoftware.Steam``` seems to remove whatever was placed in /var/lib/flatpak/app (I assume the installer). The actual client (1.7G) remains in the user directory (~/.var/app/).

What would be the best way to remove the Steam client? Is that method documented somewhere?

Thanks!

**Comment by nanonyme** [comment]
That's an interesting question. It's not just Steam that's left (you're probably talking of .var/app/com.valvesoftware.Steam/.local/share/Steam directory) but most likely also all installed games. So the result disk usage may potentially be massive
Note that for Flatpak the matter is simpler than for native Steam (which apparently also leaves things behind): if you remove .var/app/com.valvesoftware.Steam, you have removed *all* content saved by the Flatpak application for that specific user. Content for other users obviously remains in the home directories of those other users.

**Comment by heis2201** [comment]
Thanks for the reply.

Yes, that's what I did, I removed ```.var/app/com.valvesoftware.Steam```. The question is if that has to be documented somewhere so less experienced users get a chance to reclaim their disk space.

**Comment by nanonyme** [comment]
Removing it is not in general safe, you lose non-recoverable data in most cases. We could document that is where your data is kept although that's a generic thing for all Flatpak apps

**Comment by nanonyme** [comment]
Normally you would not remove Steam, you would uninstall the games within it. Games usually take the most space

**Comment by nanonyme** [comment]
Added some notes to https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#the-application-is-using-a-lot-of-disk-space

**Comment by BananaKing9126** [comment]
_______@penguin:~$ _**flatpak uninstall steam**_
Found installed ref ‘app/com.valvesoftware.Steam/x86_64/stable’ (user). Is this correct? [Y/n]: y


        ID                              Arch          Branch
 1. [-] com.valvesoftware.Steam         x86_64        stable

Uninstall complete.
--------------------------------------------------------------------------------------------------------------------------------I typed the bold and italicized command and it did a cross-search and found what I was looking for and after accepting its recommendation it fully uninstalled steam

(Also I know this is a 2 year old thread but if I was looking for a solution I'm probably not the only one)

**Comment by mrroot5** [comment]
I tried this command and deleted steam + data (games included).

```
flatpak uninstall --delete-data -v app/com.valvesoftware.Steam/x86_64/stable
```
* `-v`: is "verbose" to see exactly what flatpak is doing.
* `--delete-data`: bye bye games, configs, etc.

An image is better than a thousand words:

![image](https://user-images.githubusercontent.com/1659540/171809452-e84baf81-a4cb-4e8d-8c58-98b27d8ff468.png)

After that I free up 10GB on my HDD (I only have 1 - 2 games installed).
