### ISSUE TITLE
Flatpak support on AMD haphazard at best

### ISSUE THREAD

**Issue by etrigan63** [flathub/com.valvesoftware.Steam#242]
Using the Steam client flatpak is a crapshoot at best when using Radeon graphics cards. I have an 8-core Threadripper system with an RX580 and playing games is a hit-or-miss affair regardless if they are Linux native or running under SteamPlay. Champions Online worked under SteamPlay with a 1080 card, but fails to launch with an RX580. Ballistic Overkill (Linux version) only works with the Experimental 64-bit version. Gear Up says it is running, then syncing, then dies quietly. World of Tanks Blitz works as does Half-Life Episode 2 and Robotcraft. I posted this in the general Steam github, but they are clueless. Any ideas from the flatpak team? I am running on KDE Neon Bionic (Ubuntu 18.04).

**Comment by nanonyme** [comment]
Your initial premise is incorrect, my main testing grid involves AMD Raven Ridge APU

**Comment by nanonyme** [comment]
Many of the ports are very poor quality and require workarounds to run on non-Ubuntu. If you want to use the application, please file reports about individual games

**Comment by etrigan63** [comment]
Then can you explain the equal number of problems I am having with native linux games?

**Comment by nanonyme** [comment]
I was to be honest talking about games on Linux in general with Steam. Games are supposed to
1) Use Steam runtime
2) Bring their own dependencies
3) Put their own dependencies as lower priority or be prepared to infinitely maintain their game
4) Not use preload
Most or the game issues filed here are about games which fail one or multiple of these rules

**Comment by etrigan63** [comment]
Thanks for the clarification. For the record I loaded Kubuntu last week and had exactly the same behavior. Therefore KDE Neon = Kubuntu.

**Comment by nanonyme** [comment]
With Flatpak the distro doesn't matter because your host OS is insulated by Flatpak runtime (in this case Freedesktop runtime 18.08). It does not behave the same way as Ubuntu's userbase which is the main target when developers make games on Steam for Linux

**Comment by etrigan63** [comment]
This is why I use the Flatpak and not the native version. However, when I ask for help on the native version side, the answer I got from Valve was "KDE Neon <> Ubuntu, can't help you, sorry, bye!"

Needless to say, not a stellar customer support experience.
