### ISSUE TITLE
Proton requires libgnutls.so.26

### ISSUE THREAD

**Issue by Elinvention** [flathub/com.valvesoftware.Steam#245]
As per https://github.com/ValveSoftware/Proton/issues/225#issuecomment-425699196, Proton looks for libgnutls.so.26 and the workaround is to add a symlink to libgnutls.so. But how do I do that with flatpak?

**Comment by nanonyme** [comment]
This needs to be fixed on Valve's side

**Comment by nanonyme** [comment]
Hm, libgnuTLS already *is* part of Steam runtime....

**Comment by nanonyme** [comment]
If Valve really won't fix it, will take a look once the library blacklist feature is integrated in runtime. This isn't currently possible to fix (anywhere) without regressions in other games
