### ISSUE TITLE
can't opt out of beta

### ISSUE THREAD

**Issue by user5145** [flathub/com.valvesoftware.Steam#249]
**Game information**
steam's dependencies are missing

**Distribution name and version where applicable**
opensuse tw (freesh install), nouveau

**Flatpak info**
  flatpak --version: 1.0.0
  flatpak --gl-drivers:
  default
  host

**Problem description**
if one opts into steam beta and opts out then they will not be able to launch steam anymore. steam will return those 3 messages:

1. Couldn't set up the Steam Runtime. Are you running low on disk space? Continuing...

2. You are missing the following 32-bit libraries, and Steam may not run:
libgtk-x11-2.0.so.0
libva.so.1
libva.so.1
libva-x11.so.1

3. Failed to load steamui.so

Reinstalling doesn't work. (flatpak remove... && flatpak install...) and I have a lot of disk space

**Does this issue reproduce with native Steam**
Have not tested

I fixed it by removing ~/.var/app/.com.steamsoftware.Steam, but is it possible to prevent it from happening?

**Comment by nanonyme** [comment]
That's not related to the Flatpak itself, it's about the Steam runtime shipped by Steam. Do you have any idea how to reproduce this? I have only seen this happen if STEAM_RUNTIME points to a directory that doesn't have anything in it.

**Comment by user5145** [comment]
Yes, i reproduced it both on opensuse tw and arch
logs: https://pastebin.com/TdaNSzcK

**Comment by nanonyme** [comment]
Runtime checksum: 7482418ee515e150ae03bbde94275ab5  steam-runtime.tar.xz, expected 928b5bcbc95f655ab3d546f404889253  steam-runtime.tar.xz

**Comment by nanonyme** [comment]
Sounds like a bug in Steam. Deleting that file would probably fix it

**Comment by nanonyme** [comment]
We're not really doing anything special there. The out of space error is Steam's guess. It in many places has nothing to do with reality. It basically just means Steam failed extract the runtime it needed and as a result you're missing core dependencies.

**Comment by user5145** [comment]
ok, i tested it and i can reproduce it even without flatpak :)
thanks for you help
