### ISSUE TITLE
Poor performance in Team Fortress 2

### ISSUE THREAD

**Issue by rbrooklyn** [flathub/com.valvesoftware.Steam#250]
**System specs**
KUbuntu 18.04.1 - Fairly clean installation. No PPAs installed.
Intel I5 6400
8GB Ram
AMD RX580 8GB

**Flatpak info**
$ flatpak --version
Flatpak 1.0.3
$ flatpak --gl-drivers
default
host
Steam flatpak up to date as of today. (6th Oct 2018)

**Problem description**
On my set-up, Team Fortress 2 is able to achieve 100-150fps on high settings when Steam is installed natively. When installed through flatpak, Team Fortress 2 is unplayable, with huge input lag and stuttering performance in some maps which can drop the FPS to lower than 10 in some cases.

**Does this issue reproduce with native Steam**
No - FPS is much higher and suitable to the expectations of the system.

**Log file**
[steam tf2 flatpak log](https://github.com/flathub/com.valvesoftware.Steam/files/2453375/steam.tf2.flatpak.log) - Some errors are present, but I'm unsure if they are relevant to the issue.

**Comment by nanonyme** [comment]
18.04 has Mesa 18.0.5 so you only get compat 3.3 or whatever, core 4.5. With Freedesktop runtime you get compat 4.4, core 4.5. Sounds like gam may be using compat

**Comment by nanonyme** [comment]
Cool. At least that disproves the theory that the newer GL version would be slower

**Comment by nanonyme** [comment]
This is not the first performance difference report with Flatpak even though the sandboxing penalty should be negligible. I wonder what's going on

**Comment by nanonyme** [comment]
#83 is another case where we couldn't pinpoint the root cause

**Comment by nanonyme** [comment]
I suppose that level of difference might be expected if rendering over software rendering or the iGPU in the CPU. Logs say this shouldn't be the case

**Comment by ribs85** [comment]
I can squash the iGPU theory for you immediately. Whilst this machine is fitted with a CPU which has graphics built in, the motherboard deactivates it when a graphics card is installed. The manual says the iGPU is non-accessible in this configuration, and the iGPU is invisible to the OS. Plus obviously the video would be coming from the motherboard's ports, and not the graphics card where the monitor is plugged into.

Software rendering might be an issue. But I unsure if the game would even start in these circumstances. Another game, Ballistic Overkill, ran without issues. But I'm unsure if that's a 64-bit game. I know there are both 32 and 64 bit versions, but I'm unsure what starting them 'defaults' to.

The other bug you linked to, which describes the issue in Insurgency is interesting. Both Team Fortress 2 and Insurgency are both Source engine games.

So I would say it's more likley that Source game engine is more likely to be causing the odd behaviour. Or maybe something to do with the 32-bit nature of them? I'm unsure if Insurgency is 32-bit or not.

**Comment by nanonyme** [comment]
32bit *should not* be any special other than that you get the 32bit Mesa libraries through a runtime extension. That is a lead though. Maybe it might be worth testing other Source games for issues

**Comment by nanonyme** [comment]
Note we realized couple of days ago that 32bit binaries get built with much reduced set of CPU extensions compared to 64bit. MMX is going to be enabled soon but getting SSE2 will require more work as not all 32bit CPU's support it

**Comment by nanonyme** [comment]
This *should* not explain the magnitude of difference you're observing though

**Comment by nanonyme** [comment]
Another point if I missed it: normally your host Mesa does not affect anything. There's a shipped Mesa running as part of Flatpak runtime. It should currently be 18.2.3 (just updated)

**Comment by ribs85** [comment]
I've just reinstalled and tried again, sadly no improvement. I've also downgraded mesa back to Kubuntu's default version.

Any ideas on how to debug this?

**Comment by ribs85** [comment]
I've finally made some progress.

Today I distro hopped onto OpenSUSE Tumbleweed for a variety of reasons I will not bore you with here. Only mentioning in case this makes any difference or triggers any known bugs I'm aware of.

Part of today's hop was to try and see if flatpak'd steam would be better on this distro. Unfortunately, the result was identical to my KUbuntu setup.

Then it occurred to me that we might be looking in the wrong place. We've been assuming that mesa or graphics drivers are the issue, whereas it might actually be the CPU. TF2 is very much a CPU bound game. Even with if we somehow had a 50% mesa performance hit, the game should be very playable if the CPU is strong.

Adding in a command switch of -threads 3 (which is minus one from the number of cores my CPU provides, -threads 4 didn't seem to help) did have a remarkable performance improvement. It's *almost* playable; characters on the screen still slow things down too much, but I was getting vastly improved framerates through quieter portions of the map and a lot of the stuttering had disappeared. TF2 currently has a Halloween mode live as I type this, and the maps produced for this mode do have performance issues anyway, even when native, so this might actually be playable on regular maps. I only tested on one of the Halloween maps. I've literally done about 3 minutes of testing just to figure out if my idea had any weight. So it's a promising initial test, but definitely needs more testing.

So my current theory is that something about the CPU is being hidden from Steam/TF2 by the flatpaking process, and this is causing it to perform badly. Maybe the number of cores are hidden, but I suspect other things as well.

I'm not an expert on flatpak at all, so might be well off the mark, but initial results are promising with forcing TF2 to use 3 threads. I'll see if I'm able to do more testing later this coming week.

**Comment by ribs85** [comment]
Urgh. Forget everything I just typed. I'm wrong.

I actually benchmarked this:

-novid -sillygibs: 2639 frames 113.009 seconds 23.35 fps (42.82 ms/f) 3.517 fps variability

-novid -sillygibs -threads 2: 2639 frames 111.903 seconds 23.58 fps (42.40 ms/f) 3.178 fps variability

-novid -sillygibs -threads 3: 2639 frames 111.721 seconds 23.62 fps (42.33 ms/f) 3.229 fps variability

No improvement at all, and watching the demo was extremely slow in some parts.

It seems that coincidentally, when I was playing with -threads 3, there was presumably less character models on the screen, and so the game performed better. When it's just the map, it's fine. Other players being present is what hurts performance.

Back to square one, unfortunately.

I've attached the demo file which I used to benchmark, for future reference.
[benchmark1.dem.zip](https://github.com/flathub/com.valvesoftware.Steam/files/2523096/benchmark1.dem.zip)

**Comment by nanonyme** [comment]
Oncoming Freedesktop runtime update might affect performance  as some unintentional debugging gets removed and LLVM gets upgraded. Probably available at some point next week.

**Comment by nanonyme** [comment]
Note the music and pictures privileges were set read-only exactly because I wouldn't trust software in Steam to be allowed to manipulate my content either. It's perfectly fine to disable them, I'd prefer explicit file access through Flatpak Portals but they're not at least currently possible.
