### ISSUE TITLE
CSGO not starting

### ISSUE THREAD

**Issue by MTRNord** [flathub/com.valvesoftware.Steam#254]
**Game information**

CSGO

**Distribution name and version where applicable**

```
[marcel@Marcel-PC parser]$ cat /etc/os-release
NAME="Antergos Linux"
PRETTY_NAME="Antergos Linux"
ID=antergos
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://antergos.com/"
SUPPORT_URL="https://forum.antergos.com/"
BUG_REPORT_URL="https://github.com/antergos"
[marcel@Marcel-PC parser]$ uname -a
Linux Marcel-PC 4.18.14-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 13 13:42:37 UTC 2018 x86_64 GNU/Linux
```

**Flatpak info**

```
[marcel@Marcel-PC parser]$ flatpak --version
Flatpak 1.0.4
[marcel@Marcel-PC parser]$ flatpak --gl-drivers
nvidia-410-57
default
host
```

**Problem description**

CSGO crashes with `ERROR: ld.so: object '/home/marcel/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

[csgoCrash.txt](https://github.com/flathub/com.valvesoftware.Steam/files/2488284/csgoCrash.txt)

**Does this issue reproduce with native Steam**

Have not tested

**Comment by nanonyme** [comment]
Errors related to overlay are almost guaranteed to be red herrings

**Comment by nanonyme** [comment]
There's error multiple library load errors about things inside game install directory. You might try
flatpak run --command=bash com.valvesoftware.Steam
and then check which libraries there are in game directory and ldd them to see if their dependencies are intact

**Comment by MTRNord** [comment]
It would be weird that the Roccat joystick is the root cause :/ Because that happens on windows too and is no problem there

**Comment by Amosar** [comment]
could be related to this issue https://github.com/ValveSoftware/csgo-osx-linux/issues/1757

**Comment by Eonfge** [comment]
Can not reproduce. Works (with overlay) as of time of writing. Does this issue still apply?

# Setup
```
OS: Ubuntu 19.04 x86_64 
Host: MS-7B85 1.0 
Kernel: 5.0.0-19-generic 
Uptime: 1 day, 1 hour, 56 mins 
Packages: 3496 (dpkg), 37 (flatpak), 2 (snap) 
Shell: bash 5.0.3 
Resolution: 1280x1024, 2560x1440 
DE: GNOME 3.32.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 2700 (16) @ 3.200GHz 
GPU: NVIDIA GeForce GTX 970 
Memory: 6390MiB / 16047MiB 
```

Flatpak: 1.2.4
Drivers: nvidia-418-56

**Comment by MTRNord** [comment]
I can't test that anymore as my setup switched and I don't have the system on my hard disk anymore (Arch died on me).

**Comment by nanonyme** [comment]
Sounds like I'm closing this if there's no one who can repro this anymore.
