### ISSUE TITLE
Nvidia runtimes

### ISSUE THREAD

**Issue by Pshemas** [flathub/com.valvesoftware.Steam#263]
As my Nvidia drivers were updated to 410.78 I've noticed that Flatpaked Steam does not start - and it is clear why. Flatpak runtime for NVidia did not get such an update via "flatpak update".
Is there anything I could do in such situation?
Is there a way to find such flatpak runtime somewhere? And lastly how can I list runtimes (for example nvidia ones) that are available in flatpak repos that I currently have (it would allow me to avoid such situations in the future - I'd know when to hold a system drivers update if there are no runtimes available)?
I've tried figuring the last bit out, but I failed.

**Comment by nanonyme** [comment]
Did you already check https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#glxchoosevisual-failed?

**Comment by aeosynth** [comment]
i have the same issue, and there's no mention of `glXChooseVisual`
```
> flatpak run com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Running Steam on org.freedesktop.platform 18.08 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1541819448)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

@Pshemas you can find the flatpak nvidia packages with `flatpak remote-ls flathub | grep nvidia`; indeed 410.78 is not packaged.

**Comment by nanonyme** [comment]
Please update Wiki with errors you saw and follow the instructions already included
