### ISSUE TITLE
[Nvidia] Dota 2 not working with Vulkan!

### ISSUE THREAD

**Issue by Syntist** [flathub/com.valvesoftware.Steam#27]
On Nvidia Dota 2 Opengl working fine,
But not working when i select vulkan.

![](http://i.imgur.com/oqjod6D.jpg)

It does work on normal steam!!

**Comment by TingPing** [comment]
Maybe related to flatpak/flatpak#949

**Comment by TingPing** [comment]
Should be fixed now.
