### ISSUE TITLE
Borderlands 2 / TPS cannot connect to the SHiFT service

### ISSUE THREAD

**Issue by Shished** [flathub/com.valvesoftware.Steam#274]
**Game information**
Borderlands 2 and Borderlands: The Pre-Sequel.

**Distribution name and version where applicable**
```
NAME="openSUSE Tumbleweed"
# VERSION="20181206"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20181206"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20181206"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Flatpak info**
  flatpak --version
> Flatpak 1.0.5

  flatpak --gl-drivers
```
nvidia-415-22
default
host
```

**Problem description**
Both games tries to connect to the service after startup and fails to do it. When trying to add a golden key code, games says that they are not connected to the service.
Workaround exists - add `SSL_CERT_DIR="/etc/ssl/certs" %command%` to the games launch parameters in Steam, but that does not works for me in flatpak Steam installation.

**Does this issue reproduce with native Steam**
Yes / depends on distro. Workaround works for me with native Steam but doesn't with flatpak.

**Comment by nanonyme** [comment]
Any chance of finding out what the actual hostname is? I have a hunch that it might be the case of a missing root/intermediate CA

**Comment by Shished** [comment]
I think i found the source of this problem.
Game looks for certs in specific folder and SSL_CERT_DIR is pointing to that folder.
But /etc/ssl/certs is completely broken in flatpak environment, it's full of broken symlinks.
Check this out:
```
$ file /etc/ssl/certs/157753a5.0
/etc/ssl/certs/157753a5.0: broken symbolic link to AddTrust_External_Root.pem
$ file /etc/ssl/certs/AddTrust_External_Root.pem
/etc/ssl/certs/AddTrust_External_Root.pem: broken symbolic link to ../../../share/ca-certificates/mozilla/AddTrust_External_Root.crt
```
I copied files from host /etc/ssl/certs to the folder in flatpak home and added env variable in game properties, and it worked just fine!

**Comment by nanonyme** [comment]
Could you please add upstream ticket on this? https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues

**Comment by Shished** [comment]
How should i describe the problem?

**Comment by nanonyme** [comment]
If you know which specific PEM fixes the issue, you could file a ticket that this CA is missing. We can start auditing from there on whether this is intentional or not. I would really prefer not maintaining trust stores withing the application if I can avoid it since that's a huge amount of work._

**Comment by Shished** [comment]
Needed cert is GlobalSign_Root_CA.pem (5ad8a5d6.0)

**Comment by nanonyme** [comment]
Created https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/526

**Comment by nanonyme** [comment]
Where exactly does GlobalSign_Root_CA.pem symlink point to?

**Comment by Shished** [comment]
I think it is completely broken.
Host /etc/ssl/certs folder contains pem files and *.0 files that are symlinks to pem files.
Flatpak /etc/ssl/certs folder contains pem files which are symlinks to `../../../share/ca-certificates/mozilla`  (isn't that supposed to be `/usr/share/ca-certificates/mozilla` which contains valid pem files?) and *.0 files that are symlinks to that broken pem files.

**Comment by nanonyme** [comment]
Classically there were in Flatpak symlinks such that /bin->/usr/bin etc. I don't know if /share->/usr/share also existed. This might also be a bug in Flatpak if valid certs are under /usr/ and Flatpak stopped providing the indirection layer without fixing /etc...
@alexlarsson ping?

**Comment by nanonyme** [comment]
Note that for Flatpak workaround is setting cert dir to /usr/etc/ssl/certs for now

**Comment by smcv** [comment]
(and symlinks in `/usr/var`, if any, should also be absolute)

**Comment by nanonyme** [comment]
The root cause is that there is no copying.  /usr/etc is simply bind mounted on top of /etc.

**Comment by nanonyme** [comment]
There's now a fix to this in runtime. It may take a while for a release to be done. I think you can expect one before end of next week unless something out of ordinary happens.

**Comment by nanonyme** [comment]
Runtime import now ongoing. If this succeeds, next flatpak update should yield a runtime with non-broken /etc https://flathub.org/builds/#/builders/7/builds/60

**Comment by nanonyme** [comment]
Could you please re-test?

**Comment by Shished** [comment]
Game looks for /usr/lib/ssl folder instead of /etc/ssl. I just checked and it is not available in flatpak environment.

**Comment by nanonyme** [comment]
Oh, come on. This is getting silly.
