### ISSUE TITLE
Adding Non-Steam Games to Library

### ISSUE THREAD

**Issue by AVonGauss** [flathub/com.valvesoftware.Steam#278]
Steam has the ability to add non-Steam games (or any application for that matter) to the user's library if they are already installed.  Running in a Flatpak sandbox it appears Steam does not have the ability to determine what applications are installed outside of its own sandbox.  I believe this is done by Steam scanning the /usr/share/applications and ~/.local/share/applications folders for ".desktop" files.  Not sure if this is going to be a limitation of sandboxing or perhaps there might be an elegant way to still support this functionality.

REPRODUCTION STEPS

Steam (windowed): Select Games, Add a Non-Steam Game to My Library... from the menu.
Steam (big picture): Select Settings, Add Library Shortcut buttons.

EXPECTED RESULT

See a list of applications installed on the system. 

ACTUAL RESULT

Either no entries or a combination of Fcitx / Fcitx Configuration depending on whether or not you've previously tried to add them to the library.

**Comment by nanonyme** [comment]
Yes, home directory is part of the sandboxing. What value do you see in that Steam would see non-Steam shortcuts? It's not as if it could launch them anyway because of the sandbox

**Comment by AVonGauss** [comment]
There wouldn't be much value in not being able to launch them, but there is value in being able to launch proper applications (ex: .desktop based files) that are not part of the sandbox.  Its not much different in concept to a user on a smartphone or tablet taking an email and/or attachment and "sending" it to another application except in this case the other application is just being launched without anything being sent.

The main reasons I can see that someone would want to add a non-Steam game to their library is to make it available through big picture mode and/or provide controller support for an application that either does not have it natively and/or use a controller or mapping that the application does not natively support.  The reason I found it was while attempting to add Minecraft Java to my library.

**Comment by nanonyme** [comment]
Well, you kinda can run host commands manually but the shortcuts are useless without rewriting since they point to files inaccessible to the sandbox. If you rewrote them, they would be useless outside the sandbox. I don't believe this can work.

**Comment by nanonyme** [comment]
If you want to install it inside the sandbox, it might be fine. Your sandbox version of home is in .var/app/com.valvesoftware.Steam inside your host home dir. You can just drop whatever files you want there

**Comment by nanonyme** [comment]
The app cannot automatically do this
