### ISSUE TITLE
[Issue] Sound Issue With Steam(Flatpak)!!

### ISSUE THREAD

**Issue by Syntist** [flathub/com.valvesoftware.Steam#28]
When i run flatpak steam, the sound of the desktop stop working but i can hear the sound of steam and steam games!!

Its really annoying.

Without Steam On
![](http://i.imgur.com/PGIfxA7.jpg)

With Steam On
![](http://i.imgur.com/6olVgUp.jpg)

**Comment by nanonyme** [comment]
Is the host running a working PulseAudio installation in this case?

**Comment by Syntist** [comment]
Yeah, i am using ubuntu 16.04 default sound, i think its PulseAudio!

**Comment by nanonyme** [comment]
The reason why I asked is that sounded like classic case of Pulse Audio suspender which is normally caused by ALSA fallbacks

**Comment by nanonyme** [comment]
Does this still reproduce with the new Freedesktop runtime 18.08?

**Comment by nanonyme** [comment]
Closing as stale.
