### ISSUE TITLE
Steam not launching anymore

### ISSUE THREAD

**Issue by anonymous98721515** [flathub/com.valvesoftware.Steam#281]
Distribution name and version where applicable
Ubuntu 18.10

Flatpak info
Using "flatpak addon" in discovery store

Problem description
I succesfully had installed steam from flatpak and was using it without errors. But then one day it just stopped working :/ . Tried to reinstall and that kinda stuff, but nothing worked

Does this issue reproduce with native Steam

Native steam is fully working, but i really liked the contained version due to it being unable to detect my vpn ^^

**Comment by LeandroStanger** [comment]
Update Steam
1) Open the application called 'Terminal'
2) In this application run the command:
>flatpak update --appstream && flatpak update

**Comment by vdrandom** [comment]
Same here.
Updated both flatpak and com.valvesoftware.Steam on my archlinux, and boom.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```
Steam runs perfectly natively, but I do still prefer to bubblewrap the proprietary applications.

**Comment by LeandroStanger** [comment]
https://github.com/flathub/com.valvesoftware.Steam/pull/282

**Comment by LeandroStanger** [comment]
Fixed in https://github.com/flathub/com.valvesoftware.Steam/pull/287

**Comment by nanonyme** [comment]
The update is now merged through  #283  though I doubt it helps any here

**Comment by nanonyme** [comment]
I doubt the update helps so would be nice to get further comments from original reporter

**Comment by nanonyme** [comment]
Same errors as in https://github.com/ValveSoftware/steam-for-linux/issues/5859

**Comment by nanonyme** [comment]
Please also post output of

flatpak run --command bash com.valvesoftware.Steam 

Followed by "locale"

**Comment by nanonyme** [comment]
Assuming this still reproduces for you original reporters. Does it?

**Comment by nanonyme** [comment]
Closing due to lack of comments.
