### ISSUE TITLE
scaling on hidpi screen (GDK_SCALE)

### ISSUE THREAD

**Issue by G-Ray** [flathub/com.valvesoftware.Steam#291]
Even if `Steam > Settings > Interface > Enlarge text and icons based on monitor size (restart required)` is enabled, it seems the UI does not scale on hidpi screens.

**Comment by nanonyme** [comment]
If you use IRC, consider asking on #flatpak
Might be something missing in app or runtime, I don't have enough knowledge to say which

**Comment by nanonyme** [comment]
Does manually setting GDK_SCALE manually to 2 change anything?

**Comment by jdoda** [comment]
I've experienced this issue with Steam (and other Flatpaked applications) and I can confirm that running e.g. `export GDK_SCALE=2 & flatpak run com.valvesoftware.Steam` will make Steam scale correctly.

**Comment by jdoda** [comment]
Behaviour under Wayland and X11 is the same.

**Comment by nanonyme** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5427 hints that the setting alone should work. Is GDK_SCALE set for yoi by default?

**Comment by jdoda** [comment]
Just had a look, and the setting was already set. I tried toggling it off and on again (restarting Steam each time) but that didn't have any effect. I tried moving `~/.var/app/com.valvesoftware.Steam/` so I could start with a fresh copy, but that didn't have any effect either. As far as I can tell the setting mentioned in that issue doesn't work at all within a Flatpak.

I don't know exactly what you mean by "Is GDK_SCALE set for you by default?", but if I run `flatpak run --command=bash com.valvesoftware.Steam` and then `export | grep GDK` I don't see the variable.

**Comment by jdoda** [comment]
Just tried installing Steam from rpmfusion and trying the option on that non-flatpak version, and it doesn't do anything there either, so it looks like that option not working is not a flatpak specific bug.

**Comment by nanonyme** [comment]
Right. There's clearly something in Steam detecting your display that doesn't work right. You can use this as a workaround

flatpak override --user --env=GDK_SCALE=2 com.valvesoftware.Steam

the change will be permanent for your user

**Comment by nanonyme** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5460 as well shows some of the current limitations

**Comment by jdoda** [comment]
Just wanted to follow up quickly to say that the workaround worked (I didn't realize you could make changes like that permanent, that's pretty cool). I also wanted to thank you for your responsiveness on this issue, even though it seems that it didn't end up being a problem with the flatpak at all.

**Comment by G-Ray** [comment]
Should we report this issue to another repo ? a runtime maybe ?

**Comment by nanonyme** [comment]
@G-Ray as commented above, probably a Steam bug. There is already a ticket on Steam side.

**Comment by G-Ray** [comment]
Ok so I close this. Thanks you all :heart:
