### ISSUE TITLE
 OpenSuse tumbleweed libc.so.6

### ISSUE THREAD

**Issue by luisXoliveira** [flathub/com.valvesoftware.Steam#303]
**Game information**
 
steam doesn't open

**Distribution name and version where applicable**
 
Opensuse

**Flatpak info**

Flatpak 1.0.6
default
host

**Problem description**

when i try to launch the steam he not open and display message informing missing libc.so.6

**Does this issue reproduce with native Steam**
no

**Comment by Alexander-Wilms** [comment]
Duplicate of #1?

**Comment by nanonyme** [comment]
Which GPU is this with?

**Comment by nanonyme** [comment]
Also this is 64bit host, right?

**Comment by nanonyme** [comment]
Closing as no input.
