### ISSUE TITLE
Documentation to migrate saved games files from distrib repo install to flathub install

### ISSUE THREAD

**Issue by MightyCreak** [flathub/com.valvesoftware.Steam#307]
### Use case
I used to install Steam from RPMFusion repo, but tried recently to install it from Flathub. Overall -- and since I found the flatpak override command to add another filesystem, I'm very happy with the Flatpak version.

Only problem though: I lost all my saved games files (notably on Transport Fever).

### Investigation
After some search, I discovered where the saved games files are in the filesystem:
* For a distrib install, it's the `.local/share/Steam/userdata/#SteamUserID/` directory
* For a flatpak install, it's the `.var/app/com.valvesoftware.Steam/data/Steam/userdata/#SteamUserID/` directory

To find you Steam user ID, after you logged at least once with the Flatpak Steam, go into `.var/app/com.valvesoftware.Steam/data/Steam/userdata/`. In this folder, you should find at least one directory with a numerical name (e.g. `123456789`). Open `123456789/config/localconfig.vdf` and look at the `"PersonaName"` property. If it's your name, then the root folder name is your Steam ID (I find this way much easier than the [official one](https://support.steampowered.com/kb_article.php?ref=1558-QYAX-1965) from Steam which requires to install a Valve game and run or join a server).

Copying the content of the game ID's directory (e.g. 446800 for Transport Fever) from one directory to the other worked.

### Possible solutions
It would be nice to have a "migration" article in the wiki explaining where to find your SteamID and how to migrate Steam files from a distrib install to a flatpak install.

Even better would be to have a script...

--------
Also, maybe there are other Steam files that would be interesting to migrate?
Maybe simply copying `.local/share/Steam/userdata/#SteamUserID/` into `.var/app/com.valvesoftware.Steam/data/Steam/userdata/` is the solution?

**Comment by nanonyme** [comment]
There's no good solution that works with all games. The save game locations are a bit of a mess. Cloud sync should work fine these days for saves.

**Comment by MightyCreak** [comment]
Yeah.. but it clearly does not for some games.
I think it would still be interesting to have the procedure written somewhere in the wiki, don't you think?

**Comment by nanonyme** [comment]
Does it not work for some Steam Cloud games?

**Comment by sat3ll** [comment]
> Yeah.. but it clearly does not for some games.
> I think it would still be interesting to have the procedure written somewhere in the wiki, don't you think?

Steam cloud or not, they can save to anywhere they want (there's no universally followed standard here, some do XDG dirs, others save as .folder, ~/GameName or ~/PublisherName).

Writing a procedure on this would mostly be going on a case-by-case basis.

**Comment by nanonyme** [comment]
@sat3ll exactly and I'm not going to be writing one such document. I am expecting though that your saves get synced automagically from RPMFusion Steam to Flatpak Steam through Steam Cloud for games that use it. If that doesn't work, I want to know.

**Comment by sat3ll** [comment]
People interested could use the info at https://pcgamingwiki.com/wiki/Home (has info where the savefiles are located) and fill in the gaps themselves (map from native steam install "root" to flatpak-steam "root").

**Comment by sat3ll** [comment]
> Is there any way to get the path to savegames on per-game basis? Maybe in some .vdf files or Steam has API for that?

None that I have heard of.
You could devise a crude way by parsing the entries of games from https://pcgamingwiki.com/wiki/Home.

**Comment by gasinvein** [comment]
Well, at least we have per-game `remotecache.vdf` file, which contains paths to files synced to steam cloud. This paths are relative to some numbered `root` in the same file. Meanings of some `root` numbers can be guessed (e.g. `0` is the `remote` directory, `14` is user home), yet I've failed to find a reliable full list of this values.

**Comment by MightyCreak** [comment]
I didn't know there was no standard way to store saved files when using Steam. But anyway, I wasn't requesting for a full blown solution ;)
At least a mention in the FAQ or a dedicated page in the Wiki would be nice. Just something warning that going from distrib install to flatpak install might make you lose some saved files and list the conditions; something like that:
* if the saved files are sync with Steam Cloud => no problem
* if the saved files are outside `~/.local/share/Steam` => no problem
* if the saved files are inside `~/.local/share/Steam` => problem: you'll need to copy the files from `.local/share/Steam/userdata/#SteamUserID/` to `.var/app/com.valvesoftware.Steam/data/Steam/userdata/#SteamUserID/`

**Comment by MightyCreak** [comment]
It could be a dedicated page (in order not to clutter the FAQ), but a reference to the FAQ could be useful; something like that:

> ### I lost my saved files
> It can happens for some games, check [this page](#pagelink) for possible solutions.

**Comment by nanonyme** [comment]
@sat3ll this application actively prevents you from allowing access to home because this application rewrites some contents in your home directory to make Steam Cloud work so it's better it's safer this is a sandbox.

**Comment by nanonyme** [comment]
Anyhow. The wiki is open for contributions.
