### ISSUE TITLE
Screenshot does not appear

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#308]
![captura de tela de 2019-01-19 17-26-59](https://user-images.githubusercontent.com/26097419/51431425-56e97500-1c07-11e9-98ad-fdc1a871af28.png)

**Comment by LeandroStanger** [comment]
X11

**Comment by LeandroStanger** [comment]
@nanonyme Did not work
![captura de tela de 2019-01-20 17-35-09](https://user-images.githubusercontent.com/26097419/51444076-76e56b00-1cd1-11e9-838f-ee0052837877.png)

**Comment by nanonyme** [comment]
Sorry, wait, what is that dialog actually about? I don't speak that language.

**Comment by LeandroStanger** [comment]
@nanonyme It didn't work
![captura de tela de 2019-01-20 17-35-09](https://user-images.githubusercontent.com/26097419/51444076-76e56b00-1cd1-11e9-838f-ee0052837877.png)

**Comment by LeandroStanger** [comment]
@nanonyme Worked after update https://github.com/flathub/com.valvesoftware.Steam/pull/309
![captura de tela de 2019-01-20 18-35-54](https://user-images.githubusercontent.com/26097419/51444710-ee1efd00-1cd9-11e9-9e27-c6b771e36b4b.png)

**Comment by nanonyme** [comment]
Makes no sense really, that had no functional changes. You can close the bug if you can no longer reproduce, of course
