### ISSUE TITLE
Steam In-Home Streaming Grey/Green screen when not using "Display Performance Information"

### ISSUE THREAD

**Issue by Pobega** [flathub/com.valvesoftware.Steam#313]
As the title says, when I use In-Home streaming I get a very grey screen or a full green screen when trying to stream from my Windows PC. Streaming works fine on my Link and Link App, so the host isn't the issue.

What's strange is that when I use the "Display Performance Information" option, it seems to work perfectly fine. But I'd prefer not to play with all of that information cluttering my screen.

I've tried all combinations of disabling/enabling hardware decoding on the host and client, but the only thing that gets it to work at all is enabling the performance information overlay.

Edit: System information is Intel HD 5500, Fedora 29, Mesa 18.3.1 (per Flatpak)

Edit2: Start+Y on the controller mostly disables the HUD which is nice for playing, but still doesn't solve the initial issue.

**Comment by Pobega** [comment]
I realize that this is the wrong place to put this bug as this isn't the Valve-run repo, so I'll just close this out and post it there. Sorry.

**Comment by Ziris85** [comment]
Jut posting for visibility here in case anyone stumbles upon this bug report first like I did, the subsequent one opened by @Pobega with Valve directly got LOTS of feedback and has a fix in the beta release client as of this writing. Link to the bug report with them:

- https://github.com/ValveSoftware/steam-for-linux/issues/6066
