### ISSUE TITLE
Set the real distribution instead of "Linux 4.x"

### ISSUE THREAD

**Issue by romainf-unity** [flathub/com.valvesoftware.Steam#314]
I discovered that the Steam survey detects the distribution as "Linux 4.x" when Steam has been installed with Flatpak. Is it a "limitation" from Flatpak, or it it an information the Flatpaked app could read from the host?

**Comment by nanonyme** [comment]
Been looked at before, most likely Steam is working inconsistently. At beginning (shell wrapper) it does dig out the right information from /etc/os-release but then seems to lose it. It's also possible they just ignore some categories of distributions as generic.

**Comment by romainf-unity** [comment]
So it _is_ possible to fetch the right distribution, even when installing Steam with Flatpak, but Steam's scrapper seems to lose the information at some point, is that it?

**Comment by nanonyme** [comment]
That's how I understood it. We could for course try some hacks to see if it could work better but meh. The runtime is already using the generic cross-distro mechanism for providing the information and populating the right fields.

**Comment by romainf-unity** [comment]
Well, since it doesn't seem to be a Flatpak bug, I don't mind closing this issue.

**Comment by nanonyme** [comment]
Here's relevant upstream bug https://github.com/ValveSoftware/steam-for-linux/issues/5909

**Comment by nanonyme** [comment]
Note that it's also possible we're just too small to justify separate statistical group. Hard to know for sure without seeing Steam guts.

**Comment by nanonyme** [comment]
Ideally we would show up as Freedesktop.org 18.08 or something iirc. Actual host information will not be visible

**Comment by nanonyme** [comment]
This now finally works! I ended up having to write a bash script called lsb_release which reads /etc/os-release and implements lsb_release implementation. Apparently Steam wants that to exist and parses the output.
