### ISSUE TITLE
No menu text in Civilization V

### ISSUE THREAD

**Issue by jurf** [flathub/com.valvesoftware.Steam#32]
The menu simply doesn’t display text.

**Comment by nedrichards** [comment]
I can't reproduce this on todays release of Steam. Can you?

**Comment by jurf** [comment]
Unfortunately, yes:

![snimka obrazovky z 2017-12-17 15-07-58](https://user-images.githubusercontent.com/7472425/34080314-2b803386-e33c-11e7-99ee-d696a7de686f.png)

**Comment by TingPing** [comment]
Works fine here (Nvidia 387.34, Fedora 27)

**Comment by jurf** [comment]
Intel, F27 here. Works fine in a native Steam installation.

**Comment by jurf** [comment]
(Do you have Brave New World btw? Could be that, even if unlikely.)

**Comment by TingPing** [comment]
I do have BNW.

**Comment by TingPing** [comment]
So some issue with Intel/Mesa I suppose.

**Comment by chgue** [comment]
Had the same issue with Intel graphics , ``flatpak update`` fixed it. After playing for a few hours I encountered no bugs!

**Comment by jurf** [comment]
No, still happens for me, system up-to-date.

**Comment by nanonyme** [comment]
Does this still reproduce?

**Comment by jurf** [comment]
It doesn’t!
