### ISSUE TITLE
Add Steam Beta

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#321]

**Comment by nanonyme** [comment]
Probably not going to happen. You can already enable beta yourself.

**Comment by LeandroStanger** [comment]
Add runtime Freedesktop 19.08

**Comment by nanonyme** [comment]
Freedesktop 19.08 doesn't yet exist. We'll migrate to it when it does.

**Comment by nanonyme** [comment]
Ended up doing this anyway since https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/706 this plan changes basically everything.

**Comment by LeandroStanger** [comment]
https://repo.steampowered.com/steam/archive/precise/steam_latest-beta.tar.gz
