### ISSUE TITLE
Steam keeps asking me to log in every time I restart my computer

### ISSUE THREAD

**Issue by MightyCreak** [flathub/com.valvesoftware.Steam#323]
**Game information**
Steam

**Distribution name and version where applicable**
Fedora 29 (Workstation Edition)

**Flatpak info**
Flatpak 1.2.3
default
host

**Problem description**
Since I installed Steam with flathub, every time I reboot my machine, I have to log in again to Steam (the Steam Login window, with login password and, for me, 2FA auth), and even though I checked "Remember my password".

**Does this issue reproduce with native Steam**
No (I'm 80% sure)

**Comment by nanonyme** [comment]
Possibly related to #199.

I've been wondering if this is related to ostree storing files with mtime 0 but I don't have a good theory on sequence of events nor a machine to debug in depth with. If anyone wants to dig deeper, would be nice.

**Comment by nanonyme** [comment]
Hmm, I just realized this doesn't happen to me. Are you by chance using some other language than English?

**Comment by MightyCreak** [comment]
Yes indeed, my set up is in French Canadian. That said, I didn't have this bug for a few months now. As far as I'm concerned, this issue can be closed.
