### ISSUE TITLE
Needed Mesa update to avoid rendering issues. RE2/Biohazard 2

### ISSUE THREAD

**Issue by m0nt3sh0t** [flathub/com.valvesoftware.Steam#327]
**Game information**
Resident Evil 2/ Biohazard 2 Remake 

**Distribution name and version where applicable**
OpenSuse Tumbleweed 20190301.

**Flatpak info**

  flatpak 1.2.3
  default
  host
  amd

**Problem description**
Game launches with mfplat workaround, however walls, ceilings, and floors are all missing. Mesa 18.3.3 or newer required to solve issue. Tested with steam wine and native steam proton and host version of mesa 18.3.3/4 and runs great. I think com.valvesoftware.Steam is on 18.2.X also tested with the testing version of com.valvesoftware.Steam

**Does this issue reproduce with native Steam**
 No, I choose to run flatpak version of steam to avoid sym-linking a lot of lib files to get games to launch with the native version.

**Comment by nanonyme** [comment]
Opened https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/682 and linked things together better.

**Comment by nanonyme** [comment]
Mesa 18.3.4 is now integrated, pending release. You can ask further on #freedesktop-sdk IRC channel at Freenode.

**Comment by nanonyme** [comment]
Fix is now published
