### ISSUE TITLE
Problem in launching Civilization 6

### ISSUE THREAD

**Issue by ValYats** [flathub/com.valvesoftware.Steam#328]
**Game information**

Civilization 6
**Distribution name and version where applicable**
Endless Os 3.5.6

os-release:
AME="Endless"
VERSION="3.5.6"
ID="endless"
ID_LIKE="ubuntu debian"
PRETTY_NAME="Endless 3.5.6"
VERSION_ID="3.5.6"
HOME_URL="http://www.endlessm.com/"
BUILD_ID="190211-175752"

**Flatpak info**

  flatpak --version
Flatpak 1.0.0
  flatpak --gl-drivers
default
host

**Problem description**

When I launch Civilization 6 the game won’t show up / start and in Steam it says that the game is running.
I’ve tried to uninstall steam, uninstall the game, delete the com.valvesoftware.Steam file, restarting my PC and using the kill command on terminal. Can’t start a steam game. Tried everything. I have 3.5.6 Endless os. When I wrote sudo flatpak updatwe saw this:user@endless:~$ sudo flatpak update

Looking for updates…
flatpak update: Warning: No xa.metadata in commit 38efc5893c8b90b2658ed2889bcbdb4d65b2436fb8dcf70feba32932caaeda3f ref app/com.endlessm.translation/x86_64/eos3
flatpak update: Warning: No xa.metadata in commit d820ec5293561d48b6132a57775038ecb75d48effa3eb53011da5eecc945c444 ref app/de.billardgl.Billardgl/x86_64/eos3
flatpak update: Warning: No xa.metadata in commit 3c3c806e5bf6f49651c42b91d063cd9878f8194480006d28dcc11920fa6a6a42 ref app/org.squeakland.Etoys/x86_64/eos3
flatpak update: Warning: No xa.metadata in commit 3d5627ac4bacd36378514cb8dd4b1a52b481f12bac242a7a3f46c8a3f081e167 ref app/org.squeakland.Scratch/x86_64/eos3
flatpak update: Warning: No xa.metadata in commit 63ec8da8222881568631a9278234eacb70b1593dcd0d07832a9299bc0774e0fe ref app/org.gnome.Freecell/x86_64/eos3
flatpak update: Warning: No xa.metadata in commit f7a9b9a91c09d4629f415e13a7f01a03b3b155466d6337ca0c2a6fac05ab6e61 ref app/org.gnome.Solitaire/x86_64/eos3
user@endless:~$

**Does this issue reproduce with native Steam**

[eos-diagnostic-190307_234526_UTC+0200.txt](https://github.com/flathub/com.valvesoftware.Steam/files/2945861/eos-diagnostic-190307_234526_UTC%2B0200.txt)

**Comment by nanonyme** [comment]
See end of https://github.com/flathub/com.valvesoftware.Steam/issues/95 if you're running on Intel or AMD.

**Comment by nanonyme** [comment]
This was investigated to some extent. The game is bundling dozens of libraries it shouldn't.
