### ISSUE TITLE
Steam does not recognize my installed games on a external drive.

### ISSUE THREAD

**Issue by mzigaib** [flathub/com.valvesoftware.Steam#329]
**Game information**

**Distribution name and version where applicable**

**Flatpak info**

**Problem description**

**Does this issue reproduce with native Steam**

**Comment by nanonyme** [comment]
You followed the instructions on https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-want-to-add-external-disk-for-steam-libraries right?

**Comment by mzigaib** [comment]
Yes I did and kind of worked until the point that I could add the drive and the locations but it doesn't detect the games that are there, in windows it works just fine.
Any tips?

**Comment by nanonyme** [comment]
Ah, so it's not from native Linux Steam installation? I have no idea if that works then, at least you would end up redownloading all the non-Proton games because it's different binaries.

**Comment by mzigaib** [comment]
> Ah, so it's not from native Linux Steam installation? I have no idea if that works then, at least you would end up redownloading all the non-Proton games because it's different binaries.

I think that's the case, I have to to tell Steam to install the games again even the ones that are already in my external drive, some of the games Steam does "re-discover" other ones it is downloading partially, but it is kind of working, the last time I did installed Steam I just added the drives and the games were automatically I don't know what had changed maybe I did something wrong I don't know.

At least I have Steam working now on which is really nice, thanks again everyone for the help.
