### ISSUE TITLE
Crypt of the NecroDancer doesn't work

### ISSUE THREAD

**Issue by darkwater** [flathub/com.valvesoftware.Steam#33]
The very first screen show the developer's name. After that, a video is supposed to play but instead it's just silent black. Pressing escape quits the game instantly.

**Comment by nanonyme** [comment]
Does this still reproduce?

**Comment by darkwater** [comment]
I don't know. I stopped using Flatpak for Steam a while ago as too many games wouldn't work, and I got Steam running natively quite nicely now. I recall it still being broken a couple of months ago.

**Comment by nanonyme** [comment]
We just had a major runtime update a week or so ago which invalidated a bunch of test results. Some regressions but mostly to better direction

**Comment by Pixelnarium** [comment]
It works for me so far. (Intel iGPU)
