### ISSUE TITLE
Steam does not start

### ISSUE THREAD

**Issue by TalviT** [flathub/com.valvesoftware.Steam#369]
I just installed Steam (system-wide), but when I try to start it nothing happens.
When started via the terminal, the following output appears 
```
$ flatpak run com.valvesoftware.Steam 
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Overriding TZ to Europe/Berlin
Running Steam on org.freedesktop.platform 18.08.32 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
$ _
```
I also tried running Steam with the reset-option:
```
$ flatpak run com.valvesoftware.Steam --reset
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Overriding TZ to Europe/Berlin
/home/talvi/.local/share/Steam/steam.sh: Zeile 630: Keine Entsprechung: ssfn*
Running Steam on org.freedesktop.platform 18.08.32 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
^C
$ _
```
I'm running Manjaro Linux with Flatpak 1.4.0

Any Idea how to fix this?

**Comment by LeandroStanger** [comment]
Try the command
>flatpak run com.valvesoftware.Steam --reset

**Comment by TalviT** [comment]
I already tried that, see the second terminal output I posted before…

**Comment by nanonyme** [comment]
I would try installing GlxInfo app from branch 18.08

**Comment by TalviT** [comment]
The problem was solved, I somehow managed to install steam not system-wide, but into the "/root" directory... so I was probably the problem, not flatpak or steam. I reinstalled it correctly, now everything works. Sorry for the confusion.

**Comment by nanonyme** [comment]
Were you using sudo/root to install? Normally you use suid helper to install to system.
