### ISSUE TITLE
this Flatpak is safe? [question]

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.valvesoftware.Steam#373]
A friend questioned the safety and continuity of this flatpak, for not an official client offered on the home site Valve and for doing banking transactions...
What is the chance of this flatpak being discontinued?

**Comment by nanonyme** [comment]
Keep in mind purchases are bound to your Steam account and not this Flatpak application so even in the event this application was discontinued, you do not lose what you have bought assuming there still is some other Steam client that can be used on Linux.

That said, this is one of the high-profile apps on Flathub and there is desire to keep it running and to improve it as long as Valve keeps is legally and technically possible.

As for security, as long as you use system installation on Flatpak, this deliverable isn't any less secure that other means of running Steam in other words Steam downloads executable files with user privileges to directory writable by other user applications and executes them. There's more isolation from other Flatpak apps but uncontained software can write over application files in user home directory.
