### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by Queuecumber** [flathub/com.valvesoftware.Steam#377]
**Game information**
Any

**Distribution name and version where applicable**
Ubuntu 18.04 docker 

**Flatpak info**
Flatpak 1.4.1

nvidia-418-74
default
host

**Problem description**
I have an unusual setup that I am not able to debug. I am in the process of dockerizing Steam to run on a headless server with a GPU. Installing steam naively in the container is pretty difficult to get right, I was often having games crash or refuse to run at all. But in general audio was working fine through pulseaudio (using in-home streaming to test).

I have switched to using the flatpak and it has made my life significantly easier, all games Ive tried including proton games (so far) have worked without issue, the only thing missing is audio. This is the same audio setup I was using natively e.g. pulseaudio is installed to the container and running and I can talk to it with `pactl` etc. Steam big picture mode also reports "Audio settings unavailable. Failed to connect to an audio service" from "cog -> audio -> interface" and there's no sound over in-home streaming.

How can I debug why flatpak or steam isnt able to connect to the pulseaudio server I have running in the container? I have tried https://github.com/flathub/com.valvesoftware.Steam/issues/325#issuecomment-473433149 but it didn't work and I can't see any unusual output in the console after running steam. Is there someplace that flatpak logs what it's trying to do or maybe a verbose mode?

**Does this issue reproduce with native Steam**

No

**Comment by Queuecumber** [comment]
I did manage to find the following output using `flatpak run --verbose`

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /steam/.local/share/flatpak
F: Opening user flatpak installation at path /steam/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /steam/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2497000359
F: Allocated instance id 109973626
F: Add defaults in dir /com/valvesoftware/Steam/
F: Add locks in dir /com/valvesoftware/Steam/
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/steam/.config/pulse/client.conf': Error opening file /steam/.config/pulse/client.conf: No such file or directory
F: Could not find pulseaudio socket
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running '/usr/libexec/flatpak-bwrap --args 33 /usr/libexec/flatpak-dbus-proxy --args=35'
F: Running '/usr/libexec/flatpak-bwrap --args 33 steam-wrapper'
```

**Comment by Queuecumber** [comment]
I think those errors may be a red herring, I found that if I make sure that steam is launched directly from xinitrc, the same place pulseaudio is launched from, and not from a terminal then things seem to work fine despite the same errors appearing.

**Comment by Queuecumber** [comment]
Seems like #325 is also still required, when I destroyed the home directory mount and rebuilt it I didnt have sound until I reapplied this file

**Comment by nanonyme** [comment]
Those paths startin with /steam look weird. Are they redacted? I would expect files to be under /app, /home, /var/home or /usr.

**Comment by nanonyme** [comment]
Why do you want to dockerize Steam in the first place?

**Comment by Queuecumber** [comment]
`/steam` is where I assigned the home directory for the user in the docker container (since steam doesnt like to be run as root I needed to make a user account in the container). I assume it would work unless something is hard-coded to look in `/home` so maybe that was a bad idea. 

I have access to some headless GPU resources (in a kubernetes cluster) and thought it would be a fun (in terms of using it and in terms of creating it) to get steam in-home streaming running on one of these GPUs.

This is fully functional now, I mostly am keeping it open in case someone who knows more about flatpak has suggestions for making the setup a little smoother, and because I still see the pulseaudio error on the console even though audio appears to be working. 

The only thing that doens't work and that I can't figure out is why, during in-home streaming sessions, the controller works on the steam UI but not in games. I understand its documented and something to do with udev but I can't figure out how to fix it

**Comment by nanonyme** [comment]
Well, the app isn't using external home but a sandboxed one.

**Comment by nanonyme** [comment]
I'm just wondering why you want to put a container inside a container. What's the real use case?

**Comment by Queuecumber** [comment]
Here's what I would put on a powerpoint slide

* Kubernetes cluster has a powerful GPU
* Laptop has weak GPU
* flatpak container run steam easily but cant be scheduled by kubernetes 
* docker container can be scheduled by kubernetes
* Solution: put flatpak inside docker container, schedule docker container on cluster, play games using steam in home streaming

**Comment by nanonyme** [comment]
Hmm, could you please ping https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues about this use-case. It would technically be possible to remove Flatpak from the equation and just build a docker image with the runtime and Steam bootstrap. I feel Flatpak might add unnecessary complexity to this setup.

**Comment by nanonyme** [comment]
I mean, whether you get it to work or not. Freedesktop-sdk already creates Docker images of some of itself.

**Comment by nanonyme** [comment]
I still think it's weird though to see that path in logs. Have you been setting some overrides/parameters to Flatpak app?

**Comment by Queuecumber** [comment]
I think flatpak makes it a lot easier actually, I spent about a week trying to get it running in the docker container directly, getting that right would basically involve reimplementing the flatpak. I did eventually get steam running but games were highly unstable, with the flatpak everything just works (except the controller). 

That being said it is a little convoluted to run container in container so I'm going to take a closer look at the project you pointed me to, I hadn't heard of it and it looks pretty cool. 

I don't think I set any overrides, but what is possible is that my minimal environment misses something important 

The repository with the dockerfile is public and should be up-to-date 

https://gitlab.com/Queuecumber/docker-steam

**Comment by nanonyme** [comment]
That same project builds the Flatpak runtime that this app uses. They also have incentive to build apps through their own tool without Flatpak. I imagine they would see prebaked app docker images an interesting use case.

**Comment by Queuecumber** [comment]
Yeah that looks like exactly what I need, I'll see if I can hack something together that works based on that and then bring it to their attention

**Comment by nanonyme** [comment]
Ping @valentindavid

**Comment by nanonyme** [comment]
There was also a suggestion to try the OCI images you can export out of Flatpak.

**Comment by valentindavid** [comment]
Streaming needs a valid pulseaudio device to be configured. Not sure how you got it to work in Docker.   Maybe it was started automatically. I would add pulseaudio server in the docker image. Start it as server in the entrypoint script configured with just a null device.

You can set environment variables `PULSE_SERVER`. If the client configuration file is placed in a non standard place, please also define `PULSE_CLIENTCONFIG`.

**Comment by Queuecumber** [comment]
There's a pulseaudio server in the image and it's started in xinitrc I confirmed that it sets those environment variables. It works so I think it's just those log messages from flatpak that are wrong

**Comment by nanonyme** [comment]
Was there any progress on this or did you drop the attempt?

**Comment by Queuecumber** [comment]
I never got it working without the flatpak in docker trick but ultimately decided that scheduling windows vms would be more useful

**Comment by nanonyme** [comment]
Okay. I'm going to close this then as out of scope.
