### ISSUE TITLE
Flatpak Steam requires 32bit libraries installed via APT

### ISSUE THREAD

**Issue by RiderExMachina** [flathub/com.valvesoftware.Steam#379]
This came after trying to have a 64bit only Ubuntu to see how Canonical's decision to completely drop 32bit support in 19.10 would affect Steam titles. To get a feel for how it would affect Steam gamers, I followed Alan Pope's guide on the Ubuntu Discourse thread and did the following:

1. Grabbed the daily Ubuntu Eoan ISO and installed it on bare-metal
2. Updated the system via `sudo apt update && sudo apt dist-upgrade`
3. Removed all i386 software via `sudo apt remove "*:i386"`
4. Disabled i386 in DPKG via `sudo dpkg --remove-architecture i386`

I then attempted to install  and run the Steam flatpak. When doing so, Steam gives the error 
```
Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
```

and attempts to install the packages via APT.

**Comment by nanonyme** [comment]
You're incorrect. I wonder if Ubuntu also removed kernel support for 32bit binaries from kernel. I think the option may be CONFIG_X86_X32. If this is the right option and it's not enabled, your choices are to install a third-party kernel or change distro. Seems it's enabled by default but it can be explicitly disabled if you have a distro who doesn't want you to run 32bit.

**Comment by nanonyme** [comment]
It looks like not. So support should be available through a Flatpak extension which should get automatically installed. Try running flatpak update on command line.

**Comment by RiderExMachina** [comment]
Running `flatpak update` says there is nothing to update. Running `steam` again  brings up the same error.

Note: Canonical has now said they won't be completely dropping support for 32bit anymore, so this isn't that big of an issue as it used to be.

**Comment by nanonyme** [comment]
What does "flatpak list" output for you? The thing is, there's a sandbox, this application isn't even capable of using libraries from your host operating system.

**Comment by RiderExMachina** [comment]
```
inigo@eoan:~$ flatpak list
Name                        Application ID                                     Version         Branch       Installation
Steam                       com.valvesoftware.Steam                            1.0.0.61        stable       system
Freedesktop Platform        org.freedesktop.Platform                           18.08.32        18.08        system
i386                        org.freedesktop.Platform.Compat.i386                               18.08        system
nvidia-430-26               org.freedesktop.Platform.GL.nvidia-430-26                          1.4          system
nvidia-430-26               org.freedesktop.Platform.GL32.nvidia-430-26                        1.4          system
html5-codecs                org.freedesktop.Platform.html5-codecs                              18.08        system
Yaru Gtk Theme              org.gtk.Gtk3theme.Yaru                                             3.22         system
```

**Comment by nanonyme** [comment]
That's *really* weird. org.freedesktop.Platform.Compat.i386 contains all the libraries you were commenting about before. Are you sure you don't have a native Steam installation on the side that you're confusing things with? I definitely don't have any 32bit libraries on my host system either.

**Comment by RiderExMachina** [comment]
I did try to install the .deb package first thing. I didn't think it was successful and when I ran `apt remove steam` it said that `Package steam:i386 is not installed`

However, running `which steam` shows `/usr/bin/steam` so it could be that the .deb did actually install and that's what is causing this issue. Let me see if I can finagle some stuff...

**Comment by nanonyme** [comment]
You could try starting the Flatpak from command-line through "flatpak run com.valvesoftare.Steam". That will definitely start the right thing.

**Comment by RiderExMachina** [comment]
Looks like this was due to an oversight. I ran `flatpak run com.valvesoftare.Steam` and it started right up. I'm closing this ticket. Thanks for your help!

**Comment by nanonyme** [comment]
Note I suggest trying to run purge instead of uninstall on native Steam to try to make it be more completely removed.
