### ISSUE TITLE
Steam will not Show\Add Steam folders on ntfs partitions. [Im running KAOS\Linux]

### ISSUE THREAD

**Issue by jouks-netlander** [flathub/com.valvesoftware.Steam#383]
**Game information**

**Distribution name and version where applicable**

**Flatpak info**

**Problem description**

**Does this issue reproduce with native Steam**

**Comment by nanonyme** [comment]
Please fill the template although if the games are installed on Windows, I don't expect them to be usable on Linux.

**Comment by jouks-netlander** [comment]
Some windows games are playable via proton, the problem is when installing
games they wind up in your home folder, which I keep under the root folder,
and store all media etc in an ntfs partitions for compatibility with
windows, its bloating my Linux system partitions. Backups and redundancy
are the issue for me.

**Comment by jouks-netlander** [comment]
Update:
Adding a steam folder created under the ntfs partitions root dir
 has succeed and I am downloading a game now.
Note: I tried this months ago and it would not work
consider this issue resolved unless I repost.

**Comment by jouks-netlander** [comment]
Sorry to bother you, After reboot the ntfs folder disappears from steam
settings.

**Comment by nanonyme** [comment]
Eh. That's really strange. Does that happen with non-NTFS libraries?

**Comment by jouks-netlander** [comment]
"NTFS libraries" to me means ntfs3g.
Don't know much more about it then that, sorry.
All my Native linux apps run fine, and access all the data
in the ntfs partition. It seems to be a flatpak issue.
I think it may be due to some of its security features.

The same happens to
Phoenicis PlayOnLinux. Both only seem to
display folders made from within Linux.
Though I was able to get that last attempt
to allow adding the Steam folder made in ntfs root
it did not survive the reboot.

The KAOS Distro is KDE only thats why I have
to use flatpak. Its built from scratch and uses pacman.
https://kaosx.us/about/toolkits/ Hope that helps.

**Comment by nanonyme** [comment]
Sorry for being confusing. I meant, if you add a location on regular Linux disk as Steam library location, does it survive over reboot?

**Comment by nanonyme** [comment]
As in, I'm curious if that disappearing act happens only with NTFS.

**Comment by jouks-netlander** [comment]
Yes. I think it may be a security decision\permission\group? done at boot.
