### ISSUE TITLE
Add gamemoderun

### ISSUE THREAD

**Issue by piotr-szegda** [flathub/com.valvesoftware.Steam#393]
Beta version of this package support gamemode but it's including gamemoderun. May be should be added?

**Comment by nanonyme** [comment]
How are you trying to run it?

**Comment by piotr-szegda** [comment]
Yes on last beta, log from console:
/bin/sh: gamemoderun: command not found
I also don't see gamemoderun file in package. I think is should be in ~/.local/share/flatpak/app/com.valvesoftware.Steam/current/active/files/bin/. 
Steam system info show "Description:	Freedesktop.org 19.08beta.2 (Flatpak runtime) (64 bit)" so I using beta. Simple coping gamemoderun from system don't work because of this:
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by piotr-szegda** [comment]
Setting GAMEMODEAUTO to "/app/lib/libgamemodeauto.so.0" in gamemoderun work but probably just for 64 bit apps.

**Comment by nanonyme** [comment]
Can we put both 32bit and 64bit libraries to GAMEMODEAUTO once they are available?

**Comment by piotr-szegda** [comment]
In my opinion yes. This script just LD_PRELOAD 64 or 32 bit libgamemodeauto.so.0. On 32 bit executable loading 64 bit files just don't work and vice versa. Only drawback will be consol spam:
ERROR: ld.so: object '/usr/lib64/libgamemodeauto.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by nanonyme** [comment]
Well, that's more or less what happens now too both with some Steam libraries and shared-library-guard.

**Comment by nanonyme** [comment]
32bit gamemode should be easy to do on top of https://github.com/flathub/com.valvesoftware.Steam/pull/387 once I figure out why it doesn't build.

**Comment by gasinvein** [comment]
AFAIK gamemoderun is a helper script for running apps manually from the CLI with gamemode enabled. What do you need it for?

**Comment by piotr-szegda** [comment]
It can be also used to run any game in steam with gamemode. It's simpler to add gamemoderun %command% then LD_PRELOAD="$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so.0". Secund one also not work in this package because is different. 
gamemoderun is official recommended method in documentation https://github.com/FeralInteractive/gamemode#requesting-gamemode

**Comment by nanonyme** [comment]
Considering how simple the script interface is, it's probably less effort to provide a separate gamemoderun for this app rather than to try to patch the upstream tool.

**Comment by nanonyme** [comment]
32bit gamemode now exists. This is next on task list.

**Comment by Bryophyllum** [comment]
Can we have gamemoderun configured with a `gamemode.ini` file? I ran the command: `flatpak override --user --filesystem=~/.config/gamemode.ini:ro com.valvesoftware.Steam`, and restared Steam for the override to take affect, but my settings would not be picked up.

**Comment by gasinvein** [comment]
Try using `xdg-config/gamemode.ini` instead of `~/.config/gamemode.ini`.
Is this config file used by gamemode clients?

**Comment by Bryophyllum** [comment]
@gasinvein False alarm. The step override was unnecessary, gamemoded reads my configuration file just fine when I launch games, and I just missed an entry in logs. 🤦 Though there's still a problem with gamemode itself, as it has no permission to set change niceness levels: `Failed to renice client [19451,19454], ignoring error condition: Permission denied`. I have no idea whether it's an upstream or Fedora Silverblue issue.

**Comment by gasinvein** [comment]
@Bryophyllum looks like upstream issue to me. If the daemon did receive the request, then it's not related to flatpak anymore.
