### ISSUE TITLE
Clicking on links fails with "Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.OpenURI' of the object in path /org/freedesktop/portal/desktop"

### ISSUE THREAD

**Issue by digulla** [flathub/com.valvesoftware.Steam#405]
Clicking on links in the Steam client itself fails with the error

> Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.OpenURI' of the object in path /org/freedesktop/portal/desktop

I have xdg-desktop-portal and xdg-desktop-portal-gtk installed. I'm using Xfce as desktop.

How do I fix this?

I already tried

    dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

plus restarting Steam without success.

**Comment by nanonyme** [comment]
I have no idea. Most likely not specific to an app. Maybe file on flatpak/flatpak for better advice.

**Comment by Erick555** [comment]
AFAIK you can't open 3rd party apps from flatpak other than through portal and steam perhaps doesn't support portals.

**Comment by nanonyme** [comment]
Sounded to me more like whatever is supposed to handle the portal calls doesn't exist on that machine.

**Comment by digulla** [comment]
One of the things that I tried to fix this fixed it but I don't know what (several days after I tried, I clicked a link and it just worked). I'll close this for now since it's fixed but feel free to reopen once someone else has the same problem.

**Comment by Justuser3310** [comment]
The same issue.
Fix by:

1.  Install xdg-desktop-*
2.  Reboot

Maybe xdg-desktop-gnome required for GNOME, but I install gnome, gtk and wlr.
