### ISSUE TITLE
Notifications do not show

### ISSUE THREAD

**Issue by jgillich** [flathub/com.valvesoftware.Steam#41]
I don't get any notifications from either Steam or games. For example:

1) The Steam notification in the bottom right, for chat messages, games downloaded etc
2) The "game ready" notification in Dota 2

I'm not really familiar with flatpak, but [could this](https://github.com/AsavarTzeth/org.telegram.desktop/commit/9947bde57ff2dada6d9a94b36a8622600bd5057a) be a fix?

**Comment by TingPing** [comment]
Steam doesn't use native notifications, it just draws its own windows and works as expected IME. (Flatpak doesn't filter x11 usage, so it can draw anything it wants)

**Comment by nanonyme** [comment]
It strikes me a bit odd though libnotify would be per-app instead of in runtime

**Comment by TingPing** [comment]
@nanonyme libnotify isn't a good library (the entire API is blocking..) and GLib contains a notification implementation most apps should use.

Anyway not relevant because again Steam doesn't use the notification interface it draws its own popups.

**Comment by jgillich** [comment]
You're totally right, Steam's notifications do work (for some reason they didn't show up yesterday, but they do now). But still, Dota 2's notification doesn't show up, which is quite annoying and means you can't really tab out while waiting. They definitely work with regular Steam.

**Comment by TingPing** [comment]
So dota 2 itself actually uses native notifications? Test: `flatpak run --talk-name=org.freedesktop.Notifications com.valvesoftware.Steam`

**Comment by jgillich** [comment]
That makes no difference. Dota 2 uses `notify-send`, probably needs to be added? The logs aren't really helpful, but that's my guess.

**Comment by TingPing** [comment]
Ugh, Of course Valve would call binaries from the host instead of making portable games, why would I expect anything better out of them...

**Comment by nanonyme** [comment]
@TingPing What's your opinion, should we add notify-send to app or just label this game issue?

**Comment by TingPing** [comment]
> @TingPing What's your opinion, should we add notify-send to app or just label this game issue?

Seems harmless to add it.

**Comment by nanonyme** [comment]
Please retest with next update

**Comment by nanonyme** [comment]
Tested that notify-send works but left app by default not allowed to send notifications. Instructions on enabling notifications added to https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions

**Comment by jgillich** [comment]
Ah that explains why this didn't work when I tried it earlier. But the command doesn't work:
```
$ sudo flatpak override --talk=org.freedesktop.Notifications com.valvesoftware.Steam
error: Unknown option --talk=org.freedesktop.Notifications
```

Also, can't notifications be allowed by default?

**Comment by jgillich** [comment]
Works with `--talk-name` I guess that's what you meant?

**Comment by nanonyme** [comment]
Yes. The enabling is now sufficient as libnotify was bundled. Notifications themselves are a controversial feature and not everyone wants to allow Steam to send them. End user can now easily select which way they want it to work

**Comment by jgillich** [comment]
But Steam's own notifications are always shown, this only affects games, and most games don't even use notifications. For Dota 2, I'm sure everyone will want them, because otherwise you can't tab out while waiting for a game. IMO it would be more user friendly to have people opt out instead of having to opt in to notifications.

**Comment by nanonyme** [comment]
Afaik --no-talk-name kind of functionality doesn't even exist in Flatpak so it can only work this way for now

**Comment by andres-jurado** [comment]
(Also posted this in #1678 ValveSoftware/csgo-osx-linux)

I still have this issue on Linux. 

OS: Ubuntu 18.04.2 64-bit.
Hardware: Ryzen 7-1700, RX 580 (8GB), 32 GB DDR4 RAM
Using the default drivers in Ubuntu (AMDGPU-PRO)

Steam API: v018
Steam package versions: 1550534751
**NOT** running steam beta

running steam with flatpak: 

`flatpak run --env=LC_ALL=C com.valvesoftware.Steam`
`flatpak run --env=LC_NUMERIC=C com.valvesoftware.Steam`

The MD5 checksum of `libsteamnetworkingsockets.so` is `fc7417c468b9b816cc8a9ebbdde5eb2e`

I have tried solutions posted elsewhere such as going to CSGO properties > LOCAL FILES > Verify Integrity of Game Files. 1 file fails the test and is downloaded. This **doesn't** solve the issue. 

This problem occurs with any configuration of the firewall (UFW). Currently is set to deny in and allow out.

Another piece of information is that this occurs randomly (I had been able to play in multiplayer for the last few weeks and suddenly couldn't).

This problem persists even if I launch steam without launching any other application, and no application running in the background except those that run in a vanilla Ubuntu install. 

I **don't** have any skins installed, and this problem persists if I reinstall steam.

**Comment by jgillich** [comment]
@andres-jurado But [this](https://github.com/ValveSoftware/csgo-osx-linux/issues/1678) isn't about notifications, I think you commented on the wrong issue.

**Comment by andres-jurado** [comment]
@jgillich my bad, sorry!

**Comment by kon14** [comment]
This is not actually solved as libnotify (and therefore notify-send) is not currently built in modules.yml.
I'm sending a PR for this.

Additionally, with --no-talk-name=NAME having being introduced in flatpak, I'd suggest defaulting to --talk-name=org.freedesktop.Notifications instead, but I'll open a separate issue discussing this.

**Comment by Taza53** [comment]
I am having the same issue
