### ISSUE TITLE
[Beta][freedesktop-SDK] Native Direct3D 9 will be unavailable

### ISSUE THREAD

**Issue by Bryophyllum** [flathub/com.valvesoftware.Steam#410]
Gallium Nine Standalone installed through [Protontricks](https://github.com/Matoking/protontricks/wiki/Usage-with-Flatpak-Steam) prints out the above error when trying to run DirectX9 games. I tried using runtimes from `flathub-beta` instead of ones provided by `freedesktop-sdk` repository, also unseting the environment variable `FLATPAK_GL_DRIVERS` to rule out Valve's ACO shader compiler as the root of the error.  Nonetheless, the problem doesn't appear if I install Steam along with freedesktop runtimes from the stable channel, namely `flathub`.

I've been extensively using this setup to play games, and it'd be a hurdle to keep two installations - one for playing older DX9 games and the other for testing ACO - and switch between both back and forth.

**Comment by gasinvein** [comment]
Current official builds of gallium-nine-standalone don't search for d3dadapter library in flatpak-specific paths. Either build current master, set `D3D_MODULE_PATH` env var pointing to `/usr/lib/x86_64-linux-gnu/GL/lib/d3d`, or wait for gallium-nine-standalone update.

**Comment by Bryophyllum** [comment]
[Ah, I see. ](https://github.com/iXit/wine-nine-standalone/commit/d9c516b8ff380bd3148aaae99757efa341393142)
Do we keep this issue up, or close it?

**Comment by nanonyme** [comment]
Would setting that environment variable break some use cases? We could set it on app level for now

**Comment by nanonyme** [comment]
To be honest, runtime could set the variable too. It would apply to all apps.

**Comment by nanonyme** [comment]
@gasinvein what's the right place to track to see whether the official builds pick up support?

**Comment by Bryophyllum** [comment]
@nanonyme The code that adds the flatpak-specific d3dadapter search paths is already merged with the master branch of Gallium Nine Standalone. Just have a look at the link in my above comment. Now it's only a matter of time before it lands in the next official release.

**Comment by Bryophyllum** [comment]
https://github.com/iXit/wine-nine-standalone/releases/tag/v0.5

**Comment by Bryophyllum** [comment]
@nanonyme Are you able to get it working?

**Comment by nanonyme** [comment]
I thought you meant it's fixed.

**Comment by nanonyme** [comment]
I haven't tested personally. To be fair, we could probably just set D3D_MODULE_PATH=/usr/lib/$LIB/GL/lib/d3d in manifest and call it a day.

**Comment by gasinvein** [comment]
@nanonyme I think Steam flatpak manifest requires update similar to flathub/net.lutris.Lutris#57.

**Comment by Bryophyllum** [comment]
```
Executing w_do_call galliumnine
Executing load_galliumnine 
Executing rm -rf /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine
Executing mkdir -p /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine
Executing tar -C /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine --strip-components=1 -zxf /home/kamil/.var/app/com.valvesoftware.Steam/cache/winetricks/galliumnine/gallium-nine-standalone-v0.5.tar.gz
Executing mv /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine/lib32/d3d9-nine.dll.so /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/syswow64/d3d9-nine.dll
Executing mv /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine/bin32/ninewinecfg.exe.so /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/syswow64/ninewinecfg.exe
Executing mv /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine/lib64/d3d9-nine.dll.so /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/system32/d3d9-nine.dll
Executing mv /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine/bin64/ninewinecfg.exe.so /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/system32/ninewinecfg.exe
Executing rm -rf /home/kamil/.steam/steam/steamapps/compatdata/12120/pfx/dosdevices/c:/windows/temp/_galliumnine/galliumnine
Executing /home/kamil/.steam/steam/steamapps/common/Proton 4.11/dist/bin/wine ninewinecfg -e
wineserver: using server-side synchronization.

```
The games that I've tested the newest release with: silently fail on 4.11-6, or have Gallium Nine Standalone complain on 4.2-9:
```
err:d3d9nine:common_load_d3dadapter d3dadapter9.so.1 was not found on your system.
Setting the envvar D3D_MODULE_PATH or regkey Software\Wine\Direct3DNine\ModulePath is required
Native Direct3D 9 will be unavailable.
For more information visit https://github.com/iXit/wine-nine-standalone
err:d3d9nine:d3dadapter9_new Your display driver doesn't support native D3D9 adapters.
```
No, no. ^^' I shared the news because I thought you were eager for it.

**Comment by nanonyme** [comment]
Yes, I just noticed we're missing quite a lot of things in merge-dirs that Lutris has there.

**Comment by nanonyme** [comment]
@Bryophyllum do you know how to install beta version of this app? I'm going to fast-track the change to beta, then merge beta to stable soon if it looks good.

**Comment by Bryophyllum** [comment]
@nanonyme If you mean installing Steam from flathub-beta, then yes. Otherwise, I'm not quite sure what I'm supposed to do.

**Comment by nanonyme** [comment]
Yes, that's what I meant.

**Comment by nanonyme** [comment]
I'm now waiting for https://flathub.org/builds/#/builders/64/builds/2086 to finish

**Comment by Bryophyllum** [comment]
GTA SA launches with Gallium Nine Standalone installed on 4.2-9:
```
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
Native Direct3D 9 v0.5.0.356-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
Native Direct3D 9 v0.5.0.356-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x14bea0), stub!
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x14bea0), stub!
``` 
The game silently fails to start on 4.11-6, but there's no error concerning Gallium Nine Standalone, so it must be Gallium Nine Standalone or Proton 4.11 regression here causing this. Either way, I think it's fixed.
