### ISSUE TITLE
Mordhau (with Proton) DXVK fails to launch

### ISSUE THREAD

**Issue by NoeelMoeskops** [flathub/com.valvesoftware.Steam#415]
**Game information**
native windows game: Mordhau (proton 4.11 or 4.9)

**Distribution name and version where applicable**
Fedora 30 (kernel 5.2)

**Flatpak info**
Flatpak 1.4.2
nvidia-430-40
default
host

**Problem description**
When launching Mordhau with Proton 4.11-2 or 4.9 using default setting (DX to Vulkan) it fails to launch. It just shows a 'screenshot' of my desktop as fullscreen window and then nothing happens. When forcing OpengGL instead of Vulkan (using `PROTON_USE_WINED3D`) the game launches (with render issues, but that is not because of Flatpak). On native Steam the Vulkan Mordhau runs just fine. So my guess is that this is a Flatpak issue.

**Does this issue reproduce with native Steam**
No.

**Comment by trialism** [comment]
Does the issue still persists? The flatpak configuration is probably out-of-date because the vulkan tools use new paths for their configurations.

**Comment by nanonyme** [comment]
Does this still reproduce?
