### ISSUE TITLE
Steam not using my nvidia gpu

### ISSUE THREAD

**Issue by bithor** [flathub/com.valvesoftware.Steam#42]
After i installed steam i realised that my games where running dreadfully slow so i checked the system information on steam and it said that i was using a VMware, Inc. Gallium 0.4 gpu instead of my gtx960.
Does anyone have any idea what could be wrong and how to fix this?

**Comment by bithor** [comment]
No it's a desktop witha GTX960

**Comment by TingPing** [comment]
`flatpak --gl-drivers` output?

**Comment by bithor** [comment]
nvidia-384-98
default
host

**Comment by TingPing** [comment]
Is `org.freedesktop.Platform.GL32.nvidia-384-98` installed?
