### ISSUE TITLE
Creating new and discovering existing steam libraries on host system

### ISSUE THREAD

**Issue by Arxcis** [flathub/com.valvesoftware.Steam#425]
**Flatpak info**
```
$ flatpak --version
Flatpak 1.4.2

$ flatpak --gl-drivers
nvidia-430-40
default
host
```

**Problem description**
When creating new/discovering existing Steam Libraries, the average user expects to be able to browse the hosts filesystem, but is presented with the sandboxed filesystem.

*Sandboxed filesystem*
![image](https://user-images.githubusercontent.com/3092618/64075386-d9670680-ccb7-11e9-933e-387346b1bef7.png)

The average user does not understand that this is the sandboxed filesystem, and will get confused when:
1. He does not find his existing Steam Library
2. He creates a new Steam Library, but it does not show up in his `$HOME` folder.
3. He deletes steam and reinstalls steam later and all his steam games are gone.

Problem was initially discussed in https://github.com/flatpak/flatpak/issues/2102 . Moving the issues to this repo makes more sense.

**Does this issue reproduce with native Steam**
No

**Suggested solution**
Add `--filesystem=home` permission to `com.valvesoftware.Steam.yml`. 
ref: http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

I am a flatpak beginner, so alternative solutions from more experienced flatpakkers are welcome.

**Comment by nanonyme** [comment]
You may break to your entire home directory if you manage to force these holes open. The application tries to detect these overrides and refuse to start. See https://github.com/flathub/com.valvesoftware.Steam/issues/60 for original issue.

**Comment by Arxcis** [comment]
Thank you for your reply :+1: Personally I really prefer the aggressive sandboxing. I am just concerned how it will be perceived by non-technical people who are used to work with steam in the old un-sandboxed way. I will agree that the trade-off is worth it.

It is really the steam client that should break it's dependency on the underlying filesystem. For example having an `import/export steam library` instead of letting the user freely browse the underlying filesystem.

**Comment by nanonyme** [comment]
It would be nice if there were some beginner-friendly guides of Flatpak that were actually commonly read. Sandbox exceptions are supposed to be exceptions and not the norm. Write-access is even worse (there's a :ro identifier to that can be used with --filesystem).

Read-write access to home allows in addition to accidents wiping user data also myriads of attacks on the host system starting from ransomware attacks to injecting executable code to the system that gets run on host when user logs in.

**Comment by nanonyme** [comment]
I think the by far nicest way to share games between native and Flatpak Steam is something along the lines of https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-want-to-add-external-disk-for-steam-libraries

**Comment by Arxcis** [comment]
> I think the by far nicest way to share games between native and Flatpak Steam is something along the lines of https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-want-to-add-external-disk-for-steam-libraries

@nanonyme I like this approach as well. The FAQ focuses on expose a library from an external disk, but in a lot of cases people want to just import a steam library from somewhere on the internal disk. For instance  `~/Games/SteamLibrary`

My advice to people from now on will be to run:
```
flatpak override --user --filesystem=/path/to/steam-library com.valvesoftware.Steam
```

**Comment by Arxcis** [comment]
Here are some FAQ's that may be added:

**How do I create a Steam library for the Flatpak Steam Client?**

1. Create a new folder where you want your Steam library to be
```
mkdir -p ~/Games/SteamLibrary
```
2. Make the folder visible to the Steam Client
```
flatpak override --user --filesystem=~/Games/SteamLibrary com.valvesoftware.Steam
```
3. The folder should now be visible when you click the `Preferences > Downloads > Add Library Folder` in the Steam client
<img width="170" alt="Screenshot 2019-09-01 at 21 18 25" src="https://user-images.githubusercontent.com/3092618/64081192-11913800-ccfe-11e9-9641-fed3f674cdbf.png">


Related question:
**Why isn't my Steam Library visible in the Flatpak Steam Client?**

**Comment by Arxcis** [comment]
**Why can't the Flatpak Steam Client see my Steam games?**

*You have just replaced the Steam Client on your system with the Flatpak Steam Client. You had a lot of games installed on the old Steam Client but they do not show up in the new Flatpak Steam Client*

Your steam games are probably still on your system inside the `~/.local/share/Steam`. For security reasons the Flatpak Steam Client cannot access this folder right away. You have to give it permission.

1. Allow the Flatpak Steam Client to see your existing Steam Games
```
flatpak override --user --filesystem=~/.local/share/Steam com.valvesoftware.Steam
```
2. Restart the Flatpak Steam client

**Comment by nanonyme** [comment]
Note even with that, you might still lose local saved games and configs.

**Comment by remyabel2** [comment]
It seems that Steam wants you to point towards the harddisk itself, it will not allow me to do `steam` or `SteamLibrary` for example (it just creates another folder in there). After it recognizes the library, then you can change the overrides so that you're not exposing your entire disk.
