### ISSUE TITLE
org.freedesktop.Platform 19.08 is now stable

### ISSUE THREAD

**Issue by A6GibKm** [flathub/com.valvesoftware.Steam#429]
Today `org.freedesktop.Platform//19.08` was released at flathub, following this, one of `com.valvesoftware.Steam//{stable,beta}` should be updated to it.

**Comment by nanonyme** [comment]
My plan is to update beta first, then merge beta to master. I don't have time to do it right now.

**Comment by A6GibKm** [comment]
Ok, I made a local build only replacing all occurrences of `19.08beta` with `19.08` and it builds just fine. 

I was able to play Black mesa using D9VK on an AMD machine. Needs more testing.

**Comment by nanonyme** [comment]
It's fine. Beta version of this app has been running against 19.0beta for large part of Summer. Just need to bump the refs.

**Comment by A6GibKm** [comment]
Closing, thanks to #430

**Comment by nanonyme** [comment]
Note that was just for beta. Now both beta and stable should be 19.08 with simple history.
