### ISSUE TITLE
OpenGL runtimes get uninstalled by flatpak uninstall --unused

### ISSUE THREAD

**Issue by eternal-sorrow** [flathub/com.valvesoftware.Steam#440]
`org.freedesktop.Platform.GL.default` and `org.freedesktop.Platform.GL32.default` runtimes are being installed as they should be when I install steam from flathub, but then if I enter the command `flatpak uninstall --unused`, flatpak tries to uninstall them. If i uninstall them, steam won't start.

**Comment by nanonyme** [comment]
That's q flatpak bug.

**Comment by nanonyme** [comment]
https://github.com/flatpak/flatpak/issues/3004#issuecomment-529938606
