### ISSUE TITLE
Play games that require Uplay

### ISSUE THREAD

**Issue by dariox86** [flathub/com.valvesoftware.Steam#442]
Some games require Uplay. What is the best way to install Uplay inside the same sandbox as Steam?

**Comment by nanonyme** [comment]
How is uplay normally installed?

**Comment by dariox86** [comment]
It is installed as a Windows-only application through Wine or Proton. Maybe it can be installed with winetricks and protontricks, too. Uplay games are then manually added to Steam. At the moment I am using Lutris that handles everything for me, but I want to be able to have it installed inside the Uplay sandbox. Many games require Uplay, I can hardly believe nobody else has come up with a solution to install it inside the sandbox.

**Comment by nanonyme** [comment]
@gasinvein any views? I would sort of prefer you using Lutris app to install the games here if it can already handle things right.

**Comment by gasinvein** [comment]
@dariox86 What exactly do you mean by "Steam sandbox"?

**Comment by dariox86** [comment]
@gasinvein, flatpaked Steam does not see Lutris installed on the main system. I would like to have Uplay inside the flatpaked Steam.

**Comment by alatiera** [comment]
> Uplay games are then manually added to Steam.

What do you mean manually added. Is Steam launching Uplay if you buy a game like assassin's creed through steam?

**Comment by dariox86** [comment]
I did not buy Ubisoft games through Steam. I bought games on Uplay. I wanted to install Uplay inside the Steam sandbox, perhaps with the help of protontricks. If you think the request is not relevant to Flatpak'ed Steam, feel free to close the issue.

**Comment by alatiera** [comment]
> I did not buy Ubisoft games through Steam. I bought games on Uplay. I wanted to install Uplay inside the Steam sandbox, perhaps with the help of protontricks.

I think this usecase would be better served with a standalone Uplay through Wine Flatpak or Lutris Flatpak.

**Comment by dariox86** [comment]
Fair enough.

**Comment by nanonyme** [comment]
@alatiera well, Steam does do exactly what you described when you try to run AC on Windows that was bought through Steam. I have no idea what it does on Linux, haven't tried it with Proton myself.

**Comment by dariox86** [comment]
I opened this a long ago. This is just a non-issue.

**Comment by TheFibonacciEffect** [comment]
How did you resolve this @dariox86 ? Did you install standalone uplay?

**Comment by alatiera** [comment]
if you bought the game on steam, it will install and launch uplay on its own. This issue was about using the Steam Flatpak to install and launch the standalone uplay launcher.

**Comment by dariox86** [comment]
I installed Ubisoft Connect (formerly Uplay) through Bottles. This is a non-issue. Feel free to close the ticket.
