### ISSUE TITLE
Krita (280680) Fails to Launch

### ISSUE THREAD

**Issue by MicrosoftTakeover** [flathub/com.valvesoftware.Steam#443]
**Game information**
[Krita (280680)](https://store.steampowered.com/app/280680/Krita/)

**Distribution name and version where applicable**
Arch Linux 5.2.14

**Flatpak info**
Flatpak 1.4.2
nvidia-435-21

**Problem description**
Fails to launch.
Krita is packaged as an AppImage, running Krita produces the message "AppImages require FUSE to run." in the terminal.

**Does this issue reproduce with native Steam**
No, Krita works as intended.

**Comment by nanonyme** [comment]
Closing, FUSE inside Flatpak is not supported.

**Comment by HugKitten** [comment]
I believe there is a solution now. First make sure you are not using the proton version, then find the run.sh file (maybe be named something else) and edit it to something like this:

```#!/usr/bin/env bash
unset LD_LIBRARY_PATH
./**App image name here**.AppImage --appimage-extract-and-run

export APPIMAGE_EXTRACT_AND_RUN=1
./my.AppImage [...]

export APPIMAGE_EXTRACT_AND_RUN=1
env NO_CLEANUP=1 ./my.AppImage```
