### ISSUE TITLE
Games distributed as AppImages, like Slipstream, can't launch

### ISSUE THREAD

**Issue by TiZ-EX1** [flathub/com.valvesoftware.Steam#444]
**Game information**
Slipstream, and presumably any other application distributed as an AppImage.

**Distribution name and version where applicable**
Xubuntu 18.04.2

**Flatpak info**
Flatpak 1.4.2
nvidia-435-21
default
host

**Problem description**
Slipstream, and presumably any other game distributed as an AppImage, fails to launch because FUSE is not available. Following short console output is received:

```
dlopen(): error loading libfuse.so.2
AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

**Does this issue reproduce with native Steam**
No

**Comment by nanonyme** [comment]
Essentially same as https://github.com/flathub/com.valvesoftware.Steam/issues/443
Probably a more generic issue for Flatpak, I suggest asking at https://github.com/flatpak/flatpak/issues

**Comment by alexlarsson** [comment]
Fuse requires setuid root to work in the sandbox, that will never happen in flatpak.

**Comment by nanonyme** [comment]
@alexlarsson would it be possible to accomplish with a portal (if it's just about mounting) or is this something that simply can never work?

**Comment by alexlarsson** [comment]
A portal runs on the host, so it would mount some fuse filesystem for everyone, which isn't exactly a great security feature either.

**Comment by nanonyme** [comment]
Right, so this is not going to be a great success unless the console tip about extracting the image yourself produces something usable.

**Comment by nanonyme** [comment]
I'm going to close this as not-supported-scenario as I don't have any AppImage packages to prototype workarounds with.

**Comment by HugKitten** [comment]
I believe there is a solution now. First make sure you are not using the proton version, then find the run.sh file (maybe be named something else) and edit it to something like this. Make sure to replace [App image name here] with the name of the app image. Use the script as reference for what to put in place of ./[App image name here].AppImage.

```#!/usr/bin/env bash
unset LD_LIBRARY_PATH
./[App image name here].AppImage --appimage-extract-and-run

export APPIMAGE_EXTRACT_AND_RUN=1
./my.AppImage [...]

export APPIMAGE_EXTRACT_AND_RUN=1
env NO_CLEANUP=1 ./my.AppImage```
