### ISSUE TITLE
Error when launching with gamemoderun (Could not query /proc ...)

### ISSUE THREAD

**Issue by jimmyproton** [flathub/com.valvesoftware.Steam#454]
The GameMode portal was introduced in https://github.com/flatpak/xdg-desktop-portal/pull/314

Running `gamemoderun` inside the Steam flatpak results in an error message like this:
```
GameMode ERROR: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Could not map pid '14': Could not determine pid namespace: Could not query /proc/4196/ns/pid: Permission denied
gamemodeauto: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Could not map pid '14': Could not determine pid namespace: Could not query /proc/4196/ns/pid: Permission denied
```
...which was generated by this code: https://github.com/flatpak/xdg-desktop-portal/pull/314/commits/23bb988bf387d26e72aa6ad0a217808c68edf2e8#diff-f71e4995fc1711d619c72f151fdf1c9dR1622

My understanding is that it attempts to access `/proc/$cpid/ns/pid` where `cpid` is the child pid obtained from the `bwraapinfo.json` file located inside `$XDG_RUNTIME_DIR/.flatpak`

It would seem that the directory that corresponds to this child pid is not available under the /proc inside the Steam flatpak.
```
$ flatpak --version
Flatpak 1.2.4

$ /usr/libexec/xdg-desktop-portal --version
xdg-desktop-portal 1.4.2
```

Reference issue: https://github.com/flathub/com.valvesoftware.Steam/issues/77

**Comment by nanonyme** [comment]
Unlikely to be related to just this app and I don't have any idea how to debug. Ping @gicmo

**Comment by gicmo** [comment]
The portal is running outside the container and should be able to inspect the `/proc` directory. What OS are you running, or more importantly what kernel version is that? Also what are the permissions of the `/proc/<pid>/ns/pid` (where pid is the child pid) directory. My guess would be that we are not having user namespaces, i.e. bwrap is suid, and the normal user thus can't inspect the directory.

**Comment by jimmyproton** [comment]
I'm running Debian buster with kernel 5.2.0-0.bpo.2-amd64.
```
# ls -l /proc/3735 | grep ns
dr-x--x--x 2 root    root    0 Sep 28 11:28 ns
-rw-rw-rw- 1 root    root    0 Sep 28 11:28 timerslack_ns
# ls -l /proc/3735/ns
...
lrwxrwxrwx 1 root root 0 Sep 28 11:28 pid -> 'pid:[4026532447]'
lrwxrwxrwx 1 root root 0 Sep 28 11:28 pid_for_children -> 'pid:[4026532447]'
...
```

**Comment by nanonyme** [comment]
I have a vague recollection Debian didn't enable user namespaces at one point since they were considered not proven enough yet.

**Comment by jimmyproton** [comment]
Thank you both, I managed to get it to work by enabling user namespaces and removing the setuid permission from `bwrap`.

Reference: https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel
