### ISSUE TITLE
Proton game stopped working since the last update

### ISSUE THREAD

**Issue by doraskayo** [flathub/com.valvesoftware.Steam#456]
Since https://github.com/flathub/com.valvesoftware.Steam/commit/fc68667a15174f123cc9b24d40d02c4d3587ea8e, `Sins of a Solar Empire: Rebellion`, a 32-bit Proton game doesn't launch anymore. The process doesn't exit, but the launcher window doesn't appear either.

Removing these two lines from `/app/etc/freedesktop-sdk.ld.so.blockedlist` fixes this issue for me:
``` bash
*(/*)/Proton\ 4.11/dist/bin/wine-preloader *(/*)/Proton\ 4.11/dist/lib/libFAudio.so.0.19.08
*(/*)/Proton\ 4.11/dist/bin/wine-preloader *(/*)/Proton\ 4.11/dist/lib/libFAudio.so.0.19.09
```
Oddly enough, both lines must be removed even though I only see `libFAudio.so.0.19.09` in my Proton 4.11 directory.

**Comment by doraskayo** [comment]
Investigating this further, I see that in the original PR for FAudio (#368), @gasinvein mentioned the following:
> This currently would work only for 64-bit games, but I hope to fix it once FD.o SDK 19.08 become available.

In a following PR (#439), @gasinvein added the 32-bit libraries to the blocked list as well. However, there was a typo in the FAudio library name for Proton 4.11 in their change. It's therefore possible that 32-bit support hasn't been tested properly in that PR.

In a later PR (#448) the typo was corrected, but that change was only tested in Skyrim: SE, which is a 64-bit game.

The conclusion here is that it's possible that blocking the 32-bit FAudio libraries was never verified to work for 32-bit games.

**Comment by nanonyme** [comment]
Can you please as interim solution remove 32bit variants from https://github.com/flathub/com.valvesoftware.Steam/blob/beta/resources/blocklist/proton.yml?

**Comment by gasinvein** [comment]
@nanonyme Does the shared-library-guard even handle 32-bit binaries?

**Comment by nanonyme** [comment]
Yes, 32-bit executables load a 32-bit shared-library-guard.

**Comment by gasinvein** [comment]
Then I have no idea what's wrong if the typo was fixed.

**Comment by nanonyme** [comment]
I think they mean blocking faudio breaks 32-bit Proton. I do not have time or software to debug right now so I'm just going to assume that's true.

**Comment by doraskayo** [comment]
I'm not quite sure which other games can be tested to verify whether this affects every 32-bit Proton game. However, since it definitely prevents `Sins of a Solar Empire: Rebellion` from working, something is wrong here.
