### ISSUE TITLE
Reintegrate 32-bit FAudio

### ISSUE THREAD

**Issue by nanonyme** [flathub/com.valvesoftware.Steam#459]
It was disabled due to regressions as part of https://github.com/flathub/com.valvesoftware.Steam/issues/456

**Comment by gasinvein** [comment]
Since #488 I guess the crashing it's not specific to 32bit.

**Comment by nanonyme** [comment]
@gasinvein do we anymore need our own FAudio anyway? Wasn't it that upstream FAudio can use gstreamer anyway?

**Comment by gasinvein** [comment]
It was kinda useful for older Proton, which ships with it own, older and less feature-full FAudio. Yet I'm not sure if it still works (it depends on how backward-compatible FAudio ABI is). Maybe we don't need it anymore.
