### ISSUE TITLE
radeonsi: Navi family support requires LLVM 9 or higher

### ISSUE THREAD

**Issue by slavoslav** [flathub/com.valvesoftware.Steam#466]
**Game information**
Steam

**Distribution name and version where applicable**
Funtoo Linux

**Flatpak info**
```
$ flatpak --version
Flatpak 1.4.3
$ flatpak --gl-drivers
default
host
```
**Problem description**
When I run Steam with flatpak, i get the following output:
```
F: Can't get document portal mount path
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Overriding TZ to UTC
Running Steam on org.freedesktop.platform 19.08.2 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1568860339)
radeonsi: Navi family support requires LLVM 9 or higher
```
I've got an RX 5700 XT running with AMDGPU kernel driver and Mesa 19.2.0 on the host. If I uninstall `org.freedesktop.Platform.GL32.default`, it starts unpacking steam runtimes and whatnot, but once it's done it throws an glXChooseVisual error (which is expected, as i understand).

So I assume the GL32 runtime isn't built against LLVM 9. How can this be fixed?

Sorry if this repo is the wrong place for this, I really don't know where to post this.

**Does this issue reproduce with native Steam**
Have not tested, distro doesn't support multilib. Everything used to work on another machine with this distro.

**Comment by nanonyme** [comment]
Please file at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues as this is end-user request rather than app requirement.

**Comment by nanonyme** [comment]
I could file it myself but this way it's more clear why 19.08 needs LLVM9.

**Comment by slavoslav** [comment]
Alright, thanks a lot. Will do.

**Comment by Plailect** [comment]
If you do not want to wait for 19.08 to get LLVM9, building this repo yourself after find-replacing 19.08 to 20.08beta (then installing all the required 20.08beta packages from freedesktop-sdk) works perfectly. Maybe the beta branch of this repo should switch to 20.08 beta?

**Comment by nanonyme** [comment]
Not going to happen. It's ABI-stable starting around next Summer

**Comment by nanonyme** [comment]
It doesn't make sense to move beta branch earlier than next Spring. This app compiles a lot of things that are subject to break with 20.08beta at this point without app rebuild. In addition to that, it's not yet it Flathub beta so it cannot be used.

**Comment by nanonyme** [comment]
LLVM 9 support was backported to 19.08 Mesa so this should now work out of the box.
