### ISSUE TITLE
Add a flatpak portal for 'Set Custom Artwork' option

### ISSUE THREAD

**Issue by fabriciojardim** [flathub/com.valvesoftware.Steam#471]
The Steam client's new library (currently in open beta) has an option to set a custom artwork for certain titles by pointing to a picture on the user computer.

Steam Flatpak doesn't have access to the user home directory, so I think it probably should use a Flatpak portal to access the home directory where the user will probably keep his files.

This is a very nice feature because many old games might not get new thumbnails and will just look bad on the new library.

---------

STEPS TO REPRODUCE

1. On the new library right-click on a game cover.
2. Select 'Manage > Set custom artwork'.
3. The file picker dialog can't navigate to the user's home directory.

**Comment by nanonyme** [comment]
Steam does have read-only access to xdg-pictures.

**Comment by fabriciojardim** [comment]
Sorry, my mistake. Thanks for pointing out.

I thought I couldn't access the rest of the file tree because the 'up' button (to access the parent directory) is not working for me, but now I realized I can click on the dropdown menu, select the root folder and navigate from there.

So it works. But the user experience is not the best, as the path to the home folder can be hard to find for some. 

I think still that a portal dialog to open the pictures directory would be nicer. Just a suggestion.

**Comment by nanonyme** [comment]
According to my understanding even if said portal existed (https://github.com/flatpak/xdg-desktop-portal), Steam would need to support using portals which is not really going to happen.

**Comment by nanonyme** [comment]
Portals are implemented host-side, application doesn't have anything to do with it.
