### ISSUE TITLE
"Browse local files" button in game properties in Steam client does not opens the file manager

### ISSUE THREAD

**Issue by Shished** [flathub/com.valvesoftware.Steam#480]
**Game information**

This is Steam client problem. Pressing "Browse local files" button does nothing.
It is similar to https://github.com/flathub/com.valvesoftware.Steam/issues/73 but the dbus-monitor output is slightly different

```
method call time=1570995096.016638 sender=:1.4793 -> destination=org.freedesktop.DBus serial=14 path=/; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.DBus"
```
It does not mentions Steam.

**Distribution name and version where applicable**

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**Flatpak info**

Flatpak 1.5.0

nvidia-435-21
default
host

**Does this issue reproduce with native Steam**

Have not tested, should not be an issue.

**Comment by monterrr** [comment]
Confirmed not working on fedora 30 workstation.

**Comment by guihkx** [comment]
I'm having the same problem. Are you guys on KDE too?

**Comment by guihkx** [comment]
I have Terraria installed in a different hard drive, outside of the Flatpak sandbox. In order to Steam be able to access that path, I obviously had to whitelist the path using `flatpak override --user --filesystem=<path>`).

But here's the thing, when I click to "**Browse local files...**" of games **outside** the Flatpak sandbox, everything works as expected.

So I grabbed the output of `dbus-monitor`, which I ran right before clicking the "**Browse local files...**" button, in these two scenarios. To be honest, as I'm not familiar with DBus, I'm not sure if these log files are helpful at all, but I'll leave them here anyway, hoping it helps someone else fix this:

* Log for a game **inside** the Flatpak sandbox (browsing local files **doesn't work**): [dbus-monitor-inside-flatpak.txt](https://gist.githubusercontent.com/guihkx/1cadd2cc0ac413362439da1fcd1baa78/raw/76c1bc0abede8882d822acd7c9c164174febad7b/dbus-monitor-inside-flatpak.txt)
* Log for a game **outside** the Flatpak sandbox (browsing local files **works**): [dbus-monitor-outside-flatpak.txt](https://gist.githubusercontent.com/guihkx/2c1eb1d9fc6250f7e46c67100ff2614c/raw/6374093f6f6f7592abe61aca1daf86cd6ecd0e9e/dbus-monitor-outside-flatpak.txt)

I believe the relevant part begins only at line 201, which is where the output begins changing.

On that same topic, opening the screenshots folder doesn't work either (**View** > **Screenshots** > **Show on Disk**).

**Comment by theKAKAN** [comment]
I think the problems lies in the fact that all the symbolic links in ~/.var/*/.steam points to ~/.local/share/Steam while, in fact, they are not there.

**Comment by brianmsm** [comment]
I have the same problem in KDE Neon

**Comment by nanonyme** [comment]
@theKAKAN the symlinks are perfectly fine inside the sandbox.

**Comment by bmwalters** [comment]
message from xdg-desktop-portal after pressing "Browse local files":

```
XDP: Rejecting open request as fd has no path associated to it
```

**Comment by matthew-cline** [comment]
Works fine for me.  I'm using KDE under Fedora 33.

**Comment by guihkx** [comment]
> Works fine for me. I'm using KDE under Fedora 33.

Are you sure? If your game is installed in a different partition (i.e. not in `~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/`, then it will work indeed.

**Comment by matthew-cline** [comment]
On my machine `~/.var/app/com.valvesoftware.Steam/data` is merely a symbolic link to `~/.var/app/com.valvesoftware.Steam/.local/share`, and that's the path which Dolphin reports the game files to be in when I do "browse local files" (e.g., `/home/matt/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Wayward`).

**Comment by gasinvein** [comment]
The error probably comes from the fact that `~/.local/share` is a different directory on host.
@nanonyme  Didn't test yet, but I believe it will work if we don't change `XDG_DATA_HOME` value in the wrapper (it'll point to `~/.var/app/com.valvesoftware.Steam`, which is the same dir on host).

**Comment by nanonyme** [comment]
@gasinvein if we don't, many Wine games stop launching due to path length issues.

**Comment by gasinvein** [comment]
Maybe we should make it optional, then? Introduce an env var like `FLATPAK_FALLBACK_XDG_PATHS` or something, probably  enabled by default.

**Comment by nanonyme** [comment]
What we could do is set variable in manifest XDG_DIRECTORY_PREFIX=~/.var/app/com.valvesoftware.Steam/; XDG variables use this when constructing. If you hit max path len issues, flatpak override --user XDG_DIRECTORY_PREFIX=~/ com.valvesoftware.Steam

**Comment by nanonyme** [comment]
It seems it's possibly impossible to make the app work out of the box for everyone.

**Comment by nanonyme** [comment]
FWIW I think it's the same issue which is resulting trayicons to break.

**Comment by gasinvein** [comment]
>set variable in manifest `XDG_DIRECTORY_PREFIX=~/.var/app/com.valvesoftware.Steam/`; wrapper adds this to beginning of XDG variables

I'd rather stick with flatpak defaults, but that's implementation details. IMO the main question here is - should we default to hardcoded fallback paths or not?

**Comment by nanonyme** [comment]
flatpak default is to have XDG_DATA_HOME=~/.var/app/com.valvesoftware.Steam/data. This we do not want. But we could default to ~/.var/app/com.valvesoftware.Steam/.local/share

**Comment by nanonyme** [comment]
What do you mean hardcoded fallback paths?

**Comment by gasinvein** [comment]
>This we do not want.

Why? It's the same symlink as on host pointing to the same target.

>What do you mean hardcoded fallback paths?

`~/.local/share` and such.

**Comment by nanonyme** [comment]
Actually, I think we should maybe not touch current values at all, it will result in Steam thinking it's been relocated. But we could still make the path structure overridable.

**Comment by nanonyme** [comment]
https://github.com/flathub/com.valvesoftware.Steam/issues/60 result was
```
$XDG_CONFIG_HOME -> ~/.var/app/com.valvesoftware.Steam/.config
$XDG_DATA_HOME -> ~/.var/app/com.valvesoftware.Steam/.local/share
$XDG_CACHE_HOME -> ~/.var/app/com.valvesoftware.Steam/.cache
```
this was working nicely until the max path length issue.

**Comment by nanonyme** [comment]
@gasinvein various software can crash when XDG variables point a symlink .We do not want that.

**Comment by gasinvein** [comment]
>it will result in Steam thinking it's been relocated

I think not. We change the env vars _after_ we apply apply migrations.

**Comment by nanonyme** [comment]
Right, but Steam wants to recreate it's *own* symlinks under ~/.steam when it notices XDG variables now point to different location as the symlinks. That's how it detects it's been moved.

**Comment by nanonyme** [comment]
I think the safe way *if we think it's okay to relocate* is to take back to the values from #60 and make it possible to override if really really necessary.

**Comment by gasinvein** [comment]
Will it break, then, e.g. try to move directory it itself under different path? I guess we should just try.

**Comment by nanonyme** [comment]
Well, the worst-case is users get a confusing dialog about relocation. The symlink targets are just rewritten.

**Comment by guihkx** [comment]
Sorry to bump this, but it's not 100% clear to me how I'm supposed to set `FLATPAK_STEAM_XDG_DIRS_PREFIX`. So could you guys please explain a little better how to do it (and the side-effects), then add it to the Wiki? Thank you very much!

**Comment by gasinvein** [comment]
@guihkx We didn't yet implement unattended transition. For now you can manually remove or rename the `~/.var/app/com.valvesoftware.Steam/.steam` directory and restart Steam (your logon and some other settings will be reset). After this opening directories in FM should start working.

**Comment by romulasry** [comment]
Why is this closed this isn't fixed yet is it?

**Comment by gasinvein** [comment]
@romulasry It should be fixed for new installations, but only workaroundable for existing ones. Personally I'm still not sure if we should try to apply a fix automatically, since even a minor mistake can possibly result in data loss.

**Comment by romulasry** [comment]
@gasinvein Tell me when this is on stable.

**Comment by gasinvein** [comment]
@romulasry I think it already is, since #720

**Comment by romulasry** [comment]
Deleted ~/.var/app/com.valvesoftware.Steam/.steam restarted and now it works.

**Comment by johnr14** [comment]
I can confirm that on a fresh install of steam on new Fedora 34 KDE with latest flatpak, the system icon is there automaticaly. 

But there are no icon next to Steam in KDE's launch menu. 

KDE framework 5.79.0
plasmashell 5.21.1

**Comment by guihkx** [comment]
>But there are no icon next to Steam in KDE's launch menu.

Sorry, but what do you mean exactly? I did a test on a virtual machine with Manjaro KDE Plasma 5.20.5 and everything seems to work just fine:

![image](https://user-images.githubusercontent.com/626206/109185568-e494d880-776e-11eb-9774-9e0afc96ae15.png)
![image](https://user-images.githubusercontent.com/626206/109186177-6c7ae280-776f-11eb-8912-0baf2659f561.png)

**Comment by gasinvein** [comment]
Automatic transition for existing installations implemented in #724. Any help with testing it is welcome.

**Comment by qwelias** [comment]
Hey that's not working on latest Arch btw

**Comment by SpectralPixel** [comment]
Yeah, whenever I try to add a non-steam game the file-chooser doesn't appear
