### ISSUE TITLE
gnome-shell segfault

### ISSUE THREAD

**Issue by ekknod** [flathub/com.valvesoftware.Steam#483]
**Game information**

https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/

**Distribution name and version where applicable**

Clear Linux with native kernel,
same bug happens in Arch Linux as well.

**Flatpak info**

Flatpak 1.4.3
nvidia-430-50
default
host
**Problem description**

Video:
https://www.youtube.com/watch?v=zxr6y5rK5-w

Video contains:
1: Method that i have found to start game without crash: mouse left hold title bar
2: Normal start, gnome-shell segfaults

**Does this issue reproduce with native Steam**

No

**Comment by nanonyme** [comment]
That sounds like a driver issue to me.

**Comment by alatiera** [comment]
A stactrace or coredump would be needed in order to debug this further. But I would first suspect the nvidia driver as the culprit as well. Also is this session on wayland or X11? and does it happen if you steam isn't flatpaked?

**Comment by ekknod** [comment]
@alatiera 
Does this issue reproduce with native Steam
No

@nanonyme 
X11
Don't blame nvidia driver, because native steam works fine.

**Comment by nanonyme** [comment]
@ekknod I'm not blaming anything. It would be quite hard for anything else running in sandbox than GPU userland driver to crash software on host that badly though.

**Comment by kakolisgay** [comment]
I'm having a similar issue with TF2 however gnome-shell seems to crash entirely and refuses to restart, also seems to mess up gdm

**Comment by nanonyme** [comment]
Does this issue still persist?
