### ISSUE TITLE
EVE Online does not launch when using steam-wrapper

### ISSUE THREAD

**Issue by eskse** [flathub/com.valvesoftware.Steam#484]
**Game information**
Eve Online

**Distribution name and version where applicable**
Fedora 31 Silverblue (Beta)

**Flatpak info**
Flatpak 1.4.3
default
host

**Problem description**
When starting Steam via the desktop file or running the steam-wrapper script via the shell EVE Online loads to the point where the tray icon appears but the game launcher doesn't open. The tray icon also doesn't have any functionality when clicked.

The issue does not occur when running the steam binary directly from the flatpak shell

**Does this issue reproduce with native Steam**
Have not tested (assuming steam-wrapper is part of the flatpak)

**Comment by nanonyme** [comment]
Does this now work?

**Comment by eskse** [comment]
Yes it's working correctly now. Thanks!
