### ISSUE TITLE
steam-wrapper breaks Kindergarten (a Mono game)

### ISSUE THREAD

**Issue by nightuser** [flathub/com.valvesoftware.Steam#485]
**Game information**
Kindergarten, possibly other Mono games (haven't tested them yet)

**Distribution name and version where applicable**
ArchLinux

**Flatpak info**
```
[~]$ flatpak --version 
Flatpak 1.5.0
[~]$ flatpak --gl-drivers 
default
host
```

**Problem description**
The game ran fine a week ago. Now it doesn't work when using `steam-wrapper`. If I simply run it with `steam` everything works. Hasn't tested other Mono games yet, will report after testing.

**Does this issue reproduce with native Steam**
No

**Comment by nanonyme** [comment]
Try SHARED_LIBRARY_GUARD=0 with Steam wrapper

**Comment by nightuser** [comment]
@nanonyme no, it works now. I tried specifying it on CLI before, but apparently I forgot about `env` switch and did it incorrectly.

However, if I add `--command=steam` it works regardless of what is in `SHARED_LIBRARY_GUARD`.

**Comment by nanonyme** [comment]
Please do not do that. It will break your Steam deployment. Can you help me debug the actual bug?

**Comment by nightuser** [comment]
@nanonyme sure.

**Comment by nightuser** [comment]
@nanonyme I inspected the debug output with and without the guard, and here's the difference in logs:

With the guard:
```
Game update: AppID 589590 "", ProcID 274, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nightuser/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 589590
Installing breakpad exception handler for appid(steam)/version(1570046470)
>>> Adding process 274 for game ID 589590
GameAction [AppID 589590, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
shared-library-guard active for /home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten.x86
ERROR: ld.so: object '/home/nightuser/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 589590, ActionID 1] : LaunchApp changed task to Completed with ""
>>> Adding process 275 for game ID 589590
Found path: /home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten.x86
Mono path[0] = '/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/Managed'
Mono path[1] = '/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/Mono'
Mono config path = '/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libCSteamworks.so'
Preloaded 'libsteam_api.so'
Player data archive not found at `/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/data.unity3d`, using local filesystemJS method call Messaging.PostMessage with 4 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
Game removed: AppID 589590 "", ProcID 274 
Exiting app 589590
```

Without the guard:
```
Game update: AppID 589590 "", ProcID 270, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nightuser/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nightuser/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Starting app 589590
Installing breakpad exception handler for appid(steam)/version(1570046470)
>>> Adding process 270 for game ID 589590
GameAction [AppID 589590, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 271 for game ID 589590
Found path: /home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten.x86
Mono path[0] = '/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/Managed'
Mono path[1] = '/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/Mono'
Mono config path = '/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/Mono/etc'
GameAction [AppID 589590, ActionID 1] : LaunchApp changed task to Completed with ""
Preloaded 'ScreenSelector.so'
Preloaded 'libCSteamworks.so'
Preloaded 'libsteam_api.so'
Player data archive not found at `/home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten_Data/data.unity3d`, using local filesystemJS method call Messaging.PostMessage with 4 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
Game removed: AppID 589590 "", ProcID 270 
Exiting app 589590
```

There're some race conditions in the output (I merger stdout and stderr) but I see there a few differences related to `ld.so`

**Comment by nanonyme** [comment]
Thanks. Is the output different when you launch without the wrapper?

**Comment by nightuser** [comment]
@nanonyme if I just run `steam` with GUARD enabled through env it doesn't have `shared-library-guard active for /home/nightuser/.local/share/Steam/steamapps/common/Kindergarten/Kindergarten.x86` line in the log at all. So I suppose that the guard is the problem and somehow it doesn't turn on without the wrapper.

**Comment by nanonyme** [comment]
It's currently enabled by default. Setting SHARED_LIBRARY_GUARD=0 should disable it. This is because of an SDL2 workaround. However, there are quite many games that have had side-effects because of the workaround and I'm starting to wonder if it would ultimately be less effort to remove the generic workaround (which would make shared-library-guard not be loaded into every game) and just do game by game blocking of Steam Runtime SDL2. This is why I've been asking in recent issues about testing with shared-library-guard disabled.

**Comment by nightuser** [comment]
@nanonyme thanks! For now, I disabled the guard in the desktop file and everything works fine for the time being. Hope it'll eventually be figured out.

**Comment by nanonyme** [comment]
There will soon be a build available for testing if you want to see if it fixes the game out of the box for you.
