### ISSUE TITLE
Warhammer: End Times - Vermintide crashes while loading

### ISSUE THREAD

**Issue by monterrr** [flathub/com.valvesoftware.Steam#488]
**Game information**
Warhammer: End Times - Vermintide

**Distribution name and version where applicable**
Fedora 30

**Flatpak info**
Flatpak 1.4.3
nvidia-430-40

**Problem description**
Warhammer: End Times - Vermintide using proton crashes while loading, if using SHARED_LIBRARY_GUARD=0 it loads fine.

**Does this issue reproduce with native Steam**
Have not tested

**Comment by nanonyme** [comment]
This sounds interesting. Could you please check what the game executable is? I think this might be triggered by FAudio blocking. Ping @gasinvein

**Comment by gasinvein** [comment]
@monterrr Is this game 32 or 64 bit? What version of Proton do you launch it with?

**Comment by monterrr** [comment]
I don't know if it is 64 bit or not, I'm using proton 4.11-7 and I'm running the game without launcher option cause it crashes if I do, so I just right click on it on steam and select run without launcher (not officially supported), the binary name is vermintide.exe

**Comment by nanonyme** [comment]
If it's working with shared-library-guard disabled, that means 64bit because it's only active on 64bit Proton.

**Comment by nanonyme** [comment]
Wait, does it work with shared-library-guard if you do that running without launcher? If so, we probably need more info on what the launcher is.

**Comment by monterrr** [comment]
The launcher thing seems to be a general problem as can be seen on https://www.protondb.com/app/235540
It isn't specific to the flatpak version according to the many reports.

**Comment by gasinvein** [comment]
@monterrr So does the game work without launcher and with shared-library-guard enabled?

**Comment by gasinvein** [comment]
@nanonyme Can you please tag all issues related to Proton and FAudio blocking? Maybe I have at least some of those games to debug further.

**Comment by monterrr** [comment]
No, it only runs with SHARED_LIBRARY_GUARD=0

**Comment by gasinvein** [comment]
@nanonyme Maybe 9e8117bc07198c2a12a04c88acba74e3122ae8a7 did actually fix this? It's not in Flathub repo, the current build still blocks `*(/*|/.*)/steamapps/common*(/*)` from loading SDL, this may affect Proton as well.

**Comment by nanonyme** [comment]
Argh. I don't know what's going on. It should have landed in repo ages ago.

**Comment by nanonyme** [comment]
Any better now? I forced a build on master and force published.

**Comment by monterrr** [comment]
I just updated the flatpak steam and the game now runs without crashing.

**Comment by nanonyme** [comment]
Does it say anything about whether shared-library-guard is active or not?

**Comment by monterrr** [comment]
The command line doesn't show any text with shared-library-guard after running steam from it.

**Comment by nanonyme** [comment]
Okay, it's definitely 32bit Proton then. The FAudio support for that will be handled separately. Closing.

**Comment by gasinvein** [comment]
@nanonyme It's not, the game is 64bit.

**Comment by nanonyme** [comment]
@gasinvein that doesn't make any sense. Then there should be blocked items. Is the FAudio blocking working at all currently?

**Comment by monterrr** [comment]
It seems to be 32 bit according to https://pcgamingwiki.com/wiki/Warhammer:_End_Times_-_Vermintide but the developers only support the game on 64 bit OS as seem on the steam store page "*WARNING: 32-bit OS is NOT officially supported at this time"

**Comment by gasinvein** [comment]
My bad, sorry, I've assumed it's 64-bit because of this notice.

**Comment by nanonyme** [comment]
Might be eg SSE2 requirement. It's easier to mandate 64bit OS than to demand specific CPU instructions.

**Comment by gasinvein** [comment]
@nanonyme Maybe it's not related to FAudio, but to shared-library-guard itself?
This can be tested in two ways: by replacing `libFAudio.so` in blocklist with some nonsense (just to make sure that s-l-g is enabled but blocks nothing); or by deleting FAudio libs from Proton dist dir so it's forced to link with our libs.

**Comment by nanonyme** [comment]
You can actually now force it to activate by setting SHARED_LIBRARY_GUARD_DEBUG=match-expression. You will see what gets loaded but it won't block anything.

**Comment by nanonyme** [comment]
I think we need more data points about 32bit apps and shared-library-guard. It has test automation but it tests only native 32bit build, not cross-compiled.
