### ISSUE TITLE
Ion Fury does not run anymore

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.valvesoftware.Steam#492]
**Game information**
Ion Fury

**Distribution name and version where applicable**
NAME=Fedora
VERSION="30 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**Flatpak info**
Flatpak 1.4.3

default
host

(Intel GPU)

**Problem description**
Ion Fury does not seem to work anymore after latest Steam Flatpak update. It crashes on:
`com.valvesoftware.Steam.desktop[16575]: /home/asciiwolf/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Ion Maiden/fury.bin: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so.0: undefined symbol: SDL_RWread`

I suspect 9e8117b being the issue.

**Does this issue reproduce with native Steam**
Have not tested

**Comment by nanonyme** [comment]
Yes, this game needs a separate quirk file.

**Comment by AsciiWolf** [comment]
Ion Fury runs fine now, thanks! :-)
