### ISSUE TITLE
Borderlands 2 crash

### ISSUE THREAD

**Issue by taea00** [flathub/com.valvesoftware.Steam#5]
I'm on Antergos, and I know BL2 has an issue on Antergos with openal, but this doesn't seem related to the Flatpak crash as they happen in different spots.

BL2 starts in Flatpak, goes through the splash screens, and once it gets to the main screen when you click to continue it goes to "Searching for Downloadable Content" and then when it gets to "Downloading Updates" it crashes the game.

I restarted Steam Flatpak in Offline mode, then when I started BL2 it ran fine, albeit not online and it didn't look for updates.

I'm not able to find a log to the BL2 crash to find out what it's crashing on.  However, I do know that Fedora had SSL cert issues with BL2, not certain something like that would cause a crash.

Is there a way to strace this or get you more information?

**Comment by taea00** [comment]
Borderlands The PreSequel also has this same crash issue at the exact same place as BL2.

**Comment by TingPing** [comment]
You can run `flatpak run --devel --command=sh com.valvesoftware.Steam` to get a shell and run whatever development tools from there like `strace`.

**Comment by nanonyme** [comment]
@TingPing How about adding FAQ in the form of Readme.md to this repo and adding eg above guide there?

**Comment by taea00** [comment]
Ok so silly questions.  Looks like I found the core file that was dropped and I have very large strace, 135MB.  What is the best way to upload these?

**Comment by taea00** [comment]
Didn't realize I could just drop it here.  Here's the strace, but the core is too large to drop here.


[Steam_flatpak_strace.zip](https://github.com/flathub/com.valvesoftware.Steam/files/1085679/Steam_flatpak_strace.zip)

**Comment by TingPing** [comment]
Just looking at the last failures before exit:

```
20387 12:25:37.067823 access("/home/taea00/steam", F_OK) = -1 ENOENT (No such file or directory) <0.000004>
20387 12:25:37.071756 stat64("/home/taea00/Steam/registry.vdf", 0xffded8a0) = -1 ENOENT (No such file or directory) <0.000004>
```

Otherwise don't see much interesting at a glance.

**Comment by taea00** [comment]
Any other way to troubleshoot this?  Any suggestions?  Would you like the core file to examine, is so how do I upload it?

**Comment by TingPing** [comment]
I did push an update btw so do try that out. I'm not sure the coredump will be super useful me.

Trying to symlink the files that fail in the strace log could maybe improve something.

**Comment by FastOSlinux** [comment]
Report of my tests, errors do not happen in steam installed via dnf (Fedora repo rpmfusion)

Borderlands 2 closes when downloading savegame
Bound by flame fonts problem
DeusEx does not open
Dirt rally error 127 and does not open
2015 f1 does not open
Grid autosport does not open
Mad Max did not open
Shadow of mordor is with texture bug already fixed by nvidia
Shadow warrior fonts problems

Fedora25 gnome(xorg) nvidia 780 driver 381.22

**Comment by TingPing** [comment]
BTW I made a wiki for test results, feel free to expand: https://github.com/flathub/com.valvesoftware.Steam/wiki/Tested-Games

**Comment by Unrud** [comment]
It's missing the file ``/etc/services``. I added the file to the runtime and Borderlands starts in online-mode.

**Comment by nanonyme** [comment]
@Unrud does it work with an empty services file or did you need to add something to it, btw?

**Comment by Unrud** [comment]
> does it work with an empty services file

No.

> did you need to add something to it

I copied the file from the host system.

**Comment by nanonyme** [comment]
This seems like a bug to me in Borderlands 2, even more alarming if an empty file doesn't help. It might be good to try to find out what it's trying to find though by adding the services item by item until it doesn't crash

**Comment by Unrud** [comment]
> even more alarming if an empty file doesn't help.

Why should it be alarming?

> It might be good to try to find out what it's trying to find though by adding the services item by item until it doesn't crash

Lucky guess: ``http 80/tcp``

**Comment by nanonyme** [comment]
Afaik the point of the entire file is that local apps can query which ports on local machine are running which services. However, this seems to be using it to resolve a port to connect to on another machine (?)

**Comment by Unrud** [comment]
> Afaik the point of the entire file is that local apps can query which ports on local machine are running which services.

Most of the time the file just contains the IANA-assigned port numbers. An entry in the file doesn't necessarily mean, that an actual service is running on the computer.
Borderlands is using it wrong, but that doesn't help fixing the issue.

Can the file be added to the runtime?

**Comment by TingPing** [comment]
If it solves problems its something to discuss here: https://github.com/flatpak/freedesktop-sdk-images

**Comment by nanonyme** [comment]
This should be fixed through runtime update. Closing due to no comments

**Comment by Amosar** [comment]
I have tried borderland and I still have this issue.
The ``/etc/services`` workaround still work.

**Comment by nanonyme** [comment]
FDO runtime 18.08 may be missing the workaround that was added to FDO runtime 1.6. Ping @valentindavid

**Comment by valentindavid** [comment]
Upstream issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/331
Upstream MR: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/454

**Comment by Amosar** [comment]
As I have understand the MR have been merged.
@nanonyme Can you merge it on this repository please? I don't know how to ask a merge request like this ^^

**Comment by Amosar** [comment]
Okay, sorry I'll wait then

**Comment by Amosar** [comment]
No, I have update my runtimes before my message and I still don't have /etc/services :/

**Comment by nanonyme** [comment]
What you'd be looking at in the build system is the builder running import. Someone will manually trigger it at some point. You should test after next successful import of Freedesktop runtime 18.08

**Comment by nanonyme** [comment]
This looks actually like a nice panel to follow https://flathub.org/builds/#/builders/7

**Comment by nanonyme** [comment]
Can you please update and retry?

**Comment by Amosar** [comment]
borderland2 work now :+1:
