### ISSUE TITLE
Add the ability to add blacklists without needing to rebuild

### ISSUE THREAD

**Issue by kakolisgay** [flathub/com.valvesoftware.Steam#504]
There doesn't seem to be any way to add a blacklist file without building/rebuilding the flatpak. Couldn't a folder be added to make creating and testing blacklist flies easier?

**Comment by nanonyme** [comment]
The whole point is they're part of the app. They are common and help all users.

**Comment by kakolisgay** [comment]
@nanonyme I understand however needing to rebuild the flatpak to test blacklists is a bit cumbersome

**Comment by nanonyme** [comment]
Hm. I could probably add the config generator at least to installed flatpak, that would potentially help some. I would prefer not adding much complex logic into shared-library-guard itself since it's all written in C. Are you taking advantage of Flathub CI creating test builds out of pull requests?

**Comment by kakolisgay** [comment]
> Hm. I could probably add the config generator at least to installed flatpak, that would potentially help some. I would prefer not adding much complex logic into shared-library-guard itself since it's all written in C. Are you taking advantage of Flathub CI creating test builds out of pull requests?

@nanonyme I'm aware I can however that isn't exactly a solution, you're still having to build the flatpak package in order to test even a small change which adds time to the debug process. I think a config generator could be helpful

**Comment by nanonyme** [comment]
There actually is a config generator. It's inside app sandbox in /app/bin/shared-library-guard-config-converter and is used by build process from there. The location from which config is read is hardcoded though.

**Comment by nanonyme** [comment]
I think this is now more or less done due to added SHARED_LIBRARY_GUARD_CONFIG variable.
