### ISSUE TITLE
Include cabextract as a module for fixing Proton compatibility issues from inside the sandbox

### ISSUE THREAD

**Issue by joshua-stone** [flathub/com.valvesoftware.Steam#505]
I've followed instructions linked here for setting up Protontricks with the Steam flatpak to fix compatibility issues with certain games:

https://github.com/Matoking/protontricks/wiki/Usage-with-Flatpak-Steam

It technically works as advertised, but additional work is required for many dependencies that're stored as .cab files. Here are the steps I've made for setting up Protontricks with the Steam flatpak on Fedora:
```
sudo dnf install cabextract --assumeyes
flatpak override --user --env=PATH="/app/bin:/usr/bin:/var/data/python/bin:${HOME}/.local/bin" --env="LD_LIBRARY_PATH=${HOME}/.local/lib64" com.valvesoftware.Steam
flatpak run --command=pip3 com.valvesoftware.Steam install --user pipx
flatpak run --command=pipx com.valvesoftware.Steam install protontricks
curl https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -o ~/.var/app/com.valvesoftware.Steam/.local/bin/winetricks
chmod +x ~/.var/app/com.valvesoftware.Steam/.local/bin/winetricks
cp /usr/bin/cabextract ~/.var/app/com.valvesoftware.Steam/.local/bin
mkdir -p ~/.var/app/com.valvesoftware.Steam/.local/lib64
cp /usr/lib64/libmspack.so.0 ~/.var/app/com.valvesoftware.Steam/.local/lib64
echo "alias protontricks-flat='flatpak run --command=protontricks com.valvesoftware.Steam --no-runtime'" >> ~/.bashrc
```

The steps that include copying the cabextract binary from the host into a folder that the sandbox can see is far from ideal since it requires sudo privileges and breaks the portability that flatpak provides. Attempts to use flatpak-spawn have also failed for unknown reasons, and even if it worked it'd still have the issue of depending on the host for a specific program. Having this binary included would drastically simplify the setup process by eliminating the need for sudo, copying host binary files, defining LD_LIBRARY_PATH, or even calling flatpak-spawn.

Setup could then look more like this:
```
flatpak override --user --env=PATH="/app/bin:/usr/bin:/var/data/python/bin:${HOME}/.local/bin" com.valvesoftware.Steam
flatpak run --command=pip3 com.valvesoftware.Steam install --user pipx
flatpak run --command=pipx com.valvesoftware.Steam install protontricks
curl https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -o ~/.var/app/com.valvesoftware.Steam/.local/bin/winetricks
chmod +x ~/.var/app/com.valvesoftware.Steam/.local/bin/winetricks
echo "alias protontricks-flat='flatpak run --command=protontricks com.valvesoftware.Steam --no-runtime'" >> ~/.bashrc
```

Would it be reasonable to include cabextract for improving Proton compatibility in the Steam flatpak?

**Comment by gasinvein** [comment]
If we need `cabextract` to support Protontricks, I think it would be better to bundle Protontricks with its dependencies altogether, maybe as an extension.

**Comment by joshua-stone** [comment]
I agree that bundling all of the necessary dependencies (protontricks, winetricks, and cabextract) would be sensible, especially as an extension. Is there one available for testing?

**Comment by gasinvein** [comment]
I've created a sample flatpak-builder [manifest for protontricks](https://github.com/gasinvein/flatpak-apps-staging/tree/com.valvesoftware.Steam.Utility.protontricks/master), if you are familiar with flatpak-builder, you can build it locally.

**Comment by joshua-stone** [comment]
The build manifest you posted appears to work correctly. Here are the commands I executed:

```
flatpak --assumeyes install flathub org.freedesktop.Sdk//19.08 org.freedesktop.Sdk.Compat.i386//19.08 org.freedesktop.Sdk.Extension.toolchain-i386//19.08
git clone https://github.com/flathub/com.valvesoftware.Steam
cd com.valvesoftware.Steam
flatpak-builder --repo=steam --force-clean steam-build-dir com.valvesoftware.Steam.yml
flatpak --user remote-add --no-gpg-verify --if-not-exists steam steam
flatpak --user --assumeyes install steam com.valvesoftware.Steam
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.yml
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.metainfo.xml
flatpak-builder --repo=steam --force-clean protonworks-build-dir com.valvesoftware.Steam.Utility.protontricks.yml
flatpak --user --assumeyes install steam com.valvesoftware.Steam.Utility.protontricks
echo "alias protontricks-flat='flatpak run --command=protontricks com.valvesoftware.Steam --no-runtime'" >> ~/.bashrc
```

As an example, here's how to use Protontricks to apply a compatibility fix for [Her Story](https://www.protondb.com/app/368370) in order to get video playback:

```
protontricks-flat 368370 ffdshow l3codecx winxp directshow
```

**Comment by gasinvein** [comment]
@joshua-stone Instead of rebuilding Steam, you can edit protontricks manifest and set `branch` and `runtime-version` there to `stable`, so you could use it with Flathub-provided Steam (once the changes are merged).

Anyway, see Matoking/protontricks#32

**Comment by joshua-stone** [comment]
@gasinvein Building protontricks with the current Steam beta seems quite straightforward, and much faster than building the entire Steam flatpak:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo 
flatpak install --assumeyes flathub-beta com.valvesoftware.Steam
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.yml
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.metainfo.xml
sed -i '4ibranch: beta\nruntime-version: beta' com.valvesoftware.Steam.Utility.protontricks.yml
flatpak-builder --repo=protontricks --force-clean build-dir com.valvesoftware.Steam.Utility.protontricks.yml
flatpak --user remote-add --no-gpg-verify --if-not-exists protontricks protontricks
flatpak --user --assumeyes install protontricks com.valvesoftware.Steam.Utility.protontricks
echo "alias protontricks-flat='flatpak run --command=protontricks com.valvesoftware.Steam --no-runtime'" >> ~/.bashrc
```

Could this be added to Flathub to complement the Steam flatpak?

**Comment by gasinvein** [comment]
@joshua-stone 
>Could this be added to Flathub 

It could be added right-away, but it's preferred to be maintained by upstream.

**Comment by gasinvein** [comment]
I guess this can be closed since https://github.com/flathub/flathub/pull/1259#issuecomment-552829621.

**Comment by nanonyme** [comment]
Note that you will need to manually install this extension for it to work.
