### ISSUE TITLE
New version 

### ISSUE THREAD

**Issue by ShalokShalom** [flathub/com.valvesoftware.Steam#518]
There is a new version https://store.steampowered.com/news/56996/

**Comment by nanonyme** [comment]
All that's really needed to update is to bump this hash. https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.yml#L143 ; commit should mention the new version.

**Comment by ShalokShalom** [comment]
It seems like this is already the new checksum. So how to raise the number in Flathub? It says April instead of December. Thanks

**Comment by nanonyme** [comment]
We can only control bootstrap from app. Steam does self-update on its own schedule.
