### ISSUE TITLE
"BROWSE LOCAL FILES..." doesn't work in clear linux os

### ISSUE THREAD

**Issue by romulasry** [flathub/com.valvesoftware.Steam#519]
Anyone else have this bug?

**Comment by nanonyme** [comment]
What does it do for you?

**Comment by gurtonbuster** [comment]
I have the same problem. When I got to `Games > Add a Non-Steam game to my library`, I can't see all the folders and especially the folder where my second HDD is mounted.

**Comment by Xited** [comment]
Did you installed steam from [Flatpak](https://www.flathub.org/apps/details/com.valvesoftware.Steam)?

**Comment by nanonyme** [comment]
@gurtonbuster there is a sandboxed home inside .var/app/com.valvesoftware.Steam. The app cannot in general see outside it. Have you read FAQ? https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-want-to-add-external-disk-for-steam-libraries

>

**Comment by gurtonbuster** [comment]
@nanonyme Whoops sorry I didn't see that. It works now.

**Comment by nanonyme** [comment]
No worries. I'm still waiting a while for confirmation of whether the original posted had same issue as you before closing this though.

**Comment by monterrr** [comment]
Duplicate of bug #480

**Comment by guihkx** [comment]
This can be closed
