### ISSUE TITLE
Terraria problem 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#52]
[Hello!
when i try to open terraria on steam the game wont show up and in the steam library it says running.
i cant close the game through Terminal and i tried to uninstall the game, uninstall steam, restarting my pc, and deleting com.valvesoftware.Steam. and here is the file.](https://community.endlessos.com/t/steam-terraria-problem/5016?u=leandrostanger)

[eos-diagnostic-171215_182525_UTC 0700.txt](https://github.com/flathub/com.valvesoftware.Steam/files/1564406/eos-diagnostic-171215_182525_UTC.0700.txt)

**Comment by LeandroStanger** [comment]
@nedrichards Could help

**Comment by ajithmel** [comment]
maybe it doesn't work on your current PC, or something is keeping it from doing so, try Googling your issue.
