### ISSUE TITLE
Unrailed needs Ping access

### ISSUE THREAD

**Issue by Fatmice** [flathub/com.valvesoftware.Steam#530]
**Game information**
Unrailed.  Their discord https://discord.gg/udAwR7Q
The experimental build has support for Linux

**Distribution name and version where applicable**

**Flatpak info**
```
Steam                  com.valvesoftware.Steam               1.0.0.61   stable Flathub           user
Freedesktop Platform   org.freedesktop.Platform              19.08.7    19.08  Flathub           user
i386                   org.freedesktop.Platform.Compat.i386             19.08  Flathub           user
default                org.freedesktop.Platform.GL.default              19.08  Flathub           user
mesa-aco               org.freedesktop.Platform.GL.mesa-aco             19.08  freedesktop-sdk   user
default                org.freedesktop.Platform.GL32.default            19.08  Flathub           user
mesa-aco               org.freedesktop.Platform.GL32.mesa-aco           19.08  freedesktop-sdk   user
html5-codecs           org.freedesktop.Platform.html5-codecs            18.08  Flathub           user
openh264               org.freedesktop.Platform.openh264                19.08  Flathub           user
GNOME Application Platform version 3.32     org.gnome.Platform          3.32   Flathub           user

Flatpak --version
Flatpak 1.4.3
Flatpak --gl-drivers
default
host
```

**Problem description**
Game needs access to ping command for some reason when trying to initiate online play.

**Does this issue reproduce with native Steam**
No because native Steam has access to ping command.  The flatpak version doesn't have access to ping.

**Comment by TingPing** [comment]
Just to elaborate, `ping` requires `suid` to function and can't be just packaged in flatpak.

The options would be:

- Package `ping` and require unprivileged ping on the host (`sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"`
- Package a `ping` replacement which is either a hack or workaround.
- Create some sort of flatpak portal for ping

**Comment by nanonyme** [comment]
I suppose we could make a scratch build with ping script that exited with 0 and wrote parameters into a file to get a better idea of how it is getting called.

**Comment by Fatmice** [comment]
In response to my question

> I've opened an issue on steam flatpak, here it is (https://github.com/flathub/com.valvesoftware.Steam/issues/530). You might need to justify why ping is needed when online play is initiated through Steam, which should be the one doing the port punching and hand shaking

According to them,
> Because simply enough we don't use steam for multiplayer
And for some other reason we currently use the default .net for pings. And for some reason (I don't know why) mono (.net implementation for Linux) decided to use the native ping tool instead of writing their own.
There should be an update in followings weeks which removes that redundancy (as we are switching to a native version of photon) but as of now there is not.

**Comment by nanonyme** [comment]
@Fatmice did that update ever end up happening?

**Comment by Fatmice** [comment]
As of Experimental 1.0-5ef258bc8, which I just tested a moment ago, I am able to launch the game from flatpak Steam, host a private lobby, send an invitation to a Windows Steam, and have the latter successfully connect and play a network game.

**Comment by nanonyme** [comment]
Ok. I'm going to assume that will eventually land in stable and close this. If that turns out to be wrong assumption, feel free to ping here.
