### ISSUE TITLE
error: app/com.valvesoftware.Steam/x86_64/stable needs a later flatpak version (1.0.0)

### ISSUE THREAD

**Issue by MatchooW** [flathub/com.valvesoftware.Steam#535]
I get the above error when trying to install on Chrome OS. I followed the set up and as far as I'm aware, I have the latest version of Flatpak. (Ran flatpak update)

**Comment by nanonyme** [comment]
What does flatpak --version say?

**Comment by nanonyme** [comment]
Flatpak 1.0.0 is around two years old. This app requires that for compatibility reasons as it uses features where there is no graceful fallback when absent on old flatpak versions.

**Comment by MatchooW** [comment]
> What does flatpak --version say?

Cheers, got it now. Googled it and Crostini has an old version of flatpak for some reason. Got it in another repo and it's fine. Sorry for the mix up.
