### ISSUE TITLE
Regular arguments don't work.

### ISSUE THREAD

**Issue by Pantar2205** [flathub/com.valvesoftware.Steam#542]
using _ordinary_ steam,
a user could run;
`steam -silent`
and this would launch steam minimized to the system tray without showing any windows.
I am having trouble figuring out how to do the same with flatpaks, any ideas?

**Comment by nanonyme** [comment]
Have you tried flatpak run com.valvesoftware.Steam -silent?

**Comment by Pantar2205** [comment]
Thank You. Strange as when I put that in my startup script last week it didn't work and now its perfect. hmm. Anyway problem solved, thank you.
