### ISSUE TITLE
ERROR: ld.so at Catan Universe

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.valvesoftware.Steam#543]
**Game information**
[Catan Universe](https://store.steampowered.com/app/544730/Catan_Universe/)
Free to Play, although it's not a very well made game

**Distribution name and version where applicable**
```
System:    Host: fedora-home Kernel: 5.5.10-200.fc31.x86_64 x86_64 bits: 64 compiler: gcc v: 9.2.1 Desktop: Gnome 3.34.4 
           Distro: Fedora release 31 (Thirty One) 
Machine:   Type: Desktop Mobo: Micro-Star model: B450 GAMING PRO CARBON AC (MS-7B85) v: 1.0 serial: <root required> 
           UEFI: American Megatrends v: 1.60 date: 03/06/2019 
CPU:       Topology: 8-Core model: AMD Ryzen 7 2700 bits: 64 type: MT MCP arch: Zen+ rev: 2 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 102376 
           Speed: 1272 MHz min/max: 1550/3200 MHz Core speeds (MHz): 1: 1303 2: 2786 3: 1294 4: 2266 5: 4001 6: 1617 7: 1598 
           8: 1617 9: 1432 10: 2580 11: 4023 12: 1618 13: 1591 14: 1599 15: 1283 16: 2749 
Graphics:  Device-1: NVIDIA GM204 [GeForce GTX 970] vendor: Micro-Star MSI driver: nvidia v: 440.64 bus ID: 1f:00.0 
           Display: x11 server: Fedora Project X.org 1.20.6 driver: nvidia resolution: 1280x1024~60Hz, 2560x1440~60Hz 
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 440.64 direct render: Yes 
```

**Flatpak info**
Flatpak 1.4.4
nvidia-440-64
default
host

**Problem description**
Application does not start when using the Flathub version. Log is included, stating:
```
ERROR: ld.so: object '/home/kevin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

[steam-544730.log](https://github.com/flathub/com.valvesoftware.Steam/files/4371068/steam-544730.log)

**Does this issue reproduce with native Steam**
Yes

**Comment by nanonyme** [comment]
Are you sure you have flatpak extension matching your host drivers? nVidia setup is quite fragile and you should do make sure to reboot and flatpak update after all kernel/driver updates.

**Comment by Eonfge** [comment]
@nanonyme I made sure to apply all updates and reboot, before testing the situation again. This was after reboot, using NVidia 440-64 on both the host and within the Flatpak.

**Comment by Eonfge** [comment]
Latest version of the NVidia 440-64 Flatpak drivers has resolved the issue.
