### ISSUE TITLE
Can't add external Steam libraries

### ISSUE THREAD

**Issue by ford-prefect** [flathub/com.valvesoftware.Steam#55]
It looks like the sandbox prevents trying to add Steam libraries, such as those on other drives. Can't imagine this one's easy to fix since they seem to use a custom file chooser.

**Comment by TingPing** [comment]
`flatpak override --user --filesystem=/path/to/your/other/games com.valvesoftware.Steam` then restart the application and you can add it.

**Comment by nanonyme** [comment]
I would say that this problem most likely won't grow a better solution unless Flatpak grows a GUI for doing that. Please file a ticket against flatpak directly if you need further functionality

**Comment by MightyCreak** [comment]
If you have several Steam libraries, will this solution works as well? (I have one "fast" library on an SSD and one "slow" library on an HDD).

**Comment by Israphel** [comment]
After adding the secondary library, will it stay there even if you don't run steam with the override?

**Comment by TingPing** [comment]
@Israphel `flatpak override` is saved, yes.

**Comment by nanonyme** [comment]
@Israphel I wrote something about this to https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-messed-up-steam-app-with-overrides-and-now-it-wont-start

**Comment by WHK102** [comment]
Why `org.filezillaproject.Filezilla` from flatpak can access to `/mnt` or `/media` folder but `com.valvesoftware.Steam` can not?

**Comment by nanonyme** [comment]
It is not a problem, it's an intended behavioural different. We do not expose --filesystem=host or --filesystem=home. Filezilla has former.
