### ISSUE TITLE
NSS needs to be upgraded

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/com.valvesoftware.Steam#56]
steamwebhelper continuously crashes and this error is shown in the console:

```
[1224/175336.256065:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.

/home/awilms/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_64/steamwebhelper.sh: line 5:   911 Aborted                 (core dumped) ./steamwebhelper "$@"
```

**Comment by TingPing** [comment]
@nedrichards did that in #48 but it probably needs the 32bit version which we can't really add so...

**Comment by nanonyme** [comment]
Sounds to me like return of the "how to do multilib Flatpak" to me and probably won't be the last time. Do runtimes support some kind of inheritance so you could fix these things in a Steam runtime that inherited FDO runtime and Steam app would then just happily use Steam runtime?

**Comment by TingPing** [comment]
In theory sure.

**Comment by Alexander-Wilms** [comment]
Works fine now
