### ISSUE TITLE
Crashing on debian with nvidia driver 390 installed

### ISSUE THREAD

**Issue by mahmutelmas06** [flathub/com.valvesoftware.Steam#563]
**Flatpak info**

Overriding TZ to Europe/Istanbul
Running Steam on org.freedesktop.platform 19.08.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/mahmut/.local/share/Steam/ubuntu12_32/steam
[2020-05-16 15:11:08] Startup - updater built May 15 2020 18:18:11
[2020-05-16 15:11:08] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1589568628)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1589568628)
[2020-05-16 15:11:09] Checking for update on startup
[2020-05-16 15:11:09] Güncellemeler denetleniyor...
[2020-05-16 15:11:09] Downloading manifest: client-download.steampowered.com/client/steam_client_publicbeta_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1589568628)
[2020-05-16 15:11:09] Download skipped by HTTP 304 Not Modified
[2020-05-16 15:11:09] Nothing to do
[2020-05-16 15:11:09] Yükleme doğrulanıyor...
[2020-05-16 15:11:09] Performing checksum verification of executable files
[2020-05-16 15:11:13] Verification complete
Gtk-Message: 15:11:14.519: Failed to load module "gail"
Gtk-Message: 15:11:14.520: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  154
Serial number of failed request:  49
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154
Value in failed request:  0x0
Serial number of failed request:  48
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  154
Serial number of failed request:  50
xerror_handler: X failed, continuing
crash_20200516151108_1.dmp[168]: Uploading dump (out-of-process)
/tmp/dumps/crash_20200516151108_1.dmp
/home/mahmut/.local/share/Steam/steam.sh: satır 750:   146 Parçalama arızası    $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
mahmut@pardusum:~/Masaüstü/Github/Ev$ crash_20200516151108_1.dmp[168]: Finished uploading minidump (out-of-process): success = yes
crash_20200516151108_1.dmp[168]: response: CrashID=bp-56c87c17-af60-49d0-84d6-6d5172200516
crash_20200516151108_1.dmp[168]: file ''/tmp/dumps/crash_20200516151108_1.dmp'', upload yes: ''CrashID=bp-56c87c17-af60-49d0-84d6-6d5172200516''

mahmut@pardusum:~/Masaüstü/Github/Ev$ flatpak --gl-drivers
nvidia-390-116
default
host
mahmut@pardusum:~/Masaüstü/Github/Ev$ flatpak --version
Flatpak 1.2.5

Native version working fine

**Comment by nanonyme** [comment]
Try rebooting followed by flatpak update. There might be a conflict between nVidia kernel driver and userspace driver shipped within flatpak runtime.

**Comment by nanonyme** [comment]
Closing, no response.
