### ISSUE TITLE
Steam hang and crash on steam login window with amdgpu-pro 20.10 installed CentOS 8.1

### ISSUE THREAD

**Issue by koreanfan** [flathub/com.valvesoftware.Steam#564]
**Game information** Dota 2

**Distribution name and version where applicable** CentOS Linux release 8.1.1911 (Core), RX560
![flatpak_error](https://user-images.githubusercontent.com/60460757/82530338-1e84de80-9b4e-11ea-9b37-7a22a7ba7c9d.png)

**Flatpak info** Flatpak 1.0.9, flatpak --gl-drivers:  default host

**Problem description**

Steam hang and crash on steam login window with amdgpu-pro 20.10 installed.
Errors in terminal:
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
After deleting amdgpu-pro 20.10 driver and rebooting steam works with open stack, very poor performance with vulcan, unplayable. Pro vulkan is better on native steam (Ubuntu), no freezes and laggs, best performance with ultra settings
**Does this issue reproduce with native Steam**

Cant reproduce this on CentOS 8.1 with native steam, cuz there were no steam package for installation. Steam works perfect on ubuntu with amdgpu-pro with pro vulkan, and you can use amf encoder via ffmpeg

**Comment by nanonyme** [comment]
I would expect amdgpu-pro to be incompatible with flatpak. You will instead always get Mesa which may or may not be com compatible with your kernel.

**Comment by koreanfan** [comment]
I got new results. I delete pro driver,launch flatpack and it works, but bad open stack vulkan performance, with open stack opengl you cant play with ultra video settings, even with media video settings game not good, but its better than vulkan open stack. After that i install again pro driver and i have the same steam hang and i have errors. So i delete flatpak and all files. Cuz rpm steam package from https://download1.rpmfusion.org/nonfree/el/updates/8/x86_64/s/steam-1.0.0.62-1.el8.i686.rpm is not installable, i try install this --> https://download1.rpmfusion.org/nonfree/el/updates/testing/8/x86_64/s/steam-1.0.0.62-2.el8.i686.rpm. And steam was installed from this testing package. When i start steam login window shows and steam hang, show window with error like on screnshot and xorg crash, only tty was available. So i restart pc, but load only tty, no graphical interface. To be sure i make clean install CentOS 8.1 and install steam from testing branch and dont install pro drivers. Steam works but no performance on ultra and media video settings, and no amf encoder. This is not good.

**Comment by nanonyme** [comment]
Have you tested using ACO with open stahck?

**Comment by koreanfan** [comment]
I try aco with open stack and now vulkan is better, and seems its better than open stack opengl, but sometimes i got freezes (1 or 2 in 45-60 minutes) and fps anyway is lower than with pro vulkan and no amf encoder.

**Comment by nanonyme** [comment]
You could report at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues. There is nothing that can be done about this in application.
