### ISSUE TITLE
Dota: Underlords "Unable to Start Game" (amdgpu on Fedora 32)

### ISSUE THREAD

**Issue by kdeleteme** [flathub/com.valvesoftware.Steam#567]
**Game information**

Dota: Underlords

**Distribution name and version where applicable**

Fedora Workstation 32

**Flatpak info**

```
flatpak --version
Flatpak 1.6.3

flatpak --gl-drivers
default
host
```

**Problem description**

The game refuses to start and gives the error "Failed to initialize Vulkan. Please make sure your driver and GPU support Vulkan."

[Logs](https://hastebin.com/raw/isehebimib)

**Does this issue reproduce with native Steam**

Have not tested.

**Comment by nanonyme** [comment]
Which graphics drivers do you have in your host?

**Comment by kdeleteme** [comment]
I'm using an old amd integrated graphics so amdgpu. 

Based on `lspci | grep VGA`: 
`00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Kaveri [Radeon R7 Graphics]
`

**Comment by kdeleteme** [comment]
I did a little bit more digging, and it seems my installation is using the `radeon` drivers instead of `amdgpu`. If it helps, my old APU is an AMD A8-7600 and I'm using just the integrated graphics.

**Comment by kdeleteme** [comment]
After poking around, I switched to the `amdgpu` driver and the game works now.

So I guess it's safe to close the issue now?

**Comment by nanonyme** [comment]
Sure, if that helps. Probably you only have Vulkan with amdgpu.

**Comment by kdeleteme** [comment]
Yup. That seems to be the case. Thanks for the prompt. Your question got me to dig in and check. I assumed I was using the `amdgpu` drivers but it seemed Fedora insisted on loading the `radeon` module for my card even though it's amdgpu compatible.
