### ISSUE TITLE
bwrap: Can't make symlink at /home: File exists

### ISSUE THREAD

**Issue by mczimmermann** [flathub/com.valvesoftware.Steam#57]
On Fedora Atomic Workstation, when I run 

`flatpak` run `com.valvesoftware.Steam`

I get the following error message

`bwrap:` Can't make symlink at /home: File `exists`

The flatpak version is 0.10.2. I cleanly installed Atomic Workstation (/home is a symlink to /var/home) and 'rpm-ostree status' gives

Version: 27.26 (2017-12-22 14:44:29)
BaseCommit: d0da7129dd883735b91c3c1d2e041974d13689ae53b5da5bb1dc4d3fe07cfd66

**Comment by TingPing** [comment]
This is probably an issue you should report against flatpak/flatpak

**Comment by mczimmermann** [comment]
Opened an issue on flatpak/flatpak#1278, so closing this one.
