### ISSUE TITLE
Protontricks doesn't work; “bwrap: execvp /bin/sh: No such file or directory”

### ISSUE THREAD

**Issue by Shotweb** [flathub/com.valvesoftware.Steam#572]
Distribution: Endless OS 3.8.1
Flatpak version: 1.6.2

When trying to run Protontricks with `$ flatpak run com.valvesoftware.Steam.Utility.protontricks` I get the error `bwrap: execvp /bin/sh: No such file or directory`

Also happens if I try to run an actual command, like `flatpak run com.valvesoftware.Steam.Utility.protontricks 6910 shell`

**Comment by nanonyme** [comment]
I don't think that's how you're supposed to use it. Have you read https://github.com/flathub/com.valvesoftware.Steam.Utility.protontricks#installation?

**Comment by Shotweb** [comment]
I see, that works. I think that information needs to be put somewhere more obvious, it is not very user friendly that you need to run additional commands after installing. But I guess that's a job for my distro.

**Comment by databoose** [comment]
I'm still having this issue, even when doing the above commands.

**Comment by ranisalt** [comment]
Me too. It seems something broke in recent updates, as about 6 weeks ago I used protontricks just fine with flatpak.

Now, it errors:
```
~ ❯ flatpak run --command=protontricks com.valvesoftware.Steam
bwrap: execvp protontricks: No such file or directory
```

**Comment by nanonyme** [comment]
Please follow this up at https://github.com/flathub/com.valvesoftware.Steam.Utility.protontricks/issues/14
