### ISSUE TITLE
Segmentation fault on Centos 8

### ISSUE THREAD

**Issue by tkuraku** [flathub/com.valvesoftware.Steam#586]
**Distribution name and version where applicable**
CentOS Linux release 8.2.2004 (Core)

**Flatpak info**
Flatpak 1.6.2
nvidia-450-36-06
default
host

**Problem description**
Steam flatpak has a segmentation fault during start-up on Centos 8

**Does this issue reproduce with native Steam**
Have not tested

**Comment by tkuraku** [comment]
[steam_crash.txt](https://github.com/flathub/com.valvesoftware.Steam/files/4866752/steam_crash.txt)

Here is the console output from running 

```sh
$ flatpak run com.valvesoftware.Steam
```

**Comment by nanonyme** [comment]
Looks like nvidia GL extension isn't working correctly for you.

**Comment by tkuraku** [comment]
It might have something to do with a new nvidia driver. This is a fresh install with the cuda drivers from the official nvidia website.
[https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=CentOS&target_version=8&target_type=rpmnetwork](url)

**Comment by nanonyme** [comment]
Could be the relevant nvidia extension doesn't exist. See FAQ on where to request it.

**Comment by nanonyme** [comment]
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#glxchoosevisual-failed-segfaults-etc-with-nvidia
