### ISSUE TITLE
Flatpak steam doesn't generate run files with the PROTON_DUMP_DEBUG_COMMANDS=1 command

### ISSUE THREAD

**Issue by tatsujb** [flathub/com.valvesoftware.Steam#587]
**Distribution name and version where applicable**
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu

**Flatpak info**

Flatpak 1.6.3

nvidia-440-100
default
host

**Problem description**
Normally PROTON_DUMP_DEBUG_COMMANDS=1 will generate a run file under /tmp/proton_$USER when the game is run.

under flatpak version of steam this fails. I searched the entire computer, it cropped up nowhere.

**Does this issue reproduce with native Steam**
No

**Comment by nanonyme** [comment]
It is generated inside sandbox /tmp which is volatile. You could try TMPDIR=/var/tmp PROTON_DUMP_DEBUG_COMMANDS=1 to try to get it to /var/tmp which is somewhere under .var/app/com.valvesoftware.Steam.

**Comment by nanonyme** [comment]
The files will be available under ~/.var/app/com.valvesoftware.Steam/tmp if I've understood correctly after this PR is released.

**Comment by Bananaman** [comment]
@nanonyme Thanks, it works. It puts the files in:

```
~/.var/app/com.valvesoftware.Steam/.cache/tmp/proton_*
```

Where `*` is your computer username.

It also only worked when I used Proton as compatibility tool. It didn't work when I used GE-Proton via SteamTinkerLaunch as my tool. Most likely SteamTinkerLaunch doesn't pass on the "game command" variables into GE-Proton.

Anyway, it works. Thanks!
