### ISSUE TITLE
Does not open Dying Light, Middle-earth Shadow of mordor 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#59]
Hello I updated flatpak games also do not load on 1 photo the game is not compatible with the video card or driver! I have a video card nvida geforce GTX 1060 game 2015, it should fly! on 2 photos the driver 3.3 is necessary! on 3 photos just wrote the game is launched and because the photo is hanging and no action is bought for the money in the steam game for LINUX. I still half of them did not download I'm afraid to be disappointed further !!! Notebook among gamer's 2017 ranked 6th place and I can not even play old games !!!
[eos-diagnostic-180106_192226_UTC 0900.txt](https://community.endlessos.com/uploads/default/original/2X/5/56c7200d705df29f499721ac77f2763cedc42d85.txt)

https://community.endlessos.com/t/how-can-i-fix-and-how-up-to-date-my-video-and-graphic-card-on-endless-os/5197/12?u=leandrostanger

![058cc1d047e95175683439f0ae5e3793df13e14e_1_690x388](https://user-images.githubusercontent.com/26097419/34638727-efbb2112-f2b8-11e7-87a1-e38578f60074.jpg)
![4f0d69c587a3b708c408e7168d1bffa3e32252f6](https://user-images.githubusercontent.com/26097419/34638728-efe3e37c-f2b8-11e7-90f6-230d986a12e6.jpg)
![1d10077426a1bfbd36e4acf399caff1e0339d819](https://user-images.githubusercontent.com/26097419/34638729-f0079c0e-f2b8-11e7-8c9d-7437602bcba5.jpg)

**Comment by LeandroStanger** [comment]
@nedrichards

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by TingPing** [comment]
You'll want the proprietary Nvidia driver. I know first-hand SoM works fine with that.

**Comment by nedrichards** [comment]
@LeandroStanger a release of Endless OS that enables the prioprietary NVidia driver should be available very soon - if you ask on our beta forum you should be able to get access to a method of enabling it for testing (I know you have access to the beta channel) but there may be bugs. In the interim I'm going to close because Nouveau support isn't in the flathub charter ;-)
