### ISSUE TITLE
SDL_VIDEODRIVER=wayland

### ISSUE THREAD

**Issue by fishxz** [flathub/com.valvesoftware.Steam#591]
hey,
i found this guide: https://www.reddit.com/r/archlinux/comments/b08om6/guide_running_csgo_with_a_waylandnative_backend/ and i wonder if this can be done on flatpak version of steam.

**Comment by nanonyme** [comment]
Related to https://github.com/ValveSoftware/steam-for-linux/issues/4924#issuecomment-437690689

Steam SDL is built without Wayland support.

**Comment by fishxz** [comment]
thanks, my question is more like: is there a way to load the libsdl2.so from the runtime (assuming it has wayland enabled) instead of the steam runtime?

**Comment by nanonyme** [comment]
This has historically been quite flaky. Steam no longer pins its own SDL2, however, when runtime SDL2 is older than Steam SDL2, Steam SDL2 will be used instead. I don't know if there's a reliable way to force runtime SDL2 always.

**Comment by bgw** [comment]
> I don't know if there's a reliable way to force runtime SDL2 always.

https://sdl-mirror.readthedocs.io/en/latest/README-dynapi.html

You should be able to `export SDL_DYNAMIC_API=/my/actual/libSDL-2.0.so.0` and then launch steam (or any other app), and it should be using your specified SDL library.

**Comment by nanonyme** [comment]
@bgw does that support $LIB?

**Comment by nanonyme** [comment]
Looks like it does. We could probably set --env=SDL_DYNAMIC_API=/usr/$LIB/libSDL2-2.0.so.0 even in manifest. You can give that a try on command-line even now. So `flatpak run --env='SDL_DYNAMIC_API=/usr/$LIB/libSDL2-2.0.so.0' com.valvesoftware.Steam`. Note that quotes *must* be single-quotes there, $LIB must be evaluated by dynamic linker, not bash.

**Comment by fishxz** [comment]
tried cs:go

```Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 730, ActionID 3] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 730, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 730, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 730, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 730, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 730, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 730, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 730 "", ProcID 568, IP 0.0.0.0:0
ERROR: ld.so: object '/var/home/***/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/***/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 730
>>> Adding process 568 for game ID 730
GameAction [AppID 730, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 569 for game ID 730
pid 570 != 569, skipping destruction (fork without exec?)
ERROR: ld.so: object '/var/home/***/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 730, ActionID 3] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/var/home/***/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 571 for game ID 730
SDL video target is 'wayland'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
Game removed: AppID 730 "", ProcID 568 
Uploaded AppInterfaceStats to Steam
Exiting app 730
```
the game crash on start

**Comment by raymanfx** [comment]
Fedora 33, Steam Flatpak:
```
$ flatpak run --env='SDL_DYNAMIC_API=/usr/$LIB/libSDL2-2.0.so.0' com.valvesoftware.Steam
```
```
SDL Dynamic API Failure!
Couldn't override SDL library. Using a newer SDL build might help. Please fix or remove the SDL_DYNAMIC_API environment variable. Using the default SDL.
```

**Comment by Saroufim** [comment]
Can confirm that this doesn't work on Fedora 33.

**Comment by tidux** [comment]
Linux distros are starting to entirely drop their Xorg session support.  Steam will get dropped too if it doesn't work properly.

**Comment by nanonyme** [comment]
It works just fine with XWayland. Note this is wrong place to lobby Wayland support into Steam.

**Comment by raymanfx** [comment]
As a high-rank CS:GO player, I beg to differ.
The game is virtually unplayable in xwayland due to stuttering and input lag. The frame rate itself does not seem to be affected much.
Thus, I've been looking into testing the SDL Wayland environmen - so far without success.

**Comment by Saroufim** [comment]
I think the issue at hand here is that flatpak steam can't detect wayland with `flatpak run --env='SDL_DYNAMIC_API=/usr/$LIB/libSDL2-2.0.so.0' com.valvesoftware.Steam`. The rest can be taken up with Valve directly.

**Comment by romulasry** [comment]
Update?

**Comment by nanonyme** [comment]
This is not going to be resolved in context packaging, follow up on Steam side.
