### ISSUE TITLE
Proxy configuration error while running Steam

### ISSUE THREAD

**Issue by nanonyme** [flathub/com.valvesoftware.Steam#6]
Noticed this while running Steam from command line
[0619/180810.333416:ERROR:proxy_config_service_linux.cc(272)] Error requesting gconf directory: Failed to activate configuration server: org.freedesktop.DBus.Error.ServiceUnknown

**Comment by TingPing** [comment]
Granting access to `org.gnome.GConf` just leads to `(process:109): GConf-CRITICAL **: gconf_client_notify_remove: assertion 'client->listeners != NULL' failed`

I imagine that getting proxy information via gconf doesn't even work anymore and it is probably fine to ignore.

**Comment by nanonyme** [comment]
Hm, in that case maybe this should be closed. I do find it highly fishy though if there's ERROR-level bogus messages. Maybe that should be brought up with Valve?

**Comment by nanonyme** [comment]
Closing as noise in bug tracker
