### ISSUE TITLE
Flatpak update cannot pull latest version. Checksum mismatch

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.valvesoftware.Steam#600]
**Game information**
Base package

**Distribution name and version where applicable**
```
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 32 (Thirty Two)
Fedora release 32 (Thirty Two)
cpe:/o:fedoraproject:fedora:32
```

**Flatpak info**
```
Flatpak 1.6.5
nvidia-450-66
default
host
```

**Problem description**
> Error: While pulling app/com.valvesoftware.Steam/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='79fda7191b80fdb4e2ec091b2965e8885d4b709d20a3519204c0d20ce5ceb583' actual='5fc5779458429368101b8776ccf04ff02851abe790e3c424895f3e3f9ea347c9'

**Comment by nanonyme** [comment]
It sounds like your local ostree repo has become corrupted. Running `flatpak repair` may help.

**Comment by Eonfge** [comment]
Seems like it. I did `flatpak repair` and it found the issue. It was not able to fix it though, so I removed and reinstalled Steam to fix the issue.

**Comment by nanonyme** [comment]
To be honest, it sounds really bad that flatpak can't repair this and it would have been good to report a bug against flatpak but it might at this point be hard to pinpoint the problem anymore. Most commonly corruption is related to download issues.

**Comment by Eonfge** [comment]
I'll keep an eye open the next time. It was on my work laptop though, so I wasn't really in the situation that I could do a thorough debug. If it happens at home, I'll bring it to the attention of the Flatpak project directly.
