### ISSUE TITLE
PROTON_LOG not functional with Flatpak version of Steam

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/com.valvesoftware.Steam#603]
It seems that there isn't any way to change the location where Steam dumps Proton logs when you use `PROTON_LOG=1 %command%`, and it wants to create the file `$HOME/steam-$appid.log`. We don't allow write access to `$HOME` so that log can't be created. Is there anything we can do to get around this?

**Comment by gasinvein** [comment]
Look in `~/.var/app/com.valvesoftware.Steam/`, the log file should be there.

**Comment by HugLifeTiZ** [comment]
Huh. Yeah, there it is. That's weird, because I tried that earlier to try and figure out the SCVI 2.25 break, and it didn't seem to create that file. I'll close for now; I can't meaningfully test until tomorrow anyways because of Denuvo's activation attempt limit. If I try again tomorrow and the file doesn't appear, I'll reopen.

Thanks kindly. :)
