### ISSUE TITLE
PROTON_USE_SECCOMP=1 does nothing

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/com.valvesoftware.Steam#608]
**Game information**
SoulCalibur VI, and potentially others.

**Distribution name and version where applicable**
Xubuntu 18.04 64-bit

**Flatpak info**
Flatpak 1.8.2
nvidia-450-66
default
host

**Problem description**
The DRM in SoulCalibur VI was updated with the 2.25 patch and now requires `PROTON_USE_SECCOMP=1` in order to start. There are almost certainly other games that are similarly affected. But it seems that the option doesn't work or does nothing in the Flatpak version of Steam.

**Does this issue reproduce with native Steam**
No. `PROTON_USE_SECCOMP=1` in the launch options is the difference between SoulCalibur VI successfully starting up vs never reaching the splash screen, whereas in Flatpak Steam, having it makes no difference.

See https://github.com/ValveSoftware/Proton/issues/1780#issuecomment-691223370 for more info on how I came to this conclusion.

**Comment by nanonyme** [comment]
I doubt you can use seccomp inside bubblewrap which flatpak uses.

**Comment by nanonyme** [comment]
@alexlarsson might know for sure whether this even can work in the sandbox.

**Comment by Mershl** [comment]
Soul Calibur VI is currently not playable because of this limitation. @alexlarsson Is this a permanent limitation?

**Comment by gasinvein** [comment]
Seems like there are other games affected (with similar DRM, I guess), namely F1 2020.

**Comment by ramcq** [comment]
For more detail/context, the code in Proton's patched Wine is this: https://github.com/ValveSoftware/wine/blob/b48ce9a2778a4ff7ee14067f0ea73693ed70c52d/dlls/ntdll/unix/signal_x86_64.c#L2123

As far as I can tell it's using seccomp to trap only certain unknown syscalls, so they can be passed to a SIGSYS handler for emulation, which would be way too slow if it hit every syscall. I'm not sure why it's interacting badly with the flatpak filters - although conceptually it's permissable to compose seccomp filters.

**Comment by gasinvein** [comment]
We've probably fixed it in Proton on Flathub (community build), see the PR linked above. Currently the fix is in `beta` branch, so if you'd like to test it - you'll need both Steam and Proton `beta` branches installed from the flathub-beta repository.

**Comment by tim77** [comment]
No regressions spotted in 3dmark:

Left [with patch](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton/pull/5) | Right without patch

![image](https://user-images.githubusercontent.com/5614476/97436304-79570900-192a-11eb-9643-7aa14c4e4124.png)

**Comment by nanonyme** [comment]
@HugLifeTiZ @Mershl any chance either of you test the original game with Proton community version? I would consider this fixed if so. Upstream Proton doesn't work on the app anyway at this point.

**Comment by HugLifeTiZ** [comment]
Sorry, I'm not using the Flatpak version of Steam anymore, mainly because of the many native games where controller support breaks and it was never determined why.

**Comment by nanonyme** [comment]
@ramcq seems like we probably need to test through sample program since original reporter will not re-test. Any ideas?

**Comment by HugLifeTiZ** [comment]
It looks like there's yet another reason I can't test this out myself. SoulCalibur VI goes on sale fairly often and is usually discounted pretty deeply. I have absolutely no qualms with gifting a copy to someone so that it can be tested next time it goes on sale. Would that be acceptable? And if so, who should I gift a copy to?

**Comment by tim77** [comment]
> Would that be acceptable? And if so, who should I gift a copy to?

Definitely for our heroes: @gasinvein and @nanonyme.

**Comment by HugLifeTiZ** [comment]
SCVI is [on sale](https://www.humblebundle.com/store/soulcalibur-vi) so it's put up or shut up time for me. I intend to keep my word, but what's the best way for me to gift them? Github doesn't have DMs and their emails aren't on their profiles.

**Comment by tim77** [comment]
Since posting email in plain text not the best idea, so you can find their email and communicate directly:

```
git clone https://github.com/flathub/com.valvesoftware.Steam
cd com.valvesoftware.Steam/
git log
```

**Comment by HugLifeTiZ** [comment]
Okay. Gift copies sent. And if the weird stuff with Flatpak Steam complaining about xdg folders gets fixed and I test it before they do, I am certainly not upset to have sent gift games to contributors to the Flatpak gaming ecosystem. :)

**Comment by gasinvein** [comment]
Many thanks @HugLifeTiZ! Recieved and tested the game. Seems to work fine for me with Proton-experimental flatpak build. With normal Proton flatpak, I've got black screen and couldn't get in-game, but this is most likely related to codecs/gstreamer, not to DRM/seccomp.

**Comment by HugLifeTiZ** [comment]
SCVI's title screen is basically a Media Foundation video, so a black screen at the start *is* normal, but it shouldn't stop you from starting the game. It will stop you from doing the Soul Chronicle story mode, though. The Media Foundation videos work with Proton-GE 6.0.

In any case, after the big DRM update dropped and before seccomp stuff got rolled into Proton 5.13, you wouldn't even get to the splash screen before it failed, and you're definitely further in than that.

**Comment by gasinvein** [comment]
@HugLifeTiZ Looks like I can get in-game with normal Proton indeed. Not sure why I got stuck on previous launch.

**Comment by HugLifeTiZ** [comment]
Really glad I could help. :)

I was able to fix my hangup preventing me from starting Flatpak Steam, so I was also able to test SCVI with the Flatpak build of Proton 5.13-5. It ran successfully, even did some nice wall combos in training mode.

Hopefully there aren't any games that need both seccomp and a Proton version prior to 5.13. Otherwise, I think we're good to close this.
