### ISSUE TITLE
/bin/sh: gamemoderun: command not found

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.valvesoftware.Steam#613]
Terminal error:
/bin/sh: gamemoderun: command not found

**Distribution name and version where applicable**
$ cat /etc/os-release
NAME=Fedora
VERSION="33.20200911.n.0 (Silverblue Prerelease)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33.20200911.n.0 (Silverblue Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='33.20200911.n.0'

**Flatpak info**
$ flatpak --version
Flatpak 1.8.2

$ flatpak --version
Flatpak 1.8.2
$  flatpak --gl-drivers
default
host
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.38.0, 5.8.6-301.fc33.x86_64, LLVM 11.0.0)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.0-rc2
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.0-rc2
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.0-rc2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Problem description**
gamemoderun% command% preventing opening any game with this parameter

**Does this issue reproduce with native Steam**

**Comment by nanonyme** [comment]
Upstream issue https://github.com/FeralInteractive/gamemode/issues/281

**Comment by FastOSlinux** [comment]
working, tnks!
