### ISSUE TITLE
Remote Play shows a black screen on client

### ISSUE THREAD

**Issue by anthr76** [flathub/com.valvesoftware.Steam#617]
Game information

Steam RemotePlay

Distribution name and version where applicable

Fedora Release 32

Flatpak info

Flatpak 1.6.5
default
host

Problem description

When attempting to use Remote Play with a NVIDIA Shield or iPhone remote play shows a black screen on client device though shows steam big picture on the host. Controls work as expected.

Does this issue reproduce with native Steam

Have not tested likely not

**Comment by jeremyvisser** [comment]
I get this issue when I use Wayland, but if I use X11 instead it works fine. I get this issue regardless of whether it’s in Flatpak or not, so I suspect this issue does not belong in this bug tracker.

**Comment by anthr76** [comment]
Thanks for the info. I'll close this then.
