### ISSUE TITLE
xrandr missing in runtime

### ISSUE THREAD

**Issue by SyrupThinker** [flathub/com.valvesoftware.Steam#619]
**Game information**
Slay the Spire

**Distribution name and version where applicable**
Fedora 32 (Workstation Edition)

**Flatpak info**
```
> flatpak --version
Flatpak 1.8.2
> flatpak --gl-drivers 
default
host
> flatpak info com.valvesoftware.Steam  # Removed redundant information
          ID: com.valvesoftware.Steam
         Ref: app/com.valvesoftware.Steam/x86_64/stable
     Version: 1.0.0.66
      Origin: flathub
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 3e5de71e00ed01f1c091bee203767eac5a9875f4d4583256344f738820c7c316
      Parent: e95897d1f4a9c29ea2863aad45692ee537ec8fe888b5b4f3e4ca98173e1ab8ea
     Subject: Manually install gamemoderun Workaround for #613 (48a4b3a0)
        Date: 2020-09-13 08:07:29 +0000
```

**Steam info**
Built: Sep 10 2020, at 05:50:00
Steam API: v020
Steam package versions: 1599861500
(No updates available)

**Problem description**
Identical to #121.
#605 removed `xrandr` on the basis that "It's already included in the Runtime".
Running `find / -name xrandr` inside the flatpak with `flatpak enter com.valvesoftware.Steam bash` yields no results.
So it appears that xrandr is not actually included in my runtime.

**Does this issue reproduce with native Steam**
Have not tested (Worked earlier this year with `xrandr` installed)

**Comment by Lctrs** [comment]
Whoops. I confused with libxrandr. Sorry for this. Will revert.
