### ISSUE TITLE
Integration of vkBasalt Vulkan layer

### ISSUE THREAD

**Issue by Jojonintendo** [flathub/com.valvesoftware.Steam#625]
**Problem description**
As of today, there is no easy way to use the vkBasalt layer within the flatpak Steam. If I understand correctly, it is not easily made into a flatpak [https://github.com/flathub/com.valvesoftware.Steam.VulkanLayer.MangoHud/issues/6](url). Would a direct integration within the flatpak Steam be considered useful?

**Does this issue reproduce with native Steam**
No, native Steam recognizes vkBasalt fine and benefits from it.

Thanks in advance for your time and any comments.

**Comment by nanonyme** [comment]
Based on my understanding of the issue, putting in in app would be just as complex.

**Comment by sinaflan** [comment]
add [this](https://github.com/frostworx/steamtinkerlaunch) in addition to Boxtron MangoHud protontricks

**Comment by gasinvein** [comment]
vkBasalt build system used to be a horrifying mess, nearly impossible to package. I seen they switched to meson some time ago, so probably building a flatpak of it shouldn't be too difficult now.

**Comment by gasinvein** [comment]
[Here](https://github.com/gasinvein/flatpak-apps-staging/tree/com.valvesoftware.Steam.Utility.vkBasalt/master) is flatpak-builder manifest for building vkBasalt. It's pretty straightforward now indeed. If anyone interested, feel free to grab it and submit to Flathub. I personally don't use vkBasalt.

**Comment by TheEvilSkeleton** [comment]
@gasinvein I am not very knowledgeable in those stuff (but I'm trying really hard to learn to create patches, etc.), but if it's only about bumping (or maybe very minor issues), then I wouldn't mind maintaining it.

If I ever need help, does it bother you if I ping you?

**Comment by gasinvein** [comment]
@TheEvilSkeleton Those two patches are already in vkBasalt git master, they won't be needed anymore with next release.
>If I ever need help, does it bother you if I ping you?

No, feel free to ping me.

**Comment by TheEvilSkeleton** [comment]
In case you are interested: I submitted an MR to add vkBasalt https://github.com/flathub/flathub/pull/1921

**Comment by gasinvein** [comment]
vkBasalt extension for Steam is now available on Flathub, so I guess this can be considered resolved.

**Comment by Jojonintendo** [comment]
Thank you all so much for your time and support on this issue, it's really appreciated!
