### ISSUE TITLE
Battlevoid: Harbinger crash on launch

### ISSUE THREAD

**Issue by sonnyp** [flathub/com.valvesoftware.Steam#626]
**Game information**

Battlevoid: Harbinger

**Distribution name and version where applicable**

Fedora 32

**Flatpak info**

Flatpak 1.8.2

```
flatpak gl-drivers
default
host
```

**Problem description**

```
Thread[LWJGL Application,6,main]
java.lang.ExceptionInInitializerError
com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(SourceFile:591)
com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(SourceFile:126
```

**Does this issue reproduce with native Steam**

No

**Comment by robertu94** [comment]
This is probably a duplicate of #619 since I get the same error with Slay the Spire.  The fix has been merged, but isn't available on Master yet.

**Comment by nanonyme** [comment]
Right, that was intended to be released to stable but the Steam cloud migration changes haven't gone through enough testing yet.

**Comment by nanonyme** [comment]
Is this still happening?

**Comment by robertu94** [comment]
@nanonyme I can't speak for @sonnyp but the issue was fixed for Slay the Spire which I think uses the same library.

**Comment by sonnyp** [comment]
fixed - thanks
