### ISSUE TITLE
Gwent: cannot play online (missing ntlm_auth)

### ISSUE THREAD

**Issue by tgharib** [flathub/com.valvesoftware.Steam#631]
**Game information**

Gwent

**Distribution name and version where applicable**

Fedora silverblue 33

**Flatpak info**

```
$ flatpak --version
Flatpak 1.8.2
$ flatpak --gl-drivers
nvidia-450-66
default
host
```

**Problem description**

`2485.290:00b8:018c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated`

**Does this issue reproduce with native Steam**

Have not tested because native steam is currently broken in fedora silverblue 33.

**Comment by nanonyme** [comment]
I don't think we're providing any part of Samba.

**Comment by nanonyme** [comment]
So is this some LAN game you're trying to get working?

**Comment by tgharib** [comment]
GWENT is not a LAN game, no. It is a free-to-play online card game similar to Hearthstone or Magic the Gathering. Here is the page on steam: https://store.steampowered.com/app/1284410/GWENT_The_Witcher_Card_Game/

I cannot load into the game because the game throws a server connection issue. The issue is not server-side because the same error always happens while a WIndows client works fine.

**Comment by nanonyme** [comment]
Right, then this sounds quite odd. This winbind that you mentioned is part of Samba. Even ntlm_auth itself is for authentication against LAN servers.

**Comment by tgharib** [comment]
You're right. `ntlm_auth` had nothing to do with it. I managed to install native steam, installed `samba-winbind-clients` in fedora and that resolved the `ntlm` warning but the issue persisted.

It turned out the issue was that I didn't have the steam overlay enabled. The game opens an overlay to login into GOG and I guess I didn't see that because I had the overlay disabled which is why the game failed to connect.
