### ISSUE TITLE
Certain Xwayland Games Are Not Accelerated

### ISSUE THREAD

**Issue by Saroufim** [flathub/com.valvesoftware.Steam#634]
Forgive me if this is not your bug but I figured I would start here

**Game information**
Dark Messiah of Might and Magic, Skyrim, RetroArch
-->

**Distribution name and version where applicable**
Fedora Silverblue 33 (bug was on 32 as well)

**Flatpak info**

  flatpak --version: 1.8.2
  flatpak --gl-drivers: default, host

**Problem description**
Certain games stutterer and lag on XWayland. Other games (such as Elder Scrolls Legends) are perfectly fine. If I delete the prefix of the game, the first time it launches, the game works fine, the second time and onwards it starts stuttering as if it is not accelerated. Reverting to GNOME X11 removes the issue and the games work perfectly fine. 

**Does this issue reproduce with native Steam**
Have not tested

**Comment by Saroufim** [comment]
I discovered something additional about this issue. Not only are these windows not accelerated on Wayland but if they are unfocused they run as if they are accelerated. Additionally, these windows are not managed by Steam's input (controllers do not work on them) and the Steam overlay cannot be called for them. I have found nothing in common between these games. They all use different proton versions.

**Comment by Saroufim** [comment]
Closing this as it's actually a GNOME issue.

**Comment by nanonyme** [comment]
@Saroufim if you have an issue opened on Gnome side (I assume Mutter), could you put link here in case someone else ends up reading this?

**Comment by Saroufim** [comment]
[Games Choppy Under Xwayland](https://gitlab.gnome.org/GNOME/mutter/-/issues/1462)
[Games Choppy On Xwayland](https://gitlab.gnome.org/GNOME/mutter/-/issues/1455)
These two GNOME bug reports detail the issue that is between Mutter and Mesa.
