### ISSUE TITLE
Can't build Flatpak due to file permissions in steamcmd archive

### ISSUE THREAD

**Issue by PureTryOut** [flathub/com.valvesoftware.Steam#637]
I was trying to fix #636 myself as I just can't wait to use my new VR headset, but I'm failing to build it properly (even without any changes to the manifest). The steamcmd archive seems to have some file with 555 permissions making it impossible to write to  those files without root.
However, the manifest tries to do so anyway and thus fails:

```
eu-strip: while opening '/home/bart/Documents/Git/com.valvesoftware.steam/build-dir/files/steamcmd/linux32/steamerrorreporter': Permission denied
```

I know next to nothing about how to build Flatpaks so I'm not sure if we can somehow change the permissions of the mentioned files.

The files with 555 permissions in the steamcmd archive:

- `linux32/crashhandler.so`
- `linux32/libstdc++.so.6`
- `linux32/steamerrorreporter`

**Comment by gasinvein** [comment]
flatpak-builder is trying to strip steamcmd binaries, what it should not do. You may be hitting flatpak/flatpak-builder#358

**Comment by PureTryOut** [comment]
Huh, yes, that seems to be the case. Not specific to this Flatpak then, thanks I'll close this in favor of the one you linked.

**Comment by nanonyme** [comment]
Well, we could just fix permissions.

**Comment by gasinvein** [comment]
@nanonyme Nah, stripping a proprietary binary seems a bad idea. IANAL, but I guess this may even violate its license.
