### ISSUE TITLE
Question: start a game from command line?

### ISSUE THREAD

**Issue by muttleyxd** [flathub/com.valvesoftware.Steam#641]
Hi, I'm writing a launcher for Arma 3 game for Linux and Mac.

I want it to interact with Steam inside Flatpak, but the problem I have, is that I'm not able to start a game from outside the sandbox.

```
$ flatpak run --command=steam com.valvesoftware.Steam -applaunch 107410 -nolauncher
Running Steam on org.freedesktop.platform 20.08.0 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/muttley/.local/share/Steam/ubuntu12_32/steam -applaunch 107410 -nolauncher
```

Same issue occurs if I try to start Retro City Rampage (appid 204610). Am I doing something wrong here?

**Comment by nanonyme** [comment]
Remove the --command=steam

**Comment by gasinvein** [comment]
BTW you could also use steam uri for that, e.g. `xdg-open steam://rungameid/107410`

**Comment by muttleyxd** [comment]
Funny stuff: I restarted my testing VM, waited a day and now my command works (also with `--command=steam`) ¯\_(ツ)_/¯

Thanks for help!

**Comment by nanonyme** [comment]
@muttleyxd do not use --command=steam. There are a lot of flatpak workarounds in the wrapper and that bypasses it. Just work through the wrapper.

**Comment by RokeJulianLockhart** [comment]
How does one run the Steam-specific schema-denoted commands, like `steam 'steam://rungameid/280680'` instead?
