### ISSUE TITLE
steam won't run after did some --filesystem override

### ISSUE THREAD

**Issue by leslielg** [flathub/com.valvesoftware.Steam#656]
I did some --filesystem override for steam, trying to make steam can access my existing steamlibrary. After that steam can't open anymore. I tried reset the override, remove steam & install again, none of them can make steam run again.

**Comment by leslielg** [comment]
run steam from commandline, it shows Bad item "home"
But after reset the override, all override are clear

$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam-wrapper --file-forwarding com.valvesoftware.Steam @@u %U @@
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Bad item "home" found in filesystem overrides
Please see https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-want-to-add-external-disk-for-steam-libraries
leslie@leslie-home:~
$ sudo flatpak --show override
[sudo] leslie 的密码：
leslie@leslie-home:~
$ sudo flatpak --show override com.valvesoftware.Steam 
leslie@leslie-home:~

**Comment by leslielg** [comment]
issue solved by delete ~/.local/share/flatpak/overrides/com.valvesoftware.Steam

**Comment by All3xJ** [comment]
I have the same bug (got it when I enabled the home folder sharing). I eventually uninstalled the steam flatpak version and installed the repo version.
