### ISSUE TITLE
shutil.SameFileError ... are the same file

### ISSUE THREAD

**Issue by WhyNotHugo** [flathub/com.valvesoftware.Steam#667]
**Distribution name and version where applicable**
ArchLinux, amd64.

**Flatpak info**
```
➜ flatpak --version
Flatpak 1.9.2

➜ flatpak --gl-drivers
default
host
```

**Problem description**

I hit #1658, and since it's very unclear what's causing the issue, I ran `rm -rf .var/app/com.valvesoftware.Steam`.

Now running steam via flatpak just prints this and exists:

```
➜ com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Relocating .config/gtk-3.0/settings.ini to .config.bak/gtk-3.0/settings.ini
Relocating .config/gtk-3.0/bookmarks to .config.bak/gtk-3.0/bookmarks
Relocating /home/hugo/.var/app/com.valvesoftware.Steam/config/user-dirs.dirs to .config/user-dirs.dirs
Relocating /home/hugo/.var/app/com.valvesoftware.Steam/config/gtk-3.0/settings.ini to .config/gtk-3.0/settings.ini
Traceback (most recent call last):
  File "/app/bin/steam-wrapper", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.8/site-packages/steam_wrapper.py", line 199, in main
    migrate_config()
  File "/app/lib/python3.8/site-packages/steam_wrapper.py", line 137, in migrate_config
    copytree(source, target)
  File "/app/lib/python3.8/site-packages/steam_wrapper.py", line 90, in copytree
    shutil.copy2(full_source, full_target)
  File "/usr/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 241, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/hugo/.var/app/com.valvesoftware.Steam/config/gtk-3.0/settings.ini' and '.config/gtk-3.0/settings.ini' are the same file
```

Subsequent runs yield `bwrap: Can't make symlink at /home/hugo/.config: File exists`. This is quite odd, since Steam does not have access to anything in my home:

```
➜ cat .local/share/flatpak/overrides/com.valvesoftware.Steam
[Context]
filesystems=!xdg-music:ro;!xdg-pictures:ro
```

**Does this issue reproduce with native Steam**

No, it runs fine. The issue is in the wrapper script.

It's not clear to me what the script does -- the code indicates it's trying to migrate some config, but my config is empty / nonexistent, since I've wiped it clean.

**Comment by nanonyme** [comment]
The script lays out sandbox in a way that makes Steam Cloud work. Sounds like there is a bug though. You said this reproduce with a clean sandbox?

**Comment by nanonyme** [comment]
@gasinvein any ideas?

**Comment by gasinvein** [comment]
@WhyNotHugo Do you have any global overrides passing through `xdg-config/gtk-3.0` from host?

**Comment by nanonyme** [comment]
I think we should skip the entire migration if XDG paths already point to the targets we expect.

**Comment by WhyNotHugo** [comment]
@gasinvein Oh, yeah, actually, I do:

```
$ cat /home/hugo/.local/share/flatpak/overrides/global
[Context]
filesystems=xdg-config/gtk-3.0:ro;
```

I've no idea how that came to be though. Deleting it has fixed the issue, thanks!

**Comment by gasinvein** [comment]
Seems like when filesystem `xdg-config/gtk-3.0` is allowed, flatpak mounts the same host directory to both `~/.config/gtk-3.0` **and** `~/.var/app/com.valvesoftware.Steam/config/gtk-3.0` inside the sandbox.

@nanonyme I think we should add more checks for "bad" overrides. Maybe include everything starting with `xdg-config`, `xdg-data` or `xdg-cache`
