### ISSUE TITLE
Unable to run games (native or proton)

### ISSUE THREAD

**Issue by ElDifinitivo** [flathub/com.valvesoftware.Steam#675]
The results seem simlar to #674 but I had no kernel jump from 5.9 to 5.10 (still on 5.9.16 Void Linux w/ 5700XT), with the only difference is that it seems to be random which games will run and which won't. I tried 3 Proton and 2 native games. One native game (Pillars of Eternity) says it's running even after failure to create a window, while Proton game Hades attempts to create a window and exits. The other two Proton games (Master Chief Collection and The Ultimate Doom) and the native Plague Inc: Evolved all run flawlessly. The only launch parameters set to any of the games is `-windowed` to the MCC as it's required for it to work along with Proton-GE; I tried the launch paramter with the two games that wouldn't run and it didn't do anything.

The Steam STDOUT includes program startup as well as the logs for each game: [https://pastebin.com/5TXSXGbj](https://pastebin.com/5TXSXGbj)

The issue seemed to happen once Steam auto-updated with the update that changed the look of the Properties menu for managing individual games (Steam version 1608507519). The Flatpak is the most recent 1.0.0.68.

**Comment by nanonyme** [comment]
Have you tried tout https://github.com/flathub/com.valvesoftware.Steam/wiki#Steam_Play_games_do_not_start_for_me?

**Comment by ElDifinitivo** [comment]
So Hades seems to run with Proton-GE (community build didn't work); there may have been an update I didn't pay attention to that broke Proton.

Pillars of Eternity is still bugged despite being native, so that might be something I have to reach out to Obsidian for as I tried running the Windows version instead and it works fine.

Thanks for helping me out! I'm new to messing with PC gaming as I finally have a computer that can run things properly.
