### ISSUE TITLE
steam starts slow if you're connected to VPN

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/com.valvesoftware.Steam#676]
steam starts slow if you're connected to VPN:
During start it hangs for ~7 seconds. In the command line there is this
error while it hangs:
`** (steam:157): WARNING **: 14:42:27.546: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/12 settings: (3) type
`

Fedora 33
Flatpak git master

**Does this issue reproduce with native Steam**
Not tested. (Fedora silveblue, I have only flatpak)

**Comment by gasinvein** [comment]
What's your VPN type (i.e. openvpn, ipsec, etc) and how it's setup (e.g. via NetworkManager or not)? Do you start Steam before or after you connect to VPN (and does it affect this hang)? Also please attach the whole CLI output wile running flatpak with `--log-system-bus`.

**Comment by damianatorrpm** [comment]
[steam.txt](https://github.com/flathub/com.valvesoftware.Steam/files/5742346/steam.txt)
openVPN (https://www.expressvpn.com/) configure via gnome-control-center (NetworkManager)
if steam is started before you are connected to the VPN there is no problem.

The problem is only if you are connected to the VPN and than start steam.

**Comment by gasinvein** [comment]
Aha, I believe the actual error is here:
```
** (steam:139): WARNING **: 21:55:15.323: Unknown device type 16
C84: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus

** (steam:139): WARNING **: 21:55:15.323: Could not create object for /org/freedesktop/NetworkManager/Devices/12: unknown object type
```
Seems like Steam doesn't know how to handle network device related to your VPN connection. Looks like a Steam Client issue to me (i.e. not specific to flatpak).

**Comment by damianatorrpm** [comment]
should I report it there and close this one?

**Comment by gasinvein** [comment]
Yes, I believe it should be reported there. NetworkManager version could matter here.

**Comment by damianatorrpm** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/7569

**Comment by gasinvein** [comment]
Also it worth noting that I can't fully reproduce it. Steam prints for me the same errors when starting with VPN connection active, but doesn't seem to hang.
