### ISSUE TITLE
Bad item [...] found in filesystem overrides

### ISSUE THREAD

**Issue by wsdfhjxc** [flathub/com.valvesoftware.Steam#683]
After the latest update I can no longer launch Steam due to the following error:

```
Bad item "xdg-config/gtk-3.0:ro" found in filesystem overrides
```

Yes, I do have such an override, and it's made on purpose for theming-related stuff.
I'm curious, why does the wrapper care about that, and why does it prevent Steam from starting?

**Comment by nanonyme** [comment]
Because there is code in wrapper that fixes Steam Cloud functionality through messing with xdg directories and this is not safe if you expose some of them. Ping @gasinvein I guess this is with latest changes. Maybe we should just skip xdg config migration here instead of bailing out?

**Comment by gasinvein** [comment]
@nanonyme We'll need somehow detect when migration was already applied. Still the script will bail out when launched for the first time.
@wsdfhjxc This check was added to prevent situations like #667, which are potentially destructive. As a workaround until we find a better solution, maybe you could revoke this override for the Steam app?

**Comment by nanonyme** [comment]
https://github.com/flathub/com.valvesoftware.Steam/issues/60 is where to start reading for the "why"

**Comment by nanonyme** [comment]
@gasinvein why wouldn't it be enough not to do the migration at all if xdg-config is in filesystem overrides?

**Comment by gasinvein** [comment]
@nanonyme Because the migration will be never applied if this override was already there before the first launch?

**Comment by gasinvein** [comment]
@nanonyme Hmm, maybe just skip mount points in `copytree()`? We probably shouldn't touch them anyway.

**Comment by wsdfhjxc** [comment]
Thanks guys for the explanation, as this was quite confusing.

>[...] maybe you could revoke this override for the Steam app?

Yes, I've revoked it just for the Steam Flatpak and it works as intended.

Feel free to close the issue, or not, if you prefer to continue the discussion here.

**Comment by nanonyme** [comment]
If XDG_CONFIG_HOME already points to .config, then everything is fine and symlink is unnecessary.

**Comment by nanonyme** [comment]
@wsdfhjxc yes, sorry. This is all just to avoid creating a mess of user's *real* home since if that goes broken, there's no easy way to revert. No harm meant, just protecting your files.

**Comment by nanonyme** [comment]
@gasinvein the thing is, if you give --filesystem=xdg-something, then the paths inside sandbox will be real xdg paths and we don't need to fix anything. Of course, if you set that *after* installing a game, then the sandbox may be in interesting state. :) But I kind of like current functionality. It even allows users to eg --filesystem=xdg-data/Steam without anything more or less breaking. Random crap that games write to the sandboxed home will still remain there.

**Comment by nanonyme** [comment]
https://github.com/flathub/com.valvesoftware.Steam/pull/698 has now been rolled into beta which should allow this use case. @wsdfhjxc could you please try it out to see if it makes things work correctly for you? https://github.com/flathub/com.valvesoftware.Steam/wiki/Using-beta-branch-of-this-app

**Comment by wsdfhjxc** [comment]
I confirm that the beta version launches correctly when the override is active. Thanks for fixing this.
