### ISSUE TITLE
No sound after recent update

### ISSUE THREAD

**Issue by joyov** [flathub/com.valvesoftware.Steam#686]
**Game information**

Counter Strike: Source

**Distribution name and version where applicable**

Fedora release 33 (Thirty Three)

**Flatpak info**

Flatpak 1.8.4
default
host

**Problem description**

* After upgrading to `aca2a816fc66340cb3dc7c4ce4eb062bdae9302de34927c265c175e3f7cdfa89` sound was not working in 'Counter Strike: Source' anymore.
* Also I couldn't quit the game anymore (game window went black, I had to kill it).
* I downgraded back to `5c03fa866c0916db5ef4d7ba90699abf96cdd6f85e53ea9bba96f71a722e7a22`, which fixed the problem.

```bash
sudo flatpak update --commit=5c03fa866c0916db5ef4d7ba90699abf96cdd6f85e53ea9bba96f71a722e7a22 com.valvesoftware.Steam
```

* After looking through the commit history, I suspected that https://github.com/flathub/com.valvesoftware.Steam/pull/681 might be the cause, so I upgraded back to the latest version and applied the following override, which worked:

```bash
sudo flatpak override --env=PULSE_LATENCY_MSEC= com.valvesoftware.Steam
```

**Does this issue reproduce with native Steam**

Have not tested

**Comment by nanonyme** [comment]
Thanks for reporting. I guess we need to revert then. Do you have time to make a PR?

**Comment by berkiyo** [comment]
Yeah it's quite a bummer, oh well. It'd be interesting to find out what was causing this.

**Comment by joyov** [comment]
> Thanks for reporting. I guess we need to revert then. Do you have time to make a PR?

PR: #687
