### ISSUE TITLE
Does not recognize partition (Fedora/rpm based)

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.valvesoftware.Steam#7]
Does not recognize partition /run/media/user...games partitions..

Fedora 25

![captura de tela de 2017-06-19 22-55-20](https://user-images.githubusercontent.com/17401812/27313163-e7ba5de8-5542-11e7-923a-1350f92720f1.png)

**Comment by TingPing** [comment]
It is sandboxed so it isn't supposed to. For now you can run `flatpak run --filesystem=/run/media com.valvesoftware.Steam`. It might make sense for us to just pass everything through by default..

**Comment by FastOSlinux** [comment]
working! 
![captura de tela de 2017-06-20 03-22-16](https://user-images.githubusercontent.com/17401812/27319429-cb418aae-5567-11e7-850a-b6c3c5ea2aeb.png)

**Comment by FastOSlinux** [comment]
Report of my tests, errors do not happen in steam installed via dnf (Fedora repo rpmfusion)

Borderlands 2 closes when downloading savegame
Bound by flame fonts problem
DeusEx does not open
Dirt rally error 127 and does not open
2015 f1 does not open
Grid autosport does not open
Mad Max did not open
Shadow of mordor is with texture bug already fixed by nvidia
Shadow warrior fonts problems


Fedora25 gnome(xorg) nvidia 780 driver 381.22

**Comment by TingPing** [comment]
Anyway I'll close this for now since the partition question has a workaround. You also commented your test results on another game issue where that can be tracked. Thanks for testing!
