### ISSUE TITLE
Psychonauts won't start

### ISSUE THREAD

**Issue by LoneFenris** [flathub/com.valvesoftware.Steam#708]
**Game information**
Psychonauts

**Distribution name and version where applicable**
Arch Linux

**Flatpak info**
Flatpak 1.10.0

default
host

**Problem description**
The game fails to properly start.
[psychonauts.log](https://github.com/flathub/com.valvesoftware.Steam/files/5860909/psychonauts.log)

**Does this issue reproduce with native Steam**
No

**Comment by nanonyme** [comment]
Has it worked before or is this the first try?

**Comment by LoneFenris** [comment]
I'm pretty sure I was able to run it a month or so ago.

**Comment by nanonyme** [comment]
I would imagine `SDL_Init() failed: No available video device` is the fatal error here.

**Comment by LoneFenris** [comment]
Probably. I wasn't sure if the looking for libsteam.so in my home directory errors were playing a part or not. Not sure why the `SDL_Init()` is failing regardless. 

For what it's worth, I'm running GNOME Wayland, though Steam seems to be using XWayland.

**Comment by nanonyme** [comment]
Is this SDL 1.2 or SDL 2 game?

**Comment by LoneFenris** [comment]
I'm not completely certain, but I think it's 1.2

**Comment by gasinvein** [comment]
I think this lines may be relevant:
```
dlopen failed trying to load:
/home/lonefenris/.local/share/Steam/linux32/libsteam.so
with error:
/home/lonefenris/.local/share/Steam/linux32/libsteam.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
libsteam.so
with error:
libsteam.so: cannot open shared object file: No such file or directory
```
Looks like the game is trying to open `~/.local/share/Steam/linux32/libsteam.so` which isn't there (for me neither). Maybe it just broke after some Steam Client update?

**Comment by LoneFenris** [comment]
@gasinvein That's a thought I had too. I did copy libsteam.so to the directory it was looking for it in, but there's no change in the error. It's my understanding that the flatpak isn't supposed to have access to that directory, anyway.

I did try it in the non-flatpak Steam now and it works. Not sure why the flatpak doesn't. Perhaps there's a library missing?

**Comment by nanonyme** [comment]
@LoneFenris the changes are fast-tracked to stable. Can you give it a try now?

**Comment by LoneFenris** [comment]
Yup. Runs now. Thanks.
