### ISSUE TITLE
Only give access to needed devices

### ISSUE THREAD

**Issue by matthew-cline** [flathub/com.valvesoftware.Steam#72]
The `devices` line of the `metadata` file gives access to all devices, which is way too permissive.  As far as I can tell Steam only needs access to `/dev/input` (for keyboard, mouse, and game controllers), `/dev/dri` (direct video rendering) and `/dev/shm` (shared memory for IPC).

**Comment by TingPing** [comment]
I'm not sure more limited permissions are really possible? You can test if `--filesystem=/dev/input`  works I suppose.

**Comment by matthew-cline** [comment]
I changed `metadata` so the `devices` is `devices=dri;input;shm` and Steam worked just fine.  I tried out the games _Oxygen Not Included_, _Terraria_ and _Rogue Legacy_ and they all worked fine.  However, I don't have a game controller to test with, only keyboard and mouse, so I don't know if controllers would work with that change.

**Comment by nanonyme** [comment]
Bluetooth controller support seems to require access to network for now. I'm not sure if it's covered by those?

**Comment by nanonyme** [comment]
Please roll this into a wiki page on further sandboxing. I doubt this will become the default

**Comment by nanonyme** [comment]
http://docs.flatpak.org/en/latest/sandbox-permissions.html "While not ideal, --device=all can be used to access devices like controllers or webcams."

**Comment by nanonyme** [comment]
So looks like Flatpak docs admit input is probably insufficient for controllers

**Comment by nanonyme** [comment]
Also at least my Flatpak 1.0.0 doesn't even have input
