### ISSUE TITLE
Saves are not loaded

### ISSUE THREAD

**Issue by antanasbruzas** [flathub/com.valvesoftware.Steam#722]
Using com.valvesoftware.Steam Commit: 17c6c458a53f9dd0f7661438be8bc2f5a7eaae73a42a49a4bd4778bd2f3e623b
HITMAN cannot load saved data:
[S_API WARN] CUserRemoteStorage::FileRead( LocalProfile/index.save ) failed, couldn't find file on disk
[S_API WARN] CUserRemoteStorage::FileRead( LocalProfile/index.save ) failed, couldn't find file on disk
[S_API WARN] CUserRemoteStorage::FileRead( SystemData/index.save ) failed, couldn't find file on disk
[S_API WARN] CUserRemoteStorage::FileRead( SystemData/index.save ) failed, couldn't find file on disk

With Commit: 24a2a497d918e0958ff61d4ea89b24d7a1800421bc38263d9b78b85bebee4b76 it is working fine.

**Comment by nanonyme** [comment]
Is this about local saves or cloud saves?

**Comment by gasinvein** [comment]
What's in the directory `~/.var/app/com.valvesoftware.Steam/.local/share/feral-interactive/HITMAN/SaveData`?

**Comment by antanasbruzas** [comment]
> Is this about local saves or cloud saves?

I use online mode but saves for offline mode did not work either.

**Comment by antanasbruzas** [comment]
> What's in the directory `~/.var/app/com.valvesoftware.Steam/.local/share/feral-interactive/HITMAN/SaveData`?

ls -la ~/.var/app/com.valvesoftware.Steam/.local/share/feral-interactive/HITMAN/SaveData
total 12
drwxrwx---. 2 antanas antanas 4096 2021-02-19 10:45 .
drwxrwx---. 6 antanas antanas 4096 2021-02-25 19:20 ..
lrwxrwxrwx. 1 antanas antanas   65 2021-02-19 10:45 Steam Saves (160087621) -> /home/antanas/.local/share/Steam/userdata/160087621/236870/remote

**Comment by gasinvein** [comment]
Does `/home/antanas/.local/share/Steam/userdata/160087621/236870/remote` exist inside the sandbox and contains saves? Check with 
```
flatpak run --command=ls com.valvesoftware.Steam -la /home/antanas/.local/share/Steam/userdata/160087621/236870/remote
```

**Comment by antanasbruzas** [comment]
> Does `/home/antanas/.local/share/Steam/userdata/160087621/236870/remote` exist inside the sandbox and contain saves? Check with
> 
> ```
> flatpak run --command=ls com.valvesoftware.Steam -la /home/antanas/.local/share/Steam/userdata/160087621/236870/remote
> ```

It does:
```
flatpak run --command=ls com.valvesoftware.Steam -la /home/antanas/.local/share/Steam/userdata/160087621/236870/remote
total 80
drwxrwxr-x 20 antanas antanas 4096 2021-02-25 19:59 .
drwxrwxr-x  4 antanas antanas 4096 2021-02-21 13:26 ..
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave0
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave1
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave2
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave3
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave4
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave5
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave6
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 AutoSave7
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 LocalProfile
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave0
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave1
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave2
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave3
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave4
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave5
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave6
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 QuickSave7
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 19:59 SystemData
```

But I've noticed that when I start the game the files are not there anymore:
```
flatpak run --command=ls com.valvesoftware.Steam -la /home/antanas/.local/share/Steam/userdata/160087621/236870/remote
total 8
drwxrwxr-x 2 antanas antanas 4096 2021-02-25 20:01 .
drwxrwxr-x 4 antanas antanas 4096 2021-02-21 13:26 ..
```
After stopping the game Steam retrieves them back from the cloud (timestamps indicates that also):
```
flatpak run --command=ls com.valvesoftware.Steam -la /home/antanas/.local/share/Steam/userdata/160087621/236870/remote
total 80
drwxrwxr-x 20 antanas antanas 4096 2021-02-25 20:02 .
drwxrwxr-x  4 antanas antanas 4096 2021-02-21 13:26 ..
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:01 AutoSave0
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:01 AutoSave1
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:01 AutoSave2
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:01 AutoSave3
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:01 AutoSave4
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:01 AutoSave5
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 AutoSave6
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 AutoSave7
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 LocalProfile
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave0
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave1
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave2
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave3
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave4
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave5
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave6
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 QuickSave7
drwxrwxr-x  2 antanas antanas 4096 2021-02-25 20:02 SystemData
```

**Comment by gasinvein** [comment]
Weird. I can only guess that the game doesn't like the fact that the Steam root directory is outside `$XDG_DATA_HOME`.
Will the issue persist if you run Steam with `flatpak run --env=FLATPAK_STEAM_XDG_DIRS_PREFIX='~' com.valvesoftware.Steam`?

**Comment by nanonyme** [comment]
If that works, what we could do is

1. We never define that variable
2. If user sets override, use it
3. If no override and .steam directory present, we figure out where Steam thinks it is and set $XDG_DATA_HOME based on that
4. If there is no .steam, we use a builtin default

This should allow existing installations to remain functioning properly while steering new installations in expected direction.

**Comment by antanasbruzas** [comment]
> Weird. I can only guess that the game doesn't like the fact that the Steam root directory is outside `$XDG_DATA_HOME`.
> Will the issue persist if you run Steam with `flatpak run --env=FLATPAK_STEAM_XDG_DIRS_PREFIX='~' com.valvesoftware.Steam`?

With this variable it was able to load saves. Thank you!

**Comment by gasinvein** [comment]
@antanasbruzas If that worked, can you please also try renaming `~/.var/app/com.valvesoftware.Steam/.steam` directory (while not changing `FLATPAK_STEAM_XDG_DIRS_PREFIX` variable)? Your logon and some setting in Steam client will be reset.

**Comment by antanasbruzas** [comment]
I've renamed the directory. Then ran `flatpak run com.valvesoftware.Steam` and had to input login details. But the saves were not accessible unfortunately.

**Comment by gasinvein** [comment]
That really weird. Can you please also try fixing the
`~/.var/app/com.valvesoftware.Steam/.local/share/feral-interactive/HITMAN/SaveData/Steam Saves (160087621)`
symlink manually, so that it points to
`~/.var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/160087621/236870/remote`
instead of
`~/.local/share/Steam/userdata/160087621/236870/remote`
?

**Comment by antanasbruzas** [comment]
> That really weird. Can you please also try fixing the
> `~/.var/app/com.valvesoftware.Steam/.local/share/feral-interactive/HITMAN/SaveData/Steam Saves (160087621)`
> symlink manually, so that it points to
> `~/.var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/160087621/236870/remote`
> instead of
> `~/.local/share/Steam/userdata/160087621/236870/remote`
> ?

After modifying the symlink with
`ln -sfn ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/160087621/236870/remote ~/.var/app/com.valvesoftware.Steam/.local/share/feral-interactive/HITMAN/SaveData/Steam\ Saves\ \(160087621\)`
and starting Steam with
`flatpak run com.valvesoftware.Steam`
saves are detected now.

**Comment by gasinvein** [comment]
@antanasbruzas Thanks.
@nanonyme So it's not a path length issue. I still have no idea what's the root cause, but looks like it works if all paths are consistent (`$XDG_DATA_HOME` value, `~/.steam` symlinks and the game `Steam Saves ()` symlink), so it'll probably work fine for new installations.

**Comment by nanonyme** [comment]
Right, that is why I was thinking not normalizing environments if there's existing data but just trying to keep things to what they were. There might be really strange corner-cases coming up and I don't think it's worth spending overly much time with this if fresh installations work sensibly.
