### ISSUE TITLE
Steam crashes randomly after being closed to system tray

### ISSUE THREAD

**Issue by guihkx** [flathub/com.valvesoftware.Steam#723]
I'm having this really weird issue where Steam crashes in a random interval (between 5-60 seconds) after I close it to the system tray. It does not happen when using the `steam` package from Arch Linux.

If I leave Steam open (but minimized), it won't crash either.

Steps to reproduce:

1. Run `flatpak run com.valvesoftware.Steam`
2. Close Steam to systray (just close the window)
3. Wait a couple of seconds
4. Steam crashes
5. The `flatpak` process returns status code 137

Google tells me that indicates the process was killed, but neither `journald` nor `dmesg` show me anything relevant... 

I might note that the only thing "different" I did recently to my Steam-Flatpak installation, was the removal of the `~/.var/app/com.valvesoftware.Steam/.steam` folder, in order to fix bug #480 ([source comment](https://github.com/flathub/com.valvesoftware.Steam/issues/480#issuecomment-779296054)), but I'm not sure if these two things are related.

Here's a video showing the crash:

https://streamable.com/u1pvnq

Thank you.

**Comment by guihkx** [comment]
I've tried downgrading `com.valvesoftware.Steam` to commit `92e9c0ee0f4bb4973f13adbf25f3b7c8e047c2bfc8d8189ffef202f21539142c`, then did a clean installation, but Steam is still crashing (or being killed by some other process).

I've installed Steam-Flatpak in a virtual machine on Ubuntu 20.04 but it's not reproducible there.

This is so frustrating...

**Comment by guihkx** [comment]
I can't fucking believe it was a stupid GNOME option that was preventing Steam from running in background by killing it after a few seconds. This is the option by the way (GNOME Settings > Applications):

![image](https://user-images.githubusercontent.com/626206/109075446-e495c980-76d7-11eb-81f9-073608162ab9.png)

Never even knew that was a thing, but it's baffling to me that they wouldn't at least log something to the system journal after killing a background app. Sigh.

I still have no idea why that option got disabled though, because I didn't even know of its existence. 🤦‍♂️

**Comment by gasinvein** [comment]
I believe xdg-desktop-portal-gtk should've asked you to allow Steam to run in background the very first time you minimized it to tray. Maybe you've accidentally denied it?

**Comment by guihkx** [comment]
Is that a recent change, btw? Because my Steam installation is really old...

But I do remember seeing a notification telling me that Steam was running in background, what I don't remember is being asked to allow or deny it.

Oh well, at least it's all good now :D

**Comment by gasinvein** [comment]
Not sure what's exact version it was added in, but I think it's not entirely new, 1.6 or something.
