### ISSUE TITLE
Dungeons of Dredmor no longer launches

### ISSUE THREAD

**Issue by matthew-cline** [flathub/com.valvesoftware.Steam#729]
**Game information**
[Dungeons of Dredmor](https://store.steampowered.com/app/98800/Dungeons_of_Dredmor/)

**Distribution name and version**
Fedora 33

**Flatpak info**
Flatpak 1.10.1

default
host

**Problem description**
Dungeons of Dredmor used to work just fine under flatpak, but now won't launch.  The problem seems to be with SDL, as the line `Unable to init SDL: No available video device` shows up right after the game binary is launched.  I tried launching it with the env var `SDL_DEBUG` set to get more info, but that didn't give any further info.  [Here is the Steam output/log when attempting to run the game](https://github.com/flathub/com.valvesoftware.Steam/files/6131277/default.steam.log)

I've noted that the bourne shell wrapper script incorrectly identifies the platform as 32 bit, when I'm running a 64 bit machine, and but the same thing happens under native steam and the native steam version runs just fine, so it might be a problem with 32 bit SDL running under flatpak.  I thought forcing the wrapper script to use the 64 bit version would help, but it doesn't make things any better under flatpak and makes things worse under native Steam, so that's not it.

The game is using SDL 1.2, if that matters.

This might be a duplicate of issue #708, since it also has the same `SDL_Init() failed` error message.

**Does this issue reproduce with native Steam**
Game works fine with native steam. When running natively it uses the versions of SDL shipped with the game, not the native SDL libraries in `/usr/lib`

**Comment by matthew-cline** [comment]
The problem seems to be that the environmental variable `SDL_VIDEODRIVER` is set to the empty string.
I can get the game to work under flatpak if I put `unset SDL_VIDEODRIVER` into the wrapper script, or by by putting in `export SDL_VIDEODRIVER="x11"`.

**Comment by nanonyme** [comment]
Hmm. That is very unfortunate. The reason why it's set to an empty string in the first place is to clear it up because host environment variables were resulting in strange bugs in games. I will need to do a bit of digging for original report since the manifest has since then been converted from JSON to YAML.

**Comment by nanonyme** [comment]
Ouch. https://github.com/flathub/com.valvesoftware.Steam/issues/257 looks this added as *precaution* for failures, not because it actually broke something. And it's not working as expected, it was expected to unset the variable, not set it blank. Need to do a bit of testing on this.

**Comment by LoneFenris** [comment]
I'm not terribly familiar with flatpak, so I apologize if this is dumb, but isn't the "--unset-env" param the one to use for unsetting?

**Comment by matthew-cline** [comment]
@LoneFenris That's for the command line. This bug is caused by the Environment section of the Steam app's [metadata file](https://manpages.debian.org/testing/flatpak/flatpak-metadata.5.en.html).  The Environment section lets you set a variable to the empty string, but doesn't (yet) allow you to unset a variable.

**Comment by LoneFenris** [comment]
@matthew-cline Isn't the empty string being set by the command line arg in the yaml, though?

**Comment by matthew-cline** [comment]
@LoneFenris I'm not sure about the build process for producing a flatpak app to be downloaded.  However, in what is downloaded by the end user (`/var/lib/flatpak/app/com.valvesoftware.Steam/current/active/metadata`, in this case) is an [INI format file](https://en.wikipedia.org/wiki/INI_file), and the Environment section has key/value pairs.  The closest you can get to unsetting an environmental variable with key/value pairs is to make the value the empty string.

**Comment by LoneFenris** [comment]
Oh, I see that may be a very new feature of flatpak as the metadata entry it modifies - "unset-environment" is only documented in debian's unstable version: https://manpages.debian.org/unstable/flatpak/flatpak-metadata.5.en.html

**Comment by nanonyme** [comment]
https://github.com/flatpak/flatpak/blob/e67847e253da6756886cc727687f00c57a03b816/common/flatpak-context.c#L1655-L1658
```
  /* unset-environment is higher precedence than Environment, so that
   * we can put unset keys in both places. Old versions of Flatpak will
   * interpret the empty string as unset; new versions will obey
   * unset-environment. */
```
I guess we could try with that. Bumping build requirement of the app should not be an issue.

**Comment by LoneFenris** [comment]
Ah, I see you were looking into the precedence at the same time I was. :-)
