### ISSUE TITLE
"Browse local files" doesn't work

### ISSUE THREAD

**Issue by matthew-cline** [flathub/com.valvesoftware.Steam#73]
If you right-click on an installed game, select `Properties`, then in the properties window select the `LOCAL FILES` tab, at the top is the `BROWSE LOCAL FILES...` button.  Clicking that button should bring up the game's local files directory in the desktop's GUI file browser of choice, but the button does nothing if run under flatpak.

**Comment by TingPing** [comment]
It doesn't seem to print an error so its unclear at a glance what that button is trying to do.

**Comment by nanonyme** [comment]
Works for me on Fedora 28 on Gnome

**Comment by matthew-cline** [comment]
`dbus-monitor` shows me this when I try:

    method call time=1525901853.715432 sender=:1.484 -> destination=org.freedesktop.DBus serial=4 path=/; interface=org.freedesktop.DBus; member=AddMatch
       string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='com.valvesoftware.Steam'"
    method return time=1525901853.715459 sender=org.freedesktop.DBus -> destination=:1.484 serial=5 reply_serial=4
    method call time=1525901853.715502 sender=:1.484 -> destination=org.freedesktop.DBus serial=5 path=/; interface=org.freedesktop.DBus; member=GetNameOwner
       string "com.valvesoftware.Steam"
    error time=1525901853.715513 sender=org.freedesktop.DBus -> destination=:1.484 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=5
       string "Could not get owner of name 'com.valvesoftware.Steam': no such name"

So it looks like sandboxed Steam send a dbus request to the non-sandboxed KDE desktop to display the directory, the KDE desktop then tries to find out about Steam, but it can't because the Steam dbus stuff is going on inside the sandbox.

**Comment by nanonyme** [comment]
Unless I'm badly misinterpreting the documentation, the default policy should allow this application to own com.valvesoftware.Steam and be accessible from outside the system with that name without any further configuration.

**Comment by matthew-cline** [comment]
I tried again after upgrading to Fedora 28 and the problem is gone (though it might have been fixed before then), so I'm closing this bug.

**Comment by Shished** [comment]
Sorry for necroposting, but i have this issue right now on a freshly installed Arch with Gnome 3.34.
