### ISSUE TITLE
Open file limit is too small for some games

### ISSUE THREAD

**Issue by Avamander** [flathub/com.valvesoftware.Steam#736]
After increasing open file limit in host's settings (`/etc/systemd/system.conf`, `/etc/security/limits.conf`) some games still crash with `eventfd: Too many open files`. It's unclear if and how this limit can be increased for the platpak. 

I think other people have encountered this problem as well (https://gist.github.com/stefanocoding/ec7d54116559781455d67019439e4ae5), I've encountered this with Stardew Valley.

**Comment by nanonyme** [comment]
I suggest filing this against flatpak itself (project flatpak/flatpak). This most likely cannot be changed in scope of this app.

**Comment by Avamander** [comment]
Maybe some organization admin can migrate the issue, would be easiest if it indeed is a flatpak issue.

**Comment by nanonyme** [comment]
It's another organization https://github.com/flatpak/flatpak/issues
