### ISSUE TITLE
Invalid SSL Certificate error on Ubuntu

### ISSUE THREAD

**Issue by thoughton** [flathub/com.valvesoftware.Steam#749]
Hi,

I am still experiencing the numerous "Invalid SSL" issues as discussed in issue #526 (eg. Friends List, Store page, etc), despite that issue now being Closed and me following the recommendations detailed therein. (I originally posted on that issue, but decided it would be better to post it here as a new issue rather than on one that's already closed.)

I am running `Ubuntu 20.10` and (I believe) I have the upgraded `p11-kit` packages as suggested in the aforementioned discussions.

Here's some package info:
```
~$ apt search p11-kit

libp11-kit-dev/groovy-updates,groovy-security,now 0.23.21-2ubuntu0.1 amd64 [installed]
  library for loading and coordinating access to PKCS#11 modules - development

libp11-kit0/groovy-updates,groovy-security,now 0.23.21-2ubuntu0.1 amd64 [installed]
  library for loading and coordinating access to PKCS#11 modules - runtime

p11-kit/groovy-updates,groovy-security,now 0.23.21-2ubuntu0.1 amd64 [installed]
  p11-glue utilities

p11-kit-modules/groovy-updates,groovy-security,now 0.23.21-2ubuntu0.1 amd64 [installed]
  p11-glue proxy and trust modules
```
as can be seen, all the packages are installed at version `0.23.21`.

Are there any additional special instructions for fixing this issue on Ubuntu?

Thanks!

**Comment by jonaseberle** [comment]
I can confirm.

```shell
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
...

$ apt list p11-kit
p11-kit/focal-updates,focal-security,now 0.23.20-1ubuntu0.1 amd64  [installed]
p11-kit/focal-updates,focal-security 0.23.20-1ubuntu0.1 i386

$ flatpak --version
Flatpak 1.11.2
```

**Comment by caioraposo** [comment]
Also having this issue on Void Linux (musl) p11-kit version 0.23.22

**Comment by nanonyme** [comment]
@thoughton do you have console output from when TLS fails?

**Comment by thoughton** [comment]
@nanonyme sorry no, I reverted back to the Ubuntu repos in the end.

**Comment by jonaseberle** [comment]
````
flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/jonas/.var/app/com.valvesoftware.Steam
INFO:root:Overriding TZ to Europe/Berlin
Running Steam on org.freedesktop.platform 20.08.14 64-bit

...

[0730/232535.816656:ERROR:cert_verify_proc_nss.cc(1011)] CERT_PKIXVerifyCert for steamstore-a.akamaihd.net failed err=-8179

[0730/232535.817363:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -202

**Comment by TimB87** [comment]
same problem on CRUX for quite a while now, with both runtime and no runtime (native).

**Comment by nanonyme** [comment]
Does this no still reproduce after runtime bump?

**Comment by jonaseberle** [comment]
Yes, it is still the same:

```
$ flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/jonas/.var/app/com.valvesoftware.Steam
INFO:root:Overriding TZ to Europe/Berlin
Running Steam on org.freedesktop.platform 21.08.2 64-bit
...
```
Yet the cert_ errors are not in the console output any more.
It's still not downloading content though.

**Comment by nanonyme** [comment]
Does this still reproduce? These days freedesktop-sdk uses Fedora CA, not Debian CA.

**Comment by jonaseberle** [comment]
Sorry, can't help much. I am now on Manjaro and the flatpak fails now for totally different reasons. I won't bother with it any more.

**Comment by nanonyme** [comment]
Well, if this doesn't reproduce for anyone anymore, I'm closing.
