### ISSUE TITLE
Use the actual Steam runtime instead

### ISSUE THREAD

**Issue by gbraad** [flathub/com.valvesoftware.Steam#75]
This should probably provide better compatibility if run on the Steam runtime: https://github.com/flathub/com.valvesoftware.Steam/blob/b0691afb88f32bcdbafc9e76e649311ef2844a7c/com.valvesoftware.Steam.json#L3

See for more info: https://github.com/ValveSoftware/steam-runtime This means this needs to be wrapped in a new runtime for Flatpak.

**Comment by TingPing** [comment]
Steam downloads its runtime and it is used already.
