### ISSUE TITLE
Steam Cloud - No file conflict error message is showing, even when you modify the game files to do so

### ISSUE THREAD

**Issue by femboyfromtf2** [flathub/com.valvesoftware.Steam#753]
Steam Cloud has a bad version of my Team Fortress 2 configs, and I can't remove them from the Cloud, even after contacting Steam Support. (BTW thanks to Rob from the Support for helping me out)

My specs and infos:
Ubuntu 20.10 Groovy Gorilla (Kernel 5.11.16)

hp-laptop 15-db0xxx
AMD A6-9225
AMD Radeon R4

Steps to reproduce:
1. Delete files from /tf/cfg 
2. Delete the AppID folder in /steam/userdata/[SteamID]/
3. Try to sync data with the Steam Cloud

What should've happened:
Steam would show a conflict message about Steam Cloud

What really happened:
No messages are showing, even when I modify something to trigger the pop-up

**Comment by nanonyme** [comment]
What fixed the issue?

**Comment by femboyfromtf2** [comment]
Idk, it just started to work as intended. (I think it's because my network crashed right when it should have checked the files, connected back and found the conflict)
