### ISSUE TITLE
Problematic permissions requested by flatpak

### ISSUE THREAD

**Issue by akallabeth** [flathub/com.valvesoftware.Steam#756]
The Stream flatpak uses
`--persist=.` to request access to the whole home directory.
This could also be achieved with `--filesystem=home` with the benefit that more fine grained permission settings are possible for users who do not want to share their whole account data with Stream. (`Flatseal` et al)

**Comment by nanonyme** [comment]
This is definitely not going to be done by default.

**Comment by gasinvein** [comment]
> `--persist=.` to request access to the whole home directory

`--persist` doesn't give access to files on host. Instead, it tells flatpak that the given directory inside the sandbox (relative to home), should be preserved between launches.
For example, Mozilla Thunderbird doesn't follow XDG basedir spec, thus, the flatpak app has to add `--persist=.thunderbird`, which causes `~/.var/app/org.mozilla.Thunderbird/.thunderbird` from host to be mounted on `~/.thunderbird` inside the sandbox.
In the Steam app case, `--persist=.` causes `~/.var/app/com.valvesoftware.Steam/.` from host to be mounted on `~/.` inside the sandbox, giving the app fully persistent sandboxed home directory.

**Comment by akallabeth** [comment]
@gasinvein https://docs.flatpak.org/en/latest/sandbox-permissions.html tells differently:
```
The --persist=path option can be used to map paths from the user’s home directory into the sandbox filesystem. This makes it possible to avoid configuring access to the entire home directory, and can be useful for applications that hardcode file paths in ~/.
```

**Comment by gasinvein** [comment]
I guess this is either a mistake or a wording issue. `--persist` does map paths from user's home directory, but on host the mapped paths are relative to the per-app state directory (`~/.var/app/com.example.App`), not to the home directory itself.

**Comment by akallabeth** [comment]
Well, it is true that `--persist` does not.
It is meant to e.g. bind mount a `~/.thunderbird` direcroty to the sandboxed flatpak-app home in `~/.var`
But doing `--persist=.` does bind mount the whole user home to the sandboxed one...

**Comment by gasinvein** [comment]
> It is meant to e.g. bind mount a `~/.thunderbird` direcroty to the sandboxed flatpak-app home in `~/.var`

`--persist=.thunderbird` doesn't mount the `~/.thunderbird` directory from the host anywhere.

**Comment by akallabeth** [comment]
@gasinvein ok, when did this change happen? Did use that exactly that way in a internal package until recently, so this would be a major change and not reflected in the docs?

**Comment by gasinvein** [comment]
AFAIK `--persist` always has worked this way. It's likely just the docs section is written in a confusing way or just wrong.

**Comment by gasinvein** [comment]
FWIW, the `flatpak-run` man page is much more clear about what `--persist` does:
>--persist=FILENAME
>If the application doesn't have access to the real homedir, make the (homedir-relative) path FILENAME a bind mount to the 
>corresponding path in the per-application directory, allowing that location to be used for persistent data.
>This overrides to the Context section from the application metadata. This option can be used multiple times.

**Comment by akallabeth** [comment]
@gasinvein ok, then the descriptions are somewhat contradictory. the second one describes something different from the first one.
the description from `flatpak-run` suggests the exact behavior I described, whereas the `flatpak-metadata` one only operates in the sandboxed app user directories?

**Comment by gasinvein** [comment]
No, in the first one,
>the (homedir-relative) path FILENAME

refers to the path _inside the sandbox_.

**Comment by akallabeth** [comment]
ok, would never have guessed it from the description

**Comment by gasinvein** [comment]
Well, I agree that it might be not very clear. Mind filing a bug?

**Comment by akallabeth** [comment]
https://github.com/flatpak/flatpak/issues/4314 
hope that was the correct issue tracker :)

**Comment by gasinvein** [comment]
Not exactly, AFAIK https://docs.flatpak.org is sourced from [flatpak/flatpak-docs](https://github.com/flatpak/flatpak-docs). But it can be transferred anyway.
