### ISSUE TITLE
Bad performance with AMDGPU and vega64

### ISSUE THREAD

**Issue by pschichtel** [flathub/com.valvesoftware.Steam#76]
I tried cossacks3 and CSGO and neither of those games gets close to acceptable framerates. cossacks3 is at 2 FPS in the main menu, CSGO gets to 10 FPS in the best case during a game.
I'm on Archlinux with testing repositories enabled.
Running the same games in steam outside of flatpak yield several hundred frames per second.
I previously had a RX 460 (also using AMDGPU) in my system which worked very will with the flatpak container.

**Comment by TingPing** [comment]
This issue is handled here: https://github.com/flatpak/freedesktop-sdk-images/issues/71
