### ISSUE TITLE
Steam menus look incorrect (Vega 11)

### ISSUE THREAD

**Issue by kassindornelles** [flathub/com.valvesoftware.Steam#760]
Looks like the flatpak runtime ships old or broken drivers compared to the ones on Arch.
Steam drop down menus look like this:

![image](https://user-images.githubusercontent.com/40970965/119233667-858df800-bb00-11eb-8e4f-61f69a74cc9f.png)

It works correctly if i install Steam from the Arch repos

System info:
Distro: Arch Linux
GPU: AMD Radeon VEGA 11 Graphics (stock)
CPU: Ryzen 2400G (stock)
RAM: 8 GB (2 GB for VEGA 11 graphics)
Mesa version: 21.1.0-1

Full system info:
https://gist.github.com/kassindornelles/300a736f32feae0226b3f9e91e1e460a

**Comment by nanonyme** [comment]
Sounds like https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1247

**Comment by nanonyme** [comment]
FWIW driver bugs should also be reported against freedesktop-sdk.
