### ISSUE TITLE
Proton games crashing when Alt-Tabbing

### ISSUE THREAD

**Issue by TheGreatestJannet** [flathub/com.valvesoftware.Steam#761]
**Game information**

Wreckfest, Dead or Alive 6 and more seem to freeze when alt-tabbing out of the game. The sound keeps playing.

**Distribution name and version where applicable**
Arch Linux

**Flatpak info**

Flatpak Version: Flatpak 1.11.1
Drivers: 
```
nvidia-465-31
default
host
```

**Problem description**

Proton games seem to crash when alt-tabbing out. I'm running Gnome 40 with the latest Nvidia drivers and Valve's official build of Proton which now works in flatpak.

I have the following error in my journalctl -e:
```
May 23 11:08:37 GamingPC gnome-shell[1063]: Window manager warning: Window 0x4200001 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
May 23 11:08:55 GamingPC com.valvesoftware.Steam.desktop[5608]: OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
May 23 11:08:55 GamingPC com.valvesoftware.Steam.desktop[5608]: Controller 0 Gamepad uses xinput : true
May 23 11:08:55 GamingPC com.valvesoftware.Steam.desktop[5608]: Loaded Config for Local Override Path for App ID 413080, Controller 0: /home/user/.local/share/Steam//controller_base/empty.vdf
May 23 11:08:55 GamingPC com.valvesoftware.Steam.desktop[5608]: Controller 0 Gamepad uses xinput : true
May 23 11:08:55 GamingPC gnome-shell[1063]: Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
May 23 11:08:55 GamingPC gnome-shell[1063]: Can't update stage views actor MetaWindowActorX11 is on because it needs an allocation.
May 23 11:08:55 GamingPC gnome-shell[1063]: Can't update stage views actor MetaSurfaceActorX11 is on because it needs an allocation.
May 23 11:08:55 GamingPC kernel: NVRM: GPU at PCI:0000:01:00: GPU-38399b18-17fc-b57e-cceb-9214fa0cc25b
May 23 11:08:55 GamingPC kernel: NVRM: GPU Board Serial Number: 
May 23 11:08:55 GamingPC kernel: NVRM: Xid (PCI:0000:01:00): 31, pid=7064, Ch 00000049, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_PROP_0 faulted @ 0x1_42400000. Fault is of type FAULT_PTE ACCESS_TYPE_WRIT
```

**Does this issue reproduce with native Steam**

No it doesn't happen with Native Steam.

**Comment by TheGreatestJannet** [comment]
5.0-10 crashes too when alt tabbing which leads me to believe it has nothing to do with the new pressure vessel implementation.

**Comment by TheGreatestJannet** [comment]
I get the same warnings on native steam however the kernel NVRM lines are missing and the game doesn't crash.

**Comment by nanonyme** [comment]
Do the crashes happen also with community Proton?

**Comment by TheGreatestJannet** [comment]
Yes it does.

**Comment by gasinvein** [comment]
I've experienced games crashing with Nvidia "Xid 31" kernel OOPSes before when running games with DXVK on Gnome. It seemed like it didn't happen with other WMs, so I've assumed it's related to gnome-shell somehow.

**Comment by TheGreatestJannet** [comment]
If it is gnome-shell related why does it happen only with flatpak steam and not normal steam?

**Comment by gasinvein** [comment]
No idea. On the internet there are pretty lot of messages about alt-tabbing crash with Xid 31, not sure if it's all the same issue or not. Can you check if it reproduces with another WM, e.g. openbox?

**Comment by TheGreatestJannet** [comment]
The games don't crash in openbox when alt-tabbing under flatpak steam. This means it must be a bug with flatpak and Gnome.

**Comment by TheGreatestJannet** [comment]
Has anyone found a solution to this? It seems to be getting worse with most games running through Proton crashing on alt-tab.

**Comment by TheGreatestJannet** [comment]
It seems to only happen on fullscreen-unredirect. If I disable fullscreen-unredirect with an extension it works fine and no games hang on alt-tab.

**Comment by gasinvein** [comment]
I think this worth [reporting](https://gitlab.gnome.org/GNOME/mutter/-/issues) to mutter.

**Comment by TheGreatestJannet** [comment]
I reported it there but I’m starting to think it’s an issue with my system as no one else has reported it happening to them.

**Comment by gasinvein** [comment]
Nah, it affects different users, myself included. Just no one can tell where is the root cause, so the Alt-Tab-Xid-31 errors can be mentioned anywhere. E.g. I've seen some even in DXVK bug tracker.

**Comment by TheGreatestJannet** [comment]
Ah I see that’s reassuring, although in steam flatpak it is extremely constant with Proton games. The only Proton game that doesn’t hang on Alt-Tab in flatpak steam is Euro Truck Simulator 2 (running under Proton). Every other Proton game I’ve tried in flatpak steam will hang on an alt-tab if it isn’t the first alt-tab, you can be sure it will hang on subsequent attempts.

**Comment by gasinvein** [comment]
There is a [post](https://forums.developer.nvidia.com/t/will-the-fault-pde-access-type-read-bug-in-the-nvidia-driver-ever-be-fixed/79362) on Nvidia forum with very similar error. I'm not sure if it's the same one, but it also involves DXVK and Xid 31.

My guess is that flatpak doesn't cause this, but somehow makes it more prone to occur.

**Comment by TheGreatestJannet** [comment]
I see I think you are right. It’s ridiculous this hasn’t been fixed yet seeing as it has been happening for years… Also the OP mentions that it crashes his whole system. This isn’t the case for me, only the program freezes and must be force quit to get rid of it. The system is still fully operational apart from the game.

**Comment by TheGreatestJannet** [comment]
This seems to be fixed with the 470.57.02 driver!

**Comment by gasinvein** [comment]
This is even weirder than the issue itself. Are you sure it doesn't reproduce anymore, and it's gone after driver update (and not something else)?

**Comment by TheGreatestJannet** [comment]
Yep games like Dead or Alive 6 would crash every single time I tabbed out work just like with native steam now so issues. I’ve also tabbed out of Doom Eternal countless times and it hasn’t crashed either. Maybe the fix for Doom Eternal added to the 470 driver solved this issue too.
