### ISSUE TITLE
Support for Gamemode

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#77]
https://github.com/FeralInteractive/gamemode

**Comment by nanonyme** [comment]
I'm not sure this is reasonable to do on Flatpak-level as it doesn't know when Steam has launched a game. This seems more like a thing that should be in Steam itself.

**Comment by nanonyme** [comment]
I guess something that could be done with this is to ship libgamemode in the app and expose gamemode DBus to the container so the daemon gets to run in host and games that grow integration could take it into use. @TingPing opinions?

**Comment by nanonyme** [comment]
Seems a bit strange the library would need systemd headers. I thought they were just for the daemon

**Comment by nanonyme** [comment]
@Tomin1 Try passing it with-systemd=false with-daemon=false

**Comment by nanonyme** [comment]
Please make a pull request, we can work on review and improvements there

**Comment by valentindavid** [comment]
I suppose that to work you need to install game mode daemon on the host. Are there compatibility issues across versions?

**Comment by valentindavid** [comment]
This is something that would be good for non steam games on Flathub. Should it go in the shared modules?

**Comment by nanonyme** [comment]
Imo let's do it right this time and only put it to shared modules once we have proof it works with the build system. It's easier to test build embedded modules

**Comment by Tomin1** [comment]
@nanonyme Thank you for your insight. It was helpful although not enough here. I made a pull request.

**Comment by LeandroStanger** [comment]
@nanonyme Gamemode activated automatically?

**Comment by nanonyme** [comment]
No, you can do the described LD_PRELOAD trick manually if you need it. The library is under /app/lib. Caveat is we cannot currently provide it at all for 32bit games due to build system limitations. Note that the preload trick will not work for all games anyway

**Comment by nanonyme** [comment]
I guess we could add easier variable for setting the preload still so you wouldn't need to know the paths

**Comment by jurf** [comment]
@nanonyme is that the exact launch option you use? I was wondering whether it shouldn’t be `LD_PRELOAD=$LD_PRELOAD:/app/lib/libgamemodeauto.so.0 %command%` for Flatpak. Also, do you have a game where you can confirm it works so I can try too?

**Comment by nanonyme** [comment]
No. I don't think it even does anything on much on my machine as I have AMD CPU

**Comment by nanonyme** [comment]
Might have broken when we removed full system bus access. Metadata only gives permissions to session bus which is probably wrong

**Comment by nanonyme** [comment]
See https://github.com/flathub/com.valvesoftware.Steam/issues/188

**Comment by nanonyme** [comment]
@jurf could you test if allowing system talk for the name fixes this?

**Comment by mxre** [comment]
I've a general question on using gamemode from inside a flatpak sandbox.

gamemode uses dbus to communicate with the service gamemoded (running outside the sandbox). The releveant DBus call is com.feralinteractive.GameMode.RegisterGame/UnregisterGame this call needs as an argument the PID of the Program (libgamemodeauto.so uses getpid()) and the service uses this PID to set niceness and io_sched.

Now PIDs from inside the sandbox are useless outside, so how should gamemode work with flatpak?

**Comment by mxre** [comment]
DBus access is correct, except that runs on session bus, and not the system bus, #191 should be reverted.
(see https://github.com/FeralInteractive/gamemode/master/meson.build#L54 ) gamemoded is installed as a user unit and thus runs as on the session bus)

As for the PID issue I only noticed it, because i enabled send-notify on gamemode start and it always witched off imediatly (because the PID that was sent be the library was non existant)

**Comment by nanonyme** [comment]
Should be reverted assuming Flatpak can even support gamemode. I'm not entirely sure it can if it relied on caller to report its PID

**Comment by jurf** [comment]
Maybe would be worth pinging upstream about this whole issue?

**Comment by nanonyme** [comment]
@alexlarsson ping, do you think this thing is even solvable or should we just give up with game mode and remove it from the app?

**Comment by mxre** [comment]
@jurf It would be nice if flatpak provided an option to share the pid, currently flatpak always launches bwrap with --unshare-pid ( https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L2351 )

**Comment by jurf** [comment]
@nanonyme I meant upstream as in GameMode upstream, but yeah, Alex is good to have here to. :slightly_smiling_face:

**Comment by nanonyme** [comment]
Oh, right. That way :)
I'm not sure if they could help much if it actually involves renicing a specific PID. How could gamemode do that if it doesn't know the PID? SCHED_ISO on the other had has been documented as a "your mileage may vary" sort of a thing; it might make things better or worse

**Comment by nanonyme** [comment]
@mxre I guess that's not that surprising, that's a fairly core feature of the sandbox that have a separate pid namespace

**Comment by nanonyme** [comment]
Had a semi-brief conversation about this with @alexlarsson on IRC and it seems like this isn't really solvable without changes on gamemode side.

**Comment by nanonyme** [comment]
@gasinvein how about attaching output from
flatpak run --env=LD_PRELOAD=/app/lib/libgamemodeauto.so.0 --command=bash com.valvesoftware.Steam?
Need to manually exit though...

**Comment by nanonyme** [comment]
I don't have a useful environment to debug this with, would be really nice to see some outputs with proper logs. It will spam a lot though so might want to attach instead of pasting

**Comment by gasinvein** [comment]
@nanonyme in that case there is no calls printed, just what I've posted. `--log-session-bus` prints calls only for `dbus-send`.

**Comment by nanonyme** [comment]
The code in gamemode seemed really simple, it's just calling sd_bus_call_method from libsystemd

**Comment by gasinvein** [comment]
@nanonyme I can't see anything interesting there.
[gamemodeauto_bash_strace.txt](https://github.com/flathub/com.valvesoftware.Steam/files/2368132/gamemodeauto_bash_strace.txt)

**Comment by nanonyme** [comment]
@jurf you weren't getting these issues earlier, right?

**Comment by nanonyme** [comment]
I'm to be honest starting to wonder if it would have been less effort to just call that command-line you just did from the steam-wrapper and call it a day instead of using libsystemd and gamemode if it's really that simple to set it up.

**Comment by gasinvein** [comment]
You mean `dbus-send`?

**Comment by nanonyme** [comment]
Yes

**Comment by jurf** [comment]
@nanonyme I’m quite lost TBH, not sure what issues you’re talking about… I just installed it natively and launched the entire flatpak with it, not sure if that’s what you want.

**Comment by gasinvein** [comment]
This can be implemened easly indeed, but
- GameMode still wouldn't be able to handle PIDs, and thus won't set niceness to process
- We need to make a second call to GameMode to undo things, thus, in wrapper we need to wait until Steam exits

**Comment by nanonyme** [comment]
@gasinvein the second is not true, it tracks the PID. When Flatpak exits, the dbus-proxy exits

**Comment by nanonyme** [comment]
The main issue here is that it indeed tracks PID but it tracks *wrong* PID unless gamemode is changed.

**Comment by gasinvein** [comment]
@nanonyme 
> the second is not true, it tracks the PID. When Flatpak exits, the dbus-proxy exits

I mean, first we call RegisterGame, and then, because GameMode isn't able to track PIDs, we wold need to call UnregisterGame() manually.

**Comment by nanonyme** [comment]
I'm to be honest a bit confused still as to how you'd have something on session bus instead of system bus that is capable of changing CPU governor.

**Comment by gasinvein** [comment]
As I understand, GameMode implements this as [separate binary](https://github.com/FeralInteractive/gamemode/blob/master/daemon/cpugovctl.c), which is launched with escalated privileges [via PolKit](https://github.com/FeralInteractive/gamemode/blob/master/data/com.feralinteractive.GameMode.policy.in).

**Comment by nanonyme** [comment]
I was earlier talking of patching this line https://github.com/FeralInteractive/gamemode/blob/master/lib/client_impl.c#L70 so that PID is always 1, btw.

**Comment by gasinvein** [comment]
I think the correct way would be to actually get sender's pid from dbus on server's side, instead of entrusting the client to send it's own pid.

**Comment by nanonyme** [comment]
Yes, that's been discussed before. That doesn't work exactly correctly in our case either because the Dbus client PID is the PID of the Dbus proxy, not Steam. However, lifecycle-wise it would be better

**Comment by nanonyme** [comment]
I'd also say that the hack of using PID 1 definitely doesn't work with naive usage of LD_PRELOAD since the register/unregister go in pairs and you would get unregister from child processes. It might in fact even be easier to read some environment variable to see if we should enable gamemode and load the library using ctypes with Python if we can get the library working

**Comment by nanonyme** [comment]
Aha. I don't get the errors if I do
flatpak run --command=bash com.valvesoftware.Steam
bash-4.4$ LD_PRELOAD=/app/lib/libgamemodeauto.so.0 /bin/true
gamemodeauto: Could not call method on bus: Connection reset by peer
gamemodeauto: Could not call method on bus: Connection reset by peer

**Comment by nanonyme** [comment]
Okay, so with this in mind, my idea of using ctypes to load the library and patch it to always give 1 for PID might do... something. I'm not 100% sure if it trying to renice init would be actively harmful though

**Comment by nanonyme** [comment]
Oh, argh, I again forgot that exec'ing the other process means that it never gets to unregister

**Comment by nanonyme** [comment]
No. I'm not to be honest even sure at this point whether sd-bus works outside systemd user instance. I have never used it myself.

**Comment by matthiasclasen** [comment]
from a higher-level perspective, the right approach to this kind of issue is:

- write a portal that provides a 'gamemode' api on the session bus for sandboxed apps and uses the gamemode library to forward requests to the gamemode daemon on the system bus
- ship a patched gamemode library in the sandbox that talks to the portal instead of the gamemode daemon

Ideally, the library patch can go upstream and transparently do the right thing, by looking for /.flatpak-info.

**Comment by gasinvein** [comment]
@matthiasclasen There is no gamemode daemon on system bus.

**Comment by matthiasclasen** [comment]
But uses a privileged helper ?

**Comment by gasinvein** [comment]
Yes.

**Comment by nanonyme** [comment]
@matthiasclasen Steam launcher shouldn't be giving that many problems for explicit access of gamemode. These weird quirks are mostly about the "things don't actually have gamemode support so we're going to preload a random library into these executables and pretend they do".

**Comment by matthiasclasen** [comment]
sounds like a case for "just don't do that"

**Comment by nanonyme** [comment]
That sounds fair. That means though that this gamemode thing would probably at very least be sold to Valve, preferably game vendors as well for this feature to be at all doable.

**Comment by jurf** [comment]
Speaking of GameMode, it might be useful to somehow tell GNOME Software not to do background updates while playing a game, now that automatic updates are enabled in 3.30.

**Comment by nanonyme** [comment]
That might actually be a good thing whether or not it would be part of gamemode itself.

**Comment by jurf** [comment]
(Also the downloading of updates, which is already an issue.)

**Comment by nanonyme** [comment]
Can you please raise that with Gnome? They would probably need to provide an interface to temporarily suspend updates for what you described to work. Probably a secure one so unprivileged users can't abuse it

**Comment by jurf** [comment]
[Done.](https://gitlab.gnome.org/GNOME/gnome-software/issues/482)

**Comment by pablodav** [comment]
Good to see this discussion.

Just thinking in others things that can make issues when gaming: tracker should not do indexing operations during users is in "game mode", as it also uses disk IO and lot of CPU sometimes. Not sure if tracker already has some tweaks to not affect the user, but I see it using lot of CPU sometimes when gnome starts.

Probably best behaviour in game-mode for gnome-software and tracker:

Just sleep the processes for tracker and gnome-software when launching steam from flatpak, so also the processes could go to swap if required instead of keep using RAM/CPU/IO? could be something easy to do from steamwrapper?

**Comment by jurf** [comment]
To swap is a an overkill, but some processes could indeed be shut down.

**Comment by nanonyme** [comment]
Kernel usually makes sure memory is properly swapped where not pinned for some reason. You just need to make sure you idle and everything will be fine

**Comment by nanonyme** [comment]
@mathiasclasen your suggestion sounds reasonable. Downside is I at least have zero knowledge on writing portals. Currently using upstream library means libsystemd dependency to all parties using it. I don't know whether this constitutes as overkill since it's just a simple API for doing a couple of Dbus calls since I have never done Dbus with so low-level languages

**Comment by mxre** [comment]
IMHO the systemd dependency is easily avoided I wrote a version of gamemodeauto.so without it (https://github.com/mxre/gamemode). I think upstream libgamemode devs where to lazy to actually use dbus directly. (It's pretty easy)

I think using a portal ist the best way to map the sandboxed PIDs to system PIDs.
On the system the sandboxed PIDs can be inspected in /proc/<PID>/status as NSpid
but i found no other way to find the right NSpid (corresponding to the right namespace) unless I iterate over all running processes.

**Comment by nanonyme** [comment]
@mxre there was an earlier hint to flatpak ps code

**Comment by hadess** [comment]
We discussed gamemode integration in #flatpak today, and @matthiasclasen and I agreed that the easiest way to add gamemode support might be to modify the daemon to track D-Bus clients instead of PIDs, removing the need for a portal to do that translation, and punching a hole in the Flatpak manifest to allow Steam (and games) to talk to the gamemode daemon directly.

Making sure the gamemode versions and APIs inside and outside the sandbox match and track the same thing is going to be more complicated though...

**Comment by gasinvein** [comment]
>punching a hole in the Flatpak manifest to allow Steam (and games) to talk to the gamemode daemon directly

Can you explain it please?

**Comment by hadess** [comment]
> Can you explain it please?

Add `--system-talk-name= com.feralinteractive.GameMode` to the `finish-args`

**Comment by hadess** [comment]
> We discussed gamemode integration in #flatpak today, and @matthiasclasen and I agreed that the easiest way to add gamemode support might be to modify the daemon to track D-Bus clients instead of PIDs, removing the need for a portal to do that translation, and punching a hole in the Flatpak manifest to allow Steam (and games) to talk to the gamemode daemon directly.

And talking some more with @gicmo, the PID is really baked into the API, so the solution might be to write a portal after all. As this is very specific to a service that has a, shall we say, limited shelf life (ideally, gamemode  wouldn't need to exist, but this isn't how things worked out), we thought it best not to add it directly in xdg-desktop-portal, but it could be implemented as a separate portal, as a stand-alone daemon, or inside the gamemode daemon itself, owning the `org.freedesktop.Portal.gamemode` name.

**Comment by nanonyme** [comment]
Note this now requires quite new xdg-desktop-portal to work. @gicmo  can probably provide some details.

**Comment by gicmo** [comment]
It indeed needs xdg-desktop-portal version >= [1.4.0](https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.4.0) on the host, which added the GameMode Portal.
