### ISSUE TITLE
Selection sticking on Dialog and Library selection

### ISSUE THREAD

**Issue by lineber** [flathub/com.valvesoftware.Steam#787]
**Distribution name and version where applicable**

Fedora 34 Silverblue

**Flatpak info**
Flatpak 1.10.2
nvidia-465-24-02
default
host

CPU: Intel Pentium G4620 (4) @ 3.700GHz 
GPU: NVIDIA GeForce GTX 1060 3GB 

**Problem description**
Often when using the mouse in Steam (Flatpak) a dialog box such as the Month selector and does not disappear after selecting is made. Similarly in the Game Library when you select a game a few games, the mouse seems to be selecting multiple items as if the <shift> key is pressed. The only way to fix these issues appears to be to shut the steam client off.

**Does this issue reproduce with native Steam**
Yes, it doesn't happen.

**Comment by rowbawts** [comment]
I'm having a similar issue where the library page doesn't update unless I hover over the Store, Library, Community buttons on the top.

**Comment by lineber** [comment]
I no longer run the Flatpak version of Steam, so I cannot verify if this issue still exists. The regular Linux version of Steam does not have this minor problem.
