### ISSUE TITLE
Sync games files between flatpak and native

### ISSUE THREAD

**Issue by AshtakaOOf** [flathub/com.valvesoftware.Steam#788]
**Game information**
Only some game that won't work with proton even if they are listed as working on protondb but it's not a big issue

**Distribution name and version where applicable**
Fedora 33 

**Flatpak info**
Flatpak 1.10.2

nvidia-465-31
default
host

**Problem description**
How can i sync games files between native version and flatpak version of steam so i can do things on the native version of steam and flatpak to do other things on it

and there are no logs it's just a little issue

**Does this issue reproduce with native Steam**
Yes

**Comment by gasinvein** [comment]
I believe the most proper way to do so is to 
1. select some directory for you game library (e.g. `~/SteamGames` if your home is on the largest partition)
2. grant this flatpak app access to it (`flatpak override --user --filesystem=~/SteamGames com.valvesoftware.Steam`)
3. add this directory to library forlers in both flatpak and native Steam and make it default in both
4. if needed, move games from previous default library folders to the new one

**Comment by nanonyme** [comment]
@AshtakaOOf  does above suggestion work for you?

**Comment by nanonyme** [comment]
Closing due to no additional feedback from submitter
