### ISSUE TITLE
Is it possible to support flatpaked discord rpc?

### ISSUE THREAD

**Issue by rowbawts** [flathub/com.valvesoftware.Steam#789]
Is it possible to enable the discord rpc on this so that the steam flatpak and discord flatpak can communicate?

**Comment by lineber** [comment]
I recall that issue is open on [https://github.com/flathub/com.discordapp.Discord/issues/115](https://github.com/flathub/com.discordapp.Discord/issues/115)

**Comment by rowbawts** [comment]
> I recall that issue is open on [flathub/com.discordapp.Discord#115](https://github.com/flathub/com.discordapp.Discord/issues/115)

Oh I saw that [this](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)) existed and didn't realize steam used a different method reading processes than that provides, so I thought that all it took was to get this flatpak setup with that but it seems to be more involved.

**Comment by gasinvein** [comment]
@rowbawts What's the exact case that is broken? E.g. it's some game that is supposed to update rich presence, but doesn't?

**Comment by rowbawts** [comment]
> @rowbawts What's the exact case that is broken? E.g. it's some game that is supposed to update rich presence, but doesn't?

I think I just had a misunderstanding with how it worked I thought Steam provided the game status to Discord and not the games themselves.
