### ISSUE TITLE
Satellite Reign

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam#79]
Satellite Reign is slow and is displaying the delay on the keyboard command

**Comment by LeandroStanger** [comment]
https://www.humblebundle.com/store/satellite-reign

**Comment by nanonyme** [comment]
Any difference to this with freedesktop runtime 18.08?

**Comment by LeandroStanger** [comment]
Now it hangs in loading the game only by turning off the PC to quit the game

**Comment by LeandroStanger** [comment]
```
Game removed: AppID 268870 "", ProcID 299 
No cached sticky mapping in ActivateActionSet.[0323/130706.227323:INFO:crash_reporting.cc(265)] Crash reporting enabled for process: renderer
[0323/130708.299474:INFO:crash_reporting.cc(265)] Crash reporting enabled for process: renderer

```

**Comment by nanonyme** [comment]
Does this persist? There's now runtime 19.08 in use. (I'm assuming there's nothing as such app-dependent affecting this and it's mostly about runtime libraries)

**Comment by nanonyme** [comment]
Closing as obsolete.
