### ISSUE TITLE
The FAQ asks me to "fix directories" but I'm not sure what it means.

### ISSUE THREAD

**Issue by tvvoty** [flathub/com.valvesoftware.Steam#790]
I tried to give steam flathub access to my real file system and got an error that pointed me there: https://github.com/flathub/com.valvesoftware.Steam/wiki#i-want-to-add-external-disk-for-steam-libraries

I unchecked "All system files" in flatseal for steam and now steam starts up fine, however the FAQ says I should "fix some directories", but I don't really get what it means by that. It said it can break home folder if something's wrong, so I thought, and was advised, I'd better ask there. I also have non-flatpak steam installed if it's relevant.

**Comment by nanonyme** [comment]
That hole you added is not supported. You need to remove it for Steam to start.

**Comment by tvvoty** [comment]
I removed "all system files" access in flatseal and steam starts fine now, I just thought maybe I needed to to anything else based on the FAQ since it said I needed to fix some directories.

**Comment by nanonyme** [comment]
No, that should be all. Mostly what can happen is the migration code in the app when running without sandbox confining can end up breaking actual user home which is not great. Hence all the warnings.
