### ISSUE TITLE
Question: Why don't ship Proton Compatibility Tool as a default dependency ?

### ISSUE THREAD

**Issue by marcelovbcfilho** [flathub/com.valvesoftware.Steam#793]
I use linux for about 3/4 years, about 1.5 years ago I discovered flatpaks and I'm using it since them, but I've already tried a feel times to use steam as a flatpak, but most of the steam play games didn't run, I thought that this was a problem with flatpak, but it was just an issue with the Proton inside flatpak, after searching a little I found in the wiki the solution.
I just would like to know if there is something wrong or any other thing that prevent the steam to ship by default with the Proton Compatibility Tool, because to my eyes, many users don't know, or that are new to linux that they might install another flatpak to be able to run some games throw proton.

**Comment by nanonyme** [comment]
This was considered through https://github.com/flathub/com.valvesoftware.Steam/pull/746 and it might have well happened if not for @smcv having done huge amount of work making regular pressure-vessel work inside flatpak. The mission of this app is to allow Valve Steam to work with as few changes as possible. Not forcibly installing community Proton to user machines seems to align better with this mission. @marcelovbcfilho does this answer your questions?

**Comment by marcelovbcfilho** [comment]
I see, agree with you if it is possible to make the pressure-vessel work inside flatpak I believe that this is the way, thank you for replying.
