### ISSUE TITLE
README.md Frequently Asked Questions link is broken

### ISSUE THREAD

**Issue by eiglow** [flathub/com.valvesoftware.Steam#794]
It links to [this page](https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions) which apparently no longer exists. I think it should link to [here](https://github.com/flathub/com.valvesoftware.Steam/wiki).

**Comment by nanonyme** [comment]
Where from? All links should point to latter location if you're properly up to date.
