### ISSUE TITLE
Tooth and Tail fails to start: Possible conflict with GOG Galaxy and file permissions

### ISSUE THREAD

**Issue by Alxe** [flathub/com.valvesoftware.Steam#80]
On Fedora 27 Workstation, up to date flatpak and system.

Game fails to start on Flatpak'd Steam, while it works on "native" Steam (provided by RPM Fusion).

The exception thrown is shown below. It appears to be a problem with file permissions and GOG Galaxy integration (for multiplayer)

![screenshot from 2018-04-23 11-42-10](https://user-images.githubusercontent.com/3256915/39211751-eb3d4fc6-480c-11e8-9368-39fc103b6a60.png)

Any workaround suggestion?

**Comment by Alxe** [comment]
Starting the game from host system works fine for 64-bit version, but fails for 32-bit (which is understandable, I have no or almost no i686 packages installed).

The game boots Steam as a non-sandboxed app and runs fine.

I wonder, does flatpak'd Steam distinguish between x86 and amd64 builds? This may be close to the problem, but probably not. I still believe it has to do with any of the GOG Galaxy libraries.

**Comment by Pobega** [comment]
@Alxe Are you still seeing this issue? I can confirm that I was able to run Tooth and Tail last week via the Steam Flatpak

**Comment by Alxe** [comment]
@Pobega Sorry for the late answer, I read your comment and thought I already answered.
Since then, I've stopped using the Steam flatpak, so I can't reproduce the issue right now, w/o installing it again.

I'll get to it once I have a bit of time, I'm a bit busy at the moment. And if I don't forget.

**Comment by Pobega** [comment]
It works for me on Debian Buster, Fedora 28 and CloudReady via the Steam Flatpak. You can probably mark this as resolved.
