### ISSUE TITLE
Protontricks not working

### ISSUE THREAD

**Issue by Sultech** [flathub/com.valvesoftware.Steam#804]
Distribution name and version where applicable:
Fedora 34

Flatpak info:
Flatpak 1.10.2
nvidia-470-63-01
default
host

**Problem description**
When I open protontricks and press on any game that is installed this error will pop up
![Screenshot from 2021-09-15 03-27-45](https://user-images.githubusercontent.com/30802163/133360374-2300f732-1fd2-48bb-918b-332dc156781e.png).

"wine: could not load ntdll.so: /app/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/share/steam/compatibilitytools.d/Proton/dist/lib/wine/ntdll.so)" 

Does this issue reproduce with native Steam
I have not tested it with native steam

**Comment by nanonyme** [comment]
Try running `flatpak update`

**Comment by Sultech** [comment]
I tried that is says nothing to do.

**Comment by nanonyme** [comment]
@gasinvein can you make something of that? The glibc version sounds like what is in 21.08

**Comment by gasinvein** [comment]
@Matoking Can you please update SDK for Protontricks flatpak to 21.08? All Proton-flatpak builds were updated, so they can't run in the protontricks bundle environment.

**Comment by Matoking** [comment]
@gasinvein I've updated the SDK in the Flatpak manifest to 21.08.

The update for Protontricks should be available in ~3 hours on Flathub.

**Comment by gasinvein** [comment]
@Matoking Thanks.
@Sultech Updated Protontricks landed, it should work now, please update.

**Comment by Sultech** [comment]
Yes it is working now thanks
