### ISSUE TITLE
Fsync does not work even with fsync patched kernel

### ISSUE THREAD

**Issue by Sultech** [flathub/com.valvesoftware.Steam#806]
When I run a game from the terminal "fsync: up and running" should show as I have a patched fsync kernel however nothing comes up. This is how to test if a game is using fsync https://steamcommunity.com/app/221410/discussions/0/3158631000006906163/. I'm not sure if I have tested it correctly but from the link I posted it seems fsync is not being used. Also when using lutris from flatpak, trying to enable fsync dose not work either https://github.com/flathub/net.lutris.Lutris/issues/161

Distribution name and version where applicable:
Fedora 34

Flatpak info:
Flatpak 1.10.2
nvidia-470-63-01
default
host

Does this issue reproduce with native Steam
This issue does not happen with native steam

**Comment by nanonyme** [comment]
I have no idea if this is supposed to work inside a sandbox. @smcv any clue?

**Comment by smcv** [comment]
Note that "fsync" is a misleading name for this feature: it's really a `FUTEX_WAIT_MULTIPLE` operation for the `futex()` syscall, and has nothing to do with the `fsync()` syscall.

I don't know whether this is meant to work across a sandbox boundary either.

This is an experimental feature requiring a kernel with non-upstream patches that change its ABI, so I'm not surprised if it's fragile...

**Comment by nanonyme** [comment]
I'm assuming someone might have tested it for that because of pressure-vessel being so central to Proton plans but that's just me.

**Comment by sad-goldfish** [comment]
FUTEX_WAIT_MULTIPLE is mainlined in 5.16. Fsync does work for me with Steam's Proton 6.3-8 and 7.0-1 in Flatpak though.

**Comment by Sultech** [comment]
It also work's for me now, something must of my changed. I will close the issue.
