### ISSUE TITLE
Steam won't run, missing 'libc.so.6'

### ISSUE THREAD

**Issue by o-alquimista** [flathub/com.valvesoftware.Steam#81]
![captura de tela de 2018-05-06 11-38-33](https://user-images.githubusercontent.com/25424263/39674425-0dbe5126-5122-11e8-95be-927a7eed7589.png)
Immediately after clicking the Steam icon, this message appears. It does not start.

I suppose the flatpak should contain that library, but for some reason it doesn't. I'm running Debian Stretch.

**Comment by o-alquimista** [comment]
Alexander, how do I check that? `flatpak list` only shows Steam, not the dependencies.

**Comment by Alexander-Wilms** [comment]
For me, it's listed. Just run `flatpak install flathub org.freedesktop.Platform.Compat32` to be sure

**Comment by o-alquimista** [comment]
It's installing now. It wasn't installed. By the way, I installed Steam through GNOME Software. Any chance that didn't bring the dependencies?

**Comment by Alexander-Wilms** [comment]
Yes, it should be fixed in the latest version: https://github.com/flatpak/flatpak/issues/853

**Comment by o-alquimista** [comment]
That's it. It worked. Thank you.
