### ISSUE TITLE
Poor performance in Proton games with Steam Flatpak

### ISSUE THREAD

**Issue by kassindornelles** [flathub/com.valvesoftware.Steam#810]
**Game information**
 
Resident Evil VILLAGE / BIOHAZARD VILLAGE (https://store.steampowered.com/app/1196590/Resident_Evil_Village/)

**Distribution name and version where applicable**
 
Arch Linux

**Flatpak info**
 
Flatpak 1.11.3

flatpak --gl-drivers:
default
host

Mesa 21.2.1 - in the flatpak (reported by steam)
21.2.2 - system wide (reported by steam)

**Problem description**

The game performs poorly in the flatpaked steam version, not only the framerate is way lower but the game stutters a lot while moving around, i was using Proton Experimental in both flatpak steam and native steam.

GTA V (another game i tested) also performs poorly with Steam Flatpak.

Flatpak performance screenshot:
![steamflatpak](https://user-images.githubusercontent.com/40970965/134438646-fc7721a6-8fec-4023-8b51-8fe075403dab.png)

Steam native performance screenshot:
![steam runtime drm](https://user-images.githubusercontent.com/40970965/134438659-d74c32cc-7ecc-4d35-98cf-84c084e1b2b0.png)

**Does this issue reproduce with native Steam**

No

**Comment by soredake** [comment]
https://github.com/flatpak/flatpak/issues/4187

**Comment by gasinvein** [comment]
@soredake Seccomp alone shouldn't have this big impact.

**Comment by kassindornelles** [comment]
> @soredake Seccomp alone shouldn't have this big impact.

it might have, when i tried a full flatpak system everything was super slow, and i have a low end CPU (ryzen 2400G) so if you have anything more powerful than this the impact would probably be way lower, but still a thing.

**Comment by kassindornelles** [comment]
closing this issue because looks like the performance issues i was having were related to mesa being month's old in steam flatpak.
