### ISSUE TITLE
Shutting down system from Steam not working (dbus-send command not found)

### ISSUE THREAD

**Issue by tanovich** [flathub/com.valvesoftware.Steam#826]
Hi! 

I can't shutdown my computer using this flatpak version of Steam. Running it from command line gived me this message `sh: line 1: dbus-send: command not found` just after trying to shut down. 

Steam installed from arch repo works as expected, however i would like to make flatkpak version usable.
 
Using `flatpak run --talk-name=org.freedesktop.DBus com.valvesoftware.Steam` mentioned in #305 didn't work.

**Comment by nanonyme** [comment]
Closing, handling in linked issue.
