### ISSUE TITLE
Can't install Wine Mono on Steam

### ISSUE THREAD

**Issue by mmorschel** [flathub/com.valvesoftware.Steam#833]
- When I open Steam, the Wine-Mono-Installation window pops up. (Translated from German: "Wine couldn't find the wine mono package."
- When I try to install Wine Mono it gets canceled with following error message: "Unexpected check sum of the downloaded file. Canceling installation of the damaged file."
- Did install wine-mono manually but thios didn't solve the issue.

**Comment by iotku** [comment]
Also experiencing this on a new install on Arch (installed Steam flatpak and removed native multilib packages from pacman repos)

Seems to not be causing any problems but the popup is an annoyance for sure.

**Comment by NSQY** [comment]
Arch
Steam beta latest update and previous

```
Steam - Launcher for the Steam software distribution service

          ID: com.valvesoftware.Steam
         Ref: app/com.valvesoftware.Steam/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0.72
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 41.3 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: f625d86160a3781658ba11360d8a426c6f217ae7f2db94f76eb4fa879b33df0b
      Parent: 4be062ec80a394f91508c244f8a1bc23c2cb84d40b863bfccf3fa651eb49206c
     Subject: Allow all extension branches (f2907b16)
        Date: 2021-11-14 13:43:02 +0000
```
![steam1](https://user-images.githubusercontent.com/34185288/142141649-fc16f834-adb7-4394-b0dc-0ef2fac47f0a.png)
![steam2](https://user-images.githubusercontent.com/34185288/142141654-14f3d2f0-dcf0-4272-a09d-93efdaee109e.png)

**Comment by mmorschel** [comment]
> Also experiencing this on a new install on Arch (installed Steam flatpak and removed native multilib packages from pacman repos)
> 
> Seems to not be causing any problems but the popup is an annoyance for sure.

Newer games run just fine, but I don't know if it affects older games.

I can't get GTA: San Andreas to run, so it's a solid Gold-"Out of the box"-game over on protondb. Tested with flatpack-community-versions of Experimental, 6.3.7 and GE.

**Comment by Pshemas** [comment]
I get the same issue - on start for some reason Steam wants to install Mono.

**Comment by kaimast** [comment]
I had the same problem and it went away after removing the proton flathub package like so
` flatpak remove com.valvesoftware.Steam.CompatibilityTool.Proton`

So it's probably a bug with that package. As far as I understand, the package is not needed anymore anyways, because the most recent flatpak supports sub-sandboxing.

**Comment by gasinvein** [comment]
Did you have the Proton community build `beta` branch installed? It had outdated mono indeed, should be fixed in flathub/com.valvesoftware.Steam.CompatibilityTool.Proton@fb0576c9c30611af1f43a1969c4e36d501ffd8de

**Comment by kminardo** [comment]
I am running com.valvesoftware.Steam.CompatibilityTool.Proton-GE @ 6.21-GE-2-1, uninstalling that package removed the prompt so I'm guessing that was impacted as well. Thanks for the heads up, looking forward to the next build :)

**Comment by gasinvein** [comment]
Proton-GE community build seems to have outdated Mono as well. Ping @Lctrs

**Comment by Lctrs** [comment]
wine-mono is up to date in Proton GE now.

**Comment by nanonyme** [comment]
Excellent. Let's close this.

**Comment by spikespaz** [comment]
This is now relevant again apparently

**Comment by gasinvein** [comment]
@spikespaz Please report it to the relevant Proton extension repo on Flathub (`Proton`, `Proton-Exp` or `Proton-GE`).
