### ISSUE TITLE
Steam black screen since few weeks - libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language

### ISSUE THREAD

**Issue by pieplu** [flathub/com.valvesoftware.Steam#834]
**System:** 
Arch Linux

**Flatpak info**

```
$ flatpak --version
Flatpak 1.12.2

$ flatpak --gl-drivers
host
default
```

When lauching with terminal:
```
flatpak run -v com.valvesoftware.Steam
```
I found this error:
```
./steamwebhelper: symbol lookup error: /usr/lib/x86_64-linux-gnu/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
```

![image](https://user-images.githubusercontent.com/3260285/142081288-7476ac52-ab36-4890-b045-e70020a679c0.png)

Looks like the same issue from streamNative: https://github.com/ValveSoftware/steam-for-linux/issues/7935

**Comment by nanonyme** [comment]
It's not same issue, that one is fixed. Consider filing a new issue.

**Comment by pieplu** [comment]
Looks like fixed by this action: https://github.com/ValveSoftware/steam-for-linux/issues/8269#issuecomment-985073503

**Comment by nanonyme** [comment]
Documented and linked from wiki that updating may fix this issue.
