### ISSUE TITLE
Dualsense gyro not working

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [flathub/com.valvesoftware.Steam#836]
using pacman to install steam and uisng the gyro in csgo (if it launches) works fine.
the flatpak version of steam launches cs:go every single time, so i use it now. 
I use the gryoscope on my controller to get more precise aim and it's not working.
What do I do to fix it?

**Comment by gasinvein** [comment]
Did you test with distro steam and flatpak steam installed at the same time? Controllers to work properly in steam flatpak usually require appropriate udev rules installed on host, which come with `steam` or `steam-devices` distro packages.

**Comment by Etaash-mathamsetty** [comment]
works great, and even works in RPCS3 now!
