### ISSUE TITLE
Non-ASCII input doesn't work.

### ISSUE THREAD

**Issue by nexfwall** [flathub/com.valvesoftware.Steam#84]
Non-ASCII input (Russian, in my case) seems to be not working. I've tried to send a message through Steam, but I can only type in English keyboard layout. Not in Russian.

Using Russian keyboard layout, only space and special characters working.

I've tested it on both Wayland and Xorg.

**Comment by pablodav** [comment]
could be related also to the fact that I can't open/save on directories that have non-english characters too? https://github.com/flathub/org.libreoffice.LibreOffice/issues/23#issuecomment-376446424 

is it some flatpak bug? some runtime bug?

**Comment by nexfwall** [comment]
I've installed `org.libreoffice.LibreOffice` on my machine, to test if issue is related to `org.freedesktop.Platform` somehow. But no, it's not related, because I can type non-English characters in LibreOffice.

![image](https://user-images.githubusercontent.com/8678891/40326352-a28102fa-5d47-11e8-933b-261e5d9b9e79.png)

I think my issue comes from that 6 year old piece of garbage, called "Ubuntu 12.04 Steam runtime".

**Comment by nexfwall** [comment]
And also, @pablodav, I **can** save file to the folder with non-Latin name (in Cyrillic) in LibreOffice.

**Comment by nexfwall** [comment]
Forgot to mention. My system is Fedora 28 Silverblue (AW).

**Comment by nexfwall** [comment]
I discovered, that the non-ASCII input not always doesn't work. It works sometimes. And sometimes games lose ability to accept input by unknown reason.

I've tried to play Starboard, and discovered that keys to control character doesn't work. But you can write to the chat, in any language. And after several restarts of the game, everything returned to normal.

This is strange.

**Comment by nanonyme** [comment]
Does this still break?

**Comment by nexfwall** [comment]
No, I can't reproduce it. At least for now.

Maybe it was some runtime issue and it's corrected by itself.

I'll close the issue then.
