### ISSUE TITLE
Steam crashes on first launch

### ISSUE THREAD

**Issue by gasinvein** [flathub/com.valvesoftware.Steam#842]
I've used Steam flatpak without such issues for a long time, but then accidentally wiped the `~/.var/app/com.valvesoftware.Steam` directory, and noticed that it sporadically crashes on sign-in window.

I can't yet figure out the exact pattern to reproduce it, so here are some observations I've made so far:

- When launched for the very first time, with non-existent `~/.var/app/com.valvesoftware.Steam` directory, it always crashes right after the sign-in Steam Client window is shown
- On subsequent runs, it doesn't always crash; It seem like it's more prone to crash if I move the cursor within the window or otherwise interact with it; if the windows is left alone, it doesn't seem to crash

**Comment by UsernameRandomlyGenerated** [comment]
I'm experiencing the same problem, though the login window crashes by itself after about 5 seconds for me. 
`~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steam.sh: line 794:   142 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
`

**Comment by gasinvein** [comment]
@UsernameRandomlyGenerated Does it still crash on subsequent launches if you don't interact with the sing-in windows (and don't even move the cursor above it)?

**Comment by UsernameRandomlyGenerated** [comment]
@gasinvein yeah, it will crash without me doing anything every single time

**Comment by gasinvein** [comment]
@smcv Hello. Do you have an idea how to debug Steam Client crashes like this?

**Comment by gasinvein** [comment]
FWIW I've managed to sign-in after Nth attempt and Steam doesn't crash for me anymore. But this is a deal breaker for new users.

**Comment by TheCultLeader666** [comment]
You using a VPN?

**Comment by gasinvein** [comment]
@TheCultLeader666 No, I don't.

**Comment by smcv** [comment]
> Do you have an idea how to debug Steam Client crashes like this?

I do not have access to source code or debug symbols for the proprietary parts of the Steam client. https://github.com/ValveSoftware/steam-for-linux/ is the place to reach people who do.

For crashes during startup, I would recommend providing all of the output that you get when running the Steam client from a terminal (GNOME Terminal, Konsole, xterm or equivalent): the more information you can provide, the more likely it is that someone in Valve can identify and fix a specific problem.

If you can get a stack trace from systemd-coredump, abrt, apport or your distro's equivalent, or by using gdb by hand, then that is probably also going to be useful information, even if it lacks debug symbols.

**Comment by nanonyme** [comment]
@gasinvein do we have instructions on how to prepare the app for using the DEBUGGER=gdb stanza with Steam? I can't recall if it requires more than just installing Sdk and using --devel when launching Steam.

**Comment by nanonyme** [comment]
In theory we should get something reasonable for stack trace from system since all binaries are built with minidebuginfo.

**Comment by gasinvein** [comment]
@nanonyme No, `flatpak run --devel --env=DEBUGGER=gdb com.valvesoftware.Steam` seems to work. Although for some reason gdb immediately exists after reaching breakpoint, unless steam was started from a shell inside the sandbox.

**Comment by gasinvein** [comment]
@smcv [Reported](https://github.com/ValveSoftware/steam-for-linux/issues/8286) this upstream with console output and backtrace.

**Comment by gasinvein** [comment]
Closing since this seems to be fixed upstream and doesn't reproduce for me anymore.
