### ISSUE TITLE
setup.sh missing when trying to launch steam

### ISSUE THREAD

**Issue by VihagChaturvedi** [flathub/com.valvesoftware.Steam#848]
Hello!

I recently re-installed the Steam Flatpak as the Steam RPM was giving me some issues

Distro: Fedora 35 (GNOME 41)

here is what happens when i try to run steam in terminal 

```
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/vihag/.var/app/com.valvesoftware.Steam
INFO:root:Overriding TZ to Asia/Kolkata
Running Steam on org.freedesktop.platform 21.08.5 64-bit
STEAM_RUNTIME is enabled automatically
internal error: /home/vihag/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/setup.sh is missing, this runtime is invalid or corrupted
```

**Comment by gasinvein** [comment]
Is it the first time you launch Steam flatpak?
Try renaming the `~/.var/app/com.valvesoftware.Steam` directory and launching Steam again.

**Comment by VihagChaturvedi** [comment]
Thank you so much for your response!

This indeed is happening when I launch Steam for the first time

Also, where do I rename the directory?

**Comment by gasinvein** [comment]
> where do I rename the directory?

What I meant is to try starting Steam with non-existent `~/.var/app/com.valvesoftware.Steam` directory, as if you didn't launch it before. You can also make a backup and remove it.

**Comment by VihagChaturvedi** [comment]
It works!

Thx a lot man, have the great rest of your day (^^)
