### ISSUE TITLE
No games starting on mutter 41.2 (wayland + nvidia gbm)

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.valvesoftware.Steam#849]
**Game information**
I haven't gotten any game to work

**Distribution name and version where applicable**
Fedora release 35 (Thirty Five)

**Flatpak info**
Flatpak 1.12.2

nvidia-495-44
default
host

**Also important**
Mutter: 41.2

**Problem description**
Games either do not start at all, or crash quickly into startup. Proton version does not seem to matter.

**Does this issue reproduce with native Steam**
Have not tested

**Comment by nanonyme** [comment]
Does it work if you launch Steam with --nosocket=wayland?

**Comment by alvarlagerlof** [comment]
No, I just get black windows and a whole lot of:

`Could not connect to X session manager: None of the authentication protocols specified are supported`

**Comment by gasinvein** [comment]
@alvarlagerlof  Does [this issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/2045) look related?

**Comment by alvarlagerlof** [comment]
I don't know how to check that, I am currently not getting anything more than black windows from all of Steam.

**Comment by protheory8** [comment]
Same thing but with 495.46 driver.
This error appears before getting "Game process removed" message in the terminal:
`wine: Unhandled page fault on read access` error.
Haven't tried launching any Linux native games. Also can reproduce the black screen issue, but it doesn't occur every time for me, so I made it through.

**Comment by gasinvein** [comment]
This doesn't seem specific to flatpak. I've played around a bit on clean VM with GPU passthrough (Fedora WS 35 guest): sporadically, Xwayland OpenGL apps show a black screen while Vulkan apps (including Proton games with DXVK) just crash. Occasionally, either of or both kinds launch successfully.
This behaviour observed with both flatpak and non-flatpak Steam Proton games, as well as with non-flatpak `glxspheres64` and `vkcube` utilities.

**Comment by gasinvein** [comment]
Mutter 41.3 was released, does it fix the issue?

**Comment by protheory8** [comment]
It does for me.

**Comment by protheory8** [comment]
But after a while it seems like it stops working again (and Firefox starts crashing)

**Comment by gasinvein** [comment]
Seems like [this](https://gitlab.gnome.org/GNOME/mutter/-/issues/2034) one. Do you see errors in `dmesg` at the time apps start to crash?

**Comment by protheory8** [comment]
> Do you see errors in `dmesg` at the time apps start to crash?

Didn't check. Also only Firefox crashes as far as I'm aware.

**Comment by gasinvein** [comment]
Does it still happen with Nvidia drivers 510.xx?

**Comment by tim77** [comment]
For me now it works with 510.xx. Have the same issue with old nvidia driver.

**Comment by alvarlagerlof** [comment]
Works for me now too. I've not had a game I coudln't launch that I expect to work.
