### ISSUE TITLE
POP_OS shop flatpack Steam doesn't recognize disk partitions

### ISSUE THREAD

**Issue by pogof** [flathub/com.valvesoftware.Steam#854]
I downloaded Pop_OS 21.10 few days ago and installed Steam through the shop. I have second SSD on which I created ntfs partition with disks. I wanted to add this partition as a main Library drive, however when I went to Options > Downloads > Add library folder I couldn't see it in /mnt/ or /media/ or whatever workaround I tried. It doesn't really recognize any file path changes.

Uninstalled and downloaded .deb package directly from steam website and I didn't even have to search for it the folder was already selected for me.

**Comment by nanonyme** [comment]
Did you read https://github.com/flathub/com.valvesoftware.Steam/wiki#I_want_to_add_external_disk_for_Steam_libraries?

**Comment by pogof** [comment]
In fact I did not and it was a big mistake. Whoops.

However that still begs the question, why do I have to read about this on pop shop page (which many people probably don't even bother to open, including me. I opened it only after I noticed that it's not working and still haven't read that!) or on the github page (where my seaching didn't take me as the error is not really flatpak specific)? I mean a notice on the window would be more sensible. "Using flatpak? you need to do THIS first" With clickable link.

**Comment by nanonyme** [comment]
Sorry but there is very limited scope of things we can do. We are mostly packaging upstream Valve Steam and shipping some missing dependencies. We cannot affect Steam GUI in any possible way. Link to the FAQ is intended to be visible on store front pages as we are exposing it through appstream data but we can't do much if it's not shown.

**Comment by pogof** [comment]
Yeah no worries. I find such issues unfortunate as Valve is trying to give Linux some traction. And then there's these things. Thanks!
