### ISSUE TITLE
Cannot use game library from an NFS mounted share

### ISSUE THREAD

**Issue by tsawhill** [flathub/com.valvesoftware.Steam#856]
**Game information**
Steam client - Trying to add game library

**Distribution name and version where applicable**

Manjaro Linux, Kernel 5.14.21-2

**Flatpak info**

Flatpak 1.12.2

nvidia-470-94
default
host

**Problem description**

Steam thinks the mounted NFS file system has no execute permissions. This drive is using an XFS file system.
![image](https://user-images.githubusercontent.com/60666614/149587845-90597e88-1a6b-412b-90c5-898f8c3d6a93.png)
![image](https://user-images.githubusercontent.com/60666614/149587873-0e4b528d-6900-4271-94f8-7531725184ee.png)

I have also tried to give full permissions to the library to eliminate any kind of user permissions issue, but it still will not accept the library.
![image](https://user-images.githubusercontent.com/60666614/149588487-c818a266-7947-4ffa-94ab-c51847852489.png)

**Does this issue reproduce with native Steam**

No, native steam takes this game library with no issue. 
![image](https://user-images.githubusercontent.com/60666614/149588740-8fa1566c-d7d7-4d4c-ac84-44d7981573c4.png)

**Comment by gasinvein** [comment]
Does it actually lack exec permission? Get a shell inside the sandbox (`flatpak run --command=bash com.valvesoftware.Steam`) and try running something on the filesystem, e.g.
```bash
echo '#!/bin/bash' > /mnt/gamelib/SteamLibrary/exec_test.sh
chmod +x /mnt/gamelib/SteamLibrary/exec_test.sh
/mnt/gamelib/SteamLibrary/exec_test.sh
```

**Comment by tsawhill** [comment]
> [📦 com.valvesoftware.Steam SteamLibrary]$ ./exec_test.sh
bash: ./exec_test.sh: Permission denied
[📦 com.valvesoftware.Steam SteamLibrary]$ ls -l
total 12
-rwxr-xr-x 1 trevor nfsnobody   12 Jan 17 01:34 exec_test.sh
-rwxrwxrwx 1 trevor nfsnobody   69 Nov 12 12:57 libraryfolder.vdf
drwxrwxrwx 8 trevor nfsnobody 4096 Jan 17 01:33 steamapps



It seems like it does actually lack the execute permission, but you can see there that execute permission bits are set. I am not too familiar with Flatpak, but based on what I see in the shell there should be execute permissions.

**Comment by gasinvein** [comment]
Ok, so this is pretty weird, and I couldn't reproduce it with a local NFS export. Can you please show your `/etc/exports`, and `mount | grep /mnt/gamelib` inside and outside the sandbox?

**Comment by tsawhill** [comment]
Sure thing. Here is the export for that share.

> "/mnt/disks/games" -async,no_subtree_check,fsid=203 192.168.2.69(rw,all_squash,anongid=1000,anonuid=1000)

From sandbox: 

>192.168.2.9:/mnt/disks/games/SteamLibrary on /mnt/gamelib/SteamLibrary type nfs4 (rw,nosuid,nodev,noexec,noatime,nodiratime,vers=4.2,rsize=8192,wsize=8192,namlen=255,hard,proto=tcp,timeo=14,retrans=2,sec=sys,clientaddr=192.168.2.69,local_lock=none,addr=192.168.2.9)

Outside sandbox:

> systemd-1 on /mnt/gamelib type autofs (rw,relatime,fd=53,pgrp=1,timeout=60,minproto=5,maxproto=5,direct,pipe_ino=20649)
192.168.2.9:/mnt/disks/games on /mnt/gamelib type nfs4 (rw,nosuid,nodev,noexec,noatime,nodiratime,vers=4.2,rsize=8192,wsize=8192,namlen=255,hard,proto=tcp,timeo=14,retrans=2,sec=sys,clientaddr=192.168.2.69,local_lock=none,addr=192.168.2.9,_netdev)

I gave Steam's sandbox access to the share this way:
![image](https://user-images.githubusercontent.com/60666614/149748893-b69a517c-8c3a-4b64-bf7b-41cbdb032c4e.png)

**Comment by gasinvein** [comment]
Well, the filesystem is mounted with `noexec` option, so it's expected to forbid execution. I wonder how it works in non-flatpak Steam (it shouldn't).

**Comment by tsawhill** [comment]
Yep that was it, thanks a bunch! I saw that too and started messing with some NFS mount options. The `user` option will enforce a `noexec` option as well. I went ahead and removed that option (not needed for my use case anyway) and was able to successfully use the mount. I guess my distro must have been working some magic with the mount for it to even work in the first place.

**Comment by gasinvein** [comment]
> The `user` option will enforce a `noexec` option as well.

Yep. To avoid this, you can set `user,exec` mount options.
