### ISSUE TITLE
Can you directly launch Steam games?

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [flathub/com.valvesoftware.Steam#86]
Hello,

Is there a syntax you can use to run an installed game directly instead of launching through Steam?

I was wanting to play with loading games into a ramdisk, and would rather not have the complication of needing to remember which was loaded when accessing the Steam library (mainly because I'm sure I'd become irritated in having to close and relaunch steam to switch games).

**Comment by TingPing** [comment]
You can do `flatpak run --command=/path/to/some/game/binary com.valvesoftware.Steam`

No guarantee that will generally work though since Steam does things like set up the runtime and all.

**Comment by nanonyme** [comment]
This will totally not work anymore given how many workarounds there are in the app entrypoint
