### ISSUE TITLE
Dota 2 tries to run under Proton instead of natively and fails

### ISSUE THREAD

**Issue by arielnmz** [flathub/com.valvesoftware.Steam#862]
**Game information**

Dota 2

**Distribution name and version where applicable**

Fedora release 34 (Thirty Four)

**Flatpak info**

Flatpak 1.10.5

nvidia-495-46
default
host

**Problem description**

Tried to run Dota2 today and a modal window warned about having to use a compatibility tool to run this game (?) went back to the options and no compatibility tool was selected. This game is supposed to have a native linux version. 

I figured I might need an update, so I updated my flatpak packages (including steam) and it now complains about not being able to run in Flatpak 1.10:

> pressure-vessel-wrap[465]: E: pressure-vessel (SteamLinuxRuntime) cannot be run in Flatpak 1.10.x or older. For Proton 5.13+, unofficial community builds that do not use pressure-vessel are available.

I think the main two questions are:

1. Why did it suddenly try to use a compat tool (proton?) to run this game?
2. Why is it not running the native version of the game?

I'm not trying to run this game under proton, I don't need proton.

**Does this issue reproduce with native Steam**
~Have not tested~
Just tried using the native steam client (installed via dnf) and Dota runs fine. It did ask about using a compat tool too, though

**Comment by arielnmz** [comment]
I was wrong, it's trying to run Dota through Steam Play (not proton) 

![image](https://user-images.githubusercontent.com/24735547/151886902-f3daef6f-deb2-43aa-8028-972d9fd089f4.png)

But still, up until yesterday I didn't need any compat tool to run this game

**Comment by nanonyme** [comment]
I suggest updating to to Fedora 35 with sufficiently new flatpak. More and more games games are expected to end up needing preasure-vessel.

**Comment by nanonyme** [comment]
New major releases of Steam runtime are going to require preasure-vessel for what I've understood.

**Comment by arielnmz** [comment]
Dang it. Sticking to the native client for now then.

**Comment by stacyharper** [comment]
I'm not sure why this issue has been closed. Dota 2 still doesnt start on flatpak cause of the migration to the Steam Linux Runtime container. This leave distributions without native steam recipes as Alpine unable to start the game.

Looking at the whole context, it looks like flatpak now offers ways to use this kind of container environment. What is the state of the Steam Linux Runtime integration in flatpak ? What is the state of Dota 2 on other distributions (with or without flatpak) ?

**Comment by nanonyme** [comment]
Container Steam Runtime now has been already for some time been working out of the box assuming you have flatpak using bubblewrap with user namespaces and new enough stack.

**Comment by stacyharper** [comment]
Okay so something isnt working in an Alpine environment. Dota 2 still dont run and I just tried Portal 2 with Steam Linux Runtime and I have a similar issue.

It looks like my system meet thoses checks : https://github.com/flatpak/flatpak/wiki/User-namespace-requirements#unprivileged-bubblewrap

What should I check ?

**Comment by stacyharper** [comment]
Okay the issue may be that we dont have user namespaces on Alpine Linux kernels. I'll try to build a kernel with.

**Comment by stacyharper** [comment]
Edito: we have user namespace with the Alpine Linux Kernels. What we dont have, and will never have is the kernel patch that allow unpriviliged users to use them : https://github.com/archlinux/svntogit-packages/blob/packages/linux-lts/trunk/0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch

What are other ways to make games using the Steam Linux Runtime with un unpatched kernel ?

**Comment by stacyharper** [comment]
I tried to use the suid way :

```
--share-pids not supported by host portal

This feature requires Flatpak to be using a bubblewrap (bwrap) executable
that is not setuid root.

The non-setuid version of bubblewrap requires a kernel that allows
unprivileged users to create new user namespaces.

For more details please see:
https://github.com/flatpak/flatpak/wiki/User-namespace-requirements
```

It looks like a dead end

**Comment by stacyharper** [comment]
I've just build a patched kernel with this  kernel/unprivileged_userns_clone argument. I now have `/proc/sys/kernel/unprivileged_userns_clone = 1` but the issue remains. I got no other clues to chase :(

**Comment by nanonyme** [comment]
That failing opendir sounds suspicious. Might want to create separate report about that.

**Comment by stacyharper** [comment]
You talk about `/var/lib/flatpak/repo` ? I use a user scope and start steam with `flatpak --user run com.valvesoftware.Steam`

That could explain the issue ?
