### ISSUE TITLE
Steam Link: Controller access in non-Steam games?

### ISSUE THREAD

**Issue by falk4243** [flathub/com.valvesoftware.Steam#864]
**Game information**
 

Any non-Steam title run via Steam Link (Android app)

**Distribution name and version where applicable**
 

Debian 11.2

**Flatpak info**
 

1.12.4 (default, host)

**Problem description**

I'd like to use a gamepad for some non-Steam titles run via Steam Link, but the controller isn't visible at all outside of Steam. Not a big surprise when using the flatpak version, but is there any way to enable games outside of Steam (e.g. Dolphin, Retroarch) to access the controller (connected to the client) or do I have to use the official Debian version for that scenario?

**Does this issue reproduce with native Steam**

No, since the native Steam version registers the controller as an input device that can then be found by non-Steam titles.

**Alternatives I'd rather not use:**

Running Steam via distro package: This would make the controller available to other apps as well, but I'd really like to avoid using the "official" Debian package; it's cluttered, requires i386 arch and is potentially less secure than the flatpak version.

Connecting the controller to the host: A better option, though not great to have to switch back and forth between the Steam host PC and client device, or not possible at all when connecting from a remote location.

Starting apps via Steam: This would work, but probably require to open up the sandbox as far as possible to be able to start another flatpak app. Using "filesystem=host" prevents Steam from starting at all in any case.

Using Virtual Here: A bit less of a hassle compared to physically connecting the controller, but still requires switching back and forth.

**Tentative Solution (less secure) -**

I could replicate (a reddit user's) finding that the Steam virtual input device work with flatpaks, but only after installing Steam (distro) and (probably more correct) the steam-devices pkg. Uninstalling Steam (distro) and rebooting, flatpak Steam gave a warning that the steam-devices package wasn't installed and to expect problems with certain controllers. It also linked the flathub Steam wiki page which pretty much said the same and also stated that /dev/uinput needs to be rw for the user. Since steam-devices requires the whole steam installation, I went with the approach from the Sunshine (Gamestream for non-NVidia cards) page, which made the virtual device accessible again.

Create udev rules:

1. Run the following command: nano (vim, etc) /etc/udev/rules.d/85-sunshine-input.rules 
2. Input the following contents: KERNEL=="uinput", GROUP="input", MODE="0660"

Source: https://github.com/loki-47-6F-64/sunshine

**Comment by falk4243** [comment]
**Better solution -**

As (a reddit user) pointed out, there is a less generic (and thus safer) approach by installing the necessary (Microsoft in this case; or all) udev rules listed at

https://gitlab.com/fabiscafe/game-devices-udev

**Comment by nanonyme** [comment]
Right, flatpak apps cannot register udev rules
