### ISSUE TITLE
Symlinks on homefolder preventing launch

### ISSUE THREAD

**Issue by Willdrick** [flathub/com.valvesoftware.Steam#868]
My root drive is a smaller SSD so I symlink the "heavyweight" folders from a separate HDD, that way I keep the snappiness of loading my session quickly (reading dotfiles off the SSD) while having heavier stuff like movies, music and downloads on a slow drive.

When launching Steam as a flatpak, I get `bwrap: Can't make symlink at /home/willdrick/Imágenes: File exists` preventing the launch of the application.

Is there a way I can have steam ignore these? Or maybe a workaround where I can manually tell flatpak steam where those folders are, without interfering with my current symlinks.

 I'm not planning on saving my screenshots to `~/Pictures` nor playing my local music from `~/music` anyway

**Comment by nanonyme** [comment]
--nofilesystem=xdg-pictures and --nofilesystem=xdg-music might help for original problem
