### ISSUE TITLE
Fails to start if Music folder is symlink or mounted with --bind

### ISSUE THREAD

**Issue by luksireiku** [flathub/com.valvesoftware.Steam#87]
Can't run it right now because my music folder is in another drive, neither symlinking it or mounting it with --bind

**Comment by TingPing** [comment]
This is a Flatpak bug: https://github.com/flatpak/flatpak/issues/1275

Site note you symlinking your music dir is the wrong solution anyway. Run `xdg-user-dirs-update --set MUSIC /some/custom/path`

**Comment by ioogithub** [comment]
I have tried this solution, it does not work. I get the same result after running the recommended command.
