### ISSUE TITLE
Dota 2 crashes

### ISSUE THREAD

**Issue by aboss10123** [flathub/com.valvesoftware.Steam#877]
~ flatpak --version
Flatpak 1.12.4
 ~ flatpak --gl-drivers
default
host
 ~ uname -r
5.16.6-gentoo
 ~
Dota 2 crashes and does not open using the flatpak version of steam however this is not the case with the non-flatpak version.

**Comment by stacyharper** [comment]
Probably related to https://github.com/flathub/com.valvesoftware.Steam/issues/862

**Comment by nanonyme** [comment]
Probably not.

**Comment by shuriken1812** [comment]
This issue can be closed :+1:
