### ISSUE TITLE
Error: You are missing the following 32-bit libraries, and Steam may not run: libc.so.6

### ISSUE THREAD

**Issue by KrychaTech** [flathub/com.valvesoftware.Steam#878]
Output of flatpak run com.valvesoftware.Steam:
`INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/krystian/.var/app/com.valvesoftware.Steam
DEBUG:root:Checking input devices permissions
WARNING:root:Missing permissions for input devices
INFO:root:Overriding TZ to Europe/Warsaw
steam.sh[2]: Running Steam on org.freedesktop.platform 21.08.11 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
setup.sh[74]: Steam runtime environment up-to-date!
steam.sh[2]: Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
steam.sh[2]: Can't find 'steam-runtime-check-requirements', continuing anyway
/home/krystian/.var/app/com.valvesoftware.Steam/.local/share/Steam/steam.sh: line 788: /home/krystian/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam: cannot execute binary file: Exec format error
`

using the beta branch with all the requirements installed, and the solution from https://github.com/flathub/com.valvesoftware.Steam/issues/805 still repeats.
I am running elementaryOS 6.1 with intel graphics.

The issue **does** reproduce with native steam.

**Comment by nanonyme** [comment]
I suggest installing stable as well, that is the simplest way to fix deps. Installing from beta will not result in correctly functioning app without manually installing some deps.

**Comment by KrychaTech** [comment]
the same error occurs in the stable branch too.

**Comment by nanonyme** [comment]
@gasinvein btw, let's add steam-runtime-check-requirements into app that will ensure you have all required extensions present.

**Comment by gasinvein** [comment]
> @gasinvein btw, let's add steam-runtime-check-requirements into app that will ensure you have all required extensions present.

We can just look for required extensions in `/.flatpak-info`, can't we?

**Comment by nanonyme** [comment]
True. So maybe we could ship script that does true here to suppress the warning.

**Comment by KrychaTech** [comment]
So i see you working on the issue. should i close this one

**Comment by nanonyme** [comment]
@KrychaTech it won't fix your problem but it will make certain error scenario easier for end-user to see

**Comment by KrychaTech** [comment]
okay, but is there a fix to my problem or do i need to just wait for an update?

**Comment by gasinvein** [comment]
@KrychaTech Installing `org.freedesktop.Platform.Compat.i386//21.08` will most likely fix your problem. The actual issue here seems that it wasn't installed automatically.

**Comment by darltrash** [comment]
happens to me right now
