### ISSUE TITLE
Vulkan or dxvk games don't launch.

### ISSUE THREAD

**Issue by tati1454** [flathub/com.valvesoftware.Steam#888]
**Game information**
Ultrakill, Grand Theft Auto V, Black Mesa and all games running with dxvk or vulkan.

**Distribution name and version where applicable**
Fedora Linux 35 (KDE Plasma) x86_64

**Flatpak info**
Flatpak 1.12.7

```
$ flatpak --gl-drivers
default
host
```

**Problem description**
It looks like that dxvk or proton does't detect the vulkan installation.

Log from Black Mesa using proton:
[steam-362890.log](https://github.com/flathub/com.valvesoftware.Steam/files/8401116/steam-362890.log)

**Does this issue reproduce with native Steam**
No

**Comment by tati1454** [comment]
Woops sorry I forget to answer. I have the integrated GPU from an inte core i3 6100.

Btw, now it works I'm not sure what happened.

**Comment by Meister1593** [comment]
> Woops sorry I forget to answer. I have the integrated GPU from an inte core i3 6100.
> 
> Btw, now it works I'm not sure what happened.

there was update not long ago, it might have fixed it

**Comment by pm4rcin** [comment]
I'm on DWL(Wayland wlroots 0.15.1) with nvidia 510.68.02 as PRIME and I've tried Proton 7.0-2 and Proton experimental but it doesn't work.

**Comment by Lctrs** [comment]
@pm4rcin Do you have `org.freedesktop.Platform.GL.nvidia` installed via flatpak ? Do you have the package `xdg-desktop-portal-wlr` installed on your host ?

**Comment by pm4rcin** [comment]
> @pm4rcin Do you have `org.freedesktop.Platform.GL.nvidia` installed via flatpak ? Do you have the package `xdg-desktop-portal-wlr` installed on your host ?

Yes I have both installed but no luck.

**Comment by pm4rcin** [comment]
> I have the same issue with the same error in the Proton log on Fedora 36 with an Nvidia GPU (510.68.02).
> 
> **Flatpak info** Flatpak 1.12.7
> 
> ```
> flatpak --gl-drivers
> nvidia-510-68-02
> default
> host
> ```
> 
> **Problem description** Log from launching Elden Ring with Proton: [steam-1245620.log](https://github.com/flathub/com.valvesoftware.Steam/files/8740382/steam-1245620.log)
> 
> Weirdly, the problem _disappears_ when launching Steam from the terminal using `flatpak run ...` -- either with or without the extra arguments specified in `Exec` of com.valvesoftware.Steam.desktop.

You have GE-Proton installed and that's the biggest difference from my environment. I have installed it with flatpak and the game starts with no problem when I selected that. Probably official Protons have some problems with flatpak's Sandbox. The game tested was Portal 2 with `-vulkan` parameter.

**Comment by BartleyTheShopkeeper** [comment]
> I have the same issue with the same error in the Proton log on Fedora 36 with an Nvidia GPU (510.68.02).
> 
> **Flatpak info** Flatpak 1.12.7
> 
> ```
> flatpak --gl-drivers
> nvidia-510-68-02
> default
> host
> ```
> 
> **Problem description** Log from launching Elden Ring with Proton: [steam-1245620.log](https://github.com/flathub/com.valvesoftware.Steam/files/8740382/steam-1245620.log)
> 
> Weirdly, the problem _disappears_ when launching Steam from the terminal using `flatpak run ...` -- either with or without the extra arguments specified in `Exec` of com.valvesoftware.Steam.desktop.

Did you try launching Vulkan/DXVK games in another flatpak based program, like the Lutris flatpak beta?

I am running Silverblue with the same drivers as you, and it is affecting all my flatpak programs for around a week.

**Comment by LordKordus** [comment]
I also experience this issue, can confirm the problem disapears if launched through terminal with `flatpak run com.valvesoftware.Steam`. Created my own shortcut for now.

@BartleyTheShopkeeper Lutris works, although from a specific version, I had to manually set it to use the dedicated GPU from advanced settings.

Fedora Silverblue 36, laptop - Intel+Nvidia.

**Comment by salva09** [comment]
> I have the same issue with the same error in the Proton log on Fedora 36 with an Nvidia GPU (510.68.02).
> 
> **Flatpak info** Flatpak 1.12.7
> 
> ```
> flatpak --gl-drivers
> nvidia-510-68-02
> default
> host
> ```
> 
> **Problem description** Log from launching Elden Ring with Proton: [steam-1245620.log](https://github.com/flathub/com.valvesoftware.Steam/files/8740382/steam-1245620.log)
> 
> Weirdly, the problem _disappears_ when launching Steam from the terminal using `flatpak run ...` -- either with or without the extra arguments specified in `Exec` of com.valvesoftware.Steam.desktop.

The problem disappears when launching it from the terminal because it is using the integrated graphics, the problem occurs only when launching steam with prime render offload, being the default case in Fedora Gnome.

I have the same problem, and what I do is right clicking steam and select Launch using Integrated Graphics Card

**Comment by gcampax** [comment]
This might be related to https://gitlab.freedesktop.org/hadess/switcheroo-control/-/issues/30 - namely, the set of environment variables set by GNOME to force the Nvidia GPU was changed recently and broke Vulkan support in Flatpak apps. This was fixed upstream, so it should be solved with a new release of switcheroo-control.

**Comment by QushyQushy** [comment]
I have the same problem on an AMD 6800XT. I tried Steam Flatpak on Gentoo and Alpine. In both Vulkan fails to be loaded.

**Comment by ljmc2000** [comment]
@QushyQushy That's from flathub beta not enabling the beta channel within steam, right?

**Comment by QushyQushy** [comment]
> @QushyQushy That's from flathub beta not enabling the beta channel within steam, right?

Yes, Flathub Beta.

**Comment by nanonyme** [comment]
freedesktop-sdk 22.08 is now out as is version of this app that uses it. Please run flatpak update to get working version of this app.

**Comment by Ayush1325** [comment]
Hi everyone, I am still having the same problem. I get a black screen when launching a game in Proton. It happens only when launching steam on a discrete GPU.

System Info:
CPU: AMD Ryzen 5 4600H with Radeon Graphics   
GPU: NVIDIA GeForce GTX 1650 Ti
Driver Version:  4.6.0 NVIDIA 515.65.01
Flatpak Version: 1.12.7
Steam Version: 1.0.0.74 (Flathub beta)

Using Bottles with discrete GPU seems to work fine. The specific game I am trying to launch is [The House in Fata Morgana](https://www.protondb.com/app/303310).

**Comment by BartleyTheShopkeeper** [comment]
> Hi everyone, I am still having the same problem. I get a black screen when launching a game in Proton. It happens only when launching steam on a discrete GPU.
> 
> System Info: CPU: AMD Ryzen 5 4600H with Radeon Graphics GPU: NVIDIA GeForce GTX 1650 Ti Driver Version: 4.6.0 NVIDIA 515.65.01 Flatpak Version: 1.12.7 Steam Version: 1.0.0.74 (Flathub beta) OS: Fedora Silverblue 36
> 
> Using Bottles with discrete GPU seems to work fine. The specific game I am trying to launch is [The House in Fata Morgana](https://www.protondb.com/app/303310). I also tried XOrg to see if it was a Wayland problem, but no-luck on XOrg either.

I ended up abandoning Silverblue, returning to Fedora Workstation, and simply finding the issue persists with flatpaks. Ultimately, I did find a fix. Use flatseal and add a custom environmental variable to Steam and everything else you use your Nvidia card for:

`VK_ICD_FILENAMES=/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json`

**Comment by Ayush1325** [comment]
> I ended up abandoning Silverblue, returning to Fedora Workstation, and simply finding the issue persists with flatpaks. Ultimately, I did find a fix. Use flatseal and add a custom environmental variable to Steam and everything else you use your Nvidia card for:
> 
> `VK_ICD_FILENAMES=/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json`

Well, that path does not seem to exist in my silverblue. I did try setting 

`VK_ICD_FILENAMES=/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-515-65-01/x86_64/1.4/active/files/vulkan/icd.d/nvidia_icd.json:/var/lib/flatpak/runtime/org.freedesktop.Platform.GL32.nvidia-515-65-01/x86_64/1.4/active/files/vulkan/icd.d/nvidia_icd.json`

but that does not work either. I don't really play many games (other than vn), so using integrated GPU isn't much of a problem for me, but this still sucks.

**Comment by nanonyme** [comment]
@Ayush1325 FWIW the paths are not supposed to exist in your Silverblue, they are paths inside the sandbox.

**Comment by nanonyme** [comment]
@BartleyTheShopkeeper please open a bug at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues if icd files aren't being read out of the box on freedesktop-sdk 22.08.

**Comment by Ayush1325** [comment]
> @Ayush1325 FWIW the paths are not supposed to exist in your Silverblue, they are paths inside the sandbox.

Ok, tried `VK_ICD_FILENAMES=/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json` but still no luck. I can see the new value in Steam System Information, so at least that has been set properly. But still getting black screen.

**Comment by Hairo** [comment]
I'm having the same issue with other flatpak apps too (bottles and lutris), seems to be flatpak related.

**Comment by j0hax** [comment]
I'm also on Silverblue (37 Beta) and experiencing problems with Vulkan games. Setting `PROTON_USE_WINED3D=1 %command%` is the only way to get my games working (albeit without the performance benefits of Vulkan)

Would it be possible to re-open this issue, seeing it still affects people?

**Comment by nanonyme** [comment]
Don't resurrect old cases, file a new one if you have a new problem.
