### ISSUE TITLE
Steam Flatpak fails to run on Fedora 36 Workstation

### ISSUE THREAD

**Issue by CharDSonDev** [flathub/com.valvesoftware.Steam#889]
**Operating System:** Fedora 36 Workstation
**Package:** Steam Flatpak

After installing Steam Flatpak, it shows the following windows and never runs.

![Screenshot from 2022-04-04 17-40-20](https://user-images.githubusercontent.com/36754778/161639763-7fb7cec3-e3eb-4532-a30f-8fee0c768e29.png)
![Screenshot from 2022-04-04 17-40-27](https://user-images.githubusercontent.com/36754778/161639761-311494ee-3d7e-4f60-ae37-f33271df79ec.png)

Previously, I had installed it on this same operating system, and it did not show any problems.

I have the necessary runtimes for running Steam installed

![Screenshot from 2022-04-04 17-53-39](https://user-images.githubusercontent.com/36754778/161640298-b1f4468d-d813-4a48-be1b-ee98bb1707e9.png)

**Comment by TheFlagCourier** [comment]
Cannot reproduce. Performed a fresh, default, installation on top of Fedora Kinoite 36. It worked right out of the box. Had you tried [checking the wiki](https://github.com/flathub/com.valvesoftware.steam/wiki#libso6_cannot_be_found)?

**Comment by CharDSonDev** [comment]
I didn't know this problem was documented in the Wiki, thanks for commenting.
