### ISSUE TITLE
Missing bluetooth requirement for Steam Controller

### ISSUE THREAD

**Issue by ananace** [flathub/com.valvesoftware.Steam#89]
With the new Steam Controller over Bluetooth update available, the Steam client requires the - equally new - `--allow=bluetooth` Flatpak option to support using said controller.

**Comment by nanonyme** [comment]
The PR was reverted due to excessive amount of issues. Let's try to re-enable later

**Comment by ananace** [comment]
Understandable, guess that for now people will just have to do with manually overriding it in case they need it.  
`flatpak override com.valvesoftware.Steam --allow=bluetooth` - for reference

**Comment by nanonyme** [comment]
Looks like we can re-enable it, just needs to be well documented that support for 0.10.2 and older is dropped

**Comment by nanonyme** [comment]
Note the root issue is eg Ubuntu isn't shipping 0.10.3 which is a bugfix to their Flatpak. 0.10.4 even exists

**Comment by nanonyme** [comment]
@ananace oops; hit https://github.com/flatpak/flatpak/issues/1935 while trying to make things work nicely

**Comment by nanonyme** [comment]
Ok. There's now significantly large audit trail about this. Let's use local overrides for now and keep this ticket open as a reminder

**Comment by nanonyme** [comment]
I think we're closing the point where we can say Flatpak 1.0.0 recommended, 0.11.3 required and enable this.

**Comment by nanonyme** [comment]
Note #8 probably needs handling to make the experience more friendly

**Comment by nanonyme** [comment]
This will most likely be enabled by default somewhere 2019Q1 when Debian 10 has been released

**Comment by nanonyme** [comment]
Closing as implemented.
