### ISSUE TITLE
Steam Games using LLVM instead of GPU

### ISSUE THREAD

**Issue by Hero9909** [flathub/com.valvesoftware.Steam#894]
**General**
Issues are present since the upgrade of drivers and kernel. I'll update if I can present the old version numbers of the driver and kernel when everything worked.
for now, I'm running kernel 5.16.20-200.fc35.x86_64 with the Nvidia driver from down below.

**Distribution name and version where applicable**
Fedora Linux 35 (Workstation Edition)

**Flatpak info**
  $ flatpak --version
  Flatpak 1.12.7

  $ flatpak --gl-drivers
  nvidia-510-60-02
  default
  host

**Problem description**
launching any game is fine, but all using the llvm render pipeline instead of the GPU

**Does this issue reproduce with native Steam**
Have not tested

**Additional**
ive checked hw support, default renderer, driver, kernel mod, secure-boot, driver-usage, and installed Cuda drivers to validate against nvidia-smi. native games working fine (tried factorio, validated via nvidia-smi) therefore I assume that the driver is running fine and native usable.

I'm happy for any suggestion to debug this further, especially detecting the driver and GPU presence in flatpak.

**Comment by Hero9909** [comment]
a new version of the org.freedesktop.Platform.GL.nvidia-510 runtime appeared, ill update and report back

**Comment by Hero9909** [comment]
updated and checkt twice for other updates, but this one slipped through. 

still was my fault, updating like always is the solution.

**Comment by nanonyme** [comment]
We actually have a bug open about nVidia not properly fallbacking to software rendering at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/350 when proper extension is not present. Can you confirm it now works?

**Comment by Hero9909** [comment]
Yes, it worked pretty well, if you had the goal to run steam via llvm. Steam and all games are tried to run with llvm. Ive tested with PathOfExcile- not starting, factorio-lagging as hell and hammerwatch- 7fps.

Looking back, i would prefere a message to warn against this situation as no normal user could solve this. For forcefully running on llvm maybe an env var would be nice.

Did this answer your issues and question?
