### ISSUE TITLE
No option to add Steam Libraries in Flatpak version

### ISSUE THREAD

**Issue by RuisSoftware** [flathub/com.valvesoftware.Steam#899]
**Game information**
It's for all games in the Steam Flatpak version.

**Distribution name and version where applicable**
Ubuntu 2022.04 LTS

**Flatpak info**
Flatpak 1.12.7
nvidia-510-60-02
default
host

**Problem description**
I can't add any new library so Steam installs all games to my main disk. I don't have enough space left so i have to use my secondary ssd, but i can't add it.
![afbeelding](https://user-images.githubusercontent.com/53178920/166258127-d214434b-5ea3-40d6-97d4-b067ea03888d.png)

**Does this issue reproduce with native Steam**
No, the native version works fine on this issue. I can add libraries on all my disks.

**Comment by nanonyme** [comment]
Did https://github.com/flathub/com.valvesoftware.Steam/wiki#I_want_to_add_external_disk_for_Steam_libraries not work for you?

**Comment by RuisSoftware** [comment]
> Did https://github.com/flathub/com.valvesoftware.Steam/wiki#I_want_to_add_external_disk_for_Steam_libraries not work for you?

The command doesn't change anything and i don't have any settings option from https://help.steampowered.com/nl/faqs/view/4BD4-4528-6B2E-8327

**Comment by RuisSoftware** [comment]
This picture is taken from the native Steam app. this one does have the Move install folder option, but Flatpak not. Also not after using 
flatpak override --user --filesystem=/mnt/1TB_SSD com.valvesoftware.Steam

![afbeelding](https://user-images.githubusercontent.com/53178920/166261999-ba19f3ce-ef23-4974-9e1f-d1f26f04759c.png)

I want to use the Flatpak version because here Planet Zoo works. On native i can't get Planet Zoo working

**Comment by RuisSoftware** [comment]
I found out that the flatpak version removes the Settings option in family mode. It's all good after the command from above.
