### ISSUE TITLE
XCOM2 - Fails to start

### ISSUE THREAD

**Issue by jimmiebtlr** [flathub/com.valvesoftware.Steam#9]
First off thanks for taking the time to put it in flatpak format!

Getting the following errors when trying to start xcom2

```
>>> Adding process 182 for game ID 268500
>>> Adding process 184 for game ID 268500
/home/jimmie/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/XCOM 2/bin/XCOM2: relocation error: /home/jimmie/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/XCOM 2/bin/../lib/x86_64/libcef.so: symbol snd_rawmidi_info_sizeof, version ALSA_0.9 not defined in file libasound.so.2 with link time reference
```

uname -a
`Linux linux-5hk9.suse 4.4.70-18.9-default #1 SMP Wed May 31 09:09:25 UTC 2017 (c1231a7) x86_64 x86_64 x86_64 GNU/Linux`

zypper search libasound
```
i | libasound2       | Advanced Linux Sound Architecture-> | package
i | libasound2-32bit | Advanced Linux Sound Architecture-> | package
```

**Comment by jimmiebtlr** [comment]
Definitely don't have the system specs for this

**Comment by TingPing** [comment]
I'll keep this open as we can still solve this.

**Comment by alexlarsson** [comment]
We do have libasound, we just don't have the debian added version symbols in it...
Why is it not picking up libasound from the runtime though?

**Comment by TingPing** [comment]
@jimmiebtlr An update was pushed that *may* help this, could you please test it?

**Comment by valentindavid** [comment]
I have the same problem with Dirt Rally.

```
/home/steam_files/steamapps/common/DiRT Rally/bin/DirtRally: relocation error: /home/steam_files/steamapps/common/DiRT Rally/bin/../lib/x86_64/libcef.so: symbol snd_rawmidi_info_sizeof, version ALSA_0.9 not defined in file libasound.so.2 with link time reference
```

It works when I manually force the Steam runtime.

I do not think it is Debian specific thing to have versioning of symbols for libasound. My host is Gentoo and also has that.

**Comment by valentindavid** [comment]
`org.freedesktop.Platform` has versioning, just symbols related to midi are missing. Maybe a "--with" is missing in the `configure`?

**Comment by TingPing** [comment]
XCOM 2 runs here but results in GL errors rendering a blank window (Nvidia drivers).

**Comment by valentindavid** [comment]
This pull requests fixes Dirt Rally. I am downloading XCOM2. I will try it tomorrow.

**Comment by valentindavid** [comment]
XCOM2 works for me with nvidia through Steam through Flatpak. Just with the fix from the pull request.

**Comment by valentindavid** [comment]
Should not this issue be closed?
