### ISSUE TITLE
Replace --socket=x11 permission with --socket=fallback-x11

### ISSUE THREAD

**Issue by rugk** [flathub/com.valvesoftware.Steam#901]
The GNOME Software considers applications requiring x11 as unsafe. There's a way to declare it uses Wayland, but can use X11 as a fallback, on desktop environments where Wayland doesn't run.

More info here:
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/770#note_1136536

copied from https://github.com/flathub/org.gnome.Evolution/issues/49

**Comment by nanonyme** [comment]
Blocked by https://github.com/ValveSoftware/steam-for-linux/issues/4924

**Comment by doraskayo** [comment]
@gasinvein described the problem in doing this in https://github.com/flathub/com.valvesoftware.Steam/pull/902#issuecomment-1125862756, which is why it will likely never happen. This issue can probably be closed.
