### ISSUE TITLE
Cyberpunk 2077 does not launch under Proton Experimental

### ISSUE THREAD

**Issue by thatLeaflet** [flathub/com.valvesoftware.Steam#910]
**Game information**
Cyberpunk 2077

**Distribution name and version where applicable**
Fedora 36

**Flatpak info**
flatpak --version:
Flatpak 1.12.7

flatpak --gl-drivers:
default

**Problem description**
Cyberpunk 2077 does not launch when using Proton Experimental and the Steam Flatpak. It does work under Proton 7.0-2. The game does manage to load the launcher, but not the actual game itself.

**Does this issue reproduce with native Steam**
This issue is not reproducible with the native Steam packaging, the game launches under Proton Experimental.

[Log](https://github.com/flathub/com.valvesoftware.Steam/files/8844498/Launch.Cyberpunk.with.Experimental.and.Flatpak.txt)

**Comment by nanonyme** [comment]
Probably won't work until freedeskto-sdk 22.08 release. We will switch beta branch of this app runtime's beta branch once available.

**Comment by 1player** [comment]
Indeed Proton Experimental now requires mesa 22: https://github.com/ValveSoftware/Proton/wiki/Changelog

You can try running the mesa-git flatpak, as described here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/Mesa-git

Make sure you apply the sub-sandboxing "hack" described at the bottom of the page, it is **not** optional but required with mesa-git or some games will break. In fact, their recommendation of using `systemctl --user set-environment` will be reset after boot, so I suggest you doing this:

```
$ echo FLATPAK_GL_DRIVERS=mesa-git > $HOME/.config/environment.d/50-flatpak-gl-drivers.conf
```

And rebooting the system for it to take effect.

--

@nanonyme could you please update the wiki page with my recommendation above? (I don't think I can send a merge request to update it myself) 

And are there any plans to decouple the Steam flatpak from the freedesktop SDK mesa, so we can avoid this situation that the flatpak stays partially broken until the new sdk is released once a year?

**Comment by nanonyme** [comment]
This was not a common case. Mesa 22.0 drops support for a lot of hardware in addition to requiring ABI forward break in runtime. Since it's not feasible to test it with  involved physical hardware, Mesa amber was not considered an acceptable solution. This was a one-time thing that hasn't happened in last ten years.

**Comment by thatLeaflet** [comment]
I tried the mesa-git, but Cyberpunk still didn't launch. I don't think this is related to the Mesa 22 requirement as only Cyberpunk stopped launching for me on Experimental. All other games I tried still ran, such as Fallout 76 and Mass Effect Legendary Edition.

I didn't follow the instructions exactly because I didn't want to make the changes persistent without first checking the game launched correctly, so this is what I ran in my terminal

1. [added repo and installed GL.mesa-git and Gl32.mesa-git]
2. FLATPAK_GL_DRIVERS=mesa-git (also tried export FLATPAK_GL_DRIVERS=mesa-git)
3. systemctl --user restart flatpak-portal.service
4. FLATPAK_GL_DRIVERS=mesa-git flatpak run com.valvesoftware.Steam

I confirmed through Steam's "System Information" tab that I was using mesa-git and I was. But no game I tried launch correctly, so maybe I messed something up on the sandboxing front.

**Comment by nanonyme** [comment]
mesa-git doesn't work with upstream Proton.

**Comment by nanonyme** [comment]
Since freedesktop-sdk 22.08beta.2 is now out, you can try https://github.com/flathub/com.valvesoftware.Steam/wiki/Using-beta-branch-of-this-app

**Comment by QushyQushy** [comment]
The game still doesn't work with the regular or mesa-git drivers neither in Proton Experimental or Proton 7 on the beta branch of Steam Flaptak.

Specs:
Alpine Linux
5900HX
6800M
64 GBs of RAM

Every other game works flawlessly including EAC titles.

**Comment by nanonyme** [comment]
Please retry with latest stable. freedesktop-sdk 22.08 comes with newer Mesa.

**Comment by thatLeaflet** [comment]
Cyberpunk now launches correctly.
