### ISSUE TITLE
mesa-git not recognized by steam_wrapper.py

### ISSUE THREAD

**Issue by Big-FG** [flathub/com.valvesoftware.Steam#912]
This PR here https://github.com/flathub/com.valvesoftware.Steam/pull/879 added a check for i386 extension, but it doesnt include mesa-git as a valid extension so complains every launch asking for **org.freedesktop.Platform.GL32.default** even though everything is technically fine as its provided by org.freedesktop.Platform.GL32.mesa-git

This isnt a major issue and mostly a minor annoyance that could be fixed by simply adding mesa-git to the ones it checks for

 ```
   for ext_id in ["org.freedesktop.Platform.Compat.i386",
                   "org.freedesktop.Platform.GL32.default",
                   "org.freedesktop.Platform.GL32.mesa-git" ]:
        if ext_id not in installed_ext_ids:

```

**Comment by 1player** [comment]
Same here on Fedora Silverblue 36, every start I'm nagged with:

![image](https://user-images.githubusercontent.com/690120/173227360-3bf991be-cf94-4868-aa16-14a6ba21638d.png)

Yet everything is in place and games are OK:

```
~ % flatpak list | grep org.freedesktop.Platform.GL
Mesa    org.freedesktop.Platform.GL.default     21.3.8  21.08   flathub system
Mesa git snapshot       org.freedesktop.Platform.GL.mesa-git    22.1-branchpoint21.08   flathub-beta    user
default org.freedesktop.Platform.GL32.default           21.08   flathub system
Mesa git snapshot       org.freedesktop.Platform.GL32.mesa-git  22.1-branchpoint21.08   flathub-beta    user
```

**Comment by 1player** [comment]
Ping @gasinvein for introducing the change

**Comment by gasinvein** [comment]
@1player

> Same here on Fedora Silverblue 36

Do you use `mesa-git` GL drivers, too?

**Comment by gasinvein** [comment]
Please try a test build from [this PR](https://github.com/flathub/com.valvesoftware.Steam/pull/913).

**Comment by Big-FG** [comment]
@gasinvein this fixes it, thanks for the quick fix even though it wasnt an immediate issue :+1:

**Comment by 1player** [comment]
Same here, thanks!
