### ISSUE TITLE
Dying Light needs a symlink

### ISSUE THREAD

**Issue by cschalle** [flathub/com.valvesoftware.Steam#921]
Dying Light has a bad hardcoded library path that stops it from working on Linux currently:

lspci symlink from /usr/sbin/lspci to /usr/bin/lspci for Dying Light: https://www.gamingonlinux.com/forum/topic/2766/post_id=17381

Tom Crider filed this bug about in in Fedora:
 https://bugzilla.redhat.com/show_bug.cgi?id=1858437

**Comment by nanonyme** [comment]
Right, in the runtime /usr/sbin is a symlink to /usr/bin.
