### ISSUE TITLE
Xwayland coredump on Hades Canyon (NUC8i7HVK)

### ISSUE THREAD

**Issue by alexpattyn** [flathub/com.valvesoftware.Steam#926]
**Game information**

Pathfinder: Kingmaker

**Distribution name and version where applicable**

Fedora Linux 36.20220709.0 (Silverblue)

**Flatpak info**

```
$ flatpak --version
Flatpak 1.12.7

$ flatpak --gl-drivers
default
host
```

**Problem description**

Playing Pathfiner: Kingmaker (for example) leads to constant crashing, this appears to be specific to the NUC8i7HVK and its GPU (AMD VEGAM).

[flatpak-output.txt](https://github.com/flathub/com.valvesoftware.Steam/files/9079540/flatpak-output.txt)
[systemd-coredump.txt](https://github.com/flathub/com.valvesoftware.Steam/files/9079541/systemd-coredump.txt)

**Does this issue reproduce with native Steam**

Yes, on holoiso

**Comment by nanonyme** [comment]
If it reproduces with native Steam, make sure to file an issue in https://github.com/ValveSoftware/steam-for-linux. You can reference this one.

**Comment by alexpattyn** [comment]
Issue was resolved. It was a problem with a bad memory module and not the GPU. This was discovered via windows memory tool.
