### ISSUE TITLE
Black screen in Steam Store

### ISSUE THREAD

**Issue by Icy-Locust** [flathub/com.valvesoftware.Steam#931]
I have read the FAQ and can't find anything useful. 
When I run with or without -no-cef-sandbox, the libcef.so always crashes. dmesg shows:
traps: Chrome_IOThread[$pid] trap invalid opcode ip:xxx sp:xxx error:0 in libcef.so[xxx+6f5e000]
and I got:
steamwebhelper.sh[$pid]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[$pid]: CEF sandbox already disabled

My system is LFS and I try run steam on gentoo, everything is fine.
(I have both gentoo ans LFS on my computer)

**Comment by Icy-Locust** [comment]
It turned out to be /dev/shm issue

**Comment by fastoslinux** [comment]
https://github.com/flathub/com.valvesoftware.Steam/assets/17401812/2805b615-d0c7-492c-bbd3-7a2d8a15875d

Maybe I have the same bug?
