### ISSUE TITLE
Can't run emulators installed through Flatpak as well

### ISSUE THREAD

**Issue by MightyCreak** [flathub/com.valvesoftware.Steam#935]
**Game information**

Not really a game, but an emulator: Yuzu.

**Distribution name and version where applicable**

**Flatpak info**

```
$ flatpak --version
Flatpak 1.12.7
```

```
$ flatpak --gl-drivers
default
host
```

**Problem description**

I'm trying to run games using the Yuzu emulator (also installed through Flatpak), but it requires Steam to be able to run command lines such as `/usr/bin/flatpak run org.yuzu_emu.yuzu`, but since Steam is isolated from the other binaries on the host, it can't find `/usr/bin/flatpak`.

I tried to enable various options with Flatseal, but it still wouldn't work. Would there be a workaround somehow?

**Does this issue reproduce with native Steam**

No (it works on the Steam Deck, and I guess the Steam is installed natively on the Steam Deck)

**Comment by guihkx** [comment]
You can just give Steam the `--talk-name=org.freedesktop.Flatpak` permission, this will allow you to run commands outside the sandbox with [`flatpak-spawn --host`](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn):

```
flatpak --user override --talk-name=org.freedesktop.Flatpak com.valvesoftware.Steam
```

Then you can do something like this to launch Yuzu, for example:

```
flatpak-spawn --host flatpak run org.yuzu_emu.yuzu
```

Just keep in mind this pretty much allows any program/game to defeat the Flatpak sandbox.

**Comment by MightyCreak** [comment]
Nice! Thank you!

I understand that it breaks the sandbox, but I don't see how this kind of feature could work otherwise (i.e. Steam being able to run any external program). It seems that if we keep the sandbox, it kinda disable this feature (except if we want to run something built within Steam).

I don't know if there could be a way to punch holes in the sandbox but only for very specific files/folders?

**Comment by 1player** [comment]
This is not a Steam bug, nor a Flatpak bug either.

**Comment by soredake** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/283

**Comment by nanonyme** [comment]
Sorry to say but even if such portal existed, probability of it being taken into use is close to zero. This app is community-maintained and we have no ability to make any changes to Steam let alone games.

**Comment by MightyCreak** [comment]
> This is not a Steam bug, nor a Flatpak bug either.

You're right, but... I never said it was a bug. It's merely an issue, and as a user I shouldn't know if it's a bug or not. From a user perspective, it feels like a bug. For the sake of the Flathub/Flatpak communities, please don't reply like that to users that are merely trying to understand and/or find a solution, it definitely won't help in the long term.

**Comment by MightyCreak** [comment]
> Sorry to say but even if such portal existed, probability of it being taken into use is close to zero. This app is community-maintained and we have no ability to make any changes to Steam let alone games.

What makes you say that? Right now, Valve would lose some features if they use Flatpak to install Steam, so it seems fair that they decided to use a native package instead. But they are already using Flatpak in Steam OS, so they aren't against the idea of sandboxed apps. They maybe are simply waiting to see it mature a bit more and the question I asked is apparently not such a completely stupid one considering the amount of people asking the same (as we can see in the issue linked by @soredake, which links to other issues that gravitate around the same question).

**Comment by MightyCreak** [comment]
All that being said, I think I got my answers to my issue, so thank you all.

I'll close this issue now.
