### ISSUE TITLE
Ability to run `steamcmd` through the Flatpak version of Steam

### ISSUE THREAD

**Issue by LifeWatcher123** [flathub/com.valvesoftware.Steam#937]
After some rough surfing of the code, it seems to me that this Flatpak contains a copy of `steamcmd`. Is there a way to run that?

**Comment by doraskayo** [comment]
``` bash
flatpak run --command=steamcmd com.valvesoftware.Steam
```
You can also specify command-line arguments. For example:
``` bash
flatpak run --command=steamcmd com.valvesoftware.Steam +login foo bar
```

**Comment by LifeWatcher123** [comment]
> ```shell
> flatpak run --command=steamcmd com.valvesoftware.Steam
> ```
> 
> You can also specify command-line arguments. For example:
> 
> ```shell
> flatpak run --command=steamcmd com.valvesoftware.Steam +login foo bar
> ```

That works. Thanks!

**Comment by QmwJlHuSg9pa** [comment]
This is broken for me. Having the same issue as at #1028.
