### ISSUE TITLE
Steam crashes when setting Mesa Git Drivers

### ISSUE THREAD

**Issue by QushyQushy** [flathub/com.valvesoftware.Steam#955]
**Game information**
Steam

**Distribution name and version where applicable**
Alpine Linux Edge

**Flatpak info**
Flatpak 1.14.0
default
host

**Problem description**
The moment I put `FLATPAK_GL_DRIVERS=mesa-git` and launch steam either from the .desktop file or through `FLATPAK_GL_DRIVERS=mesa-git flatpak run com.valvesoftware.Steam` it crashes with:

```
steamwebhelper.sh[154]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[154]: CEF sandbox already disabled
glXChooseVisual failed
glXChooseVisual failedsrc/steamUI/Main.cpp (388) : Assertion Failed: Error: glXChooseVisual failed
src/steamUI/Main.cpp (388) : Assertion Failed: Error: glXChooseVisual failed
Installing breakpad exception handler for appid(steam)/version(1661985519)
assert_20220905135506_7.dmp[181]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220905135506_7.dmp
crash_20220905135506_8.dmp[204]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220905135506_8.dmp
/home/qushy/.var/app/com.valvesoftware.Steam/.local/share/Steam/steam.sh: line 796:   149 Segmentation fault      "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20220905135506_7.dmp[181]: Finished uploading minidump (out-of-process): success = yes
assert_20220905135506_7.dmp[181]: response: CrashID=bp-2b34ae4e-cb02-4fb2-a53a-6590b2220905
assert_20220905135506_7.dmp[181]: file ''/tmp/dumps/assert_20220905135506_7.dmp'', upload yes: ''CrashID=bp-2b34ae4e-cb02-4fb2-a53a-6590b2220905''
crash_20220905135506_8.dmp[204]: Finished uploading minidump (out-of-process): success = yes
crash_20220905135506_8.dmp[204]: response: CrashID=bp-8c3719e1-b1b6-45f7-b772-6fa412220905
crash_20220905135506_8.dmp[204]: file ''/tmp/dumps/crash_20220905135506_8.dmp'', upload yes: ''CrashID=bp-8c3719e1-b1b6-45f7-b772-6fa412220905''
```

**Does this issue reproduce with native Steam**
No

This happens both on Stable and Beta channels. The log is from Beta channel.

**Comment by Equivocal90** [comment]
I believe this is caused by the recent update for the Steam flatpak to the 22.08 runtime.

Run `# flatpak update --commi5ed80483da0196d5be5e455cb841940c9f8b6f651820b6f5942a93cb310e7cde com.valvesoftware.Steam`
Does it work after that?

**Comment by QushyQushy** [comment]
Yes it does and I confirmed the drivers are `21.3.9` by running Quake 2 RTX. The problem is that with this commit I can't run any Proton Vulkan games as it doesn't recognize the Vulkan drivers. Is there a workaround for that?

**Comment by Equivocal90** [comment]
Do you have both `org.freedesktop.Platform.GL.mesa-git/x86_64/21.08` and `org.freedesktop.Platform.GL32.mesa-git/x86_64/21.08` installed? Also, are you running it with the environment variable you specified?

**Comment by QushyQushy** [comment]
> I believe this is caused by the recent update for the Steam flatpak to the 22.08 runtime.
> 
> Run `# flatpak update --commit=5ed80483da0196d5be5e455cb841940c9f8b6f651820b6f5942a93cb310e7cde com.valvesoftware.Steam` Does it work after that?

Ok after running this even if I switch version and remove and reinstall steam game don't work. Where can I find the commits so I can get the latest one?

**Comment by QushyQushy** [comment]
> Do you have both `org.freedesktop.Platform.GL.mesa-git/x86_64/21.08` and `org.freedesktop.Platform.GL32.mesa-git/x86_64/21.08` installed? Also, are you running it with the environment variable you specified?

Yes, I had 22.08 beta installed and specifically installed 21.08 for mesa-git to work with the commit you sent. But Proton Vulkan games don't work at all now.

**Comment by QushyQushy** [comment]
I found the commits but I get 404 error even with the commit you sent. Is Flathub down or is this a bug?

**Comment by QushyQushy** [comment]
Ok so `DRI_PRIME=1` really bugs Steam when set through Flatseal I don't' know why. Also if you have Steam from the beta channel installed commit updates don't work.

**Comment by nanonyme** [comment]
There is now 22.08 version of mesa-git. It has same limitations as before.
