### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by Pshemas** [flathub/com.valvesoftware.Steam#96]
Is there a way to get tray icon to display correctly? I'm using Xfce and it is one of the small annoyances of this flatpak. Would love to get it fixed. Is there anything I can do?
![steam_flatpak_iconissue](https://user-images.githubusercontent.com/6144330/41302209-3223b820-6e6a-11e8-9958-eefd3567db07.jpg)
Also I've noticed that dock icon is rather low res. Is there a workaround for that? Can I add/swap icon files somewhere?

**Comment by 9f565fdc** [comment]
> Also I've noticed that dock icon is rather low res.

I believe this pull request would solve that: https://github.com/flathub/com.valvesoftware.Steam/pull/97.

**Comment by user5145** [comment]
Tray icon has been already mentioned there #4

**Comment by Pshemas** [comment]
is there a way to merge this thread with #4 - indeed it seems to be the same probem . Has anyone found a fix / workaround?
It would be awesome to get this one resolved. Also does anyone know how the icons are handled through Flatpak in general? How should I go about switching the icon?
With regular Linux app it is easy - you check the desktop file to see which image is used then go to your icon theme folder and swap it for the one you'd like to have (or change the entry in the desktop file to the one you want). As mentioned above the tray icon is only half of the problem - the 2nd one is that the one used in the app launcher is a bit on low-res site and does not match rest of the theme.

**Comment by nanonyme** [comment]
Merging is not possible. You already linked the two tickets by referencing the other one so you can always close this one.

**Comment by nanonyme** [comment]
Closing as duplicate

**Comment by Pshemas** [comment]
it seems that one of the recent updates fixed the issue - THANK YOU to all involved.
