### ISSUE TITLE
How to enable pipewire on flatpack steam?

### ISSUE THREAD

**Issue by ss8688** [flathub/com.valvesoftware.Steam#964]
I want to use steamlink with Wayland.So I should enable pipewire. But I don't know how to.

**Comment by ss8688** [comment]
I don't kown how to add add -pipewire  flag at launch on flatpack

**Comment by StianOverbye** [comment]
You add command line variables just like any other application, for example:

`flatpak run com.valvesoftware.Steam -pipewire &`

This will run Steam with the PipeWire argument, and then fork to the background. In the future, Github issues are not the right place to ask questions like this.
