### ISSUE TITLE
Terraria can go into fullscreen

### ISSUE THREAD

**Issue by lefisheryboi** [flathub/com.valvesoftware.Steam#971]
**Game information**

**Distribution name and version where applicable**

**Flatpak info**

**Problem description**

**Does this issue reproduce with native Steam**

**Comment by nanonyme** [comment]
What exactly is the problem here?

**Comment by nanonyme** [comment]
Please fill the template

**Comment by lefisheryboi** [comment]
Sorry about the template this is my first time. When I open terraria, it's in a small window. When I try to make it bigger it crashes.
