### ISSUE TITLE
Steam systematically dies 40-50 seconds after starting

### ISSUE THREAD

**Issue by fralalonde** [flathub/com.valvesoftware.Steam#977]
## Context
Fedora 36 / Kenoite (Silverblue/KDE), fully updated
```
Linux fedora 5.19.12-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Sep 28 17:11:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Platform: Asus Zephyrus G14 (2021), 16G

## Reproducing
1. Launch Steam using Flatpak
2. Steam clients dies after 40 to 60 seconds, whatever state it's in:
 - If not logging in, Steam dies while login dialog is displayed
 - If logging in, behaves normally (can start download, browse games, friends, etc.) before Steam dies

## Notes
- From the shell, output of `flatpak run com.valvesoftware.Steam` displays no error at console when the process dies.
- Same behavior using dGPU (nvidia) or iGPU (radeon)
- Problem does _not_ occur if Steam is installed "natively"  from rpm-fusion repos (Steam and games run great)

**Comment by hellot1m** [comment]
Having same issue. Started about a week ago. still on latest update through flatpak. Distro is Batocera v35. The people over at batocera have confirmed the issue is with the flatpak, not with the distro.

**Comment by Andonome** [comment]
Same issue with amd graphics card (`VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] (rev c7)`), on Arch Linux.

**Comment by Loverboy7Love** [comment]
Same issue with AMD Ryzen 5700 G.

**Comment by fralalonde** [comment]
I resolved the issue by allowing the Steam flatpak to run in the background. I've done so using Flatseal, selecting Steam and going at the very bottom of the list, in "Portals", turning on the "Background" option.

I figured it out because Steam was now dying after 5 seconds and I noticed that launching it from the CLI, the result was that the process was _killed_. It did not crash by itself but was stopped externally! Knowing what to look for lead me to this https://github.com/flatpak/xdg-desktop-portal/issues/664

I have no idea:
- why option this was disabled by default if it is required (I never touched it before)
- why it went from 50 seconds to 5 seconds before getting axed

Closing the issue since I first opened it but you may open a new one if my fix doesn't work for you.
