### ISSUE TITLE
bwrap aborts launch if ~/Music is a symlink

### ISSUE THREAD

**Issue by notklaatu** [flathub/com.valvesoftware.Steam#985]
I changed my `$HOME/Music` directory to a symlink pointing to an external drive, and afterwards bwrap aborted Steam launching with this error: 

```
bwrap: Can't make symlink at /home/klaatu/Music: File exists
```

Changing my Music dir back to a real dir fixed the issue.

Maybe this is better as a bwrap bug report, but I thought I'd post it here in case somebody in the future comes here to report a similar issue.

**Comment by rusty-snake** [comment]
Did you searched for the error?
Are you sure it is not a duplicate of #868 #66 #386 #58 #57?

**Comment by notklaatu** [comment]
Thanks, I guess I was searching for the wrong keywords. This appears to be the same error.
