### ISSUE TITLE
Segfault after having steam open for a few seconds

### ISSUE THREAD

**Issue by Slushee-a** [flathub/com.valvesoftware.Steam#987]
**Distribution name and version where applicable**
Alpine Linux edge x86_64

**Flatpak info**
Version: Flatpak 1.14.0
Drivers: default, host

**Problem description**
Steam segfaults after 33 seconds of being open:
```
.local/share/Steam/steam.sh: line 796:   149 Segmentation fault      "$STEAMROOT/$STEAMEXEPATH" "$@"
```
The update and login windows don't crash, they work perfectly. Only the steam app itself

**Does this issue reproduce with native Steam**
No

**Comment by ReaperTown** [comment]
Having the same issue, seems to be everyone using the flatpak version of steam
