### ISSUE TITLE
Intel Arc not being used by flatpak

### ISSUE THREAD

**Issue by alexpattyn** [flathub/com.valvesoftware.Steam#989]
**Game information**

All, as this is an issue with the steam flatpak not seeing the A750. 

**Distribution name and version where applicable**

```
$ cat /etc/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=37450
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
BUILD_ID=37450
```

**Flatpak info**

Flatpak 1.14.0

```
$  flatpak --gl-drivers
default
host
```

**Problem description**
Steam does not see the Intel Arc A750. This may be an issue with a mesa driver mismatch? As steam is showing Mesa 22.1.7, but the host has Mesa 22.3.0-devel.

### About Gnome
![image](https://user-images.githubusercontent.com/28536677/196744129-9edbce32-fb8d-4997-ba1a-5e43214a6c67.png)

### Steam Sys Info
![image](https://user-images.githubusercontent.com/28536677/196744161-81b2efa3-5abd-46c0-9db9-49f65886ad44.png)

### Host Mesa Version
```
$ glxinfo | grep Mesa
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
client glx vendor string: Mesa Project and SGI
    Device: Mesa Intel(R) Arc(tm) A750 Graphics (DG2) (0x56a1)
OpenGL renderer string: Mesa Intel(R) Arc(tm) A750 Graphics (DG2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.3.0-devel
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.0-devel
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.3.0-devel
```

**Does this issue reproduce with native Steam**

Have not tested.

**Comment by alexpattyn** [comment]
Also should note I enabled GPU acceleration in flatseal just in case that may have caused an issue: 

![image](https://user-images.githubusercontent.com/28536677/196745419-a26c6951-418c-498d-a32b-95b3c62e87d8.png)

**Comment by Newbytee** [comment]
Maybe try Mesa-git? I.e. `org.freedesktop.Platform.GL.mesa-git` and `org.freedesktop.Platform.GL32.mesa-git`.

**Comment by alexpattyn** [comment]
Resolved. Seems like the freedesktop platform caught up.
