### ISSUE TITLE
lib.so.6 error

### ISSUE THREAD

**Issue by bonnom** [flathub/com.valvesoftware.Steam#99]
There is an error after installing the steam flatpak.
"lib.so.6 cannot be found" or something like that.
Someone pointed out that in the review section that this can be solved by typing "sudo flatpak update" in the terminal. This installs "org.freedesktop.Platform.Compat32/x86_64/1.6 from flathub". If it wasn't for the review I wouldn't got the steam package working.
Hopefully this can be solved in a future update.

I installed the flatpak with "Discover" from KDE.
Operating system: KDE Neon (base is ubuntu 16.4).

Edit: Added more information about my installation method and OS.

**Comment by nanonyme** [comment]
There was an earlier bug in Gnome's store thingie that it didn't follow depedencies properly. This sounds like a similar bug in Discover

**Comment by bonnom** [comment]
I send it over to KDE. They are going to roll out some updates soon that might solve the problem.

**Comment by nanonyme** [comment]
Any update on this?

**Comment by nanonyme** [comment]
Added note to https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
