### ISSUE TITLE
Proton games not launching on Hyprland wayland

### ISSUE THREAD

**Issue by Roger-Roger-debug** [flathub/com.valvesoftware.Steam#990]
**Game information**
All proton games

**Distribution name and version where applicable**
Archlinux

**Flatpak info**
```
flatpak --version
Flatpak 1.14.0
```
```
flatpak --gl-drivers
default
host
```

**Problem description**
Very similar to #885, however I'm running Hyprland/Sway (wlroots). When clicking play the button changes to cancel, then stop and turns back to play without any window appearing.
 According to [this comment](https://github.com/flathub/com.valvesoftware.Steam/issues/885#issuecomment-1122200975) it should work on gnome, however it didn't work for me on gnome either.

Only affects flatpak steam with steam proton. The community builds work fine. I went over the [Steam Play games do not start for me](https://github.com/flathub/com.valvesoftware.Steam/issues/885#issuecomment-1122200975) section and made sure everything is as required. It's been some time since I used Xorg, but I think if I remember it worked there as well.

[This](https://gist.github.com/Roger-Roger-debug/43718af2bb2af645f2e9e58504199adf) is the output of `PROTON_LOG=1` for Forts.

**Does this issue reproduce with native Steam**
No

**Comment by Apogeum12** [comment]
This same for me, native steam (deb version works correctly). Flatpak non :(

**Comment by Roger-Roger-debug** [comment]
All games launch fine with the community builds of proton so I think it's related to pressure-vessel. That would also explain Dota not working for me as I read in some github threads that it too uses pressure-vessel.

**Comment by Roger-Roger-debug** [comment]
An update seems to have fixed it.
