### ISSUE TITLE
Linux flatpak- Some games will not launch

### ISSUE THREAD

**Issue by Tderueda** [flathub/com.valvesoftware.Steam#994]
**Most** games work, but some simply won't launch.  All video card drivers up to date.  I enabled the multilib repositories in pacman.conf.  

My problem is, when I go to play "Battlefield 4

https://user-images.githubusercontent.com/111088750/197419169-40f989c4-3889-4917-b1db-26922dd3e05b.mp4

" for example, I press the green play button, it says preparing to launch, then doesn't launch and the green play button returns.

Any suggestions on where to start fixing this?  I've uninstalled, and reinstalled several times.

Thanks for the help! 

Specs
OS: Arch Linux x86_64
Kernel: 5.19.12-arch1-1
Packages: 1182 (pacman), 36 (flatpak)
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 5.25.5
WM: KWin
Theme: [Plasma], Breeze [GTK2/3]
Icons: [Plasma], breeze-dark [GTK2/3]
Terminal: konsole
CPU: Intel i9-9900K (16) @ 5.000GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
Memory: 3220MiB / 32015MiB

**Comment by Tderueda** [comment]
SOLVED: 

I went to Steam - Settings - account - and I turned off Beta participation.  Now ALL games work!

**Comment by C0rn3j** [comment]
Close the issue then please

**Comment by reverse123** [comment]
Have same issue with Counter-Strike: Source. Without Flatpak it works fine. Tried beta, different Proton versions - no result.

**Comment by Peremious** [comment]
> Have same issue with Counter-Strike: Source. Without Flatpak it works fine. Tried beta, different Proton versions - no result.

What version of the Steam Flatpak are you using? You need to be using 1.12+ to use proton versions 5.13 or above. Pressure-vessel is incompatible with the Flatpak Steam when using older versions.

Alternately, get the community build for Flatpak Proton from here:
https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton

or here
https://flathub.org/apps/com.valvesoftware.Steam.CompatibilityTool.Proton

These versions don't use the sandboxing that conflicts with the already present sandboxing in Flatpaks.

**Comment by abanoub-R** [comment]
> Have same issue with Counter-Strike: Source. Without Flatpak it works fine. Tried beta, different Proton versions - no result.

It's been a long time since your post but to anyone reading this encountering this issue you may need to copy libtcmalloc-minimal.so.4 from wherever your distro installs it to (libtcmalloc on apt or lib32-gperftools on arch) to the bin/ folder in the game folder to the binary with the same name
